/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { AddUsuarioToInstituicaoMutationResponse, AddUsuarioToInstituicaoPathParams, AddUsuarioToInstituicao404, AddUsuarioToInstituicao409 } from "../../models/AddUsuarioToInstituicao.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { addUsuarioToInstituicao } from "../../client/addUsuarioToInstituicao.ts";

export const addUsuarioToInstituicaoMutationKey = () => [{ url: '/instituicoes/:instituicaoId/usuarios/:usuarioId' }] as const

export type AddUsuarioToInstituicaoMutationKey = ReturnType<typeof addUsuarioToInstituicaoMutationKey>

export function addUsuarioToInstituicaoMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = addUsuarioToInstituicaoMutationKey()
  return mutationOptions<AddUsuarioToInstituicaoMutationResponse, ResponseErrorConfig<AddUsuarioToInstituicao404 | AddUsuarioToInstituicao409>, {instituicaoId: AddUsuarioToInstituicaoPathParams["instituicaoId"], usuarioId: AddUsuarioToInstituicaoPathParams["usuarioId"]}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ instituicaoId, usuarioId }) => {
      return addUsuarioToInstituicao(instituicaoId, usuarioId, config)
    },
  })
}

/**
 * @summary Adiciona Usuário a uma Instituição de Ensino
 * {@link /instituicoes/:instituicaoId/usuarios/:usuarioId}
 */
export function useAddUsuarioToInstituicao<TContext>(options: 
{
  mutation?: UseMutationOptions<AddUsuarioToInstituicaoMutationResponse, ResponseErrorConfig<AddUsuarioToInstituicao404 | AddUsuarioToInstituicao409>, {instituicaoId: AddUsuarioToInstituicaoPathParams["instituicaoId"], usuarioId: AddUsuarioToInstituicaoPathParams["usuarioId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? addUsuarioToInstituicaoMutationKey()

  const baseOptions = addUsuarioToInstituicaoMutationOptions(config) as UseMutationOptions<AddUsuarioToInstituicaoMutationResponse, ResponseErrorConfig<AddUsuarioToInstituicao404 | AddUsuarioToInstituicao409>, {instituicaoId: AddUsuarioToInstituicaoPathParams["instituicaoId"], usuarioId: AddUsuarioToInstituicaoPathParams["usuarioId"]}, TContext>

  return useMutation<AddUsuarioToInstituicaoMutationResponse, ResponseErrorConfig<AddUsuarioToInstituicao404 | AddUsuarioToInstituicao409>, {instituicaoId: AddUsuarioToInstituicaoPathParams["instituicaoId"], usuarioId: AddUsuarioToInstituicaoPathParams["usuarioId"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<AddUsuarioToInstituicaoMutationResponse, ResponseErrorConfig<AddUsuarioToInstituicao404 | AddUsuarioToInstituicao409>, {instituicaoId: AddUsuarioToInstituicaoPathParams["instituicaoId"], usuarioId: AddUsuarioToInstituicaoPathParams["usuarioId"]}, TContext>
}