/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { CreateInstituicaoMutationRequest, CreateInstituicaoMutationResponse, CreateInstituicao409, CreateInstituicao422 } from "../../models/CreateInstituicao.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { createInstituicao } from "../../client/createInstituicao.ts";

export const createInstituicaoMutationKey = () => [{ url: '/instituicoes' }] as const

export type CreateInstituicaoMutationKey = ReturnType<typeof createInstituicaoMutationKey>

export function createInstituicaoMutationOptions(config: Partial<RequestConfig<CreateInstituicaoMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = createInstituicaoMutationKey()
  return mutationOptions<CreateInstituicaoMutationResponse, ResponseErrorConfig<CreateInstituicao409 | CreateInstituicao422>, {data: CreateInstituicaoMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return createInstituicao(data, config)
    },
  })
}

/**
 * @summary Realiza a criação de instituições, vinculando automaticamente o Gestor que realizou a solicitação
 * {@link /instituicoes}
 */
export function useCreateInstituicao<TContext>(options: 
{
  mutation?: UseMutationOptions<CreateInstituicaoMutationResponse, ResponseErrorConfig<CreateInstituicao409 | CreateInstituicao422>, {data: CreateInstituicaoMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreateInstituicaoMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createInstituicaoMutationKey()

  const baseOptions = createInstituicaoMutationOptions(config) as UseMutationOptions<CreateInstituicaoMutationResponse, ResponseErrorConfig<CreateInstituicao409 | CreateInstituicao422>, {data: CreateInstituicaoMutationRequest}, TContext>

  return useMutation<CreateInstituicaoMutationResponse, ResponseErrorConfig<CreateInstituicao409 | CreateInstituicao422>, {data: CreateInstituicaoMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreateInstituicaoMutationResponse, ResponseErrorConfig<CreateInstituicao409 | CreateInstituicao422>, {data: CreateInstituicaoMutationRequest}, TContext>
}