/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetInstituicaoByEmailQueryRequest, GetInstituicaoByEmailQueryResponse } from "../../models/GetInstituicaoByEmail.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getInstituicaoByEmail } from "../../client/getInstituicaoByEmail.ts";

export const getInstituicaoByEmailSuspenseQueryKey = (data: GetInstituicaoByEmailQueryRequest) => [{ url: '/instituicoes/getByEmail' }, ...(data ? [data] : [])] as const

export type GetInstituicaoByEmailSuspenseQueryKey = ReturnType<typeof getInstituicaoByEmailSuspenseQueryKey>

export function getInstituicaoByEmailSuspenseQueryOptions(data: GetInstituicaoByEmailQueryRequest, config: Partial<RequestConfig<GetInstituicaoByEmailQueryRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = getInstituicaoByEmailSuspenseQueryKey(data)
  return queryOptions<GetInstituicaoByEmailQueryResponse, ResponseErrorConfig<Error>, GetInstituicaoByEmailQueryResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getInstituicaoByEmail(data, config)
   },
  })
}

/**
 * {@link /instituicoes/getByEmail}
 */
export function useGetInstituicaoByEmailSuspense<TData = GetInstituicaoByEmailQueryResponse, TQueryKey extends QueryKey = GetInstituicaoByEmailSuspenseQueryKey>(data: GetInstituicaoByEmailQueryRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetInstituicaoByEmailQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<GetInstituicaoByEmailQueryRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getInstituicaoByEmailSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...getInstituicaoByEmailSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}