/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetInstituicoesQueryResponse } from "../../models/GetInstituicoes.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getInstituicoes } from "../../client/getInstituicoes.ts";

export const getInstituicoesSuspenseQueryKey = () => [{ url: '/instituicoes' }] as const

export type GetInstituicoesSuspenseQueryKey = ReturnType<typeof getInstituicoesSuspenseQueryKey>

export function getInstituicoesSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getInstituicoesSuspenseQueryKey()
  return queryOptions<GetInstituicoesQueryResponse, ResponseErrorConfig<Error>, GetInstituicoesQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getInstituicoes(config)
   },
  })
}

/**
 * @summary Obtém uma lista com as instituições de ensino cadastradas no sistema
 * {@link /instituicoes}
 */
export function useGetInstituicoesSuspense<TData = GetInstituicoesQueryResponse, TQueryKey extends QueryKey = GetInstituicoesSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetInstituicoesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getInstituicoesSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getInstituicoesSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}