/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetInstituicoesQueryResponse } from "../../models/GetInstituicoes.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getInstituicoes } from "../../client/getInstituicoes.ts";

export const getInstituicoesQueryKey = () => [{ url: '/instituicoes' }] as const

export type GetInstituicoesQueryKey = ReturnType<typeof getInstituicoesQueryKey>

export function getInstituicoesQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getInstituicoesQueryKey()
  return queryOptions<GetInstituicoesQueryResponse, ResponseErrorConfig<Error>, GetInstituicoesQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getInstituicoes(config)
   },
  })
}

/**
 * @summary Obtém uma lista com as instituições de ensino cadastradas no sistema
 * {@link /instituicoes}
 */
export function useGetInstituicoes<TData = GetInstituicoesQueryResponse, TQueryData = GetInstituicoesQueryResponse, TQueryKey extends QueryKey = GetInstituicoesQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetInstituicoesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getInstituicoesQueryKey()

  const query = useQuery({
   ...getInstituicoesQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}