/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetInstituicaoByCnpjQueryRequest, GetInstituicaoByCnpjQueryResponse, GetInstituicaoByCnpj404 } from "../../models/GetInstituicaoByCnpj.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getInstituicaoByCnpj } from "../../client/getInstituicaoByCnpj.ts";

export const getInstituicaoByCnpjSuspenseQueryKey = (data: GetInstituicaoByCnpjQueryRequest) => [{ url: '/instituicoes/getByCNPJ' }, ...(data ? [data] : [])] as const

export type GetInstituicaoByCnpjSuspenseQueryKey = ReturnType<typeof getInstituicaoByCnpjSuspenseQueryKey>

export function getInstituicaoByCnpjSuspenseQueryOptions(data: GetInstituicaoByCnpjQueryRequest, config: Partial<RequestConfig<GetInstituicaoByCnpjQueryRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = getInstituicaoByCnpjSuspenseQueryKey(data)
  return queryOptions<GetInstituicaoByCnpjQueryResponse, ResponseErrorConfig<GetInstituicaoByCnpj404>, GetInstituicaoByCnpjQueryResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getInstituicaoByCnpj(data, config)
   },
  })
}

/**
 * @summary Obtém um Instituição de Ensino através do seu CNPJ
 * {@link /instituicoes/getByCNPJ}
 */
export function useGetInstituicaoByCnpjSuspense<TData = GetInstituicaoByCnpjQueryResponse, TQueryKey extends QueryKey = GetInstituicaoByCnpjSuspenseQueryKey>(data: GetInstituicaoByCnpjQueryRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetInstituicaoByCnpjQueryResponse, ResponseErrorConfig<GetInstituicaoByCnpj404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<GetInstituicaoByCnpjQueryRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getInstituicaoByCnpjSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...getInstituicaoByCnpjSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetInstituicaoByCnpj404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}