/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetUsuariosFromInstituicaoQueryResponse, GetUsuariosFromInstituicaoPathParams, GetUsuariosFromInstituicao404 } from "../../models/GetUsuariosFromInstituicao.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getUsuariosFromInstituicao } from "../../client/getUsuariosFromInstituicao.ts";

export const getUsuariosFromInstituicaoSuspenseQueryKey = (instituicaoId: GetUsuariosFromInstituicaoPathParams["instituicaoId"]) => [{ url: '/instituicoes/:instituicaoId/usuarios', params: {instituicaoId:instituicaoId} }] as const

export type GetUsuariosFromInstituicaoSuspenseQueryKey = ReturnType<typeof getUsuariosFromInstituicaoSuspenseQueryKey>

export function getUsuariosFromInstituicaoSuspenseQueryOptions(instituicaoId: GetUsuariosFromInstituicaoPathParams["instituicaoId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getUsuariosFromInstituicaoSuspenseQueryKey(instituicaoId)
  return queryOptions<GetUsuariosFromInstituicaoQueryResponse, ResponseErrorConfig<GetUsuariosFromInstituicao404>, GetUsuariosFromInstituicaoQueryResponse, typeof queryKey>({
   enabled: !!(instituicaoId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getUsuariosFromInstituicao(instituicaoId, config)
   },
  })
}

/**
 * @summary Lista os usuários membros de uma determinada Instituição de Ensino
 * {@link /instituicoes/:instituicaoId/usuarios}
 */
export function useGetUsuariosFromInstituicaoSuspense<TData = GetUsuariosFromInstituicaoQueryResponse, TQueryKey extends QueryKey = GetUsuariosFromInstituicaoSuspenseQueryKey>(instituicaoId: GetUsuariosFromInstituicaoPathParams["instituicaoId"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetUsuariosFromInstituicaoQueryResponse, ResponseErrorConfig<GetUsuariosFromInstituicao404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getUsuariosFromInstituicaoSuspenseQueryKey(instituicaoId)

  const query = useSuspenseQuery({
   ...getUsuariosFromInstituicaoSuspenseQueryOptions(instituicaoId, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetUsuariosFromInstituicao404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}