/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetInstituicaoByIdQueryResponse, GetInstituicaoByIdPathParams, GetInstituicaoById404 } from "../../models/GetInstituicaoById.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getInstituicaoById } from "../../client/getInstituicaoById.ts";

export const getInstituicaoByIdQueryKey = (id: GetInstituicaoByIdPathParams["id"]) => [{ url: '/instituicoes/:id', params: {id:id} }] as const

export type GetInstituicaoByIdQueryKey = ReturnType<typeof getInstituicaoByIdQueryKey>

export function getInstituicaoByIdQueryOptions(id: GetInstituicaoByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getInstituicaoByIdQueryKey(id)
  return queryOptions<GetInstituicaoByIdQueryResponse, ResponseErrorConfig<GetInstituicaoById404>, GetInstituicaoByIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getInstituicaoById(id, config)
   },
  })
}

/**
 * @summary Obtém um Instituição de Ensino através do seu ID
 * {@link /instituicoes/:id}
 */
export function useGetInstituicaoById<TData = GetInstituicaoByIdQueryResponse, TQueryData = GetInstituicaoByIdQueryResponse, TQueryKey extends QueryKey = GetInstituicaoByIdQueryKey>(id: GetInstituicaoByIdPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<GetInstituicaoByIdQueryResponse, ResponseErrorConfig<GetInstituicaoById404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getInstituicaoByIdQueryKey(id)

  const query = useQuery({
   ...getInstituicaoByIdQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetInstituicaoById404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}