/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetInstituicaoByIdQueryResponse, GetInstituicaoByIdPathParams, GetInstituicaoById404 } from "../../models/GetInstituicaoById.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getInstituicaoById } from "../../client/getInstituicaoById.ts";

export const getInstituicaoByIdSuspenseQueryKey = (id: GetInstituicaoByIdPathParams["id"]) => [{ url: '/instituicoes/:id', params: {id:id} }] as const

export type GetInstituicaoByIdSuspenseQueryKey = ReturnType<typeof getInstituicaoByIdSuspenseQueryKey>

export function getInstituicaoByIdSuspenseQueryOptions(id: GetInstituicaoByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getInstituicaoByIdSuspenseQueryKey(id)
  return queryOptions<GetInstituicaoByIdQueryResponse, ResponseErrorConfig<GetInstituicaoById404>, GetInstituicaoByIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getInstituicaoById(id, config)
   },
  })
}

/**
 * @summary Obtém um Instituição de Ensino através do seu ID
 * {@link /instituicoes/:id}
 */
export function useGetInstituicaoByIdSuspense<TData = GetInstituicaoByIdQueryResponse, TQueryKey extends QueryKey = GetInstituicaoByIdSuspenseQueryKey>(id: GetInstituicaoByIdPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetInstituicaoByIdQueryResponse, ResponseErrorConfig<GetInstituicaoById404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getInstituicaoByIdSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...getInstituicaoByIdSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetInstituicaoById404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}