/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetUsuariosFromInstituicaoQueryResponse, GetUsuariosFromInstituicaoPathParams, GetUsuariosFromInstituicao404 } from "../../models/GetUsuariosFromInstituicao.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getUsuariosFromInstituicao } from "../../client/getUsuariosFromInstituicao.ts";

export const getUsuariosFromInstituicaoQueryKey = (instituicaoId: GetUsuariosFromInstituicaoPathParams["instituicaoId"]) => [{ url: '/instituicoes/:instituicaoId/usuarios', params: {instituicaoId:instituicaoId} }] as const

export type GetUsuariosFromInstituicaoQueryKey = ReturnType<typeof getUsuariosFromInstituicaoQueryKey>

export function getUsuariosFromInstituicaoQueryOptions(instituicaoId: GetUsuariosFromInstituicaoPathParams["instituicaoId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getUsuariosFromInstituicaoQueryKey(instituicaoId)
  return queryOptions<GetUsuariosFromInstituicaoQueryResponse, ResponseErrorConfig<GetUsuariosFromInstituicao404>, GetUsuariosFromInstituicaoQueryResponse, typeof queryKey>({
   enabled: !!(instituicaoId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getUsuariosFromInstituicao(instituicaoId, config)
   },
  })
}

/**
 * @summary Lista os usuários membros de uma determinada Instituição de Ensino
 * {@link /instituicoes/:instituicaoId/usuarios}
 */
export function useGetUsuariosFromInstituicao<TData = GetUsuariosFromInstituicaoQueryResponse, TQueryData = GetUsuariosFromInstituicaoQueryResponse, TQueryKey extends QueryKey = GetUsuariosFromInstituicaoQueryKey>(instituicaoId: GetUsuariosFromInstituicaoPathParams["instituicaoId"], options: 
{
  query?: Partial<QueryObserverOptions<GetUsuariosFromInstituicaoQueryResponse, ResponseErrorConfig<GetUsuariosFromInstituicao404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getUsuariosFromInstituicaoQueryKey(instituicaoId)

  const query = useQuery({
   ...getUsuariosFromInstituicaoQueryOptions(instituicaoId, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetUsuariosFromInstituicao404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}