/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetInstituicaoByEmailQueryRequest, GetInstituicaoByEmailQueryResponse } from "../../models/GetInstituicaoByEmail.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getInstituicaoByEmail } from "../../client/getInstituicaoByEmail.ts";

export const getInstituicaoByEmailQueryKey = (data: GetInstituicaoByEmailQueryRequest) => [{ url: '/instituicoes/getByEmail' }, ...(data ? [data] : [])] as const

export type GetInstituicaoByEmailQueryKey = ReturnType<typeof getInstituicaoByEmailQueryKey>

export function getInstituicaoByEmailQueryOptions(data: GetInstituicaoByEmailQueryRequest, config: Partial<RequestConfig<GetInstituicaoByEmailQueryRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = getInstituicaoByEmailQueryKey(data)
  return queryOptions<GetInstituicaoByEmailQueryResponse, ResponseErrorConfig<Error>, GetInstituicaoByEmailQueryResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getInstituicaoByEmail(data, config)
   },
  })
}

/**
 * {@link /instituicoes/getByEmail}
 */
export function useGetInstituicaoByEmail<TData = GetInstituicaoByEmailQueryResponse, TQueryData = GetInstituicaoByEmailQueryResponse, TQueryKey extends QueryKey = GetInstituicaoByEmailQueryKey>(data: GetInstituicaoByEmailQueryRequest, options: 
{
  query?: Partial<QueryObserverOptions<GetInstituicaoByEmailQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<GetInstituicaoByEmailQueryRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getInstituicaoByEmailQueryKey(data)

  const query = useQuery({
   ...getInstituicaoByEmailQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}