/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetInstituicaoByCnpjQueryRequest, GetInstituicaoByCnpjQueryResponse, GetInstituicaoByCnpj404 } from "../../models/GetInstituicaoByCnpj.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getInstituicaoByCnpj } from "../../client/getInstituicaoByCnpj.ts";

export const getInstituicaoByCnpjQueryKey = (data: GetInstituicaoByCnpjQueryRequest) => [{ url: '/instituicoes/getByCNPJ' }, ...(data ? [data] : [])] as const

export type GetInstituicaoByCnpjQueryKey = ReturnType<typeof getInstituicaoByCnpjQueryKey>

export function getInstituicaoByCnpjQueryOptions(data: GetInstituicaoByCnpjQueryRequest, config: Partial<RequestConfig<GetInstituicaoByCnpjQueryRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = getInstituicaoByCnpjQueryKey(data)
  return queryOptions<GetInstituicaoByCnpjQueryResponse, ResponseErrorConfig<GetInstituicaoByCnpj404>, GetInstituicaoByCnpjQueryResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getInstituicaoByCnpj(data, config)
   },
  })
}

/**
 * @summary Obtém um Instituição de Ensino através do seu CNPJ
 * {@link /instituicoes/getByCNPJ}
 */
export function useGetInstituicaoByCnpj<TData = GetInstituicaoByCnpjQueryResponse, TQueryData = GetInstituicaoByCnpjQueryResponse, TQueryKey extends QueryKey = GetInstituicaoByCnpjQueryKey>(data: GetInstituicaoByCnpjQueryRequest, options: 
{
  query?: Partial<QueryObserverOptions<GetInstituicaoByCnpjQueryResponse, ResponseErrorConfig<GetInstituicaoByCnpj404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<GetInstituicaoByCnpjQueryRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getInstituicaoByCnpjQueryKey(data)

  const query = useQuery({
   ...getInstituicaoByCnpjQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetInstituicaoByCnpj404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}