/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { RemoveUsuarioFromInstituicaoMutationResponse, RemoveUsuarioFromInstituicaoPathParams, RemoveUsuarioFromInstituicao404, RemoveUsuarioFromInstituicao409 } from "../../models/RemoveUsuarioFromInstituicao.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { removeUsuarioFromInstituicao } from "../../client/removeUsuarioFromInstituicao.ts";

export const removeUsuarioFromInstituicaoMutationKey = () => [{ url: '/instituicoes/:instituicaoId/usuarios/:usuarioId' }] as const

export type RemoveUsuarioFromInstituicaoMutationKey = ReturnType<typeof removeUsuarioFromInstituicaoMutationKey>

export function removeUsuarioFromInstituicaoMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = removeUsuarioFromInstituicaoMutationKey()
  return mutationOptions<RemoveUsuarioFromInstituicaoMutationResponse, ResponseErrorConfig<RemoveUsuarioFromInstituicao404 | RemoveUsuarioFromInstituicao409>, {instituicaoId: RemoveUsuarioFromInstituicaoPathParams["instituicaoId"], usuarioId: RemoveUsuarioFromInstituicaoPathParams["usuarioId"]}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ instituicaoId, usuarioId }) => {
      return removeUsuarioFromInstituicao(instituicaoId, usuarioId, config)
    },
  })
}

/**
 * @summary Remove Usuário de uma Instituição de Ensino
 * {@link /instituicoes/:instituicaoId/usuarios/:usuarioId}
 */
export function useRemoveUsuarioFromInstituicao<TContext>(options: 
{
  mutation?: UseMutationOptions<RemoveUsuarioFromInstituicaoMutationResponse, ResponseErrorConfig<RemoveUsuarioFromInstituicao404 | RemoveUsuarioFromInstituicao409>, {instituicaoId: RemoveUsuarioFromInstituicaoPathParams["instituicaoId"], usuarioId: RemoveUsuarioFromInstituicaoPathParams["usuarioId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? removeUsuarioFromInstituicaoMutationKey()

  const baseOptions = removeUsuarioFromInstituicaoMutationOptions(config) as UseMutationOptions<RemoveUsuarioFromInstituicaoMutationResponse, ResponseErrorConfig<RemoveUsuarioFromInstituicao404 | RemoveUsuarioFromInstituicao409>, {instituicaoId: RemoveUsuarioFromInstituicaoPathParams["instituicaoId"], usuarioId: RemoveUsuarioFromInstituicaoPathParams["usuarioId"]}, TContext>

  return useMutation<RemoveUsuarioFromInstituicaoMutationResponse, ResponseErrorConfig<RemoveUsuarioFromInstituicao404 | RemoveUsuarioFromInstituicao409>, {instituicaoId: RemoveUsuarioFromInstituicaoPathParams["instituicaoId"], usuarioId: RemoveUsuarioFromInstituicaoPathParams["usuarioId"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<RemoveUsuarioFromInstituicaoMutationResponse, ResponseErrorConfig<RemoveUsuarioFromInstituicao404 | RemoveUsuarioFromInstituicao409>, {instituicaoId: RemoveUsuarioFromInstituicaoPathParams["instituicaoId"], usuarioId: RemoveUsuarioFromInstituicaoPathParams["usuarioId"]}, TContext>
}