/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { UpdateInstituicaoMutationRequest, UpdateInstituicaoMutationResponse, UpdateInstituicaoPathParams, UpdateInstituicao404, UpdateInstituicao422 } from "../../models/UpdateInstituicao.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { updateInstituicao } from "../../client/updateInstituicao.ts";

export const updateInstituicaoMutationKey = () => [{ url: '/instituicoes/:id' }] as const

export type UpdateInstituicaoMutationKey = ReturnType<typeof updateInstituicaoMutationKey>

export function updateInstituicaoMutationOptions(config: Partial<RequestConfig<UpdateInstituicaoMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = updateInstituicaoMutationKey()
  return mutationOptions<UpdateInstituicaoMutationResponse, ResponseErrorConfig<UpdateInstituicao404 | UpdateInstituicao422>, {id: UpdateInstituicaoPathParams["id"], data: UpdateInstituicaoMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return updateInstituicao(id, data, config)
    },
  })
}

/**
 * @summary Atualiza as informações de uma Instituição de Ensino
 * {@link /instituicoes/:id}
 */
export function useUpdateInstituicao<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateInstituicaoMutationResponse, ResponseErrorConfig<UpdateInstituicao404 | UpdateInstituicao422>, {id: UpdateInstituicaoPathParams["id"], data: UpdateInstituicaoMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateInstituicaoMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updateInstituicaoMutationKey()

  const baseOptions = updateInstituicaoMutationOptions(config) as UseMutationOptions<UpdateInstituicaoMutationResponse, ResponseErrorConfig<UpdateInstituicao404 | UpdateInstituicao422>, {id: UpdateInstituicaoPathParams["id"], data: UpdateInstituicaoMutationRequest}, TContext>

  return useMutation<UpdateInstituicaoMutationResponse, ResponseErrorConfig<UpdateInstituicao404 | UpdateInstituicao422>, {id: UpdateInstituicaoPathParams["id"], data: UpdateInstituicaoMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<UpdateInstituicaoMutationResponse, ResponseErrorConfig<UpdateInstituicao404 | UpdateInstituicao422>, {id: UpdateInstituicaoPathParams["id"], data: UpdateInstituicaoMutationRequest}, TContext>
}