/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { CreateTarefaMutationRequest, CreateTarefaMutationResponse } from "../../models/CreateTarefa.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { createTarefa } from "../../client/createTarefa.ts";

export const createTarefaMutationKey = () => [{ url: '/tarefas' }] as const

export type CreateTarefaMutationKey = ReturnType<typeof createTarefaMutationKey>

export function createTarefaMutationOptions(config: Partial<RequestConfig<CreateTarefaMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = createTarefaMutationKey()
  return mutationOptions<CreateTarefaMutationResponse, ResponseErrorConfig<Error>, {data: CreateTarefaMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return createTarefa(data, config)
    },
  })
}

/**
 * @summary Cria uma nova tarefa
 * {@link /tarefas}
 */
export function useCreateTarefa<TContext>(options: 
{
  mutation?: UseMutationOptions<CreateTarefaMutationResponse, ResponseErrorConfig<Error>, {data: CreateTarefaMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreateTarefaMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createTarefaMutationKey()

  const baseOptions = createTarefaMutationOptions(config) as UseMutationOptions<CreateTarefaMutationResponse, ResponseErrorConfig<Error>, {data: CreateTarefaMutationRequest}, TContext>

  return useMutation<CreateTarefaMutationResponse, ResponseErrorConfig<Error>, {data: CreateTarefaMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreateTarefaMutationResponse, ResponseErrorConfig<Error>, {data: CreateTarefaMutationRequest}, TContext>
}