/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetTarefasByDisciplinaQueryResponse, GetTarefasByDisciplinaPathParams } from "../../models/GetTarefasByDisciplina.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getTarefasByDisciplina } from "../../client/getTarefasByDisciplina.ts";

export const getTarefasByDisciplinaSuspenseQueryKey = (disciplinaId: GetTarefasByDisciplinaPathParams["disciplinaId"]) => [{ url: '/tarefas/disciplina/:disciplinaId', params: {disciplinaId:disciplinaId} }] as const

export type GetTarefasByDisciplinaSuspenseQueryKey = ReturnType<typeof getTarefasByDisciplinaSuspenseQueryKey>

export function getTarefasByDisciplinaSuspenseQueryOptions(disciplinaId: GetTarefasByDisciplinaPathParams["disciplinaId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getTarefasByDisciplinaSuspenseQueryKey(disciplinaId)
  return queryOptions<GetTarefasByDisciplinaQueryResponse, ResponseErrorConfig<Error>, GetTarefasByDisciplinaQueryResponse, typeof queryKey>({
   enabled: !!(disciplinaId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getTarefasByDisciplina(disciplinaId, config)
   },
  })
}

/**
 * @summary Lista todas as tarefas de uma disciplina
 * {@link /tarefas/disciplina/:disciplinaId}
 */
export function useGetTarefasByDisciplinaSuspense<TData = GetTarefasByDisciplinaQueryResponse, TQueryKey extends QueryKey = GetTarefasByDisciplinaSuspenseQueryKey>(disciplinaId: GetTarefasByDisciplinaPathParams["disciplinaId"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetTarefasByDisciplinaQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getTarefasByDisciplinaSuspenseQueryKey(disciplinaId)

  const query = useSuspenseQuery({
   ...getTarefasByDisciplinaSuspenseQueryOptions(disciplinaId, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}