/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetTarefasByDisciplinaQueryResponse, GetTarefasByDisciplinaPathParams } from "../../models/GetTarefasByDisciplina.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getTarefasByDisciplina } from "../../client/getTarefasByDisciplina.ts";

export const getTarefasByDisciplinaQueryKey = (disciplinaId: GetTarefasByDisciplinaPathParams["disciplinaId"]) => [{ url: '/tarefas/disciplina/:disciplinaId', params: {disciplinaId:disciplinaId} }] as const

export type GetTarefasByDisciplinaQueryKey = ReturnType<typeof getTarefasByDisciplinaQueryKey>

export function getTarefasByDisciplinaQueryOptions(disciplinaId: GetTarefasByDisciplinaPathParams["disciplinaId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getTarefasByDisciplinaQueryKey(disciplinaId)
  return queryOptions<GetTarefasByDisciplinaQueryResponse, ResponseErrorConfig<Error>, GetTarefasByDisciplinaQueryResponse, typeof queryKey>({
   enabled: !!(disciplinaId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getTarefasByDisciplina(disciplinaId, config)
   },
  })
}

/**
 * @summary Lista todas as tarefas de uma disciplina
 * {@link /tarefas/disciplina/:disciplinaId}
 */
export function useGetTarefasByDisciplina<TData = GetTarefasByDisciplinaQueryResponse, TQueryData = GetTarefasByDisciplinaQueryResponse, TQueryKey extends QueryKey = GetTarefasByDisciplinaQueryKey>(disciplinaId: GetTarefasByDisciplinaPathParams["disciplinaId"], options: 
{
  query?: Partial<QueryObserverOptions<GetTarefasByDisciplinaQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getTarefasByDisciplinaQueryKey(disciplinaId)

  const query = useQuery({
   ...getTarefasByDisciplinaQueryOptions(disciplinaId, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}