/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetTarefaByIdQueryResponse, GetTarefaByIdPathParams } from "../../models/GetTarefaById.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getTarefaById } from "../../client/getTarefaById.ts";

export const getTarefaByIdSuspenseQueryKey = (id: GetTarefaByIdPathParams["id"]) => [{ url: '/tarefas/:id', params: {id:id} }] as const

export type GetTarefaByIdSuspenseQueryKey = ReturnType<typeof getTarefaByIdSuspenseQueryKey>

export function getTarefaByIdSuspenseQueryOptions(id: GetTarefaByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getTarefaByIdSuspenseQueryKey(id)
  return queryOptions<GetTarefaByIdQueryResponse, ResponseErrorConfig<Error>, GetTarefaByIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getTarefaById(id, config)
   },
  })
}

/**
 * @summary Busca uma tarefa pelo ID
 * {@link /tarefas/:id}
 */
export function useGetTarefaByIdSuspense<TData = GetTarefaByIdQueryResponse, TQueryKey extends QueryKey = GetTarefaByIdSuspenseQueryKey>(id: GetTarefaByIdPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetTarefaByIdQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getTarefaByIdSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...getTarefaByIdSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}