/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetTarefaByIdQueryResponse, GetTarefaByIdPathParams } from "../../models/GetTarefaById.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getTarefaById } from "../../client/getTarefaById.ts";

export const getTarefaByIdQueryKey = (id: GetTarefaByIdPathParams["id"]) => [{ url: '/tarefas/:id', params: {id:id} }] as const

export type GetTarefaByIdQueryKey = ReturnType<typeof getTarefaByIdQueryKey>

export function getTarefaByIdQueryOptions(id: GetTarefaByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getTarefaByIdQueryKey(id)
  return queryOptions<GetTarefaByIdQueryResponse, ResponseErrorConfig<Error>, GetTarefaByIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getTarefaById(id, config)
   },
  })
}

/**
 * @summary Busca uma tarefa pelo ID
 * {@link /tarefas/:id}
 */
export function useGetTarefaById<TData = GetTarefaByIdQueryResponse, TQueryData = GetTarefaByIdQueryResponse, TQueryKey extends QueryKey = GetTarefaByIdQueryKey>(id: GetTarefaByIdPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<GetTarefaByIdQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getTarefaByIdQueryKey(id)

  const query = useQuery({
   ...getTarefaByIdQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}