/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { RemoveTarefaMutationResponse, RemoveTarefaPathParams } from "../../models/RemoveTarefa.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { removeTarefa } from "../../client/removeTarefa.ts";

export const removeTarefaMutationKey = () => [{ url: '/tarefas/:id' }] as const

export type RemoveTarefaMutationKey = ReturnType<typeof removeTarefaMutationKey>

export function removeTarefaMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = removeTarefaMutationKey()
  return mutationOptions<RemoveTarefaMutationResponse, ResponseErrorConfig<Error>, {id: RemoveTarefaPathParams["id"]}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id }) => {
      return removeTarefa(id, config)
    },
  })
}

/**
 * @summary Remove uma tarefa existente
 * {@link /tarefas/:id}
 */
export function useRemoveTarefa<TContext>(options: 
{
  mutation?: UseMutationOptions<RemoveTarefaMutationResponse, ResponseErrorConfig<Error>, {id: RemoveTarefaPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? removeTarefaMutationKey()

  const baseOptions = removeTarefaMutationOptions(config) as UseMutationOptions<RemoveTarefaMutationResponse, ResponseErrorConfig<Error>, {id: RemoveTarefaPathParams["id"]}, TContext>

  return useMutation<RemoveTarefaMutationResponse, ResponseErrorConfig<Error>, {id: RemoveTarefaPathParams["id"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<RemoveTarefaMutationResponse, ResponseErrorConfig<Error>, {id: RemoveTarefaPathParams["id"]}, TContext>
}