/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { UpdateTarefaMutationRequest, UpdateTarefaMutationResponse, UpdateTarefaPathParams } from "../../models/UpdateTarefa.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { updateTarefa } from "../../client/updateTarefa.ts";

export const updateTarefaMutationKey = () => [{ url: '/tarefas/:id' }] as const

export type UpdateTarefaMutationKey = ReturnType<typeof updateTarefaMutationKey>

export function updateTarefaMutationOptions(config: Partial<RequestConfig<UpdateTarefaMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = updateTarefaMutationKey()
  return mutationOptions<UpdateTarefaMutationResponse, ResponseErrorConfig<Error>, {id: UpdateTarefaPathParams["id"], data?: UpdateTarefaMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return updateTarefa(id, data, config)
    },
  })
}

/**
 * @summary Atualiza uma tarefa existente
 * {@link /tarefas/:id}
 */
export function useUpdateTarefa<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateTarefaMutationResponse, ResponseErrorConfig<Error>, {id: UpdateTarefaPathParams["id"], data?: UpdateTarefaMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateTarefaMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updateTarefaMutationKey()

  const baseOptions = updateTarefaMutationOptions(config) as UseMutationOptions<UpdateTarefaMutationResponse, ResponseErrorConfig<Error>, {id: UpdateTarefaPathParams["id"], data?: UpdateTarefaMutationRequest}, TContext>

  return useMutation<UpdateTarefaMutationResponse, ResponseErrorConfig<Error>, {id: UpdateTarefaPathParams["id"], data?: UpdateTarefaMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<UpdateTarefaMutationResponse, ResponseErrorConfig<Error>, {id: UpdateTarefaPathParams["id"], data?: UpdateTarefaMutationRequest}, TContext>
}