/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetPerfilByEstudanteIdQueryResponse, GetPerfilByEstudanteIdPathParams, GetPerfilByEstudanteId404 } from "../../models/GetPerfilByEstudanteId.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getPerfilByEstudanteId } from "../../client/getPerfilByEstudanteId.ts";

export const getPerfilByEstudanteIdQueryKey = (id: GetPerfilByEstudanteIdPathParams["id"]) => [{ url: '/acessibilidade/estudante/:id', params: {id:id} }] as const

export type GetPerfilByEstudanteIdQueryKey = ReturnType<typeof getPerfilByEstudanteIdQueryKey>

export function getPerfilByEstudanteIdQueryOptions(id: GetPerfilByEstudanteIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getPerfilByEstudanteIdQueryKey(id)
  return queryOptions<GetPerfilByEstudanteIdQueryResponse, ResponseErrorConfig<GetPerfilByEstudanteId404>, GetPerfilByEstudanteIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getPerfilByEstudanteId(id, config)
   },
  })
}

/**
 * @summary Busca um Perfil de Acessibilidade de acordo com seu Estudante
 * {@link /acessibilidade/estudante/:id}
 */
export function useGetPerfilByEstudanteId<TData = GetPerfilByEstudanteIdQueryResponse, TQueryData = GetPerfilByEstudanteIdQueryResponse, TQueryKey extends QueryKey = GetPerfilByEstudanteIdQueryKey>(id: GetPerfilByEstudanteIdPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<GetPerfilByEstudanteIdQueryResponse, ResponseErrorConfig<GetPerfilByEstudanteId404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getPerfilByEstudanteIdQueryKey(id)

  const query = useQuery({
   ...getPerfilByEstudanteIdQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetPerfilByEstudanteId404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}