/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetPerfilByIdQueryResponse, GetPerfilByIdPathParams, GetPerfilById404 } from "../../models/GetPerfilById.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getPerfilById } from "../../client/getPerfilById.ts";

export const getPerfilByIdQueryKey = (id: GetPerfilByIdPathParams["id"]) => [{ url: '/acessibilidade/:id', params: {id:id} }] as const

export type GetPerfilByIdQueryKey = ReturnType<typeof getPerfilByIdQueryKey>

export function getPerfilByIdQueryOptions(id: GetPerfilByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getPerfilByIdQueryKey(id)
  return queryOptions<GetPerfilByIdQueryResponse, ResponseErrorConfig<GetPerfilById404>, GetPerfilByIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getPerfilById(id, config)
   },
  })
}

/**
 * @summary Busca um Perfil de Acessibilidade de acordo com seu ID
 * {@link /acessibilidade/:id}
 */
export function useGetPerfilById<TData = GetPerfilByIdQueryResponse, TQueryData = GetPerfilByIdQueryResponse, TQueryKey extends QueryKey = GetPerfilByIdQueryKey>(id: GetPerfilByIdPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<GetPerfilByIdQueryResponse, ResponseErrorConfig<GetPerfilById404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getPerfilByIdQueryKey(id)

  const query = useQuery({
   ...getPerfilByIdQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetPerfilById404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}