/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetPerfilByIdQueryResponse, GetPerfilByIdPathParams, GetPerfilById404 } from "../../models/GetPerfilById.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getPerfilById } from "../../client/getPerfilById.ts";

export const getPerfilByIdSuspenseQueryKey = (id: GetPerfilByIdPathParams["id"]) => [{ url: '/acessibilidade/:id', params: {id:id} }] as const

export type GetPerfilByIdSuspenseQueryKey = ReturnType<typeof getPerfilByIdSuspenseQueryKey>

export function getPerfilByIdSuspenseQueryOptions(id: GetPerfilByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getPerfilByIdSuspenseQueryKey(id)
  return queryOptions<GetPerfilByIdQueryResponse, ResponseErrorConfig<GetPerfilById404>, GetPerfilByIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getPerfilById(id, config)
   },
  })
}

/**
 * @summary Busca um Perfil de Acessibilidade de acordo com seu ID
 * {@link /acessibilidade/:id}
 */
export function useGetPerfilByIdSuspense<TData = GetPerfilByIdQueryResponse, TQueryKey extends QueryKey = GetPerfilByIdSuspenseQueryKey>(id: GetPerfilByIdPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetPerfilByIdQueryResponse, ResponseErrorConfig<GetPerfilById404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getPerfilByIdSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...getPerfilByIdSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetPerfilById404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}