/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetPerfilByEstudanteIdQueryResponse, GetPerfilByEstudanteIdPathParams, GetPerfilByEstudanteId404 } from "../../models/GetPerfilByEstudanteId.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getPerfilByEstudanteId } from "../../client/getPerfilByEstudanteId.ts";

export const getPerfilByEstudanteIdSuspenseQueryKey = (id: GetPerfilByEstudanteIdPathParams["id"]) => [{ url: '/acessibilidade/estudante/:id', params: {id:id} }] as const

export type GetPerfilByEstudanteIdSuspenseQueryKey = ReturnType<typeof getPerfilByEstudanteIdSuspenseQueryKey>

export function getPerfilByEstudanteIdSuspenseQueryOptions(id: GetPerfilByEstudanteIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getPerfilByEstudanteIdSuspenseQueryKey(id)
  return queryOptions<GetPerfilByEstudanteIdQueryResponse, ResponseErrorConfig<GetPerfilByEstudanteId404>, GetPerfilByEstudanteIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getPerfilByEstudanteId(id, config)
   },
  })
}

/**
 * @summary Busca um Perfil de Acessibilidade de acordo com seu Estudante
 * {@link /acessibilidade/estudante/:id}
 */
export function useGetPerfilByEstudanteIdSuspense<TData = GetPerfilByEstudanteIdQueryResponse, TQueryKey extends QueryKey = GetPerfilByEstudanteIdSuspenseQueryKey>(id: GetPerfilByEstudanteIdPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetPerfilByEstudanteIdQueryResponse, ResponseErrorConfig<GetPerfilByEstudanteId404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getPerfilByEstudanteIdSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...getPerfilByEstudanteIdSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetPerfilByEstudanteId404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}