/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { RemovePerfilAcessibilidadeMutationResponse, RemovePerfilAcessibilidadePathParams, RemovePerfilAcessibilidade404 } from "../../models/RemovePerfilAcessibilidade.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { removePerfilAcessibilidade } from "../../client/removePerfilAcessibilidade.ts";

export const removePerfilAcessibilidadeMutationKey = () => [{ url: '/acessibilidade/:id' }] as const

export type RemovePerfilAcessibilidadeMutationKey = ReturnType<typeof removePerfilAcessibilidadeMutationKey>

export function removePerfilAcessibilidadeMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = removePerfilAcessibilidadeMutationKey()
  return mutationOptions<RemovePerfilAcessibilidadeMutationResponse, ResponseErrorConfig<RemovePerfilAcessibilidade404>, {id: RemovePerfilAcessibilidadePathParams["id"]}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id }) => {
      return removePerfilAcessibilidade(id, config)
    },
  })
}

/**
 * @summary Remove um Perfil de Acessibilidade
 * {@link /acessibilidade/:id}
 */
export function useRemovePerfilAcessibilidade<TContext>(options: 
{
  mutation?: UseMutationOptions<RemovePerfilAcessibilidadeMutationResponse, ResponseErrorConfig<RemovePerfilAcessibilidade404>, {id: RemovePerfilAcessibilidadePathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? removePerfilAcessibilidadeMutationKey()

  const baseOptions = removePerfilAcessibilidadeMutationOptions(config) as UseMutationOptions<RemovePerfilAcessibilidadeMutationResponse, ResponseErrorConfig<RemovePerfilAcessibilidade404>, {id: RemovePerfilAcessibilidadePathParams["id"]}, TContext>

  return useMutation<RemovePerfilAcessibilidadeMutationResponse, ResponseErrorConfig<RemovePerfilAcessibilidade404>, {id: RemovePerfilAcessibilidadePathParams["id"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<RemovePerfilAcessibilidadeMutationResponse, ResponseErrorConfig<RemovePerfilAcessibilidade404>, {id: RemovePerfilAcessibilidadePathParams["id"]}, TContext>
}