/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { UpdatePerfilAcessibilidadeMutationRequest, UpdatePerfilAcessibilidadeMutationResponse, UpdatePerfilAcessibilidadePathParams, UpdatePerfilAcessibilidade400, UpdatePerfilAcessibilidade404 } from "../../models/UpdatePerfilAcessibilidade.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { updatePerfilAcessibilidade } from "../../client/updatePerfilAcessibilidade.ts";

export const updatePerfilAcessibilidadeMutationKey = () => [{ url: '/acessibilidade/:id' }] as const

export type UpdatePerfilAcessibilidadeMutationKey = ReturnType<typeof updatePerfilAcessibilidadeMutationKey>

export function updatePerfilAcessibilidadeMutationOptions(config: Partial<RequestConfig<UpdatePerfilAcessibilidadeMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = updatePerfilAcessibilidadeMutationKey()
  return mutationOptions<UpdatePerfilAcessibilidadeMutationResponse, ResponseErrorConfig<UpdatePerfilAcessibilidade400 | UpdatePerfilAcessibilidade404>, {id: UpdatePerfilAcessibilidadePathParams["id"], data?: UpdatePerfilAcessibilidadeMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return updatePerfilAcessibilidade(id, data, config)
    },
  })
}

/**
 * @summary Atualiza um Perfil de Acessibilidade
 * {@link /acessibilidade/:id}
 */
export function useUpdatePerfilAcessibilidade<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdatePerfilAcessibilidadeMutationResponse, ResponseErrorConfig<UpdatePerfilAcessibilidade400 | UpdatePerfilAcessibilidade404>, {id: UpdatePerfilAcessibilidadePathParams["id"], data?: UpdatePerfilAcessibilidadeMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdatePerfilAcessibilidadeMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updatePerfilAcessibilidadeMutationKey()

  const baseOptions = updatePerfilAcessibilidadeMutationOptions(config) as UseMutationOptions<UpdatePerfilAcessibilidadeMutationResponse, ResponseErrorConfig<UpdatePerfilAcessibilidade400 | UpdatePerfilAcessibilidade404>, {id: UpdatePerfilAcessibilidadePathParams["id"], data?: UpdatePerfilAcessibilidadeMutationRequest}, TContext>

  return useMutation<UpdatePerfilAcessibilidadeMutationResponse, ResponseErrorConfig<UpdatePerfilAcessibilidade400 | UpdatePerfilAcessibilidade404>, {id: UpdatePerfilAcessibilidadePathParams["id"], data?: UpdatePerfilAcessibilidadeMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<UpdatePerfilAcessibilidadeMutationResponse, ResponseErrorConfig<UpdatePerfilAcessibilidade400 | UpdatePerfilAcessibilidade404>, {id: UpdatePerfilAcessibilidadePathParams["id"], data?: UpdatePerfilAcessibilidadeMutationRequest}, TContext>
}