/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicLayoutRouteImport } from './routes/_public/layout'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicRedefinirSenhaRouteImport } from './routes/_public/redefinir-senha'
import { Route as PublicRecuperarSenhaRouteImport } from './routes/_public/recuperar-senha'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicCadastroRouteImport } from './routes/_public/cadastro'
import { Route as PrivateHomeRouterRouteImport } from './routes/_private/homeRouter'
import { Route as PrivateGestorLayoutRouteImport } from './routes/_private/gestor/layout'
import { Route as PrivateEstudanteLayoutRouteImport } from './routes/_private/estudante/layout'
import { Route as PrivateEducadorLayoutRouteImport } from './routes/_private/educador/layout'
import { Route as PrivateGestorIndexRouteImport } from './routes/_private/gestor/index'
import { Route as PrivateEstudanteIndexRouteImport } from './routes/_private/estudante/index'
import { Route as PrivateEducadorIndexRouteImport } from './routes/_private/educador/index'
import { Route as PrivateGestorUsuariosRouteImport } from './routes/_private/gestor/usuarios'
import { Route as PrivateGestorRelatoriosRouteImport } from './routes/_private/gestor/relatorios'
import { Route as PrivateGestorPerfilRouteImport } from './routes/_private/gestor/perfil'
import { Route as PrivateGestorEquipesRouteImport } from './routes/_private/gestor/equipes'
import { Route as PrivateGestorDisciplinasRouteImport } from './routes/_private/gestor/disciplinas'
import { Route as PrivateGestorDashboardRouteImport } from './routes/_private/gestor/dashboard'
import { Route as PrivateGestorAjudaRouteImport } from './routes/_private/gestor/ajuda'
import { Route as PrivateGestorAcessibilidadeRouteImport } from './routes/_private/gestor/acessibilidade'
import { Route as PrivateEstudanteTarefasRouteImport } from './routes/_private/estudante/tarefas'
import { Route as PrivateEstudantePerfilRouteImport } from './routes/_private/estudante/perfil'
import { Route as PrivateEstudanteMetricasRouteImport } from './routes/_private/estudante/metricas'
import { Route as PrivateEstudanteDisciplinasRouteImport } from './routes/_private/estudante/disciplinas'
import { Route as PrivateEstudanteDisciplinaEspecificaRouteImport } from './routes/_private/estudante/disciplina-especifica'
import { Route as PrivateEstudanteAjudaRouteImport } from './routes/_private/estudante/ajuda'
import { Route as PrivateEstudanteAcessibilidadeRouteImport } from './routes/_private/estudante/acessibilidade'
import { Route as PrivateEstudanteTarefaRouteImport } from './routes/_private/estudante/$tarefa'
import { Route as PrivateEducadorPublicarRouteImport } from './routes/_private/educador/publicar'
import { Route as PrivateEducadorPerfilRouteImport } from './routes/_private/educador/perfil'
import { Route as PrivateEducadorMetricasRouteImport } from './routes/_private/educador/metricas'
import { Route as PrivateEducadorCorrecaoRouteImport } from './routes/_private/educador/correcao'
import { Route as PrivateEducadorAjudaRouteImport } from './routes/_private/educador/ajuda'
import { Route as PrivateEducadorAcessibilidadeRouteImport } from './routes/_private/educador/acessibilidade'
import { Route as PrivateGestorInstituicaoIndexRouteImport } from './routes/_private/gestor/instituicao/index'
import { Route as PrivateEducadorDisciplinasIndexRouteImport } from './routes/_private/educador/disciplinas/index'
import { Route as PrivateEducadorAtividadesIndexRouteImport } from './routes/_private/educador/atividades/index'
import { Route as PrivateGestorInstituicaoEditarRouteImport } from './routes/_private/gestor/instituicao/editar'
import { Route as PrivateGestorInstituicaoCriarRouteImport } from './routes/_private/gestor/instituicao/criar'
import { Route as PrivateEducadorDisciplinasDisciplinaRouteImport } from './routes/_private/educador/disciplinas/$disciplina'
import { Route as PrivateEducadorAtividadesCriarRouteImport } from './routes/_private/educador/atividades/criar'
import { Route as PrivateEducadorAtividadesIdEditarRouteImport } from './routes/_private/educador/atividades/$id/editar'

const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicRedefinirSenhaRoute = PublicRedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicRecuperarSenhaRoute = PublicRecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicCadastroRoute = PublicCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PrivateHomeRouterRoute = PrivateHomeRouterRouteImport.update({
  id: '/_private/homeRouter',
  path: '/homeRouter',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateGestorLayoutRoute = PrivateGestorLayoutRouteImport.update({
  id: '/_private/gestor',
  path: '/gestor',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateEstudanteLayoutRoute = PrivateEstudanteLayoutRouteImport.update({
  id: '/_private/estudante',
  path: '/estudante',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateEducadorLayoutRoute = PrivateEducadorLayoutRouteImport.update({
  id: '/_private/educador',
  path: '/educador',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateGestorIndexRoute = PrivateGestorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateGestorLayoutRoute,
} as any)
const PrivateEstudanteIndexRoute = PrivateEstudanteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateEstudanteLayoutRoute,
} as any)
const PrivateEducadorIndexRoute = PrivateEducadorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateEducadorLayoutRoute,
} as any)
const PrivateGestorUsuariosRoute = PrivateGestorUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => PrivateGestorLayoutRoute,
} as any)
const PrivateGestorRelatoriosRoute = PrivateGestorRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => PrivateGestorLayoutRoute,
} as any)
const PrivateGestorPerfilRoute = PrivateGestorPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PrivateGestorLayoutRoute,
} as any)
const PrivateGestorEquipesRoute = PrivateGestorEquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => PrivateGestorLayoutRoute,
} as any)
const PrivateGestorDisciplinasRoute =
  PrivateGestorDisciplinasRouteImport.update({
    id: '/disciplinas',
    path: '/disciplinas',
    getParentRoute: () => PrivateGestorLayoutRoute,
  } as any)
const PrivateGestorDashboardRoute = PrivateGestorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateGestorLayoutRoute,
} as any)
const PrivateGestorAjudaRoute = PrivateGestorAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => PrivateGestorLayoutRoute,
} as any)
const PrivateGestorAcessibilidadeRoute =
  PrivateGestorAcessibilidadeRouteImport.update({
    id: '/acessibilidade',
    path: '/acessibilidade',
    getParentRoute: () => PrivateGestorLayoutRoute,
  } as any)
const PrivateEstudanteTarefasRoute = PrivateEstudanteTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => PrivateEstudanteLayoutRoute,
} as any)
const PrivateEstudantePerfilRoute = PrivateEstudantePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PrivateEstudanteLayoutRoute,
} as any)
const PrivateEstudanteMetricasRoute =
  PrivateEstudanteMetricasRouteImport.update({
    id: '/metricas',
    path: '/metricas',
    getParentRoute: () => PrivateEstudanteLayoutRoute,
  } as any)
const PrivateEstudanteDisciplinasRoute =
  PrivateEstudanteDisciplinasRouteImport.update({
    id: '/disciplinas',
    path: '/disciplinas',
    getParentRoute: () => PrivateEstudanteLayoutRoute,
  } as any)
const PrivateEstudanteDisciplinaEspecificaRoute =
  PrivateEstudanteDisciplinaEspecificaRouteImport.update({
    id: '/disciplina-especifica',
    path: '/disciplina-especifica',
    getParentRoute: () => PrivateEstudanteLayoutRoute,
  } as any)
const PrivateEstudanteAjudaRoute = PrivateEstudanteAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => PrivateEstudanteLayoutRoute,
} as any)
const PrivateEstudanteAcessibilidadeRoute =
  PrivateEstudanteAcessibilidadeRouteImport.update({
    id: '/acessibilidade',
    path: '/acessibilidade',
    getParentRoute: () => PrivateEstudanteLayoutRoute,
  } as any)
const PrivateEstudanteTarefaRoute = PrivateEstudanteTarefaRouteImport.update({
  id: '/$tarefa',
  path: '/$tarefa',
  getParentRoute: () => PrivateEstudanteLayoutRoute,
} as any)
const PrivateEducadorPublicarRoute = PrivateEducadorPublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => PrivateEducadorLayoutRoute,
} as any)
const PrivateEducadorPerfilRoute = PrivateEducadorPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PrivateEducadorLayoutRoute,
} as any)
const PrivateEducadorMetricasRoute = PrivateEducadorMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => PrivateEducadorLayoutRoute,
} as any)
const PrivateEducadorCorrecaoRoute = PrivateEducadorCorrecaoRouteImport.update({
  id: '/correcao',
  path: '/correcao',
  getParentRoute: () => PrivateEducadorLayoutRoute,
} as any)
const PrivateEducadorAjudaRoute = PrivateEducadorAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => PrivateEducadorLayoutRoute,
} as any)
const PrivateEducadorAcessibilidadeRoute =
  PrivateEducadorAcessibilidadeRouteImport.update({
    id: '/acessibilidade',
    path: '/acessibilidade',
    getParentRoute: () => PrivateEducadorLayoutRoute,
  } as any)
const PrivateGestorInstituicaoIndexRoute =
  PrivateGestorInstituicaoIndexRouteImport.update({
    id: '/instituicao/',
    path: '/instituicao/',
    getParentRoute: () => PrivateGestorLayoutRoute,
  } as any)
const PrivateEducadorDisciplinasIndexRoute =
  PrivateEducadorDisciplinasIndexRouteImport.update({
    id: '/disciplinas/',
    path: '/disciplinas/',
    getParentRoute: () => PrivateEducadorLayoutRoute,
  } as any)
const PrivateEducadorAtividadesIndexRoute =
  PrivateEducadorAtividadesIndexRouteImport.update({
    id: '/atividades/',
    path: '/atividades/',
    getParentRoute: () => PrivateEducadorLayoutRoute,
  } as any)
const PrivateGestorInstituicaoEditarRoute =
  PrivateGestorInstituicaoEditarRouteImport.update({
    id: '/instituicao/editar',
    path: '/instituicao/editar',
    getParentRoute: () => PrivateGestorLayoutRoute,
  } as any)
const PrivateGestorInstituicaoCriarRoute =
  PrivateGestorInstituicaoCriarRouteImport.update({
    id: '/instituicao/criar',
    path: '/instituicao/criar',
    getParentRoute: () => PrivateGestorLayoutRoute,
  } as any)
const PrivateEducadorDisciplinasDisciplinaRoute =
  PrivateEducadorDisciplinasDisciplinaRouteImport.update({
    id: '/disciplinas/$disciplina',
    path: '/disciplinas/$disciplina',
    getParentRoute: () => PrivateEducadorLayoutRoute,
  } as any)
const PrivateEducadorAtividadesCriarRoute =
  PrivateEducadorAtividadesCriarRouteImport.update({
    id: '/atividades/criar',
    path: '/atividades/criar',
    getParentRoute: () => PrivateEducadorLayoutRoute,
  } as any)
const PrivateEducadorAtividadesIdEditarRoute =
  PrivateEducadorAtividadesIdEditarRouteImport.update({
    id: '/atividades/$id/editar',
    path: '/atividades/$id/editar',
    getParentRoute: () => PrivateEducadorLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/educador': typeof PrivateEducadorLayoutRouteWithChildren
  '/estudante': typeof PrivateEstudanteLayoutRouteWithChildren
  '/gestor': typeof PrivateGestorLayoutRouteWithChildren
  '/homeRouter': typeof PrivateHomeRouterRoute
  '/cadastro': typeof PublicCadastroRoute
  '/login': typeof PublicLoginRoute
  '/recuperar-senha': typeof PublicRecuperarSenhaRoute
  '/redefinir-senha': typeof PublicRedefinirSenhaRoute
  '/': typeof PublicIndexRoute
  '/educador/acessibilidade': typeof PrivateEducadorAcessibilidadeRoute
  '/educador/ajuda': typeof PrivateEducadorAjudaRoute
  '/educador/correcao': typeof PrivateEducadorCorrecaoRoute
  '/educador/metricas': typeof PrivateEducadorMetricasRoute
  '/educador/perfil': typeof PrivateEducadorPerfilRoute
  '/educador/publicar': typeof PrivateEducadorPublicarRoute
  '/estudante/$tarefa': typeof PrivateEstudanteTarefaRoute
  '/estudante/acessibilidade': typeof PrivateEstudanteAcessibilidadeRoute
  '/estudante/ajuda': typeof PrivateEstudanteAjudaRoute
  '/estudante/disciplina-especifica': typeof PrivateEstudanteDisciplinaEspecificaRoute
  '/estudante/disciplinas': typeof PrivateEstudanteDisciplinasRoute
  '/estudante/metricas': typeof PrivateEstudanteMetricasRoute
  '/estudante/perfil': typeof PrivateEstudantePerfilRoute
  '/estudante/tarefas': typeof PrivateEstudanteTarefasRoute
  '/gestor/acessibilidade': typeof PrivateGestorAcessibilidadeRoute
  '/gestor/ajuda': typeof PrivateGestorAjudaRoute
  '/gestor/dashboard': typeof PrivateGestorDashboardRoute
  '/gestor/disciplinas': typeof PrivateGestorDisciplinasRoute
  '/gestor/equipes': typeof PrivateGestorEquipesRoute
  '/gestor/perfil': typeof PrivateGestorPerfilRoute
  '/gestor/relatorios': typeof PrivateGestorRelatoriosRoute
  '/gestor/usuarios': typeof PrivateGestorUsuariosRoute
  '/educador/': typeof PrivateEducadorIndexRoute
  '/estudante/': typeof PrivateEstudanteIndexRoute
  '/gestor/': typeof PrivateGestorIndexRoute
  '/educador/atividades/criar': typeof PrivateEducadorAtividadesCriarRoute
  '/educador/disciplinas/$disciplina': typeof PrivateEducadorDisciplinasDisciplinaRoute
  '/gestor/instituicao/criar': typeof PrivateGestorInstituicaoCriarRoute
  '/gestor/instituicao/editar': typeof PrivateGestorInstituicaoEditarRoute
  '/educador/atividades': typeof PrivateEducadorAtividadesIndexRoute
  '/educador/disciplinas': typeof PrivateEducadorDisciplinasIndexRoute
  '/gestor/instituicao': typeof PrivateGestorInstituicaoIndexRoute
  '/educador/atividades/$id/editar': typeof PrivateEducadorAtividadesIdEditarRoute
}
export interface FileRoutesByTo {
  '/homeRouter': typeof PrivateHomeRouterRoute
  '/cadastro': typeof PublicCadastroRoute
  '/login': typeof PublicLoginRoute
  '/recuperar-senha': typeof PublicRecuperarSenhaRoute
  '/redefinir-senha': typeof PublicRedefinirSenhaRoute
  '/': typeof PublicIndexRoute
  '/educador/acessibilidade': typeof PrivateEducadorAcessibilidadeRoute
  '/educador/ajuda': typeof PrivateEducadorAjudaRoute
  '/educador/correcao': typeof PrivateEducadorCorrecaoRoute
  '/educador/metricas': typeof PrivateEducadorMetricasRoute
  '/educador/perfil': typeof PrivateEducadorPerfilRoute
  '/educador/publicar': typeof PrivateEducadorPublicarRoute
  '/estudante/$tarefa': typeof PrivateEstudanteTarefaRoute
  '/estudante/acessibilidade': typeof PrivateEstudanteAcessibilidadeRoute
  '/estudante/ajuda': typeof PrivateEstudanteAjudaRoute
  '/estudante/disciplina-especifica': typeof PrivateEstudanteDisciplinaEspecificaRoute
  '/estudante/disciplinas': typeof PrivateEstudanteDisciplinasRoute
  '/estudante/metricas': typeof PrivateEstudanteMetricasRoute
  '/estudante/perfil': typeof PrivateEstudantePerfilRoute
  '/estudante/tarefas': typeof PrivateEstudanteTarefasRoute
  '/gestor/acessibilidade': typeof PrivateGestorAcessibilidadeRoute
  '/gestor/ajuda': typeof PrivateGestorAjudaRoute
  '/gestor/dashboard': typeof PrivateGestorDashboardRoute
  '/gestor/disciplinas': typeof PrivateGestorDisciplinasRoute
  '/gestor/equipes': typeof PrivateGestorEquipesRoute
  '/gestor/perfil': typeof PrivateGestorPerfilRoute
  '/gestor/relatorios': typeof PrivateGestorRelatoriosRoute
  '/gestor/usuarios': typeof PrivateGestorUsuariosRoute
  '/educador': typeof PrivateEducadorIndexRoute
  '/estudante': typeof PrivateEstudanteIndexRoute
  '/gestor': typeof PrivateGestorIndexRoute
  '/educador/atividades/criar': typeof PrivateEducadorAtividadesCriarRoute
  '/educador/disciplinas/$disciplina': typeof PrivateEducadorDisciplinasDisciplinaRoute
  '/gestor/instituicao/criar': typeof PrivateGestorInstituicaoCriarRoute
  '/gestor/instituicao/editar': typeof PrivateGestorInstituicaoEditarRoute
  '/educador/atividades': typeof PrivateEducadorAtividadesIndexRoute
  '/educador/disciplinas': typeof PrivateEducadorDisciplinasIndexRoute
  '/gestor/instituicao': typeof PrivateGestorInstituicaoIndexRoute
  '/educador/atividades/$id/editar': typeof PrivateEducadorAtividadesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicLayoutRouteWithChildren
  '/_private/educador': typeof PrivateEducadorLayoutRouteWithChildren
  '/_private/estudante': typeof PrivateEstudanteLayoutRouteWithChildren
  '/_private/gestor': typeof PrivateGestorLayoutRouteWithChildren
  '/_private/homeRouter': typeof PrivateHomeRouterRoute
  '/_public/cadastro': typeof PublicCadastroRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/recuperar-senha': typeof PublicRecuperarSenhaRoute
  '/_public/redefinir-senha': typeof PublicRedefinirSenhaRoute
  '/_public/': typeof PublicIndexRoute
  '/_private/educador/acessibilidade': typeof PrivateEducadorAcessibilidadeRoute
  '/_private/educador/ajuda': typeof PrivateEducadorAjudaRoute
  '/_private/educador/correcao': typeof PrivateEducadorCorrecaoRoute
  '/_private/educador/metricas': typeof PrivateEducadorMetricasRoute
  '/_private/educador/perfil': typeof PrivateEducadorPerfilRoute
  '/_private/educador/publicar': typeof PrivateEducadorPublicarRoute
  '/_private/estudante/$tarefa': typeof PrivateEstudanteTarefaRoute
  '/_private/estudante/acessibilidade': typeof PrivateEstudanteAcessibilidadeRoute
  '/_private/estudante/ajuda': typeof PrivateEstudanteAjudaRoute
  '/_private/estudante/disciplina-especifica': typeof PrivateEstudanteDisciplinaEspecificaRoute
  '/_private/estudante/disciplinas': typeof PrivateEstudanteDisciplinasRoute
  '/_private/estudante/metricas': typeof PrivateEstudanteMetricasRoute
  '/_private/estudante/perfil': typeof PrivateEstudantePerfilRoute
  '/_private/estudante/tarefas': typeof PrivateEstudanteTarefasRoute
  '/_private/gestor/acessibilidade': typeof PrivateGestorAcessibilidadeRoute
  '/_private/gestor/ajuda': typeof PrivateGestorAjudaRoute
  '/_private/gestor/dashboard': typeof PrivateGestorDashboardRoute
  '/_private/gestor/disciplinas': typeof PrivateGestorDisciplinasRoute
  '/_private/gestor/equipes': typeof PrivateGestorEquipesRoute
  '/_private/gestor/perfil': typeof PrivateGestorPerfilRoute
  '/_private/gestor/relatorios': typeof PrivateGestorRelatoriosRoute
  '/_private/gestor/usuarios': typeof PrivateGestorUsuariosRoute
  '/_private/educador/': typeof PrivateEducadorIndexRoute
  '/_private/estudante/': typeof PrivateEstudanteIndexRoute
  '/_private/gestor/': typeof PrivateGestorIndexRoute
  '/_private/educador/atividades/criar': typeof PrivateEducadorAtividadesCriarRoute
  '/_private/educador/disciplinas/$disciplina': typeof PrivateEducadorDisciplinasDisciplinaRoute
  '/_private/gestor/instituicao/criar': typeof PrivateGestorInstituicaoCriarRoute
  '/_private/gestor/instituicao/editar': typeof PrivateGestorInstituicaoEditarRoute
  '/_private/educador/atividades/': typeof PrivateEducadorAtividadesIndexRoute
  '/_private/educador/disciplinas/': typeof PrivateEducadorDisciplinasIndexRoute
  '/_private/gestor/instituicao/': typeof PrivateGestorInstituicaoIndexRoute
  '/_private/educador/atividades/$id/editar': typeof PrivateEducadorAtividadesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/educador'
    | '/estudante'
    | '/gestor'
    | '/homeRouter'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/'
    | '/educador/acessibilidade'
    | '/educador/ajuda'
    | '/educador/correcao'
    | '/educador/metricas'
    | '/educador/perfil'
    | '/educador/publicar'
    | '/estudante/$tarefa'
    | '/estudante/acessibilidade'
    | '/estudante/ajuda'
    | '/estudante/disciplina-especifica'
    | '/estudante/disciplinas'
    | '/estudante/metricas'
    | '/estudante/perfil'
    | '/estudante/tarefas'
    | '/gestor/acessibilidade'
    | '/gestor/ajuda'
    | '/gestor/dashboard'
    | '/gestor/disciplinas'
    | '/gestor/equipes'
    | '/gestor/perfil'
    | '/gestor/relatorios'
    | '/gestor/usuarios'
    | '/educador/'
    | '/estudante/'
    | '/gestor/'
    | '/educador/atividades/criar'
    | '/educador/disciplinas/$disciplina'
    | '/gestor/instituicao/criar'
    | '/gestor/instituicao/editar'
    | '/educador/atividades'
    | '/educador/disciplinas'
    | '/gestor/instituicao'
    | '/educador/atividades/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/homeRouter'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/'
    | '/educador/acessibilidade'
    | '/educador/ajuda'
    | '/educador/correcao'
    | '/educador/metricas'
    | '/educador/perfil'
    | '/educador/publicar'
    | '/estudante/$tarefa'
    | '/estudante/acessibilidade'
    | '/estudante/ajuda'
    | '/estudante/disciplina-especifica'
    | '/estudante/disciplinas'
    | '/estudante/metricas'
    | '/estudante/perfil'
    | '/estudante/tarefas'
    | '/gestor/acessibilidade'
    | '/gestor/ajuda'
    | '/gestor/dashboard'
    | '/gestor/disciplinas'
    | '/gestor/equipes'
    | '/gestor/perfil'
    | '/gestor/relatorios'
    | '/gestor/usuarios'
    | '/educador'
    | '/estudante'
    | '/gestor'
    | '/educador/atividades/criar'
    | '/educador/disciplinas/$disciplina'
    | '/gestor/instituicao/criar'
    | '/gestor/instituicao/editar'
    | '/educador/atividades'
    | '/educador/disciplinas'
    | '/gestor/instituicao'
    | '/educador/atividades/$id/editar'
  id:
    | '__root__'
    | '/_public'
    | '/_private/educador'
    | '/_private/estudante'
    | '/_private/gestor'
    | '/_private/homeRouter'
    | '/_public/cadastro'
    | '/_public/login'
    | '/_public/recuperar-senha'
    | '/_public/redefinir-senha'
    | '/_public/'
    | '/_private/educador/acessibilidade'
    | '/_private/educador/ajuda'
    | '/_private/educador/correcao'
    | '/_private/educador/metricas'
    | '/_private/educador/perfil'
    | '/_private/educador/publicar'
    | '/_private/estudante/$tarefa'
    | '/_private/estudante/acessibilidade'
    | '/_private/estudante/ajuda'
    | '/_private/estudante/disciplina-especifica'
    | '/_private/estudante/disciplinas'
    | '/_private/estudante/metricas'
    | '/_private/estudante/perfil'
    | '/_private/estudante/tarefas'
    | '/_private/gestor/acessibilidade'
    | '/_private/gestor/ajuda'
    | '/_private/gestor/dashboard'
    | '/_private/gestor/disciplinas'
    | '/_private/gestor/equipes'
    | '/_private/gestor/perfil'
    | '/_private/gestor/relatorios'
    | '/_private/gestor/usuarios'
    | '/_private/educador/'
    | '/_private/estudante/'
    | '/_private/gestor/'
    | '/_private/educador/atividades/criar'
    | '/_private/educador/disciplinas/$disciplina'
    | '/_private/gestor/instituicao/criar'
    | '/_private/gestor/instituicao/editar'
    | '/_private/educador/atividades/'
    | '/_private/educador/disciplinas/'
    | '/_private/gestor/instituicao/'
    | '/_private/educador/atividades/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  PrivateEducadorLayoutRoute: typeof PrivateEducadorLayoutRouteWithChildren
  PrivateEstudanteLayoutRoute: typeof PrivateEstudanteLayoutRouteWithChildren
  PrivateGestorLayoutRoute: typeof PrivateGestorLayoutRouteWithChildren
  PrivateHomeRouterRoute: typeof PrivateHomeRouterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/redefinir-senha': {
      id: '/_public/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof PublicRedefinirSenhaRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/recuperar-senha': {
      id: '/_public/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof PublicRecuperarSenhaRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/cadastro': {
      id: '/_public/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof PublicCadastroRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_private/homeRouter': {
      id: '/_private/homeRouter'
      path: '/homeRouter'
      fullPath: '/homeRouter'
      preLoaderRoute: typeof PrivateHomeRouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/gestor': {
      id: '/_private/gestor'
      path: '/gestor'
      fullPath: '/gestor'
      preLoaderRoute: typeof PrivateGestorLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/estudante': {
      id: '/_private/estudante'
      path: '/estudante'
      fullPath: '/estudante'
      preLoaderRoute: typeof PrivateEstudanteLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/educador': {
      id: '/_private/educador'
      path: '/educador'
      fullPath: '/educador'
      preLoaderRoute: typeof PrivateEducadorLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/gestor/': {
      id: '/_private/gestor/'
      path: '/'
      fullPath: '/gestor/'
      preLoaderRoute: typeof PrivateGestorIndexRouteImport
      parentRoute: typeof PrivateGestorLayoutRoute
    }
    '/_private/estudante/': {
      id: '/_private/estudante/'
      path: '/'
      fullPath: '/estudante/'
      preLoaderRoute: typeof PrivateEstudanteIndexRouteImport
      parentRoute: typeof PrivateEstudanteLayoutRoute
    }
    '/_private/educador/': {
      id: '/_private/educador/'
      path: '/'
      fullPath: '/educador/'
      preLoaderRoute: typeof PrivateEducadorIndexRouteImport
      parentRoute: typeof PrivateEducadorLayoutRoute
    }
    '/_private/gestor/usuarios': {
      id: '/_private/gestor/usuarios'
      path: '/usuarios'
      fullPath: '/gestor/usuarios'
      preLoaderRoute: typeof PrivateGestorUsuariosRouteImport
      parentRoute: typeof PrivateGestorLayoutRoute
    }
    '/_private/gestor/relatorios': {
      id: '/_private/gestor/relatorios'
      path: '/relatorios'
      fullPath: '/gestor/relatorios'
      preLoaderRoute: typeof PrivateGestorRelatoriosRouteImport
      parentRoute: typeof PrivateGestorLayoutRoute
    }
    '/_private/gestor/perfil': {
      id: '/_private/gestor/perfil'
      path: '/perfil'
      fullPath: '/gestor/perfil'
      preLoaderRoute: typeof PrivateGestorPerfilRouteImport
      parentRoute: typeof PrivateGestorLayoutRoute
    }
    '/_private/gestor/equipes': {
      id: '/_private/gestor/equipes'
      path: '/equipes'
      fullPath: '/gestor/equipes'
      preLoaderRoute: typeof PrivateGestorEquipesRouteImport
      parentRoute: typeof PrivateGestorLayoutRoute
    }
    '/_private/gestor/disciplinas': {
      id: '/_private/gestor/disciplinas'
      path: '/disciplinas'
      fullPath: '/gestor/disciplinas'
      preLoaderRoute: typeof PrivateGestorDisciplinasRouteImport
      parentRoute: typeof PrivateGestorLayoutRoute
    }
    '/_private/gestor/dashboard': {
      id: '/_private/gestor/dashboard'
      path: '/dashboard'
      fullPath: '/gestor/dashboard'
      preLoaderRoute: typeof PrivateGestorDashboardRouteImport
      parentRoute: typeof PrivateGestorLayoutRoute
    }
    '/_private/gestor/ajuda': {
      id: '/_private/gestor/ajuda'
      path: '/ajuda'
      fullPath: '/gestor/ajuda'
      preLoaderRoute: typeof PrivateGestorAjudaRouteImport
      parentRoute: typeof PrivateGestorLayoutRoute
    }
    '/_private/gestor/acessibilidade': {
      id: '/_private/gestor/acessibilidade'
      path: '/acessibilidade'
      fullPath: '/gestor/acessibilidade'
      preLoaderRoute: typeof PrivateGestorAcessibilidadeRouteImport
      parentRoute: typeof PrivateGestorLayoutRoute
    }
    '/_private/estudante/tarefas': {
      id: '/_private/estudante/tarefas'
      path: '/tarefas'
      fullPath: '/estudante/tarefas'
      preLoaderRoute: typeof PrivateEstudanteTarefasRouteImport
      parentRoute: typeof PrivateEstudanteLayoutRoute
    }
    '/_private/estudante/perfil': {
      id: '/_private/estudante/perfil'
      path: '/perfil'
      fullPath: '/estudante/perfil'
      preLoaderRoute: typeof PrivateEstudantePerfilRouteImport
      parentRoute: typeof PrivateEstudanteLayoutRoute
    }
    '/_private/estudante/metricas': {
      id: '/_private/estudante/metricas'
      path: '/metricas'
      fullPath: '/estudante/metricas'
      preLoaderRoute: typeof PrivateEstudanteMetricasRouteImport
      parentRoute: typeof PrivateEstudanteLayoutRoute
    }
    '/_private/estudante/disciplinas': {
      id: '/_private/estudante/disciplinas'
      path: '/disciplinas'
      fullPath: '/estudante/disciplinas'
      preLoaderRoute: typeof PrivateEstudanteDisciplinasRouteImport
      parentRoute: typeof PrivateEstudanteLayoutRoute
    }
    '/_private/estudante/disciplina-especifica': {
      id: '/_private/estudante/disciplina-especifica'
      path: '/disciplina-especifica'
      fullPath: '/estudante/disciplina-especifica'
      preLoaderRoute: typeof PrivateEstudanteDisciplinaEspecificaRouteImport
      parentRoute: typeof PrivateEstudanteLayoutRoute
    }
    '/_private/estudante/ajuda': {
      id: '/_private/estudante/ajuda'
      path: '/ajuda'
      fullPath: '/estudante/ajuda'
      preLoaderRoute: typeof PrivateEstudanteAjudaRouteImport
      parentRoute: typeof PrivateEstudanteLayoutRoute
    }
    '/_private/estudante/acessibilidade': {
      id: '/_private/estudante/acessibilidade'
      path: '/acessibilidade'
      fullPath: '/estudante/acessibilidade'
      preLoaderRoute: typeof PrivateEstudanteAcessibilidadeRouteImport
      parentRoute: typeof PrivateEstudanteLayoutRoute
    }
    '/_private/estudante/$tarefa': {
      id: '/_private/estudante/$tarefa'
      path: '/$tarefa'
      fullPath: '/estudante/$tarefa'
      preLoaderRoute: typeof PrivateEstudanteTarefaRouteImport
      parentRoute: typeof PrivateEstudanteLayoutRoute
    }
    '/_private/educador/publicar': {
      id: '/_private/educador/publicar'
      path: '/publicar'
      fullPath: '/educador/publicar'
      preLoaderRoute: typeof PrivateEducadorPublicarRouteImport
      parentRoute: typeof PrivateEducadorLayoutRoute
    }
    '/_private/educador/perfil': {
      id: '/_private/educador/perfil'
      path: '/perfil'
      fullPath: '/educador/perfil'
      preLoaderRoute: typeof PrivateEducadorPerfilRouteImport
      parentRoute: typeof PrivateEducadorLayoutRoute
    }
    '/_private/educador/metricas': {
      id: '/_private/educador/metricas'
      path: '/metricas'
      fullPath: '/educador/metricas'
      preLoaderRoute: typeof PrivateEducadorMetricasRouteImport
      parentRoute: typeof PrivateEducadorLayoutRoute
    }
    '/_private/educador/correcao': {
      id: '/_private/educador/correcao'
      path: '/correcao'
      fullPath: '/educador/correcao'
      preLoaderRoute: typeof PrivateEducadorCorrecaoRouteImport
      parentRoute: typeof PrivateEducadorLayoutRoute
    }
    '/_private/educador/ajuda': {
      id: '/_private/educador/ajuda'
      path: '/ajuda'
      fullPath: '/educador/ajuda'
      preLoaderRoute: typeof PrivateEducadorAjudaRouteImport
      parentRoute: typeof PrivateEducadorLayoutRoute
    }
    '/_private/educador/acessibilidade': {
      id: '/_private/educador/acessibilidade'
      path: '/acessibilidade'
      fullPath: '/educador/acessibilidade'
      preLoaderRoute: typeof PrivateEducadorAcessibilidadeRouteImport
      parentRoute: typeof PrivateEducadorLayoutRoute
    }
    '/_private/gestor/instituicao/': {
      id: '/_private/gestor/instituicao/'
      path: '/instituicao'
      fullPath: '/gestor/instituicao'
      preLoaderRoute: typeof PrivateGestorInstituicaoIndexRouteImport
      parentRoute: typeof PrivateGestorLayoutRoute
    }
    '/_private/educador/disciplinas/': {
      id: '/_private/educador/disciplinas/'
      path: '/disciplinas'
      fullPath: '/educador/disciplinas'
      preLoaderRoute: typeof PrivateEducadorDisciplinasIndexRouteImport
      parentRoute: typeof PrivateEducadorLayoutRoute
    }
    '/_private/educador/atividades/': {
      id: '/_private/educador/atividades/'
      path: '/atividades'
      fullPath: '/educador/atividades'
      preLoaderRoute: typeof PrivateEducadorAtividadesIndexRouteImport
      parentRoute: typeof PrivateEducadorLayoutRoute
    }
    '/_private/gestor/instituicao/editar': {
      id: '/_private/gestor/instituicao/editar'
      path: '/instituicao/editar'
      fullPath: '/gestor/instituicao/editar'
      preLoaderRoute: typeof PrivateGestorInstituicaoEditarRouteImport
      parentRoute: typeof PrivateGestorLayoutRoute
    }
    '/_private/gestor/instituicao/criar': {
      id: '/_private/gestor/instituicao/criar'
      path: '/instituicao/criar'
      fullPath: '/gestor/instituicao/criar'
      preLoaderRoute: typeof PrivateGestorInstituicaoCriarRouteImport
      parentRoute: typeof PrivateGestorLayoutRoute
    }
    '/_private/educador/disciplinas/$disciplina': {
      id: '/_private/educador/disciplinas/$disciplina'
      path: '/disciplinas/$disciplina'
      fullPath: '/educador/disciplinas/$disciplina'
      preLoaderRoute: typeof PrivateEducadorDisciplinasDisciplinaRouteImport
      parentRoute: typeof PrivateEducadorLayoutRoute
    }
    '/_private/educador/atividades/criar': {
      id: '/_private/educador/atividades/criar'
      path: '/atividades/criar'
      fullPath: '/educador/atividades/criar'
      preLoaderRoute: typeof PrivateEducadorAtividadesCriarRouteImport
      parentRoute: typeof PrivateEducadorLayoutRoute
    }
    '/_private/educador/atividades/$id/editar': {
      id: '/_private/educador/atividades/$id/editar'
      path: '/atividades/$id/editar'
      fullPath: '/educador/atividades/$id/editar'
      preLoaderRoute: typeof PrivateEducadorAtividadesIdEditarRouteImport
      parentRoute: typeof PrivateEducadorLayoutRoute
    }
  }
}

interface PublicLayoutRouteChildren {
  PublicCadastroRoute: typeof PublicCadastroRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRecuperarSenhaRoute: typeof PublicRecuperarSenhaRoute
  PublicRedefinirSenhaRoute: typeof PublicRedefinirSenhaRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicCadastroRoute: PublicCadastroRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRecuperarSenhaRoute: PublicRecuperarSenhaRoute,
  PublicRedefinirSenhaRoute: PublicRedefinirSenhaRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

interface PrivateEducadorLayoutRouteChildren {
  PrivateEducadorAcessibilidadeRoute: typeof PrivateEducadorAcessibilidadeRoute
  PrivateEducadorAjudaRoute: typeof PrivateEducadorAjudaRoute
  PrivateEducadorCorrecaoRoute: typeof PrivateEducadorCorrecaoRoute
  PrivateEducadorMetricasRoute: typeof PrivateEducadorMetricasRoute
  PrivateEducadorPerfilRoute: typeof PrivateEducadorPerfilRoute
  PrivateEducadorPublicarRoute: typeof PrivateEducadorPublicarRoute
  PrivateEducadorIndexRoute: typeof PrivateEducadorIndexRoute
  PrivateEducadorAtividadesCriarRoute: typeof PrivateEducadorAtividadesCriarRoute
  PrivateEducadorDisciplinasDisciplinaRoute: typeof PrivateEducadorDisciplinasDisciplinaRoute
  PrivateEducadorAtividadesIndexRoute: typeof PrivateEducadorAtividadesIndexRoute
  PrivateEducadorDisciplinasIndexRoute: typeof PrivateEducadorDisciplinasIndexRoute
  PrivateEducadorAtividadesIdEditarRoute: typeof PrivateEducadorAtividadesIdEditarRoute
}

const PrivateEducadorLayoutRouteChildren: PrivateEducadorLayoutRouteChildren = {
  PrivateEducadorAcessibilidadeRoute: PrivateEducadorAcessibilidadeRoute,
  PrivateEducadorAjudaRoute: PrivateEducadorAjudaRoute,
  PrivateEducadorCorrecaoRoute: PrivateEducadorCorrecaoRoute,
  PrivateEducadorMetricasRoute: PrivateEducadorMetricasRoute,
  PrivateEducadorPerfilRoute: PrivateEducadorPerfilRoute,
  PrivateEducadorPublicarRoute: PrivateEducadorPublicarRoute,
  PrivateEducadorIndexRoute: PrivateEducadorIndexRoute,
  PrivateEducadorAtividadesCriarRoute: PrivateEducadorAtividadesCriarRoute,
  PrivateEducadorDisciplinasDisciplinaRoute:
    PrivateEducadorDisciplinasDisciplinaRoute,
  PrivateEducadorAtividadesIndexRoute: PrivateEducadorAtividadesIndexRoute,
  PrivateEducadorDisciplinasIndexRoute: PrivateEducadorDisciplinasIndexRoute,
  PrivateEducadorAtividadesIdEditarRoute:
    PrivateEducadorAtividadesIdEditarRoute,
}

const PrivateEducadorLayoutRouteWithChildren =
  PrivateEducadorLayoutRoute._addFileChildren(
    PrivateEducadorLayoutRouteChildren,
  )

interface PrivateEstudanteLayoutRouteChildren {
  PrivateEstudanteTarefaRoute: typeof PrivateEstudanteTarefaRoute
  PrivateEstudanteAcessibilidadeRoute: typeof PrivateEstudanteAcessibilidadeRoute
  PrivateEstudanteAjudaRoute: typeof PrivateEstudanteAjudaRoute
  PrivateEstudanteDisciplinaEspecificaRoute: typeof PrivateEstudanteDisciplinaEspecificaRoute
  PrivateEstudanteDisciplinasRoute: typeof PrivateEstudanteDisciplinasRoute
  PrivateEstudanteMetricasRoute: typeof PrivateEstudanteMetricasRoute
  PrivateEstudantePerfilRoute: typeof PrivateEstudantePerfilRoute
  PrivateEstudanteTarefasRoute: typeof PrivateEstudanteTarefasRoute
  PrivateEstudanteIndexRoute: typeof PrivateEstudanteIndexRoute
}

const PrivateEstudanteLayoutRouteChildren: PrivateEstudanteLayoutRouteChildren =
  {
    PrivateEstudanteTarefaRoute: PrivateEstudanteTarefaRoute,
    PrivateEstudanteAcessibilidadeRoute: PrivateEstudanteAcessibilidadeRoute,
    PrivateEstudanteAjudaRoute: PrivateEstudanteAjudaRoute,
    PrivateEstudanteDisciplinaEspecificaRoute:
      PrivateEstudanteDisciplinaEspecificaRoute,
    PrivateEstudanteDisciplinasRoute: PrivateEstudanteDisciplinasRoute,
    PrivateEstudanteMetricasRoute: PrivateEstudanteMetricasRoute,
    PrivateEstudantePerfilRoute: PrivateEstudantePerfilRoute,
    PrivateEstudanteTarefasRoute: PrivateEstudanteTarefasRoute,
    PrivateEstudanteIndexRoute: PrivateEstudanteIndexRoute,
  }

const PrivateEstudanteLayoutRouteWithChildren =
  PrivateEstudanteLayoutRoute._addFileChildren(
    PrivateEstudanteLayoutRouteChildren,
  )

interface PrivateGestorLayoutRouteChildren {
  PrivateGestorAcessibilidadeRoute: typeof PrivateGestorAcessibilidadeRoute
  PrivateGestorAjudaRoute: typeof PrivateGestorAjudaRoute
  PrivateGestorDashboardRoute: typeof PrivateGestorDashboardRoute
  PrivateGestorDisciplinasRoute: typeof PrivateGestorDisciplinasRoute
  PrivateGestorEquipesRoute: typeof PrivateGestorEquipesRoute
  PrivateGestorPerfilRoute: typeof PrivateGestorPerfilRoute
  PrivateGestorRelatoriosRoute: typeof PrivateGestorRelatoriosRoute
  PrivateGestorUsuariosRoute: typeof PrivateGestorUsuariosRoute
  PrivateGestorIndexRoute: typeof PrivateGestorIndexRoute
  PrivateGestorInstituicaoCriarRoute: typeof PrivateGestorInstituicaoCriarRoute
  PrivateGestorInstituicaoEditarRoute: typeof PrivateGestorInstituicaoEditarRoute
  PrivateGestorInstituicaoIndexRoute: typeof PrivateGestorInstituicaoIndexRoute
}

const PrivateGestorLayoutRouteChildren: PrivateGestorLayoutRouteChildren = {
  PrivateGestorAcessibilidadeRoute: PrivateGestorAcessibilidadeRoute,
  PrivateGestorAjudaRoute: PrivateGestorAjudaRoute,
  PrivateGestorDashboardRoute: PrivateGestorDashboardRoute,
  PrivateGestorDisciplinasRoute: PrivateGestorDisciplinasRoute,
  PrivateGestorEquipesRoute: PrivateGestorEquipesRoute,
  PrivateGestorPerfilRoute: PrivateGestorPerfilRoute,
  PrivateGestorRelatoriosRoute: PrivateGestorRelatoriosRoute,
  PrivateGestorUsuariosRoute: PrivateGestorUsuariosRoute,
  PrivateGestorIndexRoute: PrivateGestorIndexRoute,
  PrivateGestorInstituicaoCriarRoute: PrivateGestorInstituicaoCriarRoute,
  PrivateGestorInstituicaoEditarRoute: PrivateGestorInstituicaoEditarRoute,
  PrivateGestorInstituicaoIndexRoute: PrivateGestorInstituicaoIndexRoute,
}

const PrivateGestorLayoutRouteWithChildren =
  PrivateGestorLayoutRoute._addFileChildren(PrivateGestorLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  PrivateEducadorLayoutRoute: PrivateEducadorLayoutRouteWithChildren,
  PrivateEstudanteLayoutRoute: PrivateEstudanteLayoutRouteWithChildren,
  PrivateGestorLayoutRoute: PrivateGestorLayoutRouteWithChildren,
  PrivateHomeRouterRoute: PrivateHomeRouterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
