/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { AddEstudanteToDisciplinaMutationResponse, AddEstudanteToDisciplinaPathParams, AddEstudanteToDisciplinaQueryParams, AddEstudanteToDisciplina404 } from "../../models/AddEstudanteToDisciplina.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { addEstudanteToDisciplina } from "../../client/addEstudanteToDisciplina.ts";

export const addEstudanteToDisciplinaMutationKey = () => [{ url: '/disciplinas/:id/estudantes' }] as const

export type AddEstudanteToDisciplinaMutationKey = ReturnType<typeof addEstudanteToDisciplinaMutationKey>

export function addEstudanteToDisciplinaMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = addEstudanteToDisciplinaMutationKey()
  return mutationOptions<AddEstudanteToDisciplinaMutationResponse, ResponseErrorConfig<AddEstudanteToDisciplina404>, {id: AddEstudanteToDisciplinaPathParams["id"], params: AddEstudanteToDisciplinaQueryParams}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, params }) => {
      return addEstudanteToDisciplina(id, params, config)
    },
  })
}

/**
 * @summary Adiciona um Estudante a uma Disciplina
 * {@link /disciplinas/:id/estudantes}
 */
export function useAddEstudanteToDisciplina<TContext>(options: 
{
  mutation?: UseMutationOptions<AddEstudanteToDisciplinaMutationResponse, ResponseErrorConfig<AddEstudanteToDisciplina404>, {id: AddEstudanteToDisciplinaPathParams["id"], params: AddEstudanteToDisciplinaQueryParams}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? addEstudanteToDisciplinaMutationKey()

  const baseOptions = addEstudanteToDisciplinaMutationOptions(config) as UseMutationOptions<AddEstudanteToDisciplinaMutationResponse, ResponseErrorConfig<AddEstudanteToDisciplina404>, {id: AddEstudanteToDisciplinaPathParams["id"], params: AddEstudanteToDisciplinaQueryParams}, TContext>

  return useMutation<AddEstudanteToDisciplinaMutationResponse, ResponseErrorConfig<AddEstudanteToDisciplina404>, {id: AddEstudanteToDisciplinaPathParams["id"], params: AddEstudanteToDisciplinaQueryParams}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<AddEstudanteToDisciplinaMutationResponse, ResponseErrorConfig<AddEstudanteToDisciplina404>, {id: AddEstudanteToDisciplinaPathParams["id"], params: AddEstudanteToDisciplinaQueryParams}, TContext>
}