/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { CreateDisciplinaMutationRequest, CreateDisciplinaMutationResponse, CreateDisciplina404, CreateDisciplina409 } from "../../models/CreateDisciplina.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { createDisciplina } from "../../client/createDisciplina.ts";

export const createDisciplinaMutationKey = () => [{ url: '/disciplinas' }] as const

export type CreateDisciplinaMutationKey = ReturnType<typeof createDisciplinaMutationKey>

export function createDisciplinaMutationOptions(config: Partial<RequestConfig<CreateDisciplinaMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = createDisciplinaMutationKey()
  return mutationOptions<CreateDisciplinaMutationResponse, ResponseErrorConfig<CreateDisciplina404 | CreateDisciplina409>, {data: CreateDisciplinaMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return createDisciplina(data, config)
    },
  })
}

/**
 * @summary Cria uma Disciplina
 * {@link /disciplinas}
 */
export function useCreateDisciplina<TContext>(options: 
{
  mutation?: UseMutationOptions<CreateDisciplinaMutationResponse, ResponseErrorConfig<CreateDisciplina404 | CreateDisciplina409>, {data: CreateDisciplinaMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreateDisciplinaMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createDisciplinaMutationKey()

  const baseOptions = createDisciplinaMutationOptions(config) as UseMutationOptions<CreateDisciplinaMutationResponse, ResponseErrorConfig<CreateDisciplina404 | CreateDisciplina409>, {data: CreateDisciplinaMutationRequest}, TContext>

  return useMutation<CreateDisciplinaMutationResponse, ResponseErrorConfig<CreateDisciplina404 | CreateDisciplina409>, {data: CreateDisciplinaMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreateDisciplinaMutationResponse, ResponseErrorConfig<CreateDisciplina404 | CreateDisciplina409>, {data: CreateDisciplinaMutationRequest}, TContext>
}