/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetDisciplinasByEstudanteQueryResponse, GetDisciplinasByEstudanteQueryParams, GetDisciplinasByEstudante404 } from "../../models/GetDisciplinasByEstudante.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getDisciplinasByEstudante } from "../../client/getDisciplinasByEstudante.ts";

export const getDisciplinasByEstudanteSuspenseQueryKey = (params: GetDisciplinasByEstudanteQueryParams) => [{ url: '/disciplinas/estudante' }, ...(params ? [params] : [])] as const

export type GetDisciplinasByEstudanteSuspenseQueryKey = ReturnType<typeof getDisciplinasByEstudanteSuspenseQueryKey>

export function getDisciplinasByEstudanteSuspenseQueryOptions(params: GetDisciplinasByEstudanteQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getDisciplinasByEstudanteSuspenseQueryKey(params)
  return queryOptions<GetDisciplinasByEstudanteQueryResponse, ResponseErrorConfig<GetDisciplinasByEstudante404>, GetDisciplinasByEstudanteQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getDisciplinasByEstudante(params, config)
   },
  })
}

/**
 * @summary Obtém as Disciplinas nas quais um estudante está matriculado
 * {@link /disciplinas/estudante}
 */
export function useGetDisciplinasByEstudanteSuspense<TData = GetDisciplinasByEstudanteQueryResponse, TQueryKey extends QueryKey = GetDisciplinasByEstudanteSuspenseQueryKey>(params: GetDisciplinasByEstudanteQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetDisciplinasByEstudanteQueryResponse, ResponseErrorConfig<GetDisciplinasByEstudante404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getDisciplinasByEstudanteSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...getDisciplinasByEstudanteSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetDisciplinasByEstudante404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}