/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetDisciplinasByEstudanteQueryResponse, GetDisciplinasByEstudanteQueryParams, GetDisciplinasByEstudante404 } from "../../models/GetDisciplinasByEstudante.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getDisciplinasByEstudante } from "../../client/getDisciplinasByEstudante.ts";

export const getDisciplinasByEstudanteQueryKey = (params: GetDisciplinasByEstudanteQueryParams) => [{ url: '/disciplinas/estudante' }, ...(params ? [params] : [])] as const

export type GetDisciplinasByEstudanteQueryKey = ReturnType<typeof getDisciplinasByEstudanteQueryKey>

export function getDisciplinasByEstudanteQueryOptions(params: GetDisciplinasByEstudanteQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getDisciplinasByEstudanteQueryKey(params)
  return queryOptions<GetDisciplinasByEstudanteQueryResponse, ResponseErrorConfig<GetDisciplinasByEstudante404>, GetDisciplinasByEstudanteQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getDisciplinasByEstudante(params, config)
   },
  })
}

/**
 * @summary Obtém as Disciplinas nas quais um estudante está matriculado
 * {@link /disciplinas/estudante}
 */
export function useGetDisciplinasByEstudante<TData = GetDisciplinasByEstudanteQueryResponse, TQueryData = GetDisciplinasByEstudanteQueryResponse, TQueryKey extends QueryKey = GetDisciplinasByEstudanteQueryKey>(params: GetDisciplinasByEstudanteQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetDisciplinasByEstudanteQueryResponse, ResponseErrorConfig<GetDisciplinasByEstudante404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getDisciplinasByEstudanteQueryKey(params)

  const query = useQuery({
   ...getDisciplinasByEstudanteQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetDisciplinasByEstudante404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}