/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetDisciplinasByEducadorQueryResponse, GetDisciplinasByEducadorQueryParams } from "../../models/GetDisciplinasByEducador.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getDisciplinasByEducador } from "../../client/getDisciplinasByEducador.ts";

export const getDisciplinasByEducadorQueryKey = (params: GetDisciplinasByEducadorQueryParams) => [{ url: '/disciplinas/educador' }, ...(params ? [params] : [])] as const

export type GetDisciplinasByEducadorQueryKey = ReturnType<typeof getDisciplinasByEducadorQueryKey>

export function getDisciplinasByEducadorQueryOptions(params: GetDisciplinasByEducadorQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getDisciplinasByEducadorQueryKey(params)
  return queryOptions<GetDisciplinasByEducadorQueryResponse, ResponseErrorConfig<Error>, GetDisciplinasByEducadorQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getDisciplinasByEducador(params, config)
   },
  })
}

/**
 * @summary Obtém as Disciplinas ministradas por um Educador
 * {@link /disciplinas/educador}
 */
export function useGetDisciplinasByEducador<TData = GetDisciplinasByEducadorQueryResponse, TQueryData = GetDisciplinasByEducadorQueryResponse, TQueryKey extends QueryKey = GetDisciplinasByEducadorQueryKey>(params: GetDisciplinasByEducadorQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetDisciplinasByEducadorQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getDisciplinasByEducadorQueryKey(params)

  const query = useQuery({
   ...getDisciplinasByEducadorQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}