/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetEstudantesFromDisciplinaQueryResponse, GetEstudantesFromDisciplinaPathParams, GetEstudantesFromDisciplina404 } from "../../models/GetEstudantesFromDisciplina.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getEstudantesFromDisciplina } from "../../client/getEstudantesFromDisciplina.ts";

export const getEstudantesFromDisciplinaQueryKey = (id: GetEstudantesFromDisciplinaPathParams["id"]) => [{ url: '/disciplinas/:id/estudantes', params: {id:id} }] as const

export type GetEstudantesFromDisciplinaQueryKey = ReturnType<typeof getEstudantesFromDisciplinaQueryKey>

export function getEstudantesFromDisciplinaQueryOptions(id: GetEstudantesFromDisciplinaPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getEstudantesFromDisciplinaQueryKey(id)
  return queryOptions<GetEstudantesFromDisciplinaQueryResponse, ResponseErrorConfig<GetEstudantesFromDisciplina404>, GetEstudantesFromDisciplinaQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getEstudantesFromDisciplina(id, config)
   },
  })
}

/**
 * @summary Obtém os Estudantes matriculados em uma Instituição de Ensino
 * {@link /disciplinas/:id/estudantes}
 */
export function useGetEstudantesFromDisciplina<TData = GetEstudantesFromDisciplinaQueryResponse, TQueryData = GetEstudantesFromDisciplinaQueryResponse, TQueryKey extends QueryKey = GetEstudantesFromDisciplinaQueryKey>(id: GetEstudantesFromDisciplinaPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<GetEstudantesFromDisciplinaQueryResponse, ResponseErrorConfig<GetEstudantesFromDisciplina404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getEstudantesFromDisciplinaQueryKey(id)

  const query = useQuery({
   ...getEstudantesFromDisciplinaQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetEstudantesFromDisciplina404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}