/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetDisciplinasByInstituicaoQueryResponse, GetDisciplinasByInstituicaoQueryParams, GetDisciplinasByInstituicao404 } from "../../models/GetDisciplinasByInstituicao.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getDisciplinasByInstituicao } from "../../client/getDisciplinasByInstituicao.ts";

export const getDisciplinasByInstituicaoSuspenseQueryKey = (params: GetDisciplinasByInstituicaoQueryParams) => [{ url: '/disciplinas/instituicao' }, ...(params ? [params] : [])] as const

export type GetDisciplinasByInstituicaoSuspenseQueryKey = ReturnType<typeof getDisciplinasByInstituicaoSuspenseQueryKey>

export function getDisciplinasByInstituicaoSuspenseQueryOptions(params: GetDisciplinasByInstituicaoQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getDisciplinasByInstituicaoSuspenseQueryKey(params)
  return queryOptions<GetDisciplinasByInstituicaoQueryResponse, ResponseErrorConfig<GetDisciplinasByInstituicao404>, GetDisciplinasByInstituicaoQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getDisciplinasByInstituicao(params, config)
   },
  })
}

/**
 * @summary Obtém as Disciplinas cadastradas em uma determinada Instituição de Ensino
 * {@link /disciplinas/instituicao}
 */
export function useGetDisciplinasByInstituicaoSuspense<TData = GetDisciplinasByInstituicaoQueryResponse, TQueryKey extends QueryKey = GetDisciplinasByInstituicaoSuspenseQueryKey>(params: GetDisciplinasByInstituicaoQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetDisciplinasByInstituicaoQueryResponse, ResponseErrorConfig<GetDisciplinasByInstituicao404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getDisciplinasByInstituicaoSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...getDisciplinasByInstituicaoSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetDisciplinasByInstituicao404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}