/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetDisciplinaByIdQueryResponse, GetDisciplinaByIdPathParams, GetDisciplinaById404 } from "../../models/GetDisciplinaById.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getDisciplinaById } from "../../client/getDisciplinaById.ts";

export const getDisciplinaByIdQueryKey = (id: GetDisciplinaByIdPathParams["id"]) => [{ url: '/disciplinas/:id', params: {id:id} }] as const

export type GetDisciplinaByIdQueryKey = ReturnType<typeof getDisciplinaByIdQueryKey>

export function getDisciplinaByIdQueryOptions(id: GetDisciplinaByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getDisciplinaByIdQueryKey(id)
  return queryOptions<GetDisciplinaByIdQueryResponse, ResponseErrorConfig<GetDisciplinaById404>, GetDisciplinaByIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getDisciplinaById(id, config)
   },
  })
}

/**
 * @summary Obtém uma Disciplina através do seu ID
 * {@link /disciplinas/:id}
 */
export function useGetDisciplinaById<TData = GetDisciplinaByIdQueryResponse, TQueryData = GetDisciplinaByIdQueryResponse, TQueryKey extends QueryKey = GetDisciplinaByIdQueryKey>(id: GetDisciplinaByIdPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<GetDisciplinaByIdQueryResponse, ResponseErrorConfig<GetDisciplinaById404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getDisciplinaByIdQueryKey(id)

  const query = useQuery({
   ...getDisciplinaByIdQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetDisciplinaById404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}