/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetDisciplinaByIdQueryResponse, GetDisciplinaByIdPathParams, GetDisciplinaById404 } from "../../models/GetDisciplinaById.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getDisciplinaById } from "../../client/getDisciplinaById.ts";

export const getDisciplinaByIdSuspenseQueryKey = (id: GetDisciplinaByIdPathParams["id"]) => [{ url: '/disciplinas/:id', params: {id:id} }] as const

export type GetDisciplinaByIdSuspenseQueryKey = ReturnType<typeof getDisciplinaByIdSuspenseQueryKey>

export function getDisciplinaByIdSuspenseQueryOptions(id: GetDisciplinaByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getDisciplinaByIdSuspenseQueryKey(id)
  return queryOptions<GetDisciplinaByIdQueryResponse, ResponseErrorConfig<GetDisciplinaById404>, GetDisciplinaByIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getDisciplinaById(id, config)
   },
  })
}

/**
 * @summary Obtém uma Disciplina através do seu ID
 * {@link /disciplinas/:id}
 */
export function useGetDisciplinaByIdSuspense<TData = GetDisciplinaByIdQueryResponse, TQueryKey extends QueryKey = GetDisciplinaByIdSuspenseQueryKey>(id: GetDisciplinaByIdPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetDisciplinaByIdQueryResponse, ResponseErrorConfig<GetDisciplinaById404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getDisciplinaByIdSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...getDisciplinaByIdSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetDisciplinaById404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}