/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetDisciplinasByEducadorQueryResponse, GetDisciplinasByEducadorQueryParams } from "../../models/GetDisciplinasByEducador.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getDisciplinasByEducador } from "../../client/getDisciplinasByEducador.ts";

export const getDisciplinasByEducadorSuspenseQueryKey = (params: GetDisciplinasByEducadorQueryParams) => [{ url: '/disciplinas/educador' }, ...(params ? [params] : [])] as const

export type GetDisciplinasByEducadorSuspenseQueryKey = ReturnType<typeof getDisciplinasByEducadorSuspenseQueryKey>

export function getDisciplinasByEducadorSuspenseQueryOptions(params: GetDisciplinasByEducadorQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getDisciplinasByEducadorSuspenseQueryKey(params)
  return queryOptions<GetDisciplinasByEducadorQueryResponse, ResponseErrorConfig<Error>, GetDisciplinasByEducadorQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getDisciplinasByEducador(params, config)
   },
  })
}

/**
 * @summary Obtém as Disciplinas ministradas por um Educador
 * {@link /disciplinas/educador}
 */
export function useGetDisciplinasByEducadorSuspense<TData = GetDisciplinasByEducadorQueryResponse, TQueryKey extends QueryKey = GetDisciplinasByEducadorSuspenseQueryKey>(params: GetDisciplinasByEducadorQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetDisciplinasByEducadorQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getDisciplinasByEducadorSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...getDisciplinasByEducadorSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}