/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetEstudantesFromDisciplinaQueryResponse, GetEstudantesFromDisciplinaPathParams, GetEstudantesFromDisciplina404 } from "../../models/GetEstudantesFromDisciplina.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getEstudantesFromDisciplina } from "../../client/getEstudantesFromDisciplina.ts";

export const getEstudantesFromDisciplinaSuspenseQueryKey = (id: GetEstudantesFromDisciplinaPathParams["id"]) => [{ url: '/disciplinas/:id/estudantes', params: {id:id} }] as const

export type GetEstudantesFromDisciplinaSuspenseQueryKey = ReturnType<typeof getEstudantesFromDisciplinaSuspenseQueryKey>

export function getEstudantesFromDisciplinaSuspenseQueryOptions(id: GetEstudantesFromDisciplinaPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getEstudantesFromDisciplinaSuspenseQueryKey(id)
  return queryOptions<GetEstudantesFromDisciplinaQueryResponse, ResponseErrorConfig<GetEstudantesFromDisciplina404>, GetEstudantesFromDisciplinaQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getEstudantesFromDisciplina(id, config)
   },
  })
}

/**
 * @summary Obtém os Estudantes matriculados em uma Instituição de Ensino
 * {@link /disciplinas/:id/estudantes}
 */
export function useGetEstudantesFromDisciplinaSuspense<TData = GetEstudantesFromDisciplinaQueryResponse, TQueryKey extends QueryKey = GetEstudantesFromDisciplinaSuspenseQueryKey>(id: GetEstudantesFromDisciplinaPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetEstudantesFromDisciplinaQueryResponse, ResponseErrorConfig<GetEstudantesFromDisciplina404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getEstudantesFromDisciplinaSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...getEstudantesFromDisciplinaSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetEstudantesFromDisciplina404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}