/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { RemoveEstudanteToDisciplinaMutationResponse, RemoveEstudanteToDisciplinaPathParams, RemoveEstudanteToDisciplinaQueryParams, RemoveEstudanteToDisciplina404 } from "../../models/RemoveEstudanteToDisciplina.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { removeEstudanteToDisciplina } from "../../client/removeEstudanteToDisciplina.ts";

export const removeEstudanteToDisciplinaMutationKey = () => [{ url: '/disciplinas/:id/estudantes' }] as const

export type RemoveEstudanteToDisciplinaMutationKey = ReturnType<typeof removeEstudanteToDisciplinaMutationKey>

export function removeEstudanteToDisciplinaMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = removeEstudanteToDisciplinaMutationKey()
  return mutationOptions<RemoveEstudanteToDisciplinaMutationResponse, ResponseErrorConfig<RemoveEstudanteToDisciplina404>, {id: RemoveEstudanteToDisciplinaPathParams["id"], params: RemoveEstudanteToDisciplinaQueryParams}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, params }) => {
      return removeEstudanteToDisciplina(id, params, config)
    },
  })
}

/**
 * @summary Adiciona um Estudante a uma Disciplina
 * {@link /disciplinas/:id/estudantes}
 */
export function useRemoveEstudanteToDisciplina<TContext>(options: 
{
  mutation?: UseMutationOptions<RemoveEstudanteToDisciplinaMutationResponse, ResponseErrorConfig<RemoveEstudanteToDisciplina404>, {id: RemoveEstudanteToDisciplinaPathParams["id"], params: RemoveEstudanteToDisciplinaQueryParams}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? removeEstudanteToDisciplinaMutationKey()

  const baseOptions = removeEstudanteToDisciplinaMutationOptions(config) as UseMutationOptions<RemoveEstudanteToDisciplinaMutationResponse, ResponseErrorConfig<RemoveEstudanteToDisciplina404>, {id: RemoveEstudanteToDisciplinaPathParams["id"], params: RemoveEstudanteToDisciplinaQueryParams}, TContext>

  return useMutation<RemoveEstudanteToDisciplinaMutationResponse, ResponseErrorConfig<RemoveEstudanteToDisciplina404>, {id: RemoveEstudanteToDisciplinaPathParams["id"], params: RemoveEstudanteToDisciplinaQueryParams}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<RemoveEstudanteToDisciplinaMutationResponse, ResponseErrorConfig<RemoveEstudanteToDisciplina404>, {id: RemoveEstudanteToDisciplinaPathParams["id"], params: RemoveEstudanteToDisciplinaQueryParams}, TContext>
}