/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { UpdateDisciplinaMutationRequest, UpdateDisciplinaMutationResponse, UpdateDisciplinaPathParams, UpdateDisciplina404, UpdateDisciplina409 } from "../../models/UpdateDisciplina.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { updateDisciplina } from "../../client/updateDisciplina.ts";

export const updateDisciplinaMutationKey = () => [{ url: '/disciplinas/:id' }] as const

export type UpdateDisciplinaMutationKey = ReturnType<typeof updateDisciplinaMutationKey>

export function updateDisciplinaMutationOptions(config: Partial<RequestConfig<UpdateDisciplinaMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = updateDisciplinaMutationKey()
  return mutationOptions<UpdateDisciplinaMutationResponse, ResponseErrorConfig<UpdateDisciplina404 | UpdateDisciplina409>, {id: UpdateDisciplinaPathParams["id"], data?: UpdateDisciplinaMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return updateDisciplina(id, data, config)
    },
  })
}

/**
 * @summary Atualiza as informações de uma Disciplina
 * {@link /disciplinas/:id}
 */
export function useUpdateDisciplina<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateDisciplinaMutationResponse, ResponseErrorConfig<UpdateDisciplina404 | UpdateDisciplina409>, {id: UpdateDisciplinaPathParams["id"], data?: UpdateDisciplinaMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateDisciplinaMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updateDisciplinaMutationKey()

  const baseOptions = updateDisciplinaMutationOptions(config) as UseMutationOptions<UpdateDisciplinaMutationResponse, ResponseErrorConfig<UpdateDisciplina404 | UpdateDisciplina409>, {id: UpdateDisciplinaPathParams["id"], data?: UpdateDisciplinaMutationRequest}, TContext>

  return useMutation<UpdateDisciplinaMutationResponse, ResponseErrorConfig<UpdateDisciplina404 | UpdateDisciplina409>, {id: UpdateDisciplinaPathParams["id"], data?: UpdateDisciplinaMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<UpdateDisciplinaMutationResponse, ResponseErrorConfig<UpdateDisciplina404 | UpdateDisciplina409>, {id: UpdateDisciplinaPathParams["id"], data?: UpdateDisciplinaMutationRequest}, TContext>
}