export type { DeletarArquivoMutationKey } from "./arquivoControllerController/useDeletarArquivo.ts";
export type { DownloadArquivoQueryKey } from "./arquivoControllerController/useDownloadArquivo.ts";
export type { DownloadArquivoSuspenseQueryKey } from "./arquivoControllerController/useDownloadArquivoSuspense.ts";
export type { ListarArquivosQueryKey } from "./arquivoControllerController/useListarArquivos.ts";
export type { ListarArquivosSuspenseQueryKey } from "./arquivoControllerController/useListarArquivosSuspense.ts";
export type { UploadArquivoMutationKey } from "./arquivoControllerController/useUploadArquivo.ts";
export type { LoginMutationKey } from "./authenticationController/useLogin.ts";
export type { RegisterMutationKey } from "./authenticationController/useRegister.ts";
export type { GetAllUsuariosQueryKey } from "./buscaDeUsuriosController/useGetAllUsuarios.ts";
export type { GetAllUsuariosSuspenseQueryKey } from "./buscaDeUsuriosController/useGetAllUsuariosSuspense.ts";
export type { GetUsuarioByIdQueryKey } from "./buscaDeUsuriosController/useGetUsuarioById.ts";
export type { GetUsuarioByIdSuspenseQueryKey } from "./buscaDeUsuriosController/useGetUsuarioByIdSuspense.ts";
export type { AdicionarFormacaoMutationKey } from "./EducadoresController/useAdicionarFormacao.ts";
export type { GetEducadorQueryKey } from "./EducadoresController/useGetEducador.ts";
export type { GetEducadorSuspenseQueryKey } from "./EducadoresController/useGetEducadorSuspense.ts";
export type { ListarFormacoesQueryKey } from "./EducadoresController/useListarFormacoes.ts";
export type { ListarFormacoesSuspenseQueryKey } from "./EducadoresController/useListarFormacoesSuspense.ts";
export type { RemoverFormacaoMutationKey } from "./EducadoresController/useRemoverFormacao.ts";
export type { UpdateEducadorMutationKey } from "./EducadoresController/useUpdateEducador.ts";
export type { AtualizarComentarioMutationKey } from "./mduloComentriosController/useAtualizarComentario.ts";
export type { GetComentarioByIdQueryKey } from "./mduloComentriosController/useGetComentarioById.ts";
export type { GetComentarioByIdSuspenseQueryKey } from "./mduloComentriosController/useGetComentarioByIdSuspense.ts";
export type { ObterComentariosDaPublicacaoQueryKey } from "./mduloComentriosController/useObterComentariosDaPublicacao.ts";
export type { ObterComentariosDaPublicacaoSuspenseQueryKey } from "./mduloComentriosController/useObterComentariosDaPublicacaoSuspense.ts";
export type { RemoverComentarioMutationKey } from "./mduloComentriosController/useRemoverComentario.ts";
export type { ResponderComentarioMutationKey } from "./mduloComentriosController/useResponderComentario.ts";
export type { ResponderPublicacaoMutationKey } from "./mduloComentriosController/useResponderPublicacao.ts";
export type { AtualizarMutationKey } from "./mduloDeEstudantesController/useAtualizar.ts";
export type { BuscarPorIdQueryKey } from "./mduloDeEstudantesController/useBuscarPorId.ts";
export type { BuscarPorIdSuspenseQueryKey } from "./mduloDeEstudantesController/useBuscarPorIdSuspense.ts";
export type { ListarQueryKey } from "./mduloDeEstudantesController/useListar.ts";
export type { ListarSuspenseQueryKey } from "./mduloDeEstudantesController/useListarSuspense.ts";
export type { RemoverMutationKey } from "./mduloDeEstudantesController/useRemover.ts";
export type { GetGestorByEmailQueryKey } from "./mduloDeGestoresController/useGetGestorByEmail.ts";
export type { GetGestorByEmailSuspenseQueryKey } from "./mduloDeGestoresController/useGetGestorByEmailSuspense.ts";
export type { GetGestorByIdQueryKey } from "./mduloDeGestoresController/useGetGestorById.ts";
export type { GetGestorByIdSuspenseQueryKey } from "./mduloDeGestoresController/useGetGestorByIdSuspense.ts";
export type { UpdateGestorMutationKey } from "./mduloDeGestoresController/useUpdateGestor.ts";
export type { AddEstudanteToDisciplinaMutationKey } from "./mduloDisciplinasController/useAddEstudanteToDisciplina.ts";
export type { CreateDisciplinaMutationKey } from "./mduloDisciplinasController/useCreateDisciplina.ts";
export type { GetDisciplinaByIdQueryKey } from "./mduloDisciplinasController/useGetDisciplinaById.ts";
export type { GetDisciplinaByIdSuspenseQueryKey } from "./mduloDisciplinasController/useGetDisciplinaByIdSuspense.ts";
export type { GetDisciplinasByEducadorQueryKey } from "./mduloDisciplinasController/useGetDisciplinasByEducador.ts";
export type { GetDisciplinasByEducadorSuspenseQueryKey } from "./mduloDisciplinasController/useGetDisciplinasByEducadorSuspense.ts";
export type { GetDisciplinasByEstudanteQueryKey } from "./mduloDisciplinasController/useGetDisciplinasByEstudante.ts";
export type { GetDisciplinasByEstudanteSuspenseQueryKey } from "./mduloDisciplinasController/useGetDisciplinasByEstudanteSuspense.ts";
export type { GetDisciplinasByInstituicaoQueryKey } from "./mduloDisciplinasController/useGetDisciplinasByInstituicao.ts";
export type { GetDisciplinasByInstituicaoSuspenseQueryKey } from "./mduloDisciplinasController/useGetDisciplinasByInstituicaoSuspense.ts";
export type { GetEstudantesFromDisciplinaQueryKey } from "./mduloDisciplinasController/useGetEstudantesFromDisciplina.ts";
export type { GetEstudantesFromDisciplinaSuspenseQueryKey } from "./mduloDisciplinasController/useGetEstudantesFromDisciplinaSuspense.ts";
export type { RemoveEstudanteToDisciplinaMutationKey } from "./mduloDisciplinasController/useRemoveEstudanteToDisciplina.ts";
export type { UpdateDisciplinaMutationKey } from "./mduloDisciplinasController/useUpdateDisciplina.ts";
export type { AddUsuarioToInstituicaoMutationKey } from "./mduloInstituiesDeEnsinoController/useAddUsuarioToInstituicao.ts";
export type { CreateInstituicaoMutationKey } from "./mduloInstituiesDeEnsinoController/useCreateInstituicao.ts";
export type { GetInstituicaoByCnpjQueryKey } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByCnpj.ts";
export type { GetInstituicaoByCnpjSuspenseQueryKey } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByCnpjSuspense.ts";
export type { GetInstituicaoByEmailQueryKey } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByEmail.ts";
export type { GetInstituicaoByEmailSuspenseQueryKey } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByEmailSuspense.ts";
export type { GetInstituicaoByIdQueryKey } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoById.ts";
export type { GetInstituicaoByIdSuspenseQueryKey } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByIdSuspense.ts";
export type { GetInstituicoesQueryKey } from "./mduloInstituiesDeEnsinoController/useGetInstituicoes.ts";
export type { GetInstituicoesSuspenseQueryKey } from "./mduloInstituiesDeEnsinoController/useGetInstituicoesSuspense.ts";
export type { GetUsuariosFromInstituicaoQueryKey } from "./mduloInstituiesDeEnsinoController/useGetUsuariosFromInstituicao.ts";
export type { GetUsuariosFromInstituicaoSuspenseQueryKey } from "./mduloInstituiesDeEnsinoController/useGetUsuariosFromInstituicaoSuspense.ts";
export type { RemoveUsuarioFromInstituicaoMutationKey } from "./mduloInstituiesDeEnsinoController/useRemoveUsuarioFromInstituicao.ts";
export type { UpdateInstituicaoMutationKey } from "./mduloInstituiesDeEnsinoController/useUpdateInstituicao.ts";
export type { CreatePerfilAcessibilidadeMutationKey } from "./mduloPerfilDeAcessibilidadeController/useCreatePerfilAcessibilidade.ts";
export type { GetPerfilByEstudanteIdQueryKey } from "./mduloPerfilDeAcessibilidadeController/useGetPerfilByEstudanteId.ts";
export type { GetPerfilByEstudanteIdSuspenseQueryKey } from "./mduloPerfilDeAcessibilidadeController/useGetPerfilByEstudanteIdSuspense.ts";
export type { GetPerfilByIdQueryKey } from "./mduloPerfilDeAcessibilidadeController/useGetPerfilById.ts";
export type { GetPerfilByIdSuspenseQueryKey } from "./mduloPerfilDeAcessibilidadeController/useGetPerfilByIdSuspense.ts";
export type { RemovePerfilAcessibilidadeMutationKey } from "./mduloPerfilDeAcessibilidadeController/useRemovePerfilAcessibilidade.ts";
export type { UpdatePerfilAcessibilidadeMutationKey } from "./mduloPerfilDeAcessibilidadeController/useUpdatePerfilAcessibilidade.ts";
export type { CreatePublicacaoMutationKey } from "./mduloPublicaesController/useCreatePublicacao.ts";
export type { DeletePublicacaoMutationKey } from "./mduloPublicaesController/useDeletePublicacao.ts";
export type { GetPublicacaoQueryKey } from "./mduloPublicaesController/useGetPublicacao.ts";
export type { GetPublicacaoSuspenseQueryKey } from "./mduloPublicaesController/useGetPublicacaoSuspense.ts";
export type { GetPublicacoesQueryKey } from "./mduloPublicaesController/useGetPublicacoes.ts";
export type { GetPublicacoesSuspenseQueryKey } from "./mduloPublicaesController/useGetPublicacoesSuspense.ts";
export type { UpdatePublicacaoMutationKey } from "./mduloPublicaesController/useUpdatePublicacao.ts";
export type { CreateTarefaMutationKey } from "./mduloTarefasController/useCreateTarefa.ts";
export type { GetTarefaByIdQueryKey } from "./mduloTarefasController/useGetTarefaById.ts";
export type { GetTarefaByIdSuspenseQueryKey } from "./mduloTarefasController/useGetTarefaByIdSuspense.ts";
export type { GetTarefasByDisciplinaQueryKey } from "./mduloTarefasController/useGetTarefasByDisciplina.ts";
export type { GetTarefasByDisciplinaSuspenseQueryKey } from "./mduloTarefasController/useGetTarefasByDisciplinaSuspense.ts";
export type { RemoveTarefaMutationKey } from "./mduloTarefasController/useRemoveTarefa.ts";
export type { UpdateTarefaMutationKey } from "./mduloTarefasController/useUpdateTarefa.ts";
export type { ForgotPasswordMutationKey } from "./redefinioDeSenhaController/useForgotPassword.ts";
export type { UpdatePasswordMutationKey } from "./redefinioDeSenhaController/useUpdatePassword.ts";
export type { ValidateTokenMutationKey } from "./redefinioDeSenhaController/useValidateToken.ts";
export type { AvaliarRespostaMutationKey } from "./respostasController/useAvaliarResposta.ts";
export type { CriarRespostaComUploadMutationKey } from "./respostasController/useCriarRespostaComUpload.ts";
export type { EnviarRespostaMutationKey } from "./respostasController/useEnviarResposta.ts";
export { deletarArquivoMutationKey } from "./arquivoControllerController/useDeletarArquivo.ts";
export { deletarArquivoMutationOptions } from "./arquivoControllerController/useDeletarArquivo.ts";
export { useDeletarArquivo } from "./arquivoControllerController/useDeletarArquivo.ts";
export { downloadArquivoQueryKey } from "./arquivoControllerController/useDownloadArquivo.ts";
export { downloadArquivoQueryOptions } from "./arquivoControllerController/useDownloadArquivo.ts";
export { useDownloadArquivo } from "./arquivoControllerController/useDownloadArquivo.ts";
export { downloadArquivoSuspenseQueryKey } from "./arquivoControllerController/useDownloadArquivoSuspense.ts";
export { downloadArquivoSuspenseQueryOptions } from "./arquivoControllerController/useDownloadArquivoSuspense.ts";
export { useDownloadArquivoSuspense } from "./arquivoControllerController/useDownloadArquivoSuspense.ts";
export { listarArquivosQueryKey } from "./arquivoControllerController/useListarArquivos.ts";
export { listarArquivosQueryOptions } from "./arquivoControllerController/useListarArquivos.ts";
export { useListarArquivos } from "./arquivoControllerController/useListarArquivos.ts";
export { listarArquivosSuspenseQueryKey } from "./arquivoControllerController/useListarArquivosSuspense.ts";
export { listarArquivosSuspenseQueryOptions } from "./arquivoControllerController/useListarArquivosSuspense.ts";
export { useListarArquivosSuspense } from "./arquivoControllerController/useListarArquivosSuspense.ts";
export { uploadArquivoMutationKey } from "./arquivoControllerController/useUploadArquivo.ts";
export { uploadArquivoMutationOptions } from "./arquivoControllerController/useUploadArquivo.ts";
export { useUploadArquivo } from "./arquivoControllerController/useUploadArquivo.ts";
export { loginMutationKey } from "./authenticationController/useLogin.ts";
export { loginMutationOptions } from "./authenticationController/useLogin.ts";
export { useLogin } from "./authenticationController/useLogin.ts";
export { registerMutationKey } from "./authenticationController/useRegister.ts";
export { registerMutationOptions } from "./authenticationController/useRegister.ts";
export { useRegister } from "./authenticationController/useRegister.ts";
export { getAllUsuariosQueryKey } from "./buscaDeUsuriosController/useGetAllUsuarios.ts";
export { getAllUsuariosQueryOptions } from "./buscaDeUsuriosController/useGetAllUsuarios.ts";
export { useGetAllUsuarios } from "./buscaDeUsuriosController/useGetAllUsuarios.ts";
export { getAllUsuariosSuspenseQueryKey } from "./buscaDeUsuriosController/useGetAllUsuariosSuspense.ts";
export { getAllUsuariosSuspenseQueryOptions } from "./buscaDeUsuriosController/useGetAllUsuariosSuspense.ts";
export { useGetAllUsuariosSuspense } from "./buscaDeUsuriosController/useGetAllUsuariosSuspense.ts";
export { getUsuarioByIdQueryKey } from "./buscaDeUsuriosController/useGetUsuarioById.ts";
export { getUsuarioByIdQueryOptions } from "./buscaDeUsuriosController/useGetUsuarioById.ts";
export { useGetUsuarioById } from "./buscaDeUsuriosController/useGetUsuarioById.ts";
export { getUsuarioByIdSuspenseQueryKey } from "./buscaDeUsuriosController/useGetUsuarioByIdSuspense.ts";
export { getUsuarioByIdSuspenseQueryOptions } from "./buscaDeUsuriosController/useGetUsuarioByIdSuspense.ts";
export { useGetUsuarioByIdSuspense } from "./buscaDeUsuriosController/useGetUsuarioByIdSuspense.ts";
export { adicionarFormacaoMutationKey } from "./EducadoresController/useAdicionarFormacao.ts";
export { adicionarFormacaoMutationOptions } from "./EducadoresController/useAdicionarFormacao.ts";
export { useAdicionarFormacao } from "./EducadoresController/useAdicionarFormacao.ts";
export { getEducadorQueryKey } from "./EducadoresController/useGetEducador.ts";
export { getEducadorQueryOptions } from "./EducadoresController/useGetEducador.ts";
export { useGetEducador } from "./EducadoresController/useGetEducador.ts";
export { getEducadorSuspenseQueryKey } from "./EducadoresController/useGetEducadorSuspense.ts";
export { getEducadorSuspenseQueryOptions } from "./EducadoresController/useGetEducadorSuspense.ts";
export { useGetEducadorSuspense } from "./EducadoresController/useGetEducadorSuspense.ts";
export { listarFormacoesQueryKey } from "./EducadoresController/useListarFormacoes.ts";
export { listarFormacoesQueryOptions } from "./EducadoresController/useListarFormacoes.ts";
export { useListarFormacoes } from "./EducadoresController/useListarFormacoes.ts";
export { listarFormacoesSuspenseQueryKey } from "./EducadoresController/useListarFormacoesSuspense.ts";
export { listarFormacoesSuspenseQueryOptions } from "./EducadoresController/useListarFormacoesSuspense.ts";
export { useListarFormacoesSuspense } from "./EducadoresController/useListarFormacoesSuspense.ts";
export { removerFormacaoMutationKey } from "./EducadoresController/useRemoverFormacao.ts";
export { removerFormacaoMutationOptions } from "./EducadoresController/useRemoverFormacao.ts";
export { useRemoverFormacao } from "./EducadoresController/useRemoverFormacao.ts";
export { updateEducadorMutationKey } from "./EducadoresController/useUpdateEducador.ts";
export { updateEducadorMutationOptions } from "./EducadoresController/useUpdateEducador.ts";
export { useUpdateEducador } from "./EducadoresController/useUpdateEducador.ts";
export { atualizarComentarioMutationKey } from "./mduloComentriosController/useAtualizarComentario.ts";
export { atualizarComentarioMutationOptions } from "./mduloComentriosController/useAtualizarComentario.ts";
export { useAtualizarComentario } from "./mduloComentriosController/useAtualizarComentario.ts";
export { getComentarioByIdQueryKey } from "./mduloComentriosController/useGetComentarioById.ts";
export { getComentarioByIdQueryOptions } from "./mduloComentriosController/useGetComentarioById.ts";
export { useGetComentarioById } from "./mduloComentriosController/useGetComentarioById.ts";
export { getComentarioByIdSuspenseQueryKey } from "./mduloComentriosController/useGetComentarioByIdSuspense.ts";
export { getComentarioByIdSuspenseQueryOptions } from "./mduloComentriosController/useGetComentarioByIdSuspense.ts";
export { useGetComentarioByIdSuspense } from "./mduloComentriosController/useGetComentarioByIdSuspense.ts";
export { obterComentariosDaPublicacaoQueryKey } from "./mduloComentriosController/useObterComentariosDaPublicacao.ts";
export { obterComentariosDaPublicacaoQueryOptions } from "./mduloComentriosController/useObterComentariosDaPublicacao.ts";
export { useObterComentariosDaPublicacao } from "./mduloComentriosController/useObterComentariosDaPublicacao.ts";
export { obterComentariosDaPublicacaoSuspenseQueryKey } from "./mduloComentriosController/useObterComentariosDaPublicacaoSuspense.ts";
export { obterComentariosDaPublicacaoSuspenseQueryOptions } from "./mduloComentriosController/useObterComentariosDaPublicacaoSuspense.ts";
export { useObterComentariosDaPublicacaoSuspense } from "./mduloComentriosController/useObterComentariosDaPublicacaoSuspense.ts";
export { removerComentarioMutationKey } from "./mduloComentriosController/useRemoverComentario.ts";
export { removerComentarioMutationOptions } from "./mduloComentriosController/useRemoverComentario.ts";
export { useRemoverComentario } from "./mduloComentriosController/useRemoverComentario.ts";
export { responderComentarioMutationKey } from "./mduloComentriosController/useResponderComentario.ts";
export { responderComentarioMutationOptions } from "./mduloComentriosController/useResponderComentario.ts";
export { useResponderComentario } from "./mduloComentriosController/useResponderComentario.ts";
export { responderPublicacaoMutationKey } from "./mduloComentriosController/useResponderPublicacao.ts";
export { responderPublicacaoMutationOptions } from "./mduloComentriosController/useResponderPublicacao.ts";
export { useResponderPublicacao } from "./mduloComentriosController/useResponderPublicacao.ts";
export { atualizarMutationKey } from "./mduloDeEstudantesController/useAtualizar.ts";
export { atualizarMutationOptions } from "./mduloDeEstudantesController/useAtualizar.ts";
export { useAtualizar } from "./mduloDeEstudantesController/useAtualizar.ts";
export { buscarPorIdQueryKey } from "./mduloDeEstudantesController/useBuscarPorId.ts";
export { buscarPorIdQueryOptions } from "./mduloDeEstudantesController/useBuscarPorId.ts";
export { useBuscarPorId } from "./mduloDeEstudantesController/useBuscarPorId.ts";
export { buscarPorIdSuspenseQueryKey } from "./mduloDeEstudantesController/useBuscarPorIdSuspense.ts";
export { buscarPorIdSuspenseQueryOptions } from "./mduloDeEstudantesController/useBuscarPorIdSuspense.ts";
export { useBuscarPorIdSuspense } from "./mduloDeEstudantesController/useBuscarPorIdSuspense.ts";
export { listarQueryKey } from "./mduloDeEstudantesController/useListar.ts";
export { listarQueryOptions } from "./mduloDeEstudantesController/useListar.ts";
export { useListar } from "./mduloDeEstudantesController/useListar.ts";
export { listarSuspenseQueryKey } from "./mduloDeEstudantesController/useListarSuspense.ts";
export { listarSuspenseQueryOptions } from "./mduloDeEstudantesController/useListarSuspense.ts";
export { useListarSuspense } from "./mduloDeEstudantesController/useListarSuspense.ts";
export { removerMutationKey } from "./mduloDeEstudantesController/useRemover.ts";
export { removerMutationOptions } from "./mduloDeEstudantesController/useRemover.ts";
export { useRemover } from "./mduloDeEstudantesController/useRemover.ts";
export { getGestorByEmailQueryKey } from "./mduloDeGestoresController/useGetGestorByEmail.ts";
export { getGestorByEmailQueryOptions } from "./mduloDeGestoresController/useGetGestorByEmail.ts";
export { useGetGestorByEmail } from "./mduloDeGestoresController/useGetGestorByEmail.ts";
export { getGestorByEmailSuspenseQueryKey } from "./mduloDeGestoresController/useGetGestorByEmailSuspense.ts";
export { getGestorByEmailSuspenseQueryOptions } from "./mduloDeGestoresController/useGetGestorByEmailSuspense.ts";
export { useGetGestorByEmailSuspense } from "./mduloDeGestoresController/useGetGestorByEmailSuspense.ts";
export { getGestorByIdQueryKey } from "./mduloDeGestoresController/useGetGestorById.ts";
export { getGestorByIdQueryOptions } from "./mduloDeGestoresController/useGetGestorById.ts";
export { useGetGestorById } from "./mduloDeGestoresController/useGetGestorById.ts";
export { getGestorByIdSuspenseQueryKey } from "./mduloDeGestoresController/useGetGestorByIdSuspense.ts";
export { getGestorByIdSuspenseQueryOptions } from "./mduloDeGestoresController/useGetGestorByIdSuspense.ts";
export { useGetGestorByIdSuspense } from "./mduloDeGestoresController/useGetGestorByIdSuspense.ts";
export { updateGestorMutationKey } from "./mduloDeGestoresController/useUpdateGestor.ts";
export { updateGestorMutationOptions } from "./mduloDeGestoresController/useUpdateGestor.ts";
export { useUpdateGestor } from "./mduloDeGestoresController/useUpdateGestor.ts";
export { addEstudanteToDisciplinaMutationKey } from "./mduloDisciplinasController/useAddEstudanteToDisciplina.ts";
export { addEstudanteToDisciplinaMutationOptions } from "./mduloDisciplinasController/useAddEstudanteToDisciplina.ts";
export { useAddEstudanteToDisciplina } from "./mduloDisciplinasController/useAddEstudanteToDisciplina.ts";
export { createDisciplinaMutationKey } from "./mduloDisciplinasController/useCreateDisciplina.ts";
export { createDisciplinaMutationOptions } from "./mduloDisciplinasController/useCreateDisciplina.ts";
export { useCreateDisciplina } from "./mduloDisciplinasController/useCreateDisciplina.ts";
export { getDisciplinaByIdQueryKey } from "./mduloDisciplinasController/useGetDisciplinaById.ts";
export { getDisciplinaByIdQueryOptions } from "./mduloDisciplinasController/useGetDisciplinaById.ts";
export { useGetDisciplinaById } from "./mduloDisciplinasController/useGetDisciplinaById.ts";
export { getDisciplinaByIdSuspenseQueryKey } from "./mduloDisciplinasController/useGetDisciplinaByIdSuspense.ts";
export { getDisciplinaByIdSuspenseQueryOptions } from "./mduloDisciplinasController/useGetDisciplinaByIdSuspense.ts";
export { useGetDisciplinaByIdSuspense } from "./mduloDisciplinasController/useGetDisciplinaByIdSuspense.ts";
export { getDisciplinasByEducadorQueryKey } from "./mduloDisciplinasController/useGetDisciplinasByEducador.ts";
export { getDisciplinasByEducadorQueryOptions } from "./mduloDisciplinasController/useGetDisciplinasByEducador.ts";
export { useGetDisciplinasByEducador } from "./mduloDisciplinasController/useGetDisciplinasByEducador.ts";
export { getDisciplinasByEducadorSuspenseQueryKey } from "./mduloDisciplinasController/useGetDisciplinasByEducadorSuspense.ts";
export { getDisciplinasByEducadorSuspenseQueryOptions } from "./mduloDisciplinasController/useGetDisciplinasByEducadorSuspense.ts";
export { useGetDisciplinasByEducadorSuspense } from "./mduloDisciplinasController/useGetDisciplinasByEducadorSuspense.ts";
export { getDisciplinasByEstudanteQueryKey } from "./mduloDisciplinasController/useGetDisciplinasByEstudante.ts";
export { getDisciplinasByEstudanteQueryOptions } from "./mduloDisciplinasController/useGetDisciplinasByEstudante.ts";
export { useGetDisciplinasByEstudante } from "./mduloDisciplinasController/useGetDisciplinasByEstudante.ts";
export { getDisciplinasByEstudanteSuspenseQueryKey } from "./mduloDisciplinasController/useGetDisciplinasByEstudanteSuspense.ts";
export { getDisciplinasByEstudanteSuspenseQueryOptions } from "./mduloDisciplinasController/useGetDisciplinasByEstudanteSuspense.ts";
export { useGetDisciplinasByEstudanteSuspense } from "./mduloDisciplinasController/useGetDisciplinasByEstudanteSuspense.ts";
export { getDisciplinasByInstituicaoQueryKey } from "./mduloDisciplinasController/useGetDisciplinasByInstituicao.ts";
export { getDisciplinasByInstituicaoQueryOptions } from "./mduloDisciplinasController/useGetDisciplinasByInstituicao.ts";
export { useGetDisciplinasByInstituicao } from "./mduloDisciplinasController/useGetDisciplinasByInstituicao.ts";
export { getDisciplinasByInstituicaoSuspenseQueryKey } from "./mduloDisciplinasController/useGetDisciplinasByInstituicaoSuspense.ts";
export { getDisciplinasByInstituicaoSuspenseQueryOptions } from "./mduloDisciplinasController/useGetDisciplinasByInstituicaoSuspense.ts";
export { useGetDisciplinasByInstituicaoSuspense } from "./mduloDisciplinasController/useGetDisciplinasByInstituicaoSuspense.ts";
export { getEstudantesFromDisciplinaQueryKey } from "./mduloDisciplinasController/useGetEstudantesFromDisciplina.ts";
export { getEstudantesFromDisciplinaQueryOptions } from "./mduloDisciplinasController/useGetEstudantesFromDisciplina.ts";
export { useGetEstudantesFromDisciplina } from "./mduloDisciplinasController/useGetEstudantesFromDisciplina.ts";
export { getEstudantesFromDisciplinaSuspenseQueryKey } from "./mduloDisciplinasController/useGetEstudantesFromDisciplinaSuspense.ts";
export { getEstudantesFromDisciplinaSuspenseQueryOptions } from "./mduloDisciplinasController/useGetEstudantesFromDisciplinaSuspense.ts";
export { useGetEstudantesFromDisciplinaSuspense } from "./mduloDisciplinasController/useGetEstudantesFromDisciplinaSuspense.ts";
export { removeEstudanteToDisciplinaMutationKey } from "./mduloDisciplinasController/useRemoveEstudanteToDisciplina.ts";
export { removeEstudanteToDisciplinaMutationOptions } from "./mduloDisciplinasController/useRemoveEstudanteToDisciplina.ts";
export { useRemoveEstudanteToDisciplina } from "./mduloDisciplinasController/useRemoveEstudanteToDisciplina.ts";
export { updateDisciplinaMutationKey } from "./mduloDisciplinasController/useUpdateDisciplina.ts";
export { updateDisciplinaMutationOptions } from "./mduloDisciplinasController/useUpdateDisciplina.ts";
export { useUpdateDisciplina } from "./mduloDisciplinasController/useUpdateDisciplina.ts";
export { addUsuarioToInstituicaoMutationKey } from "./mduloInstituiesDeEnsinoController/useAddUsuarioToInstituicao.ts";
export { addUsuarioToInstituicaoMutationOptions } from "./mduloInstituiesDeEnsinoController/useAddUsuarioToInstituicao.ts";
export { useAddUsuarioToInstituicao } from "./mduloInstituiesDeEnsinoController/useAddUsuarioToInstituicao.ts";
export { createInstituicaoMutationKey } from "./mduloInstituiesDeEnsinoController/useCreateInstituicao.ts";
export { createInstituicaoMutationOptions } from "./mduloInstituiesDeEnsinoController/useCreateInstituicao.ts";
export { useCreateInstituicao } from "./mduloInstituiesDeEnsinoController/useCreateInstituicao.ts";
export { getInstituicaoByCnpjQueryKey } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByCnpj.ts";
export { getInstituicaoByCnpjQueryOptions } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByCnpj.ts";
export { useGetInstituicaoByCnpj } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByCnpj.ts";
export { getInstituicaoByCnpjSuspenseQueryKey } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByCnpjSuspense.ts";
export { getInstituicaoByCnpjSuspenseQueryOptions } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByCnpjSuspense.ts";
export { useGetInstituicaoByCnpjSuspense } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByCnpjSuspense.ts";
export { getInstituicaoByEmailQueryKey } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByEmail.ts";
export { getInstituicaoByEmailQueryOptions } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByEmail.ts";
export { useGetInstituicaoByEmail } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByEmail.ts";
export { getInstituicaoByEmailSuspenseQueryKey } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByEmailSuspense.ts";
export { getInstituicaoByEmailSuspenseQueryOptions } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByEmailSuspense.ts";
export { useGetInstituicaoByEmailSuspense } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByEmailSuspense.ts";
export { getInstituicaoByIdQueryKey } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoById.ts";
export { getInstituicaoByIdQueryOptions } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoById.ts";
export { useGetInstituicaoById } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoById.ts";
export { getInstituicaoByIdSuspenseQueryKey } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByIdSuspense.ts";
export { getInstituicaoByIdSuspenseQueryOptions } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByIdSuspense.ts";
export { useGetInstituicaoByIdSuspense } from "./mduloInstituiesDeEnsinoController/useGetInstituicaoByIdSuspense.ts";
export { getInstituicoesQueryKey } from "./mduloInstituiesDeEnsinoController/useGetInstituicoes.ts";
export { getInstituicoesQueryOptions } from "./mduloInstituiesDeEnsinoController/useGetInstituicoes.ts";
export { useGetInstituicoes } from "./mduloInstituiesDeEnsinoController/useGetInstituicoes.ts";
export { getInstituicoesSuspenseQueryKey } from "./mduloInstituiesDeEnsinoController/useGetInstituicoesSuspense.ts";
export { getInstituicoesSuspenseQueryOptions } from "./mduloInstituiesDeEnsinoController/useGetInstituicoesSuspense.ts";
export { useGetInstituicoesSuspense } from "./mduloInstituiesDeEnsinoController/useGetInstituicoesSuspense.ts";
export { getUsuariosFromInstituicaoQueryKey } from "./mduloInstituiesDeEnsinoController/useGetUsuariosFromInstituicao.ts";
export { getUsuariosFromInstituicaoQueryOptions } from "./mduloInstituiesDeEnsinoController/useGetUsuariosFromInstituicao.ts";
export { useGetUsuariosFromInstituicao } from "./mduloInstituiesDeEnsinoController/useGetUsuariosFromInstituicao.ts";
export { getUsuariosFromInstituicaoSuspenseQueryKey } from "./mduloInstituiesDeEnsinoController/useGetUsuariosFromInstituicaoSuspense.ts";
export { getUsuariosFromInstituicaoSuspenseQueryOptions } from "./mduloInstituiesDeEnsinoController/useGetUsuariosFromInstituicaoSuspense.ts";
export { useGetUsuariosFromInstituicaoSuspense } from "./mduloInstituiesDeEnsinoController/useGetUsuariosFromInstituicaoSuspense.ts";
export { removeUsuarioFromInstituicaoMutationKey } from "./mduloInstituiesDeEnsinoController/useRemoveUsuarioFromInstituicao.ts";
export { removeUsuarioFromInstituicaoMutationOptions } from "./mduloInstituiesDeEnsinoController/useRemoveUsuarioFromInstituicao.ts";
export { useRemoveUsuarioFromInstituicao } from "./mduloInstituiesDeEnsinoController/useRemoveUsuarioFromInstituicao.ts";
export { updateInstituicaoMutationKey } from "./mduloInstituiesDeEnsinoController/useUpdateInstituicao.ts";
export { updateInstituicaoMutationOptions } from "./mduloInstituiesDeEnsinoController/useUpdateInstituicao.ts";
export { useUpdateInstituicao } from "./mduloInstituiesDeEnsinoController/useUpdateInstituicao.ts";
export { createPerfilAcessibilidadeMutationKey } from "./mduloPerfilDeAcessibilidadeController/useCreatePerfilAcessibilidade.ts";
export { createPerfilAcessibilidadeMutationOptions } from "./mduloPerfilDeAcessibilidadeController/useCreatePerfilAcessibilidade.ts";
export { useCreatePerfilAcessibilidade } from "./mduloPerfilDeAcessibilidadeController/useCreatePerfilAcessibilidade.ts";
export { getPerfilByEstudanteIdQueryKey } from "./mduloPerfilDeAcessibilidadeController/useGetPerfilByEstudanteId.ts";
export { getPerfilByEstudanteIdQueryOptions } from "./mduloPerfilDeAcessibilidadeController/useGetPerfilByEstudanteId.ts";
export { useGetPerfilByEstudanteId } from "./mduloPerfilDeAcessibilidadeController/useGetPerfilByEstudanteId.ts";
export { getPerfilByEstudanteIdSuspenseQueryKey } from "./mduloPerfilDeAcessibilidadeController/useGetPerfilByEstudanteIdSuspense.ts";
export { getPerfilByEstudanteIdSuspenseQueryOptions } from "./mduloPerfilDeAcessibilidadeController/useGetPerfilByEstudanteIdSuspense.ts";
export { useGetPerfilByEstudanteIdSuspense } from "./mduloPerfilDeAcessibilidadeController/useGetPerfilByEstudanteIdSuspense.ts";
export { getPerfilByIdQueryKey } from "./mduloPerfilDeAcessibilidadeController/useGetPerfilById.ts";
export { getPerfilByIdQueryOptions } from "./mduloPerfilDeAcessibilidadeController/useGetPerfilById.ts";
export { useGetPerfilById } from "./mduloPerfilDeAcessibilidadeController/useGetPerfilById.ts";
export { getPerfilByIdSuspenseQueryKey } from "./mduloPerfilDeAcessibilidadeController/useGetPerfilByIdSuspense.ts";
export { getPerfilByIdSuspenseQueryOptions } from "./mduloPerfilDeAcessibilidadeController/useGetPerfilByIdSuspense.ts";
export { useGetPerfilByIdSuspense } from "./mduloPerfilDeAcessibilidadeController/useGetPerfilByIdSuspense.ts";
export { removePerfilAcessibilidadeMutationKey } from "./mduloPerfilDeAcessibilidadeController/useRemovePerfilAcessibilidade.ts";
export { removePerfilAcessibilidadeMutationOptions } from "./mduloPerfilDeAcessibilidadeController/useRemovePerfilAcessibilidade.ts";
export { useRemovePerfilAcessibilidade } from "./mduloPerfilDeAcessibilidadeController/useRemovePerfilAcessibilidade.ts";
export { updatePerfilAcessibilidadeMutationKey } from "./mduloPerfilDeAcessibilidadeController/useUpdatePerfilAcessibilidade.ts";
export { updatePerfilAcessibilidadeMutationOptions } from "./mduloPerfilDeAcessibilidadeController/useUpdatePerfilAcessibilidade.ts";
export { useUpdatePerfilAcessibilidade } from "./mduloPerfilDeAcessibilidadeController/useUpdatePerfilAcessibilidade.ts";
export { createPublicacaoMutationKey } from "./mduloPublicaesController/useCreatePublicacao.ts";
export { createPublicacaoMutationOptions } from "./mduloPublicaesController/useCreatePublicacao.ts";
export { useCreatePublicacao } from "./mduloPublicaesController/useCreatePublicacao.ts";
export { deletePublicacaoMutationKey } from "./mduloPublicaesController/useDeletePublicacao.ts";
export { deletePublicacaoMutationOptions } from "./mduloPublicaesController/useDeletePublicacao.ts";
export { useDeletePublicacao } from "./mduloPublicaesController/useDeletePublicacao.ts";
export { getPublicacaoQueryKey } from "./mduloPublicaesController/useGetPublicacao.ts";
export { getPublicacaoQueryOptions } from "./mduloPublicaesController/useGetPublicacao.ts";
export { useGetPublicacao } from "./mduloPublicaesController/useGetPublicacao.ts";
export { getPublicacaoSuspenseQueryKey } from "./mduloPublicaesController/useGetPublicacaoSuspense.ts";
export { getPublicacaoSuspenseQueryOptions } from "./mduloPublicaesController/useGetPublicacaoSuspense.ts";
export { useGetPublicacaoSuspense } from "./mduloPublicaesController/useGetPublicacaoSuspense.ts";
export { getPublicacoesQueryKey } from "./mduloPublicaesController/useGetPublicacoes.ts";
export { getPublicacoesQueryOptions } from "./mduloPublicaesController/useGetPublicacoes.ts";
export { useGetPublicacoes } from "./mduloPublicaesController/useGetPublicacoes.ts";
export { getPublicacoesSuspenseQueryKey } from "./mduloPublicaesController/useGetPublicacoesSuspense.ts";
export { getPublicacoesSuspenseQueryOptions } from "./mduloPublicaesController/useGetPublicacoesSuspense.ts";
export { useGetPublicacoesSuspense } from "./mduloPublicaesController/useGetPublicacoesSuspense.ts";
export { updatePublicacaoMutationKey } from "./mduloPublicaesController/useUpdatePublicacao.ts";
export { updatePublicacaoMutationOptions } from "./mduloPublicaesController/useUpdatePublicacao.ts";
export { useUpdatePublicacao } from "./mduloPublicaesController/useUpdatePublicacao.ts";
export { createTarefaMutationKey } from "./mduloTarefasController/useCreateTarefa.ts";
export { createTarefaMutationOptions } from "./mduloTarefasController/useCreateTarefa.ts";
export { useCreateTarefa } from "./mduloTarefasController/useCreateTarefa.ts";
export { getTarefaByIdQueryKey } from "./mduloTarefasController/useGetTarefaById.ts";
export { getTarefaByIdQueryOptions } from "./mduloTarefasController/useGetTarefaById.ts";
export { useGetTarefaById } from "./mduloTarefasController/useGetTarefaById.ts";
export { getTarefaByIdSuspenseQueryKey } from "./mduloTarefasController/useGetTarefaByIdSuspense.ts";
export { getTarefaByIdSuspenseQueryOptions } from "./mduloTarefasController/useGetTarefaByIdSuspense.ts";
export { useGetTarefaByIdSuspense } from "./mduloTarefasController/useGetTarefaByIdSuspense.ts";
export { getTarefasByDisciplinaQueryKey } from "./mduloTarefasController/useGetTarefasByDisciplina.ts";
export { getTarefasByDisciplinaQueryOptions } from "./mduloTarefasController/useGetTarefasByDisciplina.ts";
export { useGetTarefasByDisciplina } from "./mduloTarefasController/useGetTarefasByDisciplina.ts";
export { getTarefasByDisciplinaSuspenseQueryKey } from "./mduloTarefasController/useGetTarefasByDisciplinaSuspense.ts";
export { getTarefasByDisciplinaSuspenseQueryOptions } from "./mduloTarefasController/useGetTarefasByDisciplinaSuspense.ts";
export { useGetTarefasByDisciplinaSuspense } from "./mduloTarefasController/useGetTarefasByDisciplinaSuspense.ts";
export { removeTarefaMutationKey } from "./mduloTarefasController/useRemoveTarefa.ts";
export { removeTarefaMutationOptions } from "./mduloTarefasController/useRemoveTarefa.ts";
export { useRemoveTarefa } from "./mduloTarefasController/useRemoveTarefa.ts";
export { updateTarefaMutationKey } from "./mduloTarefasController/useUpdateTarefa.ts";
export { updateTarefaMutationOptions } from "./mduloTarefasController/useUpdateTarefa.ts";
export { useUpdateTarefa } from "./mduloTarefasController/useUpdateTarefa.ts";
export { forgotPasswordMutationKey } from "./redefinioDeSenhaController/useForgotPassword.ts";
export { forgotPasswordMutationOptions } from "./redefinioDeSenhaController/useForgotPassword.ts";
export { useForgotPassword } from "./redefinioDeSenhaController/useForgotPassword.ts";
export { updatePasswordMutationKey } from "./redefinioDeSenhaController/useUpdatePassword.ts";
export { updatePasswordMutationOptions } from "./redefinioDeSenhaController/useUpdatePassword.ts";
export { useUpdatePassword } from "./redefinioDeSenhaController/useUpdatePassword.ts";
export { validateTokenMutationKey } from "./redefinioDeSenhaController/useValidateToken.ts";
export { validateTokenMutationOptions } from "./redefinioDeSenhaController/useValidateToken.ts";
export { useValidateToken } from "./redefinioDeSenhaController/useValidateToken.ts";
export { avaliarRespostaMutationKey } from "./respostasController/useAvaliarResposta.ts";
export { avaliarRespostaMutationOptions } from "./respostasController/useAvaliarResposta.ts";
export { useAvaliarResposta } from "./respostasController/useAvaliarResposta.ts";
export { criarRespostaComUploadMutationKey } from "./respostasController/useCriarRespostaComUpload.ts";
export { criarRespostaComUploadMutationOptions } from "./respostasController/useCriarRespostaComUpload.ts";
export { useCriarRespostaComUpload } from "./respostasController/useCriarRespostaComUpload.ts";
export { enviarRespostaMutationKey } from "./respostasController/useEnviarResposta.ts";
export { enviarRespostaMutationOptions } from "./respostasController/useEnviarResposta.ts";
export { useEnviarResposta } from "./respostasController/useEnviarResposta.ts";