/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { AtualizarComentarioMutationRequest, AtualizarComentarioMutationResponse, AtualizarComentarioPathParams, AtualizarComentario404 } from "../../models/AtualizarComentario.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { atualizarComentario } from "../../client/atualizarComentario.ts";

export const atualizarComentarioMutationKey = () => [{ url: '/comentarios/:id' }] as const

export type AtualizarComentarioMutationKey = ReturnType<typeof atualizarComentarioMutationKey>

export function atualizarComentarioMutationOptions(config: Partial<RequestConfig<AtualizarComentarioMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = atualizarComentarioMutationKey()
  return mutationOptions<AtualizarComentarioMutationResponse, ResponseErrorConfig<AtualizarComentario404>, {id: AtualizarComentarioPathParams["id"], data?: AtualizarComentarioMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return atualizarComentario(id, data, config)
    },
  })
}

/**
 * @summary Atualiza um comentário
 * {@link /comentarios/:id}
 */
export function useAtualizarComentario<TContext>(options: 
{
  mutation?: UseMutationOptions<AtualizarComentarioMutationResponse, ResponseErrorConfig<AtualizarComentario404>, {id: AtualizarComentarioPathParams["id"], data?: AtualizarComentarioMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AtualizarComentarioMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? atualizarComentarioMutationKey()

  const baseOptions = atualizarComentarioMutationOptions(config) as UseMutationOptions<AtualizarComentarioMutationResponse, ResponseErrorConfig<AtualizarComentario404>, {id: AtualizarComentarioPathParams["id"], data?: AtualizarComentarioMutationRequest}, TContext>

  return useMutation<AtualizarComentarioMutationResponse, ResponseErrorConfig<AtualizarComentario404>, {id: AtualizarComentarioPathParams["id"], data?: AtualizarComentarioMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<AtualizarComentarioMutationResponse, ResponseErrorConfig<AtualizarComentario404>, {id: AtualizarComentarioPathParams["id"], data?: AtualizarComentarioMutationRequest}, TContext>
}