/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetComentarioByIdQueryResponse, GetComentarioByIdPathParams, GetComentarioById404 } from "../../models/GetComentarioById.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getComentarioById } from "../../client/getComentarioById.ts";

export const getComentarioByIdSuspenseQueryKey = (id: GetComentarioByIdPathParams["id"]) => [{ url: '/comentarios/:id', params: {id:id} }] as const

export type GetComentarioByIdSuspenseQueryKey = ReturnType<typeof getComentarioByIdSuspenseQueryKey>

export function getComentarioByIdSuspenseQueryOptions(id: GetComentarioByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getComentarioByIdSuspenseQueryKey(id)
  return queryOptions<GetComentarioByIdQueryResponse, ResponseErrorConfig<GetComentarioById404>, GetComentarioByIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getComentarioById(id, config)
   },
  })
}

/**
 * @summary Busca um comentário com base no seu ID
 * {@link /comentarios/:id}
 */
export function useGetComentarioByIdSuspense<TData = GetComentarioByIdQueryResponse, TQueryKey extends QueryKey = GetComentarioByIdSuspenseQueryKey>(id: GetComentarioByIdPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetComentarioByIdQueryResponse, ResponseErrorConfig<GetComentarioById404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getComentarioByIdSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...getComentarioByIdSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetComentarioById404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}