/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetComentarioByIdQueryResponse, GetComentarioByIdPathParams, GetComentarioById404 } from "../../models/GetComentarioById.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getComentarioById } from "../../client/getComentarioById.ts";

export const getComentarioByIdQueryKey = (id: GetComentarioByIdPathParams["id"]) => [{ url: '/comentarios/:id', params: {id:id} }] as const

export type GetComentarioByIdQueryKey = ReturnType<typeof getComentarioByIdQueryKey>

export function getComentarioByIdQueryOptions(id: GetComentarioByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getComentarioByIdQueryKey(id)
  return queryOptions<GetComentarioByIdQueryResponse, ResponseErrorConfig<GetComentarioById404>, GetComentarioByIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getComentarioById(id, config)
   },
  })
}

/**
 * @summary Busca um comentário com base no seu ID
 * {@link /comentarios/:id}
 */
export function useGetComentarioById<TData = GetComentarioByIdQueryResponse, TQueryData = GetComentarioByIdQueryResponse, TQueryKey extends QueryKey = GetComentarioByIdQueryKey>(id: GetComentarioByIdPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<GetComentarioByIdQueryResponse, ResponseErrorConfig<GetComentarioById404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getComentarioByIdQueryKey(id)

  const query = useQuery({
   ...getComentarioByIdQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetComentarioById404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}