/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { ObterComentariosDaPublicacaoQueryResponse, ObterComentariosDaPublicacaoQueryParams, ObterComentariosDaPublicacao404 } from "../../models/ObterComentariosDaPublicacao.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { obterComentariosDaPublicacao } from "../../client/obterComentariosDaPublicacao.ts";

export const obterComentariosDaPublicacaoSuspenseQueryKey = (params: ObterComentariosDaPublicacaoQueryParams) => [{ url: '/comentarios/publicacao' }, ...(params ? [params] : [])] as const

export type ObterComentariosDaPublicacaoSuspenseQueryKey = ReturnType<typeof obterComentariosDaPublicacaoSuspenseQueryKey>

export function obterComentariosDaPublicacaoSuspenseQueryOptions(params: ObterComentariosDaPublicacaoQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = obterComentariosDaPublicacaoSuspenseQueryKey(params)
  return queryOptions<ObterComentariosDaPublicacaoQueryResponse, ResponseErrorConfig<ObterComentariosDaPublicacao404>, ObterComentariosDaPublicacaoQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return obterComentariosDaPublicacao(params, config)
   },
  })
}

/**
 * @summary Busca comentários-pai de uma Publicação
 * {@link /comentarios/publicacao}
 */
export function useObterComentariosDaPublicacaoSuspense<TData = ObterComentariosDaPublicacaoQueryResponse, TQueryKey extends QueryKey = ObterComentariosDaPublicacaoSuspenseQueryKey>(params: ObterComentariosDaPublicacaoQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ObterComentariosDaPublicacaoQueryResponse, ResponseErrorConfig<ObterComentariosDaPublicacao404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? obterComentariosDaPublicacaoSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...obterComentariosDaPublicacaoSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<ObterComentariosDaPublicacao404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}