/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { ObterComentariosDaPublicacaoQueryResponse, ObterComentariosDaPublicacaoQueryParams, ObterComentariosDaPublicacao404 } from "../../models/ObterComentariosDaPublicacao.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { obterComentariosDaPublicacao } from "../../client/obterComentariosDaPublicacao.ts";

export const obterComentariosDaPublicacaoQueryKey = (params: ObterComentariosDaPublicacaoQueryParams) => [{ url: '/comentarios/publicacao' }, ...(params ? [params] : [])] as const

export type ObterComentariosDaPublicacaoQueryKey = ReturnType<typeof obterComentariosDaPublicacaoQueryKey>

export function obterComentariosDaPublicacaoQueryOptions(params: ObterComentariosDaPublicacaoQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = obterComentariosDaPublicacaoQueryKey(params)
  return queryOptions<ObterComentariosDaPublicacaoQueryResponse, ResponseErrorConfig<ObterComentariosDaPublicacao404>, ObterComentariosDaPublicacaoQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return obterComentariosDaPublicacao(params, config)
   },
  })
}

/**
 * @summary Busca comentários-pai de uma Publicação
 * {@link /comentarios/publicacao}
 */
export function useObterComentariosDaPublicacao<TData = ObterComentariosDaPublicacaoQueryResponse, TQueryData = ObterComentariosDaPublicacaoQueryResponse, TQueryKey extends QueryKey = ObterComentariosDaPublicacaoQueryKey>(params: ObterComentariosDaPublicacaoQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ObterComentariosDaPublicacaoQueryResponse, ResponseErrorConfig<ObterComentariosDaPublicacao404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? obterComentariosDaPublicacaoQueryKey(params)

  const query = useQuery({
   ...obterComentariosDaPublicacaoQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<ObterComentariosDaPublicacao404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}