/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { ResponderComentarioMutationRequest, ResponderComentarioMutationResponse, ResponderComentarioQueryParams, ResponderComentario404, ResponderComentario409 } from "../../models/ResponderComentario.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { responderComentario } from "../../client/responderComentario.ts";

export const responderComentarioMutationKey = () => [{ url: '/comentarios/responder/comentario' }] as const

export type ResponderComentarioMutationKey = ReturnType<typeof responderComentarioMutationKey>

export function responderComentarioMutationOptions(config: Partial<RequestConfig<ResponderComentarioMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = responderComentarioMutationKey()
  return mutationOptions<ResponderComentarioMutationResponse, ResponseErrorConfig<ResponderComentario404 | ResponderComentario409>, {data: ResponderComentarioMutationRequest, params: ResponderComentarioQueryParams}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data, params }) => {
      return responderComentario(data, params, config)
    },
  })
}

/**
 * @summary Responde um comentário em uma Publicação
 * {@link /comentarios/responder/comentario}
 */
export function useResponderComentario<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponderComentarioMutationResponse, ResponseErrorConfig<ResponderComentario404 | ResponderComentario409>, {data: ResponderComentarioMutationRequest, params: ResponderComentarioQueryParams}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ResponderComentarioMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? responderComentarioMutationKey()

  const baseOptions = responderComentarioMutationOptions(config) as UseMutationOptions<ResponderComentarioMutationResponse, ResponseErrorConfig<ResponderComentario404 | ResponderComentario409>, {data: ResponderComentarioMutationRequest, params: ResponderComentarioQueryParams}, TContext>

  return useMutation<ResponderComentarioMutationResponse, ResponseErrorConfig<ResponderComentario404 | ResponderComentario409>, {data: ResponderComentarioMutationRequest, params: ResponderComentarioQueryParams}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponderComentarioMutationResponse, ResponseErrorConfig<ResponderComentario404 | ResponderComentario409>, {data: ResponderComentarioMutationRequest, params: ResponderComentarioQueryParams}, TContext>
}