/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { RemoverComentarioMutationResponse, RemoverComentarioPathParams, RemoverComentario404 } from "../../models/RemoverComentario.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { removerComentario } from "../../client/removerComentario.ts";

export const removerComentarioMutationKey = () => [{ url: '/comentarios/:id' }] as const

export type RemoverComentarioMutationKey = ReturnType<typeof removerComentarioMutationKey>

export function removerComentarioMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = removerComentarioMutationKey()
  return mutationOptions<RemoverComentarioMutationResponse, ResponseErrorConfig<RemoverComentario404>, {id: RemoverComentarioPathParams["id"]}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id }) => {
      return removerComentario(id, config)
    },
  })
}

/**
 * @summary Atualiza um comentário
 * {@link /comentarios/:id}
 */
export function useRemoverComentario<TContext>(options: 
{
  mutation?: UseMutationOptions<RemoverComentarioMutationResponse, ResponseErrorConfig<RemoverComentario404>, {id: RemoverComentarioPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? removerComentarioMutationKey()

  const baseOptions = removerComentarioMutationOptions(config) as UseMutationOptions<RemoverComentarioMutationResponse, ResponseErrorConfig<RemoverComentario404>, {id: RemoverComentarioPathParams["id"]}, TContext>

  return useMutation<RemoverComentarioMutationResponse, ResponseErrorConfig<RemoverComentario404>, {id: RemoverComentarioPathParams["id"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<RemoverComentarioMutationResponse, ResponseErrorConfig<RemoverComentario404>, {id: RemoverComentarioPathParams["id"]}, TContext>
}