/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { DownloadArquivoQueryResponse, DownloadArquivoPathParams } from "../../models/DownloadArquivo.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { downloadArquivo } from "../../client/downloadArquivo.ts";

export const downloadArquivoSuspenseQueryKey = (arquivoId: DownloadArquivoPathParams["arquivoId"]) => [{ url: '/arquivos/download/:arquivoId', params: {arquivoId:arquivoId} }] as const

export type DownloadArquivoSuspenseQueryKey = ReturnType<typeof downloadArquivoSuspenseQueryKey>

export function downloadArquivoSuspenseQueryOptions(arquivoId: DownloadArquivoPathParams["arquivoId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = downloadArquivoSuspenseQueryKey(arquivoId)
  return queryOptions<DownloadArquivoQueryResponse, ResponseErrorConfig<Error>, DownloadArquivoQueryResponse, typeof queryKey>({
   enabled: !!(arquivoId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return downloadArquivo(arquivoId, config)
   },
  })
}

/**
 * @summary Baixa um arquivo pelo ID
 * {@link /arquivos/download/:arquivoId}
 */
export function useDownloadArquivoSuspense<TData = DownloadArquivoQueryResponse, TQueryKey extends QueryKey = DownloadArquivoSuspenseQueryKey>(arquivoId: DownloadArquivoPathParams["arquivoId"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<DownloadArquivoQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? downloadArquivoSuspenseQueryKey(arquivoId)

  const query = useSuspenseQuery({
   ...downloadArquivoSuspenseQueryOptions(arquivoId, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}