/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { DeletarArquivoMutationResponse, DeletarArquivoPathParams, DeletarArquivoQueryParams } from "../../models/DeletarArquivo.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { deletarArquivo } from "../../client/deletarArquivo.ts";

export const deletarArquivoMutationKey = () => [{ url: '/arquivos/:arquivoId' }] as const

export type DeletarArquivoMutationKey = ReturnType<typeof deletarArquivoMutationKey>

export function deletarArquivoMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = deletarArquivoMutationKey()
  return mutationOptions<DeletarArquivoMutationResponse, ResponseErrorConfig<Error>, {arquivoId: DeletarArquivoPathParams["arquivoId"], params: DeletarArquivoQueryParams}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ arquivoId, params }) => {
      return deletarArquivo(arquivoId, params, config)
    },
  })
}

/**
 * @summary Deleta um arquivo (restrições: estudantes só podem deletar os próprios arquivos)
 * {@link /arquivos/:arquivoId}
 */
export function useDeletarArquivo<TContext>(options: 
{
  mutation?: UseMutationOptions<DeletarArquivoMutationResponse, ResponseErrorConfig<Error>, {arquivoId: DeletarArquivoPathParams["arquivoId"], params: DeletarArquivoQueryParams}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deletarArquivoMutationKey()

  const baseOptions = deletarArquivoMutationOptions(config) as UseMutationOptions<DeletarArquivoMutationResponse, ResponseErrorConfig<Error>, {arquivoId: DeletarArquivoPathParams["arquivoId"], params: DeletarArquivoQueryParams}, TContext>

  return useMutation<DeletarArquivoMutationResponse, ResponseErrorConfig<Error>, {arquivoId: DeletarArquivoPathParams["arquivoId"], params: DeletarArquivoQueryParams}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<DeletarArquivoMutationResponse, ResponseErrorConfig<Error>, {arquivoId: DeletarArquivoPathParams["arquivoId"], params: DeletarArquivoQueryParams}, TContext>
}