/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { DownloadArquivoQueryResponse, DownloadArquivoPathParams } from "../../models/DownloadArquivo.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { downloadArquivo } from "../../client/downloadArquivo.ts";

export const downloadArquivoQueryKey = (arquivoId: DownloadArquivoPathParams["arquivoId"]) => [{ url: '/arquivos/download/:arquivoId', params: {arquivoId:arquivoId} }] as const

export type DownloadArquivoQueryKey = ReturnType<typeof downloadArquivoQueryKey>

export function downloadArquivoQueryOptions(arquivoId: DownloadArquivoPathParams["arquivoId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = downloadArquivoQueryKey(arquivoId)
  return queryOptions<DownloadArquivoQueryResponse, ResponseErrorConfig<Error>, DownloadArquivoQueryResponse, typeof queryKey>({
   enabled: !!(arquivoId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return downloadArquivo(arquivoId, config)
   },
  })
}

/**
 * @summary Baixa um arquivo pelo ID
 * {@link /arquivos/download/:arquivoId}
 */
export function useDownloadArquivo<TData = DownloadArquivoQueryResponse, TQueryData = DownloadArquivoQueryResponse, TQueryKey extends QueryKey = DownloadArquivoQueryKey>(arquivoId: DownloadArquivoPathParams["arquivoId"], options: 
{
  query?: Partial<QueryObserverOptions<DownloadArquivoQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? downloadArquivoQueryKey(arquivoId)

  const query = useQuery({
   ...downloadArquivoQueryOptions(arquivoId, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}