/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { ListarArquivosQueryResponse, ListarArquivosPathParams } from "../../models/ListarArquivos.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { listarArquivos } from "../../client/listarArquivos.ts";

export const listarArquivosQueryKey = (disciplinaId: ListarArquivosPathParams["disciplinaId"]) => [{ url: '/arquivos/disciplina/:disciplinaId', params: {disciplinaId:disciplinaId} }] as const

export type ListarArquivosQueryKey = ReturnType<typeof listarArquivosQueryKey>

export function listarArquivosQueryOptions(disciplinaId: ListarArquivosPathParams["disciplinaId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = listarArquivosQueryKey(disciplinaId)
  return queryOptions<ListarArquivosQueryResponse, ResponseErrorConfig<Error>, ListarArquivosQueryResponse, typeof queryKey>({
   enabled: !!(disciplinaId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return listarArquivos(disciplinaId, config)
   },
  })
}

/**
 * @summary Lista todos os arquivos de uma disciplina
 * {@link /arquivos/disciplina/:disciplinaId}
 */
export function useListarArquivos<TData = ListarArquivosQueryResponse, TQueryData = ListarArquivosQueryResponse, TQueryKey extends QueryKey = ListarArquivosQueryKey>(disciplinaId: ListarArquivosPathParams["disciplinaId"], options: 
{
  query?: Partial<QueryObserverOptions<ListarArquivosQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? listarArquivosQueryKey(disciplinaId)

  const query = useQuery({
   ...listarArquivosQueryOptions(disciplinaId, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}