/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { UploadArquivoMutationRequest, UploadArquivoMutationResponse, UploadArquivoPathParams, UploadArquivoQueryParams, UploadArquivo400, UploadArquivo404 } from "../../models/UploadArquivo.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { uploadArquivo } from "../../client/uploadArquivo.ts";

export const uploadArquivoMutationKey = () => [{ url: '/arquivos/upload/:disciplinaId' }] as const

export type UploadArquivoMutationKey = ReturnType<typeof uploadArquivoMutationKey>

export function uploadArquivoMutationOptions(config: Partial<RequestConfig<UploadArquivoMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = uploadArquivoMutationKey()
  return mutationOptions<UploadArquivoMutationResponse, ResponseErrorConfig<UploadArquivo400 | UploadArquivo404>, {disciplinaId: UploadArquivoPathParams["disciplinaId"], data: UploadArquivoMutationRequest, params: UploadArquivoQueryParams}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ disciplinaId, data, params }) => {
      return uploadArquivo(disciplinaId, data, params, config)
    },
  })
}

/**
 * @summary Faz upload de um arquivo para uma disciplina
 * {@link /arquivos/upload/:disciplinaId}
 */
export function useUploadArquivo<TContext>(options: 
{
  mutation?: UseMutationOptions<UploadArquivoMutationResponse, ResponseErrorConfig<UploadArquivo400 | UploadArquivo404>, {disciplinaId: UploadArquivoPathParams["disciplinaId"], data: UploadArquivoMutationRequest, params: UploadArquivoQueryParams}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UploadArquivoMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? uploadArquivoMutationKey()

  const baseOptions = uploadArquivoMutationOptions(config) as UseMutationOptions<UploadArquivoMutationResponse, ResponseErrorConfig<UploadArquivo400 | UploadArquivo404>, {disciplinaId: UploadArquivoPathParams["disciplinaId"], data: UploadArquivoMutationRequest, params: UploadArquivoQueryParams}, TContext>

  return useMutation<UploadArquivoMutationResponse, ResponseErrorConfig<UploadArquivo400 | UploadArquivo404>, {disciplinaId: UploadArquivoPathParams["disciplinaId"], data: UploadArquivoMutationRequest, params: UploadArquivoQueryParams}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<UploadArquivoMutationResponse, ResponseErrorConfig<UploadArquivo400 | UploadArquivo404>, {disciplinaId: UploadArquivoPathParams["disciplinaId"], data: UploadArquivoMutationRequest, params: UploadArquivoQueryParams}, TContext>
}