/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { educadorResponseDTOSchema } from "./educadorResponseDTOSchema.ts";
import { formacaoRequestDTOSchema } from "./formacaoRequestDTOSchema.ts";
import { z } from "zod/v4";

export const adicionarFormacaoPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description Formação adicionada com sucesso
 */
export const adicionarFormacao200Schema = z.lazy(() => educadorResponseDTOSchema)

export const adicionarFormacaoMutationRequestSchema = z.lazy(() => formacaoRequestDTOSchema)

export const adicionarFormacaoMutationResponseSchema = z.lazy(() => adicionarFormacao200Schema)