/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const authenticationDTOSchema = z.object({
    "email": z.optional(z.string()),
"senha": z.optional(z.string())
    })