/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const avaliarRespostaDTOSchema = z.object({
    "respostaId": z.int(),
"nota": z.number(),
"comentario": z.optional(z.string())
    })