/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { estudanteSummaryDTOSchema } from "./estudanteSummaryDTOSchema.ts";
import { z } from "zod/v4";

export const buscarPorIdPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description Estudante obtido com sucesso
 */
export const buscarPorId200Schema = z.lazy(() => estudanteSummaryDTOSchema)

/**
 * @description Estudante não encontrado
 */
export const buscarPorId404Schema = z.lazy(() => estudanteSummaryDTOSchema)

export const buscarPorIdQueryResponseSchema = z.lazy(() => buscarPorId200Schema)