/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { respostaAComentarioSummaryDTOSchema } from "./respostaAComentarioSummaryDTOSchema.ts";
import { usuarioSummaryDTOSchema } from "./usuarioSummaryDTOSchema.ts";
import { z } from "zod/v4";

export const comentarioSummaryDTOSchema = z.object({
    "id": z.optional(z.int()),
"conteudo": z.optional(z.string()),
get "autor"(){
                return usuarioSummaryDTOSchema.describe("Sumário de usuários").optional()
              },
"dataCriacao": z.optional(z.string().datetime()),
get "respostas"(){
                return z.array(respostaAComentarioSummaryDTOSchema).optional()
              }
    })