/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const createTarefaDTOSchema = z.object({
    "titulo": z.string().min(1),
"conteudo": z.string().min(1),
"disciplinaId": z.int(),
"autorId": z.int(),
"dataExpiracao": z.string().datetime(),
"valorTotal": z.number(),
"permitirArquivoResposta": z.optional(z.boolean())
    })