/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const createDisciplinaDTOSchema = z.object({
    "nome": z.string().min(1),
"descricao": z.string().min(1),
"idEducadorResponsavel": z.int(),
"idInstituicao": z.int()
    })