/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { enderecoSchema } from "./enderecoSchema.ts";
import { z } from "zod/v4";

export const createInstituicaoDTOSchema = z.object({
    "nome": z.string().min(1),
"telefone": z.string().min(1),
"cnpj": z.string().min(1),
"email": z.email().min(1),
get "endereco"(){
                return enderecoSchema
              }
    })