/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const createPublicacaoDTOSchema = z.object({
    "titulo": z.string().min(0).max(120),
"conteudo": z.string().min(0).max(5000),
"caminhoAnexo": z.optional(z.string()),
"disciplinaId": z.int(),
"educadorId": z.int()
    })