/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { createPublicacaoDTOSchema } from "./createPublicacaoDTOSchema.ts";
import { publicacaoSummaryDTOSchema } from "./publicacaoSummaryDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Publicação criada com sucesso
 */
export const createPublicacao201Schema = z.lazy(() => publicacaoSummaryDTOSchema)

/**
 * @description O Educador que está realizando a Publicação não é o responsável pela Disciplina
 */
export const createPublicacao403Schema = z.lazy(() => publicacaoSummaryDTOSchema)

/**
 * @description Disciplina não encontrada
 */
export const createPublicacao404Schema = z.lazy(() => publicacaoSummaryDTOSchema)

/**
 * @description Dados inválidos ou conflitantes
 */
export const createPublicacao409Schema = z.lazy(() => publicacaoSummaryDTOSchema)

export const createPublicacaoMutationRequestSchema = z.lazy(() => createPublicacaoDTOSchema)

export const createPublicacaoMutationResponseSchema = z.lazy(() => createPublicacao201Schema)