/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const createRespostaMultipartDTOSchema = z.object({
    "tarefaId": z.optional(z.int()),
"conteudoTexto": z.optional(z.string()),
"arquivo": z.optional(z.instanceof(File))
    })