/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { createPerfilAcessibilidadeDTOSchema } from "./createPerfilAcessibilidadeDTOSchema.ts";
import { z } from "zod/v4";

export const createPerfilAcessibilidadeQueryParamsSchema = z.object({
    "estudanteId": z.coerce.number().int().gt(0)
    })

/**
 * @description Perfil de Acessibilidade registrado com sucesso
 */
export const createPerfilAcessibilidade201Schema = z.object({
    
    })

/**
 * @description Requisição tem parâmetros inválidos
 */
export const createPerfilAcessibilidade400Schema = z.object({
    
    })

/**
 * @description Estudante não encontrado
 */
export const createPerfilAcessibilidade404Schema = z.object({
    
    })

export const createPerfilAcessibilidadeMutationRequestSchema = z.lazy(() => createPerfilAcessibilidadeDTOSchema)

export const createPerfilAcessibilidadeMutationResponseSchema = z.lazy(() => createPerfilAcessibilidade201Schema)