/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const createPerfilAcessibilidadeDTOSchema = z.object({
    "tipoDeficiencia": z.enum(["NENHUMA", "VISUAL", "AUDITIVA", "MOTORA", "COGNITIVA", "OUTRA"]),
"usaLeitorDeTela": z.boolean(),
"modoAltoContraste": z.boolean(),
"tamanhoFonte": z.int(),
"talkBack": z.boolean()
    })