/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { createDisciplinaDTOSchema } from "./createDisciplinaDTOSchema.ts";
import { disciplinaSummaryDTOSchema } from "./disciplinaSummaryDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Disciplina criada com sucesso
 */
export const createDisciplina201Schema = z.lazy(() => disciplinaSummaryDTOSchema)

/**
 * @description Instituição de Ensino ou Educador não encontrados
 */
export const createDisciplina404Schema = z.lazy(() => disciplinaSummaryDTOSchema)

/**
 * @description Dados inválidos ou conflitantes
 */
export const createDisciplina409Schema = z.lazy(() => disciplinaSummaryDTOSchema)

export const createDisciplinaMutationRequestSchema = z.lazy(() => createDisciplinaDTOSchema)

export const createDisciplinaMutationResponseSchema = z.lazy(() => createDisciplina201Schema)