/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { createTarefaDTOSchema } from "./createTarefaDTOSchema.ts";
import { summaryTarefaDTOSchema } from "./summaryTarefaDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const createTarefa200Schema = z.lazy(() => summaryTarefaDTOSchema)

export const createTarefaMutationRequestSchema = z.lazy(() => createTarefaDTOSchema)

export const createTarefaMutationResponseSchema = z.lazy(() => createTarefa200Schema)