/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const createRespostaDTOSchema = z.object({
    "tarefaId": z.int(),
"estudanteId": z.int(),
"caminhoAnexo": z.optional(z.string()),
"conteudoTexto": z.optional(z.string())
    })