/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const createComentarioDTOSchema = z.object({
    "conteudo": z.string().min(0).max(280)
    })