/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { createRespostaMultipartDTOSchema } from "./createRespostaMultipartDTOSchema.ts";
import { respostaDTOSchema } from "./respostaDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const criarRespostaComUpload200Schema = z.lazy(() => respostaDTOSchema)

export const criarRespostaComUploadMutationRequestSchema = z.lazy(() => createRespostaMultipartDTOSchema)

export const criarRespostaComUploadMutationResponseSchema = z.lazy(() => criarRespostaComUpload200Schema)