/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const deletePublicacaoPathParamsSchema = z.object({
    "publicacaoId": z.coerce.number().int()
    })

/**
 * @description Publicação deletada com sucesso
 */
export const deletePublicacao204Schema = z.object({
    
    })

/**
 * @description Disciplina não encontrada
 */
export const deletePublicacao404Schema = z.object({
    
    })

export const deletePublicacaoMutationResponseSchema = z.lazy(() => deletePublicacao204Schema)