/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const deletarArquivoPathParamsSchema = z.object({
    "arquivoId": z.coerce.number().int()
    })

export const deletarArquivoQueryParamsSchema = z.object({
    "usuarioId": z.coerce.number().int(),
"isEducador": z.optional(z.boolean().default(false))
    })

/**
 * @description OK
 */
export const deletarArquivo200Schema = z.any()

export const deletarArquivoMutationResponseSchema = z.lazy(() => deletarArquivo200Schema)