/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const disciplinaSummaryDTOSchema = z.object({
    "id": z.optional(z.int()),
"nome": z.optional(z.string()),
"descricao": z.optional(z.string()),
"educadorResponsavel": z.optional(z.string()),
"instituicao": z.optional(z.string()),
"alunos": z.optional(z.int())
    })