/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { formacaoResponseDTOSchema } from "./formacaoResponseDTOSchema.ts";
import { z } from "zod/v4";

export const educadorResponseDTOSchema = z.object({
    "id": z.optional(z.int()),
"nome": z.optional(z.string()),
"email": z.optional(z.string()),
"matricula": z.optional(z.string()),
"titulo": z.optional(z.string()),
get "formacaoAcademica"(){
                return z.array(formacaoResponseDTOSchema).optional()
              }
    })