/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const enderecoSchema = z.object({
    "logradouro": z.string().min(1),
"numero": z.string().min(1),
"bairro": z.string().min(1),
"cidade": z.string().min(1),
"estado": z.string().min(1),
"cep": z.string().min(1)
    })