/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { createRespostaDTOSchema } from "./createRespostaDTOSchema.ts";
import { respostaDTOSchema } from "./respostaDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const enviarResposta200Schema = z.lazy(() => respostaDTOSchema)

export const enviarRespostaMutationRequestSchema = z.lazy(() => createRespostaDTOSchema)

export const enviarRespostaMutationResponseSchema = z.lazy(() => enviarResposta200Schema)