/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const estudanteUpdateDTOSchema = z.object({
    "nome": z.optional(z.string()),
"telefone": z.optional(z.string()),
"genero": z.optional(z.enum(["MASCULINO", "FEMININO", "OUTRO", "NAO_INFORMAR"])),
"dataNascimento": z.optional(z.iso.date())
    })