/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const estudanteListDTOSchema = z.object({
    "id": z.optional(z.int()),
"nome": z.optional(z.string()),
"email": z.optional(z.string()),
"matricula": z.optional(z.string()),
"anoEscolar": z.optional(z.enum(["PRIMEIRO_ANO", "SEGUNDO_ANO", "TERCEIRO_ANO", "QUARTO_ANO", "QUINTO_ANO", "SEXTO_ANO", "SETIMO_ANO", "OITAVO_ANO", "NONO_ANO", "PRIMEIO_ANO_EM", "SEGUNDO_ANO_EM", "TERCEIRO_ANO_EM"])),
"periodo": z.optional(z.enum(["MATUTINO", "VESPERTINO", "NOTURNO"]))
    })