/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { instituicaoDetailsDTOSchema } from "./instituicaoDetailsDTOSchema.ts";
import { z } from "zod/v4";

export const estudanteResponseDTOSchema = z.object({
    "id": z.optional(z.int()),
"nome": z.optional(z.string()),
"cpf": z.optional(z.string()),
"email": z.optional(z.string()),
"matricula": z.optional(z.string()),
"periodo": z.optional(z.enum(["MATUTINO", "VESPERTINO", "NOTURNO"])),
"anoEscolar": z.optional(z.enum(["PRIMEIRO_ANO", "SEGUNDO_ANO", "TERCEIRO_ANO", "QUARTO_ANO", "QUINTO_ANO", "SEXTO_ANO", "SETIMO_ANO", "OITAVO_ANO", "NONO_ANO", "PRIMEIO_ANO_EM", "SEGUNDO_ANO_EM", "TERCEIRO_ANO_EM"])),
"telefone": z.optional(z.string()),
"genero": z.optional(z.enum(["MASCULINO", "FEMININO", "OUTRO", "NAO_INFORMAR"])),
"dataNascimento": z.optional(z.iso.date()),
get "instituicao"(){
                return instituicaoDetailsDTOSchema.optional()
              }
    })