/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const formacaoResponseDTOSchema = z.object({
    "id": z.optional(z.int()),
"titulo": z.optional(z.string()),
"instituicao": z.optional(z.string()),
"dataInicio": z.optional(z.iso.date()),
"dataConclusao": z.optional(z.iso.date()),
"descricao": z.optional(z.string())
    })