/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { formacaoResponseDTOSchema } from "./formacaoResponseDTOSchema.ts";
import { z } from "zod/v4";

export const formacaoListResponseDTOSchema = z.object({
    get "formacoes"(){
                return z.array(formacaoResponseDTOSchema).optional()
              },
"totalRegistros": z.optional(z.int())
    })