/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { instituicaoDetailsDTOSchema } from "./instituicaoDetailsDTOSchema.ts";
import { z } from "zod/v4";

export const gestorDetailsDTOSchema = z.object({
    "id": z.optional(z.int()),
"nome": z.optional(z.string()),
"cpf": z.optional(z.string()),
"email": z.optional(z.string()),
"telefone": z.optional(z.string()),
"genero": z.optional(z.enum(["MASCULINO", "FEMININO", "OUTRO", "NAO_INFORMAR"])),
"dataNascimento": z.optional(z.iso.date()),
"cargo": z.optional(z.string()),
get "instituicao"(){
                return instituicaoDetailsDTOSchema.optional()
              }
    })