/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { usuarioDetailsDTOSchema } from "./usuarioDetailsDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Lista de usuários retornada com sucesso
 */
export const getAllUsuarios200Schema = z.array(z.lazy(() => usuarioDetailsDTOSchema))

/**
 * @description Nenhum usuário encontrado
 */
export const getAllUsuarios204Schema = z.array(z.lazy(() => usuarioDetailsDTOSchema))

export const getAllUsuariosQueryResponseSchema = z.union([z.lazy(() => getAllUsuarios200Schema), z.lazy(() => getAllUsuarios204Schema)])