/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { comentarioSummaryDTOSchema } from "./comentarioSummaryDTOSchema.ts";
import { z } from "zod/v4";

export const getComentarioByIdPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description Comentário obtido com sucesso
 */
export const getComentarioById200Schema = z.lazy(() => comentarioSummaryDTOSchema)

/**
 * @description Comentário não encontrado
 */
export const getComentarioById404Schema = z.lazy(() => comentarioSummaryDTOSchema)

export const getComentarioByIdQueryResponseSchema = z.lazy(() => getComentarioById200Schema)