/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { disciplinaSummaryDTOSchema } from "./disciplinaSummaryDTOSchema.ts";
import { z } from "zod/v4";

export const getDisciplinaByIdPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description Disciplina obtida com sucesso
 */
export const getDisciplinaById200Schema = z.lazy(() => disciplinaSummaryDTOSchema)

/**
 * @description Disciplina não encontrada
 */
export const getDisciplinaById404Schema = z.lazy(() => disciplinaSummaryDTOSchema)

export const getDisciplinaByIdQueryResponseSchema = z.lazy(() => getDisciplinaById200Schema)