/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { disciplinaSummaryDTOSchema } from "./disciplinaSummaryDTOSchema.ts";
import { z } from "zod/v4";

export const getDisciplinasByEstudanteQueryParamsSchema = z.object({
    "estudanteId": z.coerce.number().int().gt(0)
    })

/**
 * @description Disciplinas obtidas com sucesso
 */
export const getDisciplinasByEstudante200Schema = z.array(z.lazy(() => disciplinaSummaryDTOSchema))

/**
 * @description O estudante não está matriculado em nenhuma disciplina
 */
export const getDisciplinasByEstudante204Schema = z.array(z.lazy(() => disciplinaSummaryDTOSchema))

/**
 * @description Estudante não encontrado
 */
export const getDisciplinasByEstudante404Schema = z.array(z.lazy(() => disciplinaSummaryDTOSchema))

export const getDisciplinasByEstudanteQueryResponseSchema = z.union([z.lazy(() => getDisciplinasByEstudante200Schema), z.lazy(() => getDisciplinasByEstudante204Schema)])