/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { disciplinaSummaryDTOSchema } from "./disciplinaSummaryDTOSchema.ts";
import { z } from "zod/v4";

export const getDisciplinasByInstituicaoQueryParamsSchema = z.object({
    "instituicaoId": z.coerce.number().int().gt(0)
    })

/**
 * @description Disciplinas obtidas com sucesso
 */
export const getDisciplinasByInstituicao200Schema = z.array(z.lazy(() => disciplinaSummaryDTOSchema))

/**
 * @description A Instituição de Ensino não tem nenhuma Disciplina cadastrada
 */
export const getDisciplinasByInstituicao204Schema = z.array(z.lazy(() => disciplinaSummaryDTOSchema))

/**
 * @description Instituição de Ensino não encontrada
 */
export const getDisciplinasByInstituicao404Schema = z.array(z.lazy(() => disciplinaSummaryDTOSchema))

export const getDisciplinasByInstituicaoQueryResponseSchema = z.union([z.lazy(() => getDisciplinasByInstituicao200Schema), z.lazy(() => getDisciplinasByInstituicao204Schema)])