/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { disciplinaSummaryDTOSchema } from "./disciplinaSummaryDTOSchema.ts";
import { z } from "zod/v4";

export const getDisciplinasByEducadorQueryParamsSchema = z.object({
    "educadorId": z.coerce.number().int().gt(0)
    })

/**
 * @description Disciplinas obtidas com sucesso
 */
export const getDisciplinasByEducador200Schema = z.array(z.lazy(() => disciplinaSummaryDTOSchema))

/**
 * @description Educador não encontrado
 */
export const getDisciplinasByEducador204Schema = z.array(z.lazy(() => disciplinaSummaryDTOSchema))

export const getDisciplinasByEducadorQueryResponseSchema = z.union([z.lazy(() => getDisciplinasByEducador200Schema), z.lazy(() => getDisciplinasByEducador204Schema)])