/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { educadorResponseDTOSchema } from "./educadorResponseDTOSchema.ts";
import { z } from "zod/v4";

export const getEducadorPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const getEducador200Schema = z.lazy(() => educadorResponseDTOSchema)

export const getEducadorQueryResponseSchema = z.lazy(() => getEducador200Schema)