/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { gestorDetailsDTOSchema } from "./gestorDetailsDTOSchema.ts";
import { gestorGetByEmailDTOSchema } from "./gestorGetByEmailDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Gestor obtido com sucesso
 */
export const getGestorByEmail200Schema = z.lazy(() => gestorDetailsDTOSchema)

/**
 * @description Ocorreu erro durante o processamento da requsição
 */
export const getGestorByEmail400Schema = z.lazy(() => gestorDetailsDTOSchema)

/**
 * @description Não foi possível obter o Gestor com o ID especificado
 */
export const getGestorByEmail404Schema = z.lazy(() => gestorDetailsDTOSchema)

export const getGestorByEmailQueryRequestSchema = z.lazy(() => gestorGetByEmailDTOSchema)

export const getGestorByEmailQueryResponseSchema = z.lazy(() => getGestorByEmail200Schema)