/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { instituicaoDetailsDTOSchema } from "./instituicaoDetailsDTOSchema.ts";
import { instituicaoEmailDTOSchema } from "./instituicaoEmailDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const getInstituicaoByEmail200Schema = z.lazy(() => instituicaoDetailsDTOSchema)

export const getInstituicaoByEmailQueryRequestSchema = z.lazy(() => instituicaoEmailDTOSchema)

export const getInstituicaoByEmailQueryResponseSchema = z.lazy(() => getInstituicaoByEmail200Schema)