/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { instituicaoDetailsDTOSchema } from "./instituicaoDetailsDTOSchema.ts";
import { z } from "zod/v4";

export const getInstituicaoByIdPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description Instituição de Ensino encontrada com sucesso
 */
export const getInstituicaoById200Schema = z.lazy(() => instituicaoDetailsDTOSchema)

/**
 * @description Instituição de Ensino não encontrada
 */
export const getInstituicaoById404Schema = z.lazy(() => instituicaoDetailsDTOSchema)

export const getInstituicaoByIdQueryResponseSchema = z.lazy(() => getInstituicaoById200Schema)