/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { instituicaoDetailsDTOSchema } from "./instituicaoDetailsDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Lista retornada com sucesso
 */
export const getInstituicoes200Schema = z.array(z.lazy(() => instituicaoDetailsDTOSchema))

/**
 * @description Nenhuma instituição encontrada
 */
export const getInstituicoes204Schema = z.array(z.lazy(() => instituicaoDetailsDTOSchema))

export const getInstituicoesQueryResponseSchema = z.union([z.lazy(() => getInstituicoes200Schema), z.lazy(() => getInstituicoes204Schema)])