/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { instituicaoCnpjDTOSchema } from "./instituicaoCnpjDTOSchema.ts";
import { instituicaoDetailsDTOSchema } from "./instituicaoDetailsDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Instituição de Ensino encontrada com sucesso
 */
export const getInstituicaoByCnpj200Schema = z.lazy(() => instituicaoDetailsDTOSchema)

/**
 * @description Instituição de Ensino não encontrada
 */
export const getInstituicaoByCnpj404Schema = z.lazy(() => instituicaoDetailsDTOSchema)

export const getInstituicaoByCnpjQueryRequestSchema = z.lazy(() => instituicaoCnpjDTOSchema)

export const getInstituicaoByCnpjQueryResponseSchema = z.lazy(() => getInstituicaoByCnpj200Schema)