/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const getPerfilByIdPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description Perfil de Acessibilidade obtido com sucesso
 */
export const getPerfilById200Schema = z.object({
    
    })

/**
 * @description Perfil de Acessibilidade não encontrado
 */
export const getPerfilById404Schema = z.object({
    
    })

export const getPerfilByIdQueryResponseSchema = z.lazy(() => getPerfilById200Schema)