/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { publicacaoDetailsDTOSchema } from "./publicacaoDetailsDTOSchema.ts";
import { z } from "zod/v4";

export const getPublicacaoPathParamsSchema = z.object({
    "publicacaoId": z.coerce.number().int()
    })

/**
 * @description Publicação obtida com sucesso
 */
export const getPublicacao200Schema = z.lazy(() => publicacaoDetailsDTOSchema)

/**
 * @description Publicação não encontrada
 */
export const getPublicacao404Schema = z.lazy(() => publicacaoDetailsDTOSchema)

export const getPublicacaoQueryResponseSchema = z.lazy(() => getPublicacao200Schema)