/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { publicacaoDetailsDTOSchema } from "./publicacaoDetailsDTOSchema.ts";
import { z } from "zod/v4";

export const getPublicacoesQueryParamsSchema = z.object({
    "discplinaId": z.coerce.number().int().gt(0)
    })

/**
 * @description Publicações listadas com sucesso
 */
export const getPublicacoes200Schema = z.array(z.lazy(() => publicacaoDetailsDTOSchema))

/**
 * @description Não há Publicações cadastradas nesta Disciplina
 */
export const getPublicacoes204Schema = z.array(z.lazy(() => publicacaoDetailsDTOSchema))

/**
 * @description Disciplina não encontrada
 */
export const getPublicacoes404Schema = z.array(z.lazy(() => publicacaoDetailsDTOSchema))

export const getPublicacoesQueryResponseSchema = z.union([z.lazy(() => getPublicacoes200Schema), z.lazy(() => getPublicacoes204Schema)])