/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const getPerfilByEstudanteIdPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description Perfil de Acessibilidade obtido com sucesso
 */
export const getPerfilByEstudanteId200Schema = z.object({
    
    })

/**
 * @description Perfil de Acessibilidade ou Estudante não encontrado
 */
export const getPerfilByEstudanteId404Schema = z.object({
    
    })

export const getPerfilByEstudanteIdQueryResponseSchema = z.lazy(() => getPerfilByEstudanteId200Schema)