/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { summaryTarefaDTOSchema } from "./summaryTarefaDTOSchema.ts";
import { z } from "zod/v4";

export const getTarefasByDisciplinaPathParamsSchema = z.object({
    "disciplinaId": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const getTarefasByDisciplina200Schema = z.array(z.lazy(() => summaryTarefaDTOSchema))

export const getTarefasByDisciplinaQueryResponseSchema = z.lazy(() => getTarefasByDisciplina200Schema)