/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { usuarioSummaryDTOSchema } from "./usuarioSummaryDTOSchema.ts";
import { z } from "zod/v4";

export const getUsuariosFromInstituicaoPathParamsSchema = z.object({
    "instituicaoId": z.coerce.number().int()
    })

/**
 * @description Dados listados com sucesso
 */
export const getUsuariosFromInstituicao200Schema = z.array(z.lazy(() => usuarioSummaryDTOSchema).describe("Sumário de usuários"))

/**
 * @description Nenhum usuário para listar
 */
export const getUsuariosFromInstituicao204Schema = z.array(z.lazy(() => usuarioSummaryDTOSchema).describe("Sumário de usuários"))

/**
 * @description Instituição não encontrada
 */
export const getUsuariosFromInstituicao404Schema = z.array(z.lazy(() => usuarioSummaryDTOSchema).describe("Sumário de usuários"))

export const getUsuariosFromInstituicaoQueryResponseSchema = z.union([z.lazy(() => getUsuariosFromInstituicao200Schema), z.lazy(() => getUsuariosFromInstituicao204Schema)])