export { addEstudanteToDisciplinaPathParamsSchema, addEstudanteToDisciplinaQueryParamsSchema, addEstudanteToDisciplina200Schema, addEstudanteToDisciplina404Schema, addEstudanteToDisciplinaMutationResponseSchema } from "./addEstudanteToDisciplinaSchema.ts";
export { addUsuarioToInstituicaoPathParamsSchema, addUsuarioToInstituicao200Schema, addUsuarioToInstituicao404Schema, addUsuarioToInstituicao409Schema, addUsuarioToInstituicaoMutationResponseSchema } from "./addUsuarioToInstituicaoSchema.ts";
export { adicionarFormacaoPathParamsSchema, adicionarFormacao200Schema, adicionarFormacaoMutationRequestSchema, adicionarFormacaoMutationResponseSchema } from "./adicionarFormacaoSchema.ts";
export { arquivoDTOSchema } from "./arquivoDTOSchema.ts";
export { atualizarComentarioPathParamsSchema, atualizarComentario200Schema, atualizarComentario404Schema, atualizarComentarioMutationRequestSchema, atualizarComentarioMutationResponseSchema } from "./atualizarComentarioSchema.ts";
export { atualizarPathParamsSchema, atualizar200Schema, atualizar400Schema, atualizar404Schema, atualizarMutationRequestSchema, atualizarMutationResponseSchema } from "./atualizarSchema.ts";
export { authenticationDTOSchema } from "./authenticationDTOSchema.ts";
export { avaliarRespostaDTOSchema } from "./avaliarRespostaDTOSchema.ts";
export { avaliarRespostaPathParamsSchema, avaliarResposta200Schema, avaliarRespostaMutationRequestSchema, avaliarRespostaMutationResponseSchema } from "./avaliarRespostaSchema.ts";
export { buscarPorIdPathParamsSchema, buscarPorId200Schema, buscarPorId404Schema, buscarPorIdQueryResponseSchema } from "./buscarPorIdSchema.ts";
export { comentarioSummaryDTOSchema } from "./comentarioSummaryDTOSchema.ts";
export { createComentarioDTOSchema } from "./createComentarioDTOSchema.ts";
export { createDisciplinaDTOSchema } from "./createDisciplinaDTOSchema.ts";
export { createDisciplina201Schema, createDisciplina404Schema, createDisciplina409Schema, createDisciplinaMutationRequestSchema, createDisciplinaMutationResponseSchema } from "./createDisciplinaSchema.ts";
export { createInstituicaoDTOSchema } from "./createInstituicaoDTOSchema.ts";
export { createInstituicao201Schema, createInstituicao409Schema, createInstituicao422Schema, createInstituicaoMutationRequestSchema, createInstituicaoMutationResponseSchema } from "./createInstituicaoSchema.ts";
export { createPerfilAcessibilidadeDTOSchema } from "./createPerfilAcessibilidadeDTOSchema.ts";
export { createPerfilAcessibilidadeQueryParamsSchema, createPerfilAcessibilidade201Schema, createPerfilAcessibilidade400Schema, createPerfilAcessibilidade404Schema, createPerfilAcessibilidadeMutationRequestSchema, createPerfilAcessibilidadeMutationResponseSchema } from "./createPerfilAcessibilidadeSchema.ts";
export { createPublicacaoDTOSchema } from "./createPublicacaoDTOSchema.ts";
export { createPublicacao201Schema, createPublicacao403Schema, createPublicacao404Schema, createPublicacao409Schema, createPublicacaoMutationRequestSchema, createPublicacaoMutationResponseSchema } from "./createPublicacaoSchema.ts";
export { createRespostaDTOSchema } from "./createRespostaDTOSchema.ts";
export { createRespostaMultipartDTOSchema } from "./createRespostaMultipartDTOSchema.ts";
export { createTarefaDTOSchema } from "./createTarefaDTOSchema.ts";
export { createTarefa200Schema, createTarefaMutationRequestSchema, createTarefaMutationResponseSchema } from "./createTarefaSchema.ts";
export { criarRespostaComUpload200Schema, criarRespostaComUploadMutationRequestSchema, criarRespostaComUploadMutationResponseSchema } from "./criarRespostaComUploadSchema.ts";
export { deletarArquivoPathParamsSchema, deletarArquivoQueryParamsSchema, deletarArquivo200Schema, deletarArquivoMutationResponseSchema } from "./deletarArquivoSchema.ts";
export { deletePublicacaoPathParamsSchema, deletePublicacao204Schema, deletePublicacao404Schema, deletePublicacaoMutationResponseSchema } from "./deletePublicacaoSchema.ts";
export { disciplinaSummaryDTOSchema } from "./disciplinaSummaryDTOSchema.ts";
export { downloadArquivoPathParamsSchema, downloadArquivo200Schema, downloadArquivoQueryResponseSchema } from "./downloadArquivoSchema.ts";
export { educadorResponseDTOSchema } from "./educadorResponseDTOSchema.ts";
export { educadorSummaryDTOSchema } from "./educadorSummaryDTOSchema.ts";
export { enderecoSchema } from "./enderecoSchema.ts";
export { enviarResposta200Schema, enviarRespostaMutationRequestSchema, enviarRespostaMutationResponseSchema } from "./enviarRespostaSchema.ts";
export { estudanteListDTOSchema } from "./estudanteListDTOSchema.ts";
export { estudanteResponseDTOSchema } from "./estudanteResponseDTOSchema.ts";
export { estudanteSummaryDTOSchema } from "./estudanteSummaryDTOSchema.ts";
export { estudanteUpdateDTOSchema } from "./estudanteUpdateDTOSchema.ts";
export { forgotPassword200Schema, forgotPasswordMutationRequestSchema, forgotPasswordMutationResponseSchema } from "./forgotPasswordSchema.ts";
export { formacaoListResponseDTOSchema } from "./formacaoListResponseDTOSchema.ts";
export { formacaoRequestDTOSchema } from "./formacaoRequestDTOSchema.ts";
export { formacaoResponseDTOSchema } from "./formacaoResponseDTOSchema.ts";
export { gestorDetailsDTOSchema } from "./gestorDetailsDTOSchema.ts";
export { gestorGetByEmailDTOSchema } from "./gestorGetByEmailDTOSchema.ts";
export { getAllUsuarios200Schema, getAllUsuarios204Schema, getAllUsuariosQueryResponseSchema } from "./getAllUsuariosSchema.ts";
export { getComentarioByIdPathParamsSchema, getComentarioById200Schema, getComentarioById404Schema, getComentarioByIdQueryResponseSchema } from "./getComentarioByIdSchema.ts";
export { getDisciplinaByIdPathParamsSchema, getDisciplinaById200Schema, getDisciplinaById404Schema, getDisciplinaByIdQueryResponseSchema } from "./getDisciplinaByIdSchema.ts";
export { getDisciplinasByEducadorQueryParamsSchema, getDisciplinasByEducador200Schema, getDisciplinasByEducador204Schema, getDisciplinasByEducadorQueryResponseSchema } from "./getDisciplinasByEducadorSchema.ts";
export { getDisciplinasByEstudanteQueryParamsSchema, getDisciplinasByEstudante200Schema, getDisciplinasByEstudante204Schema, getDisciplinasByEstudante404Schema, getDisciplinasByEstudanteQueryResponseSchema } from "./getDisciplinasByEstudanteSchema.ts";
export { getDisciplinasByInstituicaoQueryParamsSchema, getDisciplinasByInstituicao200Schema, getDisciplinasByInstituicao204Schema, getDisciplinasByInstituicao404Schema, getDisciplinasByInstituicaoQueryResponseSchema } from "./getDisciplinasByInstituicaoSchema.ts";
export { getEducadorPathParamsSchema, getEducador200Schema, getEducadorQueryResponseSchema } from "./getEducadorSchema.ts";
export { getEstudantesFromDisciplinaPathParamsSchema, getEstudantesFromDisciplina200Schema, getEstudantesFromDisciplina204Schema, getEstudantesFromDisciplina404Schema, getEstudantesFromDisciplinaQueryResponseSchema } from "./getEstudantesFromDisciplinaSchema.ts";
export { getGestorByEmail200Schema, getGestorByEmail400Schema, getGestorByEmail404Schema, getGestorByEmailQueryRequestSchema, getGestorByEmailQueryResponseSchema } from "./getGestorByEmailSchema.ts";
export { getGestorByIdPathParamsSchema, getGestorById200Schema, getGestorById400Schema, getGestorById404Schema, getGestorByIdQueryResponseSchema } from "./getGestorByIdSchema.ts";
export { getInstituicaoByCnpj200Schema, getInstituicaoByCnpj404Schema, getInstituicaoByCnpjQueryRequestSchema, getInstituicaoByCnpjQueryResponseSchema } from "./getInstituicaoByCnpjSchema.ts";
export { getInstituicaoByEmail200Schema, getInstituicaoByEmailQueryRequestSchema, getInstituicaoByEmailQueryResponseSchema } from "./getInstituicaoByEmailSchema.ts";
export { getInstituicaoByIdPathParamsSchema, getInstituicaoById200Schema, getInstituicaoById404Schema, getInstituicaoByIdQueryResponseSchema } from "./getInstituicaoByIdSchema.ts";
export { getInstituicoes200Schema, getInstituicoes204Schema, getInstituicoesQueryResponseSchema } from "./getInstituicoesSchema.ts";
export { getPerfilByEstudanteIdPathParamsSchema, getPerfilByEstudanteId200Schema, getPerfilByEstudanteId404Schema, getPerfilByEstudanteIdQueryResponseSchema } from "./getPerfilByEstudanteIdSchema.ts";
export { getPerfilByIdPathParamsSchema, getPerfilById200Schema, getPerfilById404Schema, getPerfilByIdQueryResponseSchema } from "./getPerfilByIdSchema.ts";
export { getPublicacaoPathParamsSchema, getPublicacao200Schema, getPublicacao404Schema, getPublicacaoQueryResponseSchema } from "./getPublicacaoSchema.ts";
export { getPublicacoesQueryParamsSchema, getPublicacoes200Schema, getPublicacoes204Schema, getPublicacoes404Schema, getPublicacoesQueryResponseSchema } from "./getPublicacoesSchema.ts";
export { getTarefaByIdPathParamsSchema, getTarefaById200Schema, getTarefaByIdQueryResponseSchema } from "./getTarefaByIdSchema.ts";
export { getTarefasByDisciplinaPathParamsSchema, getTarefasByDisciplina200Schema, getTarefasByDisciplinaQueryResponseSchema } from "./getTarefasByDisciplinaSchema.ts";
export { getUsuarioByIdPathParamsSchema, getUsuarioById200Schema, getUsuarioById404Schema, getUsuarioByIdQueryResponseSchema } from "./getUsuarioByIdSchema.ts";
export { getUsuariosFromInstituicaoPathParamsSchema, getUsuariosFromInstituicao200Schema, getUsuariosFromInstituicao204Schema, getUsuariosFromInstituicao404Schema, getUsuariosFromInstituicaoQueryResponseSchema } from "./getUsuariosFromInstituicaoSchema.ts";
export { instituicaoCnpjDTOSchema } from "./instituicaoCnpjDTOSchema.ts";
export { instituicaoDetailsDTOSchema } from "./instituicaoDetailsDTOSchema.ts";
export { instituicaoEmailDTOSchema } from "./instituicaoEmailDTOSchema.ts";
export { listarArquivosPathParamsSchema, listarArquivos200Schema, listarArquivos204Schema, listarArquivosQueryResponseSchema } from "./listarArquivosSchema.ts";
export { listarFormacoesPathParamsSchema, listarFormacoes200Schema, listarFormacoesQueryResponseSchema } from "./listarFormacoesSchema.ts";
export { listarQueryParamsSchema, listar200Schema, listar404Schema, listarQueryResponseSchema } from "./listarSchema.ts";
export { login200Schema, login400Schema, loginMutationRequestSchema, loginMutationResponseSchema } from "./loginSchema.ts";
export { obterComentariosDaPublicacaoQueryParamsSchema, obterComentariosDaPublicacao200Schema, obterComentariosDaPublicacao204Schema, obterComentariosDaPublicacao404Schema, obterComentariosDaPublicacaoQueryResponseSchema } from "./obterComentariosDaPublicacaoSchema.ts";
export { passwordResetDTOSchema } from "./passwordResetDTOSchema.ts";
export { publicacaoDetailsDTOSchema } from "./publicacaoDetailsDTOSchema.ts";
export { publicacaoSummaryDTOSchema } from "./publicacaoSummaryDTOSchema.ts";
export { registerDTOSchema } from "./registerDTOSchema.ts";
export { register201Schema, register400Schema, registerMutationRequestSchema, registerMutationResponseSchema } from "./registerSchema.ts";
export { removeEstudanteToDisciplinaPathParamsSchema, removeEstudanteToDisciplinaQueryParamsSchema, removeEstudanteToDisciplina200Schema, removeEstudanteToDisciplina404Schema, removeEstudanteToDisciplinaMutationResponseSchema } from "./removeEstudanteToDisciplinaSchema.ts";
export { removePerfilAcessibilidadePathParamsSchema, removePerfilAcessibilidade204Schema, removePerfilAcessibilidade404Schema, removePerfilAcessibilidadeMutationResponseSchema } from "./removePerfilAcessibilidadeSchema.ts";
export { removerComentarioPathParamsSchema, removerComentario204Schema, removerComentario404Schema, removerComentarioMutationResponseSchema } from "./removerComentarioSchema.ts";
export { removerFormacaoPathParamsSchema, removerFormacao204Schema, removerFormacaoMutationResponseSchema } from "./removerFormacaoSchema.ts";
export { removerPathParamsSchema, remover204Schema, remover404Schema, removerMutationResponseSchema } from "./removerSchema.ts";
export { removeTarefaPathParamsSchema, removeTarefa200Schema, removeTarefaMutationResponseSchema } from "./removeTarefaSchema.ts";
export { removeUsuarioFromInstituicaoPathParamsSchema, removeUsuarioFromInstituicao200Schema, removeUsuarioFromInstituicao404Schema, removeUsuarioFromInstituicao409Schema, removeUsuarioFromInstituicaoMutationResponseSchema } from "./removeUsuarioFromInstituicaoSchema.ts";
export { requestResetDTOSchema } from "./requestResetDTOSchema.ts";
export { responderComentarioQueryParamsSchema, responderComentario200Schema, responderComentario404Schema, responderComentario409Schema, responderComentarioMutationRequestSchema, responderComentarioMutationResponseSchema } from "./responderComentarioSchema.ts";
export { responderPublicacaoQueryParamsSchema, responderPublicacao201Schema, responderPublicacao404Schema, responderPublicacao409Schema, responderPublicacaoMutationRequestSchema, responderPublicacaoMutationResponseSchema } from "./responderPublicacaoSchema.ts";
export { respostaAComentarioSummaryDTOSchema } from "./respostaAComentarioSummaryDTOSchema.ts";
export { respostaDTOSchema } from "./respostaDTOSchema.ts";
export { summaryTarefaDTOSchema } from "./summaryTarefaDTOSchema.ts";
export { tarefaDetailsDTOSchema } from "./tarefaDetailsDTOSchema.ts";
export { updateComentarioDTOSchema } from "./updateComentarioDTOSchema.ts";
export { updateDisciplinaDTOSchema } from "./updateDisciplinaDTOSchema.ts";
export { updateDisciplinaPathParamsSchema, updateDisciplina200Schema, updateDisciplina404Schema, updateDisciplina409Schema, updateDisciplinaMutationRequestSchema, updateDisciplinaMutationResponseSchema } from "./updateDisciplinaSchema.ts";
export { updateEducadorDTOSchema } from "./updateEducadorDTOSchema.ts";
export { updateEducadorPathParamsSchema, updateEducador200Schema, updateEducador404Schema, updateEducador409Schema, updateEducadorMutationRequestSchema, updateEducadorMutationResponseSchema } from "./updateEducadorSchema.ts";
export { updateGestorDTOSchema } from "./updateGestorDTOSchema.ts";
export { updateGestorPathParamsSchema, updateGestor200Schema, updateGestor400Schema, updateGestor404Schema, updateGestorMutationRequestSchema, updateGestorMutationResponseSchema } from "./updateGestorSchema.ts";
export { updateInstituicaoDTOSchema } from "./updateInstituicaoDTOSchema.ts";
export { updateInstituicaoPathParamsSchema, updateInstituicao200Schema, updateInstituicao404Schema, updateInstituicao422Schema, updateInstituicaoMutationRequestSchema, updateInstituicaoMutationResponseSchema } from "./updateInstituicaoSchema.ts";
export { updatePassword200Schema, updatePassword400Schema, updatePasswordMutationRequestSchema, updatePasswordMutationResponseSchema } from "./updatePasswordSchema.ts";
export { updatePerfilAcessibilidadeDTOSchema } from "./updatePerfilAcessibilidadeDTOSchema.ts";
export { updatePerfilAcessibilidadePathParamsSchema, updatePerfilAcessibilidade200Schema, updatePerfilAcessibilidade400Schema, updatePerfilAcessibilidade404Schema, updatePerfilAcessibilidadeMutationRequestSchema, updatePerfilAcessibilidadeMutationResponseSchema } from "./updatePerfilAcessibilidadeSchema.ts";
export { updatePublicacaoDTOSchema } from "./updatePublicacaoDTOSchema.ts";
export { updatePublicacaoPathParamsSchema, updatePublicacao200Schema, updatePublicacao404Schema, updatePublicacao409Schema, updatePublicacaoMutationRequestSchema, updatePublicacaoMutationResponseSchema } from "./updatePublicacaoSchema.ts";
export { updateTarefaDTOSchema } from "./updateTarefaDTOSchema.ts";
export { updateTarefaPathParamsSchema, updateTarefa200Schema, updateTarefaMutationRequestSchema, updateTarefaMutationResponseSchema } from "./updateTarefaSchema.ts";
export { uploadArquivoPathParamsSchema, uploadArquivoQueryParamsSchema, uploadArquivo201Schema, uploadArquivo400Schema, uploadArquivo404Schema, uploadArquivoMutationRequestSchema, uploadArquivoMutationResponseSchema } from "./uploadArquivoSchema.ts";
export { usuarioDetailsDTOSchema } from "./usuarioDetailsDTOSchema.ts";
export { usuarioSummaryDTOSchema } from "./usuarioSummaryDTOSchema.ts";
export { validateTokenQueryParamsSchema, validateToken200Schema, validateToken400Schema, validateTokenMutationResponseSchema } from "./validateTokenSchema.ts";