/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { enderecoSchema } from "./enderecoSchema.ts";
import { z } from "zod/v4";

export const instituicaoDetailsDTOSchema = z.object({
    "id": z.optional(z.int()),
"nome": z.optional(z.string()),
"telefone": z.optional(z.string()),
"email": z.optional(z.string()),
"cnpj": z.optional(z.string()),
get "endereco"(){
                return enderecoSchema.optional()
              }
    })