/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { arquivoDTOSchema } from "./arquivoDTOSchema.ts";
import { z } from "zod/v4";

export const listarArquivosPathParamsSchema = z.object({
    "disciplinaId": z.coerce.number().int().gt(0)
    })

/**
 * @description Arquivos listados com sucesso
 */
export const listarArquivos200Schema = z.array(z.lazy(() => arquivoDTOSchema))

/**
 * @description Nenhum arquivo encontrado
 */
export const listarArquivos204Schema = z.array(z.lazy(() => arquivoDTOSchema))

export const listarArquivosQueryResponseSchema = z.union([z.lazy(() => listarArquivos200Schema), z.lazy(() => listarArquivos204Schema)])