/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { formacaoListResponseDTOSchema } from "./formacaoListResponseDTOSchema.ts";
import { z } from "zod/v4";

export const listarFormacoesPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const listarFormacoes200Schema = z.lazy(() => formacaoListResponseDTOSchema)

export const listarFormacoesQueryResponseSchema = z.lazy(() => listarFormacoes200Schema)