/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { authenticationDTOSchema } from "./authenticationDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Usuário autenticado com sucesso
 */
export const login200Schema = z.object({
    
    })

/**
 * @description Requisição tem parâmetros inválidos
 */
export const login400Schema = z.object({
    
    })

export const loginMutationRequestSchema = z.lazy(() => authenticationDTOSchema)

export const loginMutationResponseSchema = z.lazy(() => login200Schema)