/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const publicacaoSummaryDTOSchema = z.object({
    "id": z.optional(z.int()),
"titulo": z.optional(z.string()),
"dataEnvio": z.optional(z.string().datetime())
    })