/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { educadorSummaryDTOSchema } from "./educadorSummaryDTOSchema.ts";
import { z } from "zod/v4";

export const publicacaoDetailsDTOSchema = z.object({
    "id": z.optional(z.int()),
"titulo": z.optional(z.string()),
"conteudo": z.optional(z.string()),
"caminhoAnexo": z.optional(z.string()),
"dataEnvio": z.optional(z.string().datetime()),
get "autor"(){
                return educadorSummaryDTOSchema.optional()
              }
    })