/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { registerDTOSchema } from "./registerDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Usuário registrado com sucesso
 */
export const register201Schema = z.object({
    
    })

/**
 * @description Requisição tem parâmetros inválidos
 */
export const register400Schema = z.object({
    
    })

export const registerMutationRequestSchema = z.lazy(() => registerDTOSchema)

export const registerMutationResponseSchema = z.lazy(() => register201Schema)