/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const registerDTOSchema = z.object({
    "nome": z.string().min(1),
"cpf": z.string().min(1),
"email": z.string().min(1),
"telefone": z.string().min(1),
"genero": z.optional(z.enum(["MASCULINO", "FEMININO", "OUTRO", "NAO_INFORMAR"])),
"dataNascimento": z.optional(z.iso.date()),
"senha": z.string().min(1),
"userType": z.optional(z.enum(["ESTUDANTE", "EDUCADOR", "GESTOR"])),
"matricula": z.optional(z.string()),
"titulo": z.optional(z.string()),
"periodo": z.optional(z.enum(["MATUTINO", "VESPERTINO", "NOTURNO"])),
"anoEscolar": z.optional(z.enum(["PRIMEIRO_ANO", "SEGUNDO_ANO", "TERCEIRO_ANO", "QUARTO_ANO", "QUINTO_ANO", "SEXTO_ANO", "SETIMO_ANO", "OITAVO_ANO", "NONO_ANO", "PRIMEIO_ANO_EM", "SEGUNDO_ANO_EM", "TERCEIRO_ANO_EM"])),
"cargo": z.optional(z.string()),
"educadorValido": z.optional(z.boolean()),
"estudanteValido": z.optional(z.boolean())
    })