/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const removerPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description Estudante removido com sucesso
 */
export const remover204Schema = z.any()

/**
 * @description Estudante não encontrado
 */
export const remover404Schema = z.any()

export const removerMutationResponseSchema = z.lazy(() => remover204Schema)