/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const removeTarefaPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const removeTarefa200Schema = z.any()

export const removeTarefaMutationResponseSchema = z.lazy(() => removeTarefa200Schema)