/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const removePerfilAcessibilidadePathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description Perfil de Acessibilidade removido com sucesso
 */
export const removePerfilAcessibilidade204Schema = z.object({
    
    })

/**
 * @description Perfil de Acessibilidade não encontrado
 */
export const removePerfilAcessibilidade404Schema = z.object({
    
    })

export const removePerfilAcessibilidadeMutationResponseSchema = z.lazy(() => removePerfilAcessibilidade204Schema)