/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const removerComentarioPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description Comentário removido com sucesso
 */
export const removerComentario204Schema = z.object({
    
    })

/**
 * @description Comentário não encontrado
 */
export const removerComentario404Schema = z.object({
    
    })

export const removerComentarioMutationResponseSchema = z.lazy(() => removerComentario204Schema)