/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { estudanteSummaryDTOSchema } from "./estudanteSummaryDTOSchema.ts";
import { z } from "zod/v4";

export const removeEstudanteToDisciplinaPathParamsSchema = z.object({
    "id": z.coerce.number().int().gt(0)
    })

export const removeEstudanteToDisciplinaQueryParamsSchema = z.object({
    "estudanteId": z.coerce.number().int().gt(0)
    })

/**
 * @description Estudante removido com sucesso
 */
export const removeEstudanteToDisciplina200Schema = z.array(z.lazy(() => estudanteSummaryDTOSchema))

/**
 * @description Estudante ou Disciplina não encontrados
 */
export const removeEstudanteToDisciplina404Schema = z.array(z.lazy(() => estudanteSummaryDTOSchema))

export const removeEstudanteToDisciplinaMutationResponseSchema = z.lazy(() => removeEstudanteToDisciplina200Schema)