/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { usuarioSummaryDTOSchema } from "./usuarioSummaryDTOSchema.ts";
import { z } from "zod/v4";

export const removeUsuarioFromInstituicaoPathParamsSchema = z.object({
    "instituicaoId": z.coerce.number().int(),
"usuarioId": z.coerce.number().int()
    })

/**
 * @description Usuário removidos com sucesso
 */
export const removeUsuarioFromInstituicao200Schema = z.array(z.lazy(() => usuarioSummaryDTOSchema).describe("Sumário de usuários"))

/**
 * @description Instituição ou Usuário não encontrados
 */
export const removeUsuarioFromInstituicao404Schema = z.array(z.lazy(() => usuarioSummaryDTOSchema).describe("Sumário de usuários"))

/**
 * @description Usuário não está associado a Instituição de Ensino
 */
export const removeUsuarioFromInstituicao409Schema = z.array(z.lazy(() => usuarioSummaryDTOSchema).describe("Sumário de usuários"))

export const removeUsuarioFromInstituicaoMutationResponseSchema = z.lazy(() => removeUsuarioFromInstituicao200Schema)