/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const removerFormacaoPathParamsSchema = z.object({
    "id": z.coerce.number().int(),
"formacaoId": z.coerce.number().int()
    })

/**
 * @description Formação removida com sucesso
 */
export const removerFormacao204Schema = z.any()

export const removerFormacaoMutationResponseSchema = z.lazy(() => removerFormacao204Schema)