/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { comentarioSummaryDTOSchema } from "./comentarioSummaryDTOSchema.ts";
import { createComentarioDTOSchema } from "./createComentarioDTOSchema.ts";
import { z } from "zod/v4";

export const responderComentarioQueryParamsSchema = z.object({
    "comentarioId": z.coerce.number().int().gt(0)
    })

/**
 * @description Comentário criado com sucesso
 */
export const responderComentario200Schema = z.lazy(() => comentarioSummaryDTOSchema)

/**
 * @description Comentário, Publicação ou Usuário Autenticado não encontrados
 */
export const responderComentario404Schema = z.lazy(() => comentarioSummaryDTOSchema)

/**
 * @description Dados inválidos ou conflitantes
 */
export const responderComentario409Schema = z.lazy(() => comentarioSummaryDTOSchema)

export const responderComentarioMutationRequestSchema = z.lazy(() => createComentarioDTOSchema)

export const responderComentarioMutationResponseSchema = z.lazy(() => responderComentario200Schema)