/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { comentarioSummaryDTOSchema } from "./comentarioSummaryDTOSchema.ts";
import { createComentarioDTOSchema } from "./createComentarioDTOSchema.ts";
import { z } from "zod/v4";

export const responderPublicacaoQueryParamsSchema = z.object({
    "publicacaoId": z.coerce.number().int().gt(0)
    })

/**
 * @description Comentário criado com sucesso
 */
export const responderPublicacao201Schema = z.lazy(() => comentarioSummaryDTOSchema)

/**
 * @description Publicação ou Usuário Autenticado não encontrados
 */
export const responderPublicacao404Schema = z.lazy(() => comentarioSummaryDTOSchema)

/**
 * @description Dados inválidos ou conflitantes
 */
export const responderPublicacao409Schema = z.lazy(() => comentarioSummaryDTOSchema)

export const responderPublicacaoMutationRequestSchema = z.lazy(() => createComentarioDTOSchema)

export const responderPublicacaoMutationResponseSchema = z.lazy(() => responderPublicacao201Schema)