/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { arquivoDTOSchema } from "./arquivoDTOSchema.ts";
import { z } from "zod/v4";

export const respostaDTOSchema = z.object({
    "id": z.optional(z.int()),
"estudanteNome": z.optional(z.string()),
"nota": z.optional(z.number()),
"comentarioEducador": z.optional(z.string()),
get "arquivo"(){
                return arquivoDTOSchema.optional()
              },
"conteudoTexto": z.optional(z.string()),
"dataUpload": z.optional(z.string().datetime())
    })