/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const summaryTarefaDTOSchema = z.object({
    "id": z.optional(z.int()),
"titulo": z.optional(z.string()),
"resumoConteudo": z.optional(z.string()),
"dataCriacao": z.optional(z.string().datetime()),
"dataExpiracao": z.optional(z.string().datetime()),
"valorTotal": z.optional(z.number()),
"educadorResponsavel": z.optional(z.string()),
"disciplinaId": z.optional(z.int())
    })