/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { respostaDTOSchema } from "./respostaDTOSchema.ts";
import { z } from "zod/v4";

export const tarefaDetailsDTOSchema = z.object({
    "id": z.optional(z.int()),
"titulo": z.optional(z.string()),
"conteudo": z.optional(z.string()),
"dataEnvio": z.optional(z.string().datetime()),
"dataExpiracao": z.optional(z.string().datetime()),
"valorTotal": z.optional(z.number()),
"permitirArquivoResposta": z.optional(z.boolean()),
"disciplinaNome": z.optional(z.string()),
"autorNome": z.optional(z.string()),
get "respostas"(){
                return z.array(respostaDTOSchema).optional()
              }
    })