/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const updateDisciplinaDTOSchema = z.object({
    "nome": z.optional(z.string()),
"descricao": z.optional(z.string()),
"idEducadorResponsavel": z.optional(z.int())
    })