/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const updateComentarioDTOSchema = z.object({
    "conteudo": z.optional(z.string().min(0).max(280))
    })