/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const updateTarefaDTOSchema = z.object({
    "titulo": z.optional(z.string()),
"conteudo": z.optional(z.string()),
"dataExpiracao": z.optional(z.string().datetime()),
"valorTotal": z.optional(z.number()),
"permitirArquivoResposta": z.optional(z.boolean())
    })