/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const updatePublicacaoDTOSchema = z.object({
    "titulo": z.optional(z.string()),
"conteudo": z.optional(z.string()),
"caminhoAnexo": z.optional(z.string())
    })