/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { publicacaoDetailsDTOSchema } from "./publicacaoDetailsDTOSchema.ts";
import { updatePublicacaoDTOSchema } from "./updatePublicacaoDTOSchema.ts";
import { z } from "zod/v4";

export const updatePublicacaoPathParamsSchema = z.object({
    "publicacaoId": z.coerce.number().int()
    })

/**
 * @description Publicação atualizada com sucesso
 */
export const updatePublicacao200Schema = z.lazy(() => publicacaoDetailsDTOSchema)

/**
 * @description Disciplina não encontrada
 */
export const updatePublicacao404Schema = z.lazy(() => publicacaoDetailsDTOSchema)

/**
 * @description Dados inválidos ou conflitantes
 */
export const updatePublicacao409Schema = z.lazy(() => publicacaoDetailsDTOSchema)

export const updatePublicacaoMutationRequestSchema = z.lazy(() => updatePublicacaoDTOSchema)

export const updatePublicacaoMutationResponseSchema = z.lazy(() => updatePublicacao200Schema)