/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { disciplinaSummaryDTOSchema } from "./disciplinaSummaryDTOSchema.ts";
import { updateDisciplinaDTOSchema } from "./updateDisciplinaDTOSchema.ts";
import { z } from "zod/v4";

export const updateDisciplinaPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description Disciplina atualizada com sucesso
 */
export const updateDisciplina200Schema = z.lazy(() => disciplinaSummaryDTOSchema)

/**
 * @description Disciplina ou Educador responsável não encontrados
 */
export const updateDisciplina404Schema = z.lazy(() => disciplinaSummaryDTOSchema)

/**
 * @description Dados inválidos ou conflitantes
 */
export const updateDisciplina409Schema = z.lazy(() => disciplinaSummaryDTOSchema)

export const updateDisciplinaMutationRequestSchema = z.lazy(() => updateDisciplinaDTOSchema)

export const updateDisciplinaMutationResponseSchema = z.lazy(() => updateDisciplina200Schema)