/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { instituicaoDetailsDTOSchema } from "./instituicaoDetailsDTOSchema.ts";
import { updateInstituicaoDTOSchema } from "./updateInstituicaoDTOSchema.ts";
import { z } from "zod/v4";

export const updateInstituicaoPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description Atualização concluída
 */
export const updateInstituicao200Schema = z.lazy(() => instituicaoDetailsDTOSchema)

/**
 * @description Instituição não encontrada
 */
export const updateInstituicao404Schema = z.lazy(() => instituicaoDetailsDTOSchema)

/**
 * @description Dados inválidos
 */
export const updateInstituicao422Schema = z.lazy(() => instituicaoDetailsDTOSchema)

export const updateInstituicaoMutationRequestSchema = z.lazy(() => updateInstituicaoDTOSchema)

export const updateInstituicaoMutationResponseSchema = z.lazy(() => updateInstituicao200Schema)