/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { updatePerfilAcessibilidadeDTOSchema } from "./updatePerfilAcessibilidadeDTOSchema.ts";
import { z } from "zod/v4";

export const updatePerfilAcessibilidadePathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description Perfil de Acessibilidade atualizado com sucesso
 */
export const updatePerfilAcessibilidade200Schema = z.object({
    
    })

/**
 * @description Requisição tem parâmetros inválidos
 */
export const updatePerfilAcessibilidade400Schema = z.object({
    
    })

/**
 * @description Perfil de Acessibilidade não encontrado
 */
export const updatePerfilAcessibilidade404Schema = z.object({
    
    })

export const updatePerfilAcessibilidadeMutationRequestSchema = z.lazy(() => updatePerfilAcessibilidadeDTOSchema)

export const updatePerfilAcessibilidadeMutationResponseSchema = z.lazy(() => updatePerfilAcessibilidade200Schema)