/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const updatePerfilAcessibilidadeDTOSchema = z.object({
    "tipoDeficiencia": z.optional(z.enum(["NENHUMA", "VISUAL", "AUDITIVA", "MOTORA", "COGNITIVA", "OUTRA"])),
"usaLeitorDeTela": z.optional(z.boolean()),
"modoAltoContraste": z.optional(z.boolean()),
"tamanhoFonte": z.optional(z.int()),
"talkBack": z.optional(z.boolean())
    })