/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { summaryTarefaDTOSchema } from "./summaryTarefaDTOSchema.ts";
import { updateTarefaDTOSchema } from "./updateTarefaDTOSchema.ts";
import { z } from "zod/v4";

export const updateTarefaPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const updateTarefa200Schema = z.lazy(() => summaryTarefaDTOSchema)

export const updateTarefaMutationRequestSchema = z.lazy(() => updateTarefaDTOSchema)

export const updateTarefaMutationResponseSchema = z.lazy(() => updateTarefa200Schema)