/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { passwordResetDTOSchema } from "./passwordResetDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description A senha é alterada com sucesso
 */
export const updatePassword200Schema = z.object({
    
    })

/**
 * @description Não foi possível atualizar a senha
 */
export const updatePassword400Schema = z.object({
    
    })

export const updatePasswordMutationRequestSchema = z.lazy(() => passwordResetDTOSchema)

export const updatePasswordMutationResponseSchema = z.lazy(() => updatePassword200Schema)