/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { arquivoDTOSchema } from "./arquivoDTOSchema.ts";
import { z } from "zod/v4";

export const uploadArquivoPathParamsSchema = z.object({
    "disciplinaId": z.coerce.number().int().gt(0)
    })

export const uploadArquivoQueryParamsSchema = z.object({
    "descricao": z.optional(z.string()),
"usuarioId": z.coerce.number().int()
    })

/**
 * @description Arquivo enviado com sucesso
 */
export const uploadArquivo201Schema = z.lazy(() => arquivoDTOSchema)

/**
 * @description Falha ao enviar o arquivo
 */
export const uploadArquivo400Schema = z.lazy(() => arquivoDTOSchema)

/**
 * @description Disciplina ou Educador não encontrados
 */
export const uploadArquivo404Schema = z.lazy(() => arquivoDTOSchema)

export const uploadArquivoMutationRequestSchema = z.object({
    "arquivo": z.instanceof(File)
    })

export const uploadArquivoMutationResponseSchema = z.lazy(() => uploadArquivo201Schema)