/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { instituicaoDetailsDTOSchema } from "./instituicaoDetailsDTOSchema.ts";
import { z } from "zod/v4";

export const usuarioDetailsDTOSchema = z.object({
    "id": z.optional(z.int()),
"nome": z.optional(z.string()),
"email": z.optional(z.string()),
"telefone": z.optional(z.string()),
"genero": z.optional(z.enum(["MASCULINO", "FEMININO", "OUTRO", "NAO_INFORMAR"])),
"dataNascimento": z.optional(z.iso.date()),
get "instituicao"(){
                return instituicaoDetailsDTOSchema.optional()
              },
"roles": z.optional(z.enum(["ESTUDANTE", "EDUCADOR", "GESTOR", "GUEST", "USER", "ADMIN"]))
    })