/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Sumário de usuários
 */
export const usuarioSummaryDTOSchema = z.object({
    "id": z.optional(z.int()),
"nome": z.optional(z.string()),
"email": z.optional(z.string()),
"funcao": z.optional(z.string())
    }).describe("Sumário de usuários")