/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const validateTokenQueryParamsSchema = z.object({
    "token": z.string()
    })

/**
 * @description O token é válido
 */
export const validateToken200Schema = z.object({
    
    })

/**
 * @description O token não é válido
 */
export const validateToken400Schema = z.object({
    
    })

export const validateTokenMutationResponseSchema = z.lazy(() => validateToken200Schema)