/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { AdicionarFormacaoMutationRequest, AdicionarFormacaoMutationResponse, AdicionarFormacaoPathParams } from "../../models/AdicionarFormacao.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { adicionarFormacao } from "../../client/adicionarFormacao.ts";

export const adicionarFormacaoMutationKey = () => [{ url: '/educadores/:id/formacoes' }] as const

export type AdicionarFormacaoMutationKey = ReturnType<typeof adicionarFormacaoMutationKey>

export function adicionarFormacaoMutationOptions(config: Partial<RequestConfig<AdicionarFormacaoMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = adicionarFormacaoMutationKey()
  return mutationOptions<AdicionarFormacaoMutationResponse, ResponseErrorConfig<Error>, {id: AdicionarFormacaoPathParams["id"], data?: AdicionarFormacaoMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return adicionarFormacao(id, data, config)
    },
  })
}

/**
 * @summary Adicionar nova formação ao educador
 * {@link /educadores/:id/formacoes}
 */
export function useAdicionarFormacao<TContext>(options: 
{
  mutation?: UseMutationOptions<AdicionarFormacaoMutationResponse, ResponseErrorConfig<Error>, {id: AdicionarFormacaoPathParams["id"], data?: AdicionarFormacaoMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AdicionarFormacaoMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? adicionarFormacaoMutationKey()

  const baseOptions = adicionarFormacaoMutationOptions(config) as UseMutationOptions<AdicionarFormacaoMutationResponse, ResponseErrorConfig<Error>, {id: AdicionarFormacaoPathParams["id"], data?: AdicionarFormacaoMutationRequest}, TContext>

  return useMutation<AdicionarFormacaoMutationResponse, ResponseErrorConfig<Error>, {id: AdicionarFormacaoPathParams["id"], data?: AdicionarFormacaoMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<AdicionarFormacaoMutationResponse, ResponseErrorConfig<Error>, {id: AdicionarFormacaoPathParams["id"], data?: AdicionarFormacaoMutationRequest}, TContext>
}