/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetEducadorQueryResponse, GetEducadorPathParams } from "../../models/GetEducador.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getEducador } from "../../client/getEducador.ts";

export const getEducadorQueryKey = (id: GetEducadorPathParams["id"]) => [{ url: '/educadores/:id', params: {id:id} }] as const

export type GetEducadorQueryKey = ReturnType<typeof getEducadorQueryKey>

export function getEducadorQueryOptions(id: GetEducadorPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getEducadorQueryKey(id)
  return queryOptions<GetEducadorQueryResponse, ResponseErrorConfig<Error>, GetEducadorQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getEducador(id, config)
   },
  })
}

/**
 * @summary Buscar Educador por ID
 * {@link /educadores/:id}
 */
export function useGetEducador<TData = GetEducadorQueryResponse, TQueryData = GetEducadorQueryResponse, TQueryKey extends QueryKey = GetEducadorQueryKey>(id: GetEducadorPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<GetEducadorQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getEducadorQueryKey(id)

  const query = useQuery({
   ...getEducadorQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}