/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetEducadorQueryResponse, GetEducadorPathParams } from "../../models/GetEducador.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getEducador } from "../../client/getEducador.ts";

export const getEducadorSuspenseQueryKey = (id: GetEducadorPathParams["id"]) => [{ url: '/educadores/:id', params: {id:id} }] as const

export type GetEducadorSuspenseQueryKey = ReturnType<typeof getEducadorSuspenseQueryKey>

export function getEducadorSuspenseQueryOptions(id: GetEducadorPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getEducadorSuspenseQueryKey(id)
  return queryOptions<GetEducadorQueryResponse, ResponseErrorConfig<Error>, GetEducadorQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getEducador(id, config)
   },
  })
}

/**
 * @summary Buscar Educador por ID
 * {@link /educadores/:id}
 */
export function useGetEducadorSuspense<TData = GetEducadorQueryResponse, TQueryKey extends QueryKey = GetEducadorSuspenseQueryKey>(id: GetEducadorPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetEducadorQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getEducadorSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...getEducadorSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}