/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { ListarFormacoesQueryResponse, ListarFormacoesPathParams } from "../../models/ListarFormacoes.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { listarFormacoes } from "../../client/listarFormacoes.ts";

export const listarFormacoesSuspenseQueryKey = (id: ListarFormacoesPathParams["id"]) => [{ url: '/educadores/:id/formacoes', params: {id:id} }] as const

export type ListarFormacoesSuspenseQueryKey = ReturnType<typeof listarFormacoesSuspenseQueryKey>

export function listarFormacoesSuspenseQueryOptions(id: ListarFormacoesPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = listarFormacoesSuspenseQueryKey(id)
  return queryOptions<ListarFormacoesQueryResponse, ResponseErrorConfig<Error>, ListarFormacoesQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return listarFormacoes(id, config)
   },
  })
}

/**
 * {@link /educadores/:id/formacoes}
 */
export function useListarFormacoesSuspense<TData = ListarFormacoesQueryResponse, TQueryKey extends QueryKey = ListarFormacoesSuspenseQueryKey>(id: ListarFormacoesPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ListarFormacoesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? listarFormacoesSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...listarFormacoesSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}