/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { RemoverFormacaoMutationResponse, RemoverFormacaoPathParams } from "../../models/RemoverFormacao.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { removerFormacao } from "../../client/removerFormacao.ts";

export const removerFormacaoMutationKey = () => [{ url: '/educadores/:id/formacoes/:formacaoId' }] as const

export type RemoverFormacaoMutationKey = ReturnType<typeof removerFormacaoMutationKey>

export function removerFormacaoMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = removerFormacaoMutationKey()
  return mutationOptions<RemoverFormacaoMutationResponse, ResponseErrorConfig<Error>, {id: RemoverFormacaoPathParams["id"], formacaoId: RemoverFormacaoPathParams["formacaoId"]}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, formacaoId }) => {
      return removerFormacao(id, formacaoId, config)
    },
  })
}

/**
 * @summary Remover formação do educador
 * {@link /educadores/:id/formacoes/:formacaoId}
 */
export function useRemoverFormacao<TContext>(options: 
{
  mutation?: UseMutationOptions<RemoverFormacaoMutationResponse, ResponseErrorConfig<Error>, {id: RemoverFormacaoPathParams["id"], formacaoId: RemoverFormacaoPathParams["formacaoId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? removerFormacaoMutationKey()

  const baseOptions = removerFormacaoMutationOptions(config) as UseMutationOptions<RemoverFormacaoMutationResponse, ResponseErrorConfig<Error>, {id: RemoverFormacaoPathParams["id"], formacaoId: RemoverFormacaoPathParams["formacaoId"]}, TContext>

  return useMutation<RemoverFormacaoMutationResponse, ResponseErrorConfig<Error>, {id: RemoverFormacaoPathParams["id"], formacaoId: RemoverFormacaoPathParams["formacaoId"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<RemoverFormacaoMutationResponse, ResponseErrorConfig<Error>, {id: RemoverFormacaoPathParams["id"], formacaoId: RemoverFormacaoPathParams["formacaoId"]}, TContext>
}