/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { UpdateEducadorMutationRequest, UpdateEducadorMutationResponse, UpdateEducadorPathParams, UpdateEducador404, UpdateEducador409 } from "../../models/UpdateEducador.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { updateEducador } from "../../client/updateEducador.ts";

export const updateEducadorMutationKey = () => [{ url: '/educadores/:id' }] as const

export type UpdateEducadorMutationKey = ReturnType<typeof updateEducadorMutationKey>

export function updateEducadorMutationOptions(config: Partial<RequestConfig<UpdateEducadorMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = updateEducadorMutationKey()
  return mutationOptions<UpdateEducadorMutationResponse, ResponseErrorConfig<UpdateEducador404 | UpdateEducador409>, {id: UpdateEducadorPathParams["id"], data?: UpdateEducadorMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return updateEducador(id, data, config)
    },
  })
}

/**
 * @summary Atualiza um Educador
 * {@link /educadores/:id}
 */
export function useUpdateEducador<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateEducadorMutationResponse, ResponseErrorConfig<UpdateEducador404 | UpdateEducador409>, {id: UpdateEducadorPathParams["id"], data?: UpdateEducadorMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateEducadorMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updateEducadorMutationKey()

  const baseOptions = updateEducadorMutationOptions(config) as UseMutationOptions<UpdateEducadorMutationResponse, ResponseErrorConfig<UpdateEducador404 | UpdateEducador409>, {id: UpdateEducadorPathParams["id"], data?: UpdateEducadorMutationRequest}, TContext>

  return useMutation<UpdateEducadorMutationResponse, ResponseErrorConfig<UpdateEducador404 | UpdateEducador409>, {id: UpdateEducadorPathParams["id"], data?: UpdateEducadorMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<UpdateEducadorMutationResponse, ResponseErrorConfig<UpdateEducador404 | UpdateEducador409>, {id: UpdateEducadorPathParams["id"], data?: UpdateEducadorMutationRequest}, TContext>
}