/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { ForgotPasswordMutationRequest, ForgotPasswordMutationResponse } from "../../models/ForgotPassword.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { forgotPassword } from "../../client/forgotPassword.ts";

export const forgotPasswordMutationKey = () => [{ url: '/reset-password/forgot-password' }] as const

export type ForgotPasswordMutationKey = ReturnType<typeof forgotPasswordMutationKey>

export function forgotPasswordMutationOptions(config: Partial<RequestConfig<ForgotPasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = forgotPasswordMutationKey()
  return mutationOptions<ForgotPasswordMutationResponse, ResponseErrorConfig<Error>, {data?: ForgotPasswordMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return forgotPassword(data, config)
    },
  })
}

/**
 * @summary Solicita redefinição de senha através do e-mail
 * {@link /reset-password/forgot-password}
 */
export function useForgotPassword<TContext>(options: 
{
  mutation?: UseMutationOptions<ForgotPasswordMutationResponse, ResponseErrorConfig<Error>, {data?: ForgotPasswordMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ForgotPasswordMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? forgotPasswordMutationKey()

  const baseOptions = forgotPasswordMutationOptions(config) as UseMutationOptions<ForgotPasswordMutationResponse, ResponseErrorConfig<Error>, {data?: ForgotPasswordMutationRequest}, TContext>

  return useMutation<ForgotPasswordMutationResponse, ResponseErrorConfig<Error>, {data?: ForgotPasswordMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ForgotPasswordMutationResponse, ResponseErrorConfig<Error>, {data?: ForgotPasswordMutationRequest}, TContext>
}