/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { UpdatePasswordMutationRequest, UpdatePasswordMutationResponse, UpdatePassword400 } from "../../models/UpdatePassword.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { updatePassword } from "../../client/updatePassword.ts";

export const updatePasswordMutationKey = () => [{ url: '/reset-password' }] as const

export type UpdatePasswordMutationKey = ReturnType<typeof updatePasswordMutationKey>

export function updatePasswordMutationOptions(config: Partial<RequestConfig<UpdatePasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = updatePasswordMutationKey()
  return mutationOptions<UpdatePasswordMutationResponse, ResponseErrorConfig<UpdatePassword400>, {data: UpdatePasswordMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return updatePassword(data, config)
    },
  })
}

/**
 * @summary Recebe o token e senha nova do usuário para redefiní-la
 * {@link /reset-password}
 */
export function useUpdatePassword<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdatePasswordMutationResponse, ResponseErrorConfig<UpdatePassword400>, {data: UpdatePasswordMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdatePasswordMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updatePasswordMutationKey()

  const baseOptions = updatePasswordMutationOptions(config) as UseMutationOptions<UpdatePasswordMutationResponse, ResponseErrorConfig<UpdatePassword400>, {data: UpdatePasswordMutationRequest}, TContext>

  return useMutation<UpdatePasswordMutationResponse, ResponseErrorConfig<UpdatePassword400>, {data: UpdatePasswordMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<UpdatePasswordMutationResponse, ResponseErrorConfig<UpdatePassword400>, {data: UpdatePasswordMutationRequest}, TContext>
}