/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { ValidateTokenMutationResponse, ValidateTokenQueryParams, ValidateToken400 } from "../../models/ValidateToken.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { validateToken } from "../../client/validateToken.ts";

export const validateTokenMutationKey = () => [{ url: '/reset-password/validate' }] as const

export type ValidateTokenMutationKey = ReturnType<typeof validateTokenMutationKey>

export function validateTokenMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = validateTokenMutationKey()
  return mutationOptions<ValidateTokenMutationResponse, ResponseErrorConfig<ValidateToken400>, {params: ValidateTokenQueryParams}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ params }) => {
      return validateToken(params, config)
    },
  })
}

/**
 * @summary Valida o token enviado através do email
 * {@link /reset-password/validate}
 */
export function useValidateToken<TContext>(options: 
{
  mutation?: UseMutationOptions<ValidateTokenMutationResponse, ResponseErrorConfig<ValidateToken400>, {params: ValidateTokenQueryParams}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? validateTokenMutationKey()

  const baseOptions = validateTokenMutationOptions(config) as UseMutationOptions<ValidateTokenMutationResponse, ResponseErrorConfig<ValidateToken400>, {params: ValidateTokenQueryParams}, TContext>

  return useMutation<ValidateTokenMutationResponse, ResponseErrorConfig<ValidateToken400>, {params: ValidateTokenQueryParams}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ValidateTokenMutationResponse, ResponseErrorConfig<ValidateToken400>, {params: ValidateTokenQueryParams}, TContext>
}