/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { AddEstudanteToDisciplinaMutationResponse, AddEstudanteToDisciplinaPathParams, AddEstudanteToDisciplinaQueryParams, AddEstudanteToDisciplina404 } from "../models/AddEstudanteToDisciplina.ts";

function getAddEstudanteToDisciplinaUrl(id: AddEstudanteToDisciplinaPathParams["id"]) {
  const res = { method: 'POST', url: `http://localhost:8080/disciplinas/${id}/estudantes` as const }  
  return res
}

/**
 * @summary Adiciona um Estudante a uma Disciplina
 * {@link /disciplinas/:id/estudantes}
 */
export async function addEstudanteToDisciplina(id: AddEstudanteToDisciplinaPathParams["id"], params: AddEstudanteToDisciplinaQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<AddEstudanteToDisciplinaMutationResponse, ResponseErrorConfig<AddEstudanteToDisciplina404>, unknown>({ method : "POST", url : getAddEstudanteToDisciplinaUrl(id).url.toString(), params, ... requestConfig })  
  return res.data
}