/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { AddUsuarioToInstituicaoMutationResponse, AddUsuarioToInstituicaoPathParams, AddUsuarioToInstituicao404, AddUsuarioToInstituicao409 } from "../models/AddUsuarioToInstituicao.ts";

function getAddUsuarioToInstituicaoUrl(instituicaoId: AddUsuarioToInstituicaoPathParams["instituicaoId"], usuarioId: AddUsuarioToInstituicaoPathParams["usuarioId"]) {
  const res = { method: 'POST', url: `http://localhost:8080/instituicoes/${instituicaoId}/usuarios/${usuarioId}` as const }  
  return res
}

/**
 * @summary Adiciona Usuário a uma Instituição de Ensino
 * {@link /instituicoes/:instituicaoId/usuarios/:usuarioId}
 */
export async function addUsuarioToInstituicao(instituicaoId: AddUsuarioToInstituicaoPathParams["instituicaoId"], usuarioId: AddUsuarioToInstituicaoPathParams["usuarioId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<AddUsuarioToInstituicaoMutationResponse, ResponseErrorConfig<AddUsuarioToInstituicao404 | AddUsuarioToInstituicao409>, unknown>({ method : "POST", url : getAddUsuarioToInstituicaoUrl(instituicaoId, usuarioId).url.toString(), ... requestConfig })  
  return res.data
}