/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { AtualizarComentarioMutationRequest, AtualizarComentarioMutationResponse, AtualizarComentarioPathParams, AtualizarComentario404 } from "../models/AtualizarComentario.ts";

function getAtualizarComentarioUrl(id: AtualizarComentarioPathParams["id"]) {
  const res = { method: 'PUT', url: `http://localhost:8080/comentarios/${id}` as const }  
  return res
}

/**
 * @summary Atualiza um comentário
 * {@link /comentarios/:id}
 */
export async function atualizarComentario(id: AtualizarComentarioPathParams["id"], data?: AtualizarComentarioMutationRequest, config: Partial<RequestConfig<AtualizarComentarioMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AtualizarComentarioMutationResponse, ResponseErrorConfig<AtualizarComentario404>, AtualizarComentarioMutationRequest>({ method : "PUT", url : getAtualizarComentarioUrl(id).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}