/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { AvaliarRespostaMutationRequest, AvaliarRespostaMutationResponse, AvaliarRespostaPathParams } from "../models/AvaliarResposta.ts";

function getAvaliarRespostaUrl(id: AvaliarRespostaPathParams["id"]) {
  const res = { method: 'PATCH', url: `http://localhost:8080/respostas/${id}/avaliar` as const }  
  return res
}

/**
 * @summary Avalia uma resposta enviada por um estudante
 * {@link /respostas/:id/avaliar}
 */
export async function avaliarResposta(id: AvaliarRespostaPathParams["id"], data: AvaliarRespostaMutationRequest, config: Partial<RequestConfig<AvaliarRespostaMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AvaliarRespostaMutationResponse, ResponseErrorConfig<Error>, AvaliarRespostaMutationRequest>({ method : "PATCH", url : getAvaliarRespostaUrl(id).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}