/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { BuscarPorIdQueryResponse, BuscarPorIdPathParams, BuscarPorId404 } from "../models/BuscarPorId.ts";

function getBuscarPorIdUrl(id: BuscarPorIdPathParams["id"]) {
  const res = { method: 'GET', url: `http://localhost:8080/estudantes/${id}` as const }  
  return res
}

/**
 * @summary Obtém um Estudante de acordo com seu ID
 * {@link /estudantes/:id}
 */
export async function buscarPorId(id: BuscarPorIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<BuscarPorIdQueryResponse, ResponseErrorConfig<BuscarPorId404>, unknown>({ method : "GET", url : getBuscarPorIdUrl(id).url.toString(), ... requestConfig })  
  return res.data
}