/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { CreatePerfilAcessibilidadeMutationRequest, CreatePerfilAcessibilidadeMutationResponse, CreatePerfilAcessibilidadeQueryParams, CreatePerfilAcessibilidade400, CreatePerfilAcessibilidade404 } from "../models/CreatePerfilAcessibilidade.ts";

function getCreatePerfilAcessibilidadeUrl() {
  const res = { method: 'POST', url: `http://localhost:8080/acessibilidade/estudante` as const }  
  return res
}

/**
 * @summary Cadastra um novo perfil de acessibilidade para um Estudante
 * {@link /acessibilidade/estudante}
 */
export async function createPerfilAcessibilidade(data: CreatePerfilAcessibilidadeMutationRequest, params: CreatePerfilAcessibilidadeQueryParams, config: Partial<RequestConfig<CreatePerfilAcessibilidadeMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreatePerfilAcessibilidadeMutationResponse, ResponseErrorConfig<CreatePerfilAcessibilidade400 | CreatePerfilAcessibilidade404>, CreatePerfilAcessibilidadeMutationRequest>({ method : "POST", url : getCreatePerfilAcessibilidadeUrl().url.toString(), params, data : requestData, ... requestConfig })  
  return res.data
}