/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { CreateInstituicaoMutationRequest, CreateInstituicaoMutationResponse, CreateInstituicao409, CreateInstituicao422 } from "../models/CreateInstituicao.ts";

function getCreateInstituicaoUrl() {
  const res = { method: 'POST', url: `http://localhost:8080/instituicoes` as const }  
  return res
}

/**
 * @summary Realiza a criação de instituições, vinculando automaticamente o Gestor que realizou a solicitação
 * {@link /instituicoes}
 */
export async function createInstituicao(data: CreateInstituicaoMutationRequest, config: Partial<RequestConfig<CreateInstituicaoMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateInstituicaoMutationResponse, ResponseErrorConfig<CreateInstituicao409 | CreateInstituicao422>, CreateInstituicaoMutationRequest>({ method : "POST", url : getCreateInstituicaoUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}