/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { CreateTarefaMutationRequest, CreateTarefaMutationResponse } from "../models/CreateTarefa.ts";

function getCreateTarefaUrl() {
  const res = { method: 'POST', url: `http://localhost:8080/tarefas` as const }  
  return res
}

/**
 * @summary Cria uma nova tarefa
 * {@link /tarefas}
 */
export async function createTarefa(data: CreateTarefaMutationRequest, config: Partial<RequestConfig<CreateTarefaMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateTarefaMutationResponse, ResponseErrorConfig<Error>, CreateTarefaMutationRequest>({ method : "POST", url : getCreateTarefaUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}