/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { CreateDisciplinaMutationRequest, CreateDisciplinaMutationResponse, CreateDisciplina404, CreateDisciplina409 } from "../models/CreateDisciplina.ts";

function getCreateDisciplinaUrl() {
  const res = { method: 'POST', url: `http://localhost:8080/disciplinas` as const }  
  return res
}

/**
 * @summary Cria uma Disciplina
 * {@link /disciplinas}
 */
export async function createDisciplina(data: CreateDisciplinaMutationRequest, config: Partial<RequestConfig<CreateDisciplinaMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateDisciplinaMutationResponse, ResponseErrorConfig<CreateDisciplina404 | CreateDisciplina409>, CreateDisciplinaMutationRequest>({ method : "POST", url : getCreateDisciplinaUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}