/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { CriarRespostaComUploadMutationRequest, CriarRespostaComUploadMutationResponse } from "../models/CriarRespostaComUpload.ts";
import { buildFormData } from "../.kubb/config.ts";

function getCriarRespostaComUploadUrl() {
  const res = { method: 'POST', url: `http://localhost:8080/respostas/upload` as const }  
  return res
}

/**
 * @summary Cria uma nova resposta com upload de arquivo
 * {@link /respostas/upload}
 */
export async function criarRespostaComUpload(data?: CriarRespostaComUploadMutationRequest, config: Partial<RequestConfig<CriarRespostaComUploadMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  const formData = buildFormData(requestData)  
  const res = await request<CriarRespostaComUploadMutationResponse, ResponseErrorConfig<Error>, CriarRespostaComUploadMutationRequest>({ method : "POST", url : getCriarRespostaComUploadUrl().url.toString(), data : formData as FormData, ... requestConfig })  
  return res.data
}