/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { DeletarArquivoMutationResponse, DeletarArquivoPathParams, DeletarArquivoQueryParams } from "../models/DeletarArquivo.ts";

function getDeletarArquivoUrl(arquivoId: DeletarArquivoPathParams["arquivoId"]) {
  const res = { method: 'DELETE', url: `http://localhost:8080/arquivos/${arquivoId}` as const }  
  return res
}

/**
 * @summary Deleta um arquivo (restrições: estudantes só podem deletar os próprios arquivos)
 * {@link /arquivos/:arquivoId}
 */
export async function deletarArquivo(arquivoId: DeletarArquivoPathParams["arquivoId"], params: DeletarArquivoQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeletarArquivoMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getDeletarArquivoUrl(arquivoId).url.toString(), params, ... requestConfig })  
  return res.data
}