/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { DeletePublicacaoMutationResponse, DeletePublicacaoPathParams, DeletePublicacao404 } from "../models/DeletePublicacao.ts";

function getDeletePublicacaoUrl(publicacaoId: DeletePublicacaoPathParams["publicacaoId"]) {
  const res = { method: 'DELETE', url: `http://localhost:8080/publicacoes/${publicacaoId}` as const }  
  return res
}

/**
 * @summary Deleta uma Publicação a partir do seu ID
 * {@link /publicacoes/:publicacaoId}
 */
export async function deletePublicacao(publicacaoId: DeletePublicacaoPathParams["publicacaoId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeletePublicacaoMutationResponse, ResponseErrorConfig<DeletePublicacao404>, unknown>({ method : "DELETE", url : getDeletePublicacaoUrl(publicacaoId).url.toString(), ... requestConfig })  
  return res.data
}