/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { DownloadArquivoQueryResponse, DownloadArquivoPathParams } from "../models/DownloadArquivo.ts";

function getDownloadArquivoUrl(arquivoId: DownloadArquivoPathParams["arquivoId"]) {
  const res = { method: 'GET', url: `http://localhost:8080/arquivos/download/${arquivoId}` as const }  
  return res
}

/**
 * @summary Baixa um arquivo pelo ID
 * {@link /arquivos/download/:arquivoId}
 */
export async function downloadArquivo(arquivoId: DownloadArquivoPathParams["arquivoId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DownloadArquivoQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getDownloadArquivoUrl(arquivoId).url.toString(), ... requestConfig })  
  return res.data
}