/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { EnviarRespostaMutationRequest, EnviarRespostaMutationResponse } from "../models/EnviarResposta.ts";

function getEnviarRespostaUrl() {
  const res = { method: 'POST', url: `http://localhost:8080/respostas` as const }  
  return res
}

/**
 * @summary Cria uma nova resposta de texto para uma tarefa
 * {@link /respostas}
 */
export async function enviarResposta(data: EnviarRespostaMutationRequest, config: Partial<RequestConfig<EnviarRespostaMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<EnviarRespostaMutationResponse, ResponseErrorConfig<Error>, EnviarRespostaMutationRequest>({ method : "POST", url : getEnviarRespostaUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}