/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { ForgotPasswordMutationRequest, ForgotPasswordMutationResponse } from "../models/ForgotPassword.ts";

function getForgotPasswordUrl() {
  const res = { method: 'POST', url: `http://localhost:8080/reset-password/forgot-password` as const }  
  return res
}

/**
 * @summary Solicita redefinição de senha através do e-mail
 * {@link /reset-password/forgot-password}
 */
export async function forgotPassword(data?: ForgotPasswordMutationRequest, config: Partial<RequestConfig<ForgotPasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ForgotPasswordMutationResponse, ResponseErrorConfig<Error>, ForgotPasswordMutationRequest>({ method : "POST", url : getForgotPasswordUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}