/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetDisciplinasByEducadorQueryResponse, GetDisciplinasByEducadorQueryParams } from "../models/GetDisciplinasByEducador.ts";

function getGetDisciplinasByEducadorUrl() {
  const res = { method: 'GET', url: `http://localhost:8080/disciplinas/educador` as const }  
  return res
}

/**
 * @summary Obtém as Disciplinas ministradas por um Educador
 * {@link /disciplinas/educador}
 */
export async function getDisciplinasByEducador(params: GetDisciplinasByEducadorQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetDisciplinasByEducadorQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetDisciplinasByEducadorUrl().url.toString(), params, ... requestConfig })  
  return res.data
}