/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetDisciplinasByInstituicaoQueryResponse, GetDisciplinasByInstituicaoQueryParams, GetDisciplinasByInstituicao404 } from "../models/GetDisciplinasByInstituicao.ts";

function getGetDisciplinasByInstituicaoUrl() {
  const res = { method: 'GET', url: `http://localhost:8080/disciplinas/instituicao` as const }  
  return res
}

/**
 * @summary Obtém as Disciplinas cadastradas em uma determinada Instituição de Ensino
 * {@link /disciplinas/instituicao}
 */
export async function getDisciplinasByInstituicao(params: GetDisciplinasByInstituicaoQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetDisciplinasByInstituicaoQueryResponse, ResponseErrorConfig<GetDisciplinasByInstituicao404>, unknown>({ method : "GET", url : getGetDisciplinasByInstituicaoUrl().url.toString(), params, ... requestConfig })  
  return res.data
}