/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetDisciplinaByIdQueryResponse, GetDisciplinaByIdPathParams, GetDisciplinaById404 } from "../models/GetDisciplinaById.ts";

function getGetDisciplinaByIdUrl(id: GetDisciplinaByIdPathParams["id"]) {
  const res = { method: 'GET', url: `http://localhost:8080/disciplinas/${id}` as const }  
  return res
}

/**
 * @summary Obtém uma Disciplina através do seu ID
 * {@link /disciplinas/:id}
 */
export async function getDisciplinaById(id: GetDisciplinaByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetDisciplinaByIdQueryResponse, ResponseErrorConfig<GetDisciplinaById404>, unknown>({ method : "GET", url : getGetDisciplinaByIdUrl(id).url.toString(), ... requestConfig })  
  return res.data
}