/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetDisciplinasByEstudanteQueryResponse, GetDisciplinasByEstudanteQueryParams, GetDisciplinasByEstudante404 } from "../models/GetDisciplinasByEstudante.ts";

function getGetDisciplinasByEstudanteUrl() {
  const res = { method: 'GET', url: `http://localhost:8080/disciplinas/estudante` as const }  
  return res
}

/**
 * @summary Obtém as Disciplinas nas quais um estudante está matriculado
 * {@link /disciplinas/estudante}
 */
export async function getDisciplinasByEstudante(params: GetDisciplinasByEstudanteQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetDisciplinasByEstudanteQueryResponse, ResponseErrorConfig<GetDisciplinasByEstudante404>, unknown>({ method : "GET", url : getGetDisciplinasByEstudanteUrl().url.toString(), params, ... requestConfig })  
  return res.data
}