/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetEducadorQueryResponse, GetEducadorPathParams } from "../models/GetEducador.ts";

function getGetEducadorUrl(id: GetEducadorPathParams["id"]) {
  const res = { method: 'GET', url: `http://localhost:8080/educadores/${id}` as const }  
  return res
}

/**
 * @summary Buscar Educador por ID
 * {@link /educadores/:id}
 */
export async function getEducador(id: GetEducadorPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetEducadorQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetEducadorUrl(id).url.toString(), ... requestConfig })  
  return res.data
}