/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetEstudantesFromDisciplinaQueryResponse, GetEstudantesFromDisciplinaPathParams, GetEstudantesFromDisciplina404 } from "../models/GetEstudantesFromDisciplina.ts";

function getGetEstudantesFromDisciplinaUrl(id: GetEstudantesFromDisciplinaPathParams["id"]) {
  const res = { method: 'GET', url: `http://localhost:8080/disciplinas/${id}/estudantes` as const }  
  return res
}

/**
 * @summary Obtém os Estudantes matriculados em uma Instituição de Ensino
 * {@link /disciplinas/:id/estudantes}
 */
export async function getEstudantesFromDisciplina(id: GetEstudantesFromDisciplinaPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetEstudantesFromDisciplinaQueryResponse, ResponseErrorConfig<GetEstudantesFromDisciplina404>, unknown>({ method : "GET", url : getGetEstudantesFromDisciplinaUrl(id).url.toString(), ... requestConfig })  
  return res.data
}