/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetGestorByIdQueryResponse, GetGestorByIdPathParams, GetGestorById400, GetGestorById404 } from "../models/GetGestorById.ts";

function getGetGestorByIdUrl(id: GetGestorByIdPathParams["id"]) {
  const res = { method: 'GET', url: `http://localhost:8080/gestor/${id}` as const }  
  return res
}

/**
 * @summary Obtém um Gestor de acordo com seu ID
 * {@link /gestor/:id}
 */
export async function getGestorById(id: GetGestorByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetGestorByIdQueryResponse, ResponseErrorConfig<GetGestorById400 | GetGestorById404>, unknown>({ method : "GET", url : getGetGestorByIdUrl(id).url.toString(), ... requestConfig })  
  return res.data
}