/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetGestorByEmailQueryRequest, GetGestorByEmailQueryResponse, GetGestorByEmail400, GetGestorByEmail404 } from "../models/GetGestorByEmail.ts";

function getGetGestorByEmailUrl() {
  const res = { method: 'GET', url: `http://localhost:8080/gestor` as const }  
  return res
}

/**
 * @summary Obtém um Gestor de acordo com seu e-mail
 * {@link /gestor}
 */
export async function getGestorByEmail(data: GetGestorByEmailQueryRequest, config: Partial<RequestConfig<GetGestorByEmailQueryRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<GetGestorByEmailQueryResponse, ResponseErrorConfig<GetGestorByEmail400 | GetGestorByEmail404>, GetGestorByEmailQueryRequest>({ method : "GET", url : getGetGestorByEmailUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}