/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetInstituicaoByCnpjQueryRequest, GetInstituicaoByCnpjQueryResponse, GetInstituicaoByCnpj404 } from "../models/GetInstituicaoByCnpj.ts";

function getGetInstituicaoByCnpjUrl() {
  const res = { method: 'GET', url: `http://localhost:8080/instituicoes/getByCNPJ` as const }  
  return res
}

/**
 * @summary Obtém um Instituição de Ensino através do seu CNPJ
 * {@link /instituicoes/getByCNPJ}
 */
export async function getInstituicaoByCnpj(data: GetInstituicaoByCnpjQueryRequest, config: Partial<RequestConfig<GetInstituicaoByCnpjQueryRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<GetInstituicaoByCnpjQueryResponse, ResponseErrorConfig<GetInstituicaoByCnpj404>, GetInstituicaoByCnpjQueryRequest>({ method : "GET", url : getGetInstituicaoByCnpjUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}