/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetInstituicoesQueryResponse } from "../models/GetInstituicoes.ts";

function getGetInstituicoesUrl() {
  const res = { method: 'GET', url: `http://localhost:8080/instituicoes` as const }  
  return res
}

/**
 * @summary Obtém uma lista com as instituições de ensino cadastradas no sistema
 * {@link /instituicoes}
 */
export async function getInstituicoes(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetInstituicoesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetInstituicoesUrl().url.toString(), ... requestConfig })  
  return res.data
}