/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetInstituicaoByIdQueryResponse, GetInstituicaoByIdPathParams, GetInstituicaoById404 } from "../models/GetInstituicaoById.ts";

function getGetInstituicaoByIdUrl(id: GetInstituicaoByIdPathParams["id"]) {
  const res = { method: 'GET', url: `http://localhost:8080/instituicoes/${id}` as const }  
  return res
}

/**
 * @summary Obtém um Instituição de Ensino através do seu ID
 * {@link /instituicoes/:id}
 */
export async function getInstituicaoById(id: GetInstituicaoByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetInstituicaoByIdQueryResponse, ResponseErrorConfig<GetInstituicaoById404>, unknown>({ method : "GET", url : getGetInstituicaoByIdUrl(id).url.toString(), ... requestConfig })  
  return res.data
}