/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetInstituicaoByEmailQueryRequest, GetInstituicaoByEmailQueryResponse } from "../models/GetInstituicaoByEmail.ts";

function getGetInstituicaoByEmailUrl() {
  const res = { method: 'GET', url: `http://localhost:8080/instituicoes/getByEmail` as const }  
  return res
}

/**
 * {@link /instituicoes/getByEmail}
 */
export async function getInstituicaoByEmail(data: GetInstituicaoByEmailQueryRequest, config: Partial<RequestConfig<GetInstituicaoByEmailQueryRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<GetInstituicaoByEmailQueryResponse, ResponseErrorConfig<Error>, GetInstituicaoByEmailQueryRequest>({ method : "GET", url : getGetInstituicaoByEmailUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}