/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetPublicacoesQueryResponse, GetPublicacoesQueryParams, GetPublicacoes404 } from "../models/GetPublicacoes.ts";

function getGetPublicacoesUrl() {
  const res = { method: 'GET', url: `http://localhost:8080/publicacoes/disciplina` as const }  
  return res
}

/**
 * @summary Busca as Publicações em uma Disciplina
 * {@link /publicacoes/disciplina}
 */
export async function getPublicacoes(params: GetPublicacoesQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetPublicacoesQueryResponse, ResponseErrorConfig<GetPublicacoes404>, unknown>({ method : "GET", url : getGetPublicacoesUrl().url.toString(), params, ... requestConfig })  
  return res.data
}