/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetPerfilByIdQueryResponse, GetPerfilByIdPathParams, GetPerfilById404 } from "../models/GetPerfilById.ts";

function getGetPerfilByIdUrl(id: GetPerfilByIdPathParams["id"]) {
  const res = { method: 'GET', url: `http://localhost:8080/acessibilidade/${id}` as const }  
  return res
}

/**
 * @summary Busca um Perfil de Acessibilidade de acordo com seu ID
 * {@link /acessibilidade/:id}
 */
export async function getPerfilById(id: GetPerfilByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetPerfilByIdQueryResponse, ResponseErrorConfig<GetPerfilById404>, unknown>({ method : "GET", url : getGetPerfilByIdUrl(id).url.toString(), ... requestConfig })  
  return res.data
}