/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetPerfilByEstudanteIdQueryResponse, GetPerfilByEstudanteIdPathParams, GetPerfilByEstudanteId404 } from "../models/GetPerfilByEstudanteId.ts";

function getGetPerfilByEstudanteIdUrl(id: GetPerfilByEstudanteIdPathParams["id"]) {
  const res = { method: 'GET', url: `http://localhost:8080/acessibilidade/estudante/${id}` as const }  
  return res
}

/**
 * @summary Busca um Perfil de Acessibilidade de acordo com seu Estudante
 * {@link /acessibilidade/estudante/:id}
 */
export async function getPerfilByEstudanteId(id: GetPerfilByEstudanteIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetPerfilByEstudanteIdQueryResponse, ResponseErrorConfig<GetPerfilByEstudanteId404>, unknown>({ method : "GET", url : getGetPerfilByEstudanteIdUrl(id).url.toString(), ... requestConfig })  
  return res.data
}