/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetPublicacaoQueryResponse, GetPublicacaoPathParams, GetPublicacao404 } from "../models/GetPublicacao.ts";

function getGetPublicacaoUrl(publicacaoId: GetPublicacaoPathParams["publicacaoId"]) {
  const res = { method: 'GET', url: `http://localhost:8080/publicacoes/${publicacaoId}` as const }  
  return res
}

/**
 * @description Obtém uma Publicação através de seu ID
 * {@link /publicacoes/:publicacaoId}
 */
export async function getPublicacao(publicacaoId: GetPublicacaoPathParams["publicacaoId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetPublicacaoQueryResponse, ResponseErrorConfig<GetPublicacao404>, unknown>({ method : "GET", url : getGetPublicacaoUrl(publicacaoId).url.toString(), ... requestConfig })  
  return res.data
}