/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetTarefasByDisciplinaQueryResponse, GetTarefasByDisciplinaPathParams } from "../models/GetTarefasByDisciplina.ts";

function getGetTarefasByDisciplinaUrl(disciplinaId: GetTarefasByDisciplinaPathParams["disciplinaId"]) {
  const res = { method: 'GET', url: `http://localhost:8080/tarefas/disciplina/${disciplinaId}` as const }  
  return res
}

/**
 * @summary Lista todas as tarefas de uma disciplina
 * {@link /tarefas/disciplina/:disciplinaId}
 */
export async function getTarefasByDisciplina(disciplinaId: GetTarefasByDisciplinaPathParams["disciplinaId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetTarefasByDisciplinaQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetTarefasByDisciplinaUrl(disciplinaId).url.toString(), ... requestConfig })  
  return res.data
}