/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetUsuariosFromInstituicaoQueryResponse, GetUsuariosFromInstituicaoPathParams, GetUsuariosFromInstituicao404 } from "../models/GetUsuariosFromInstituicao.ts";

function getGetUsuariosFromInstituicaoUrl(instituicaoId: GetUsuariosFromInstituicaoPathParams["instituicaoId"]) {
  const res = { method: 'GET', url: `http://localhost:8080/instituicoes/${instituicaoId}/usuarios` as const }  
  return res
}

/**
 * @summary Lista os usuários membros de uma determinada Instituição de Ensino
 * {@link /instituicoes/:instituicaoId/usuarios}
 */
export async function getUsuariosFromInstituicao(instituicaoId: GetUsuariosFromInstituicaoPathParams["instituicaoId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetUsuariosFromInstituicaoQueryResponse, ResponseErrorConfig<GetUsuariosFromInstituicao404>, unknown>({ method : "GET", url : getGetUsuariosFromInstituicaoUrl(instituicaoId).url.toString(), ... requestConfig })  
  return res.data
}