/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetUsuarioByIdQueryResponse, GetUsuarioByIdPathParams, GetUsuarioById404 } from "../models/GetUsuarioById.ts";

function getGetUsuarioByIdUrl(id: GetUsuarioByIdPathParams["id"]) {
  const res = { method: 'GET', url: `http://localhost:8080/usuarios/${id}` as const }  
  return res
}

/**
 * @summary Busca um usuário com base no seu ID
 * {@link /usuarios/:id}
 */
export async function getUsuarioById(id: GetUsuarioByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetUsuarioByIdQueryResponse, ResponseErrorConfig<GetUsuarioById404>, unknown>({ method : "GET", url : getGetUsuarioByIdUrl(id).url.toString(), ... requestConfig })  
  return res.data
}