/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { ListarFormacoesQueryResponse, ListarFormacoesPathParams } from "../models/ListarFormacoes.ts";

function getListarFormacoesUrl(id: ListarFormacoesPathParams["id"]) {
  const res = { method: 'GET', url: `http://localhost:8080/educadores/${id}/formacoes` as const }  
  return res
}

/**
 * {@link /educadores/:id/formacoes}
 */
export async function listarFormacoes(id: ListarFormacoesPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ListarFormacoesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getListarFormacoesUrl(id).url.toString(), ... requestConfig })  
  return res.data
}