/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { ListarQueryResponse, ListarQueryParams, Listar404 } from "../models/Listar.ts";

function getListarUrl() {
  const res = { method: 'GET', url: `http://localhost:8080/estudantes` as const }  
  return res
}

/**
 * @summary Lista Estudantes com filtros opcionais
 * {@link /estudantes}
 */
export async function listar(params?: ListarQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ListarQueryResponse, ResponseErrorConfig<Listar404>, unknown>({ method : "GET", url : getListarUrl().url.toString(), params, ... requestConfig })  
  return res.data
}