/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { ListarArquivosQueryResponse, ListarArquivosPathParams } from "../models/ListarArquivos.ts";

function getListarArquivosUrl(disciplinaId: ListarArquivosPathParams["disciplinaId"]) {
  const res = { method: 'GET', url: `http://localhost:8080/arquivos/disciplina/${disciplinaId}` as const }  
  return res
}

/**
 * @summary Lista todos os arquivos de uma disciplina
 * {@link /arquivos/disciplina/:disciplinaId}
 */
export async function listarArquivos(disciplinaId: ListarArquivosPathParams["disciplinaId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ListarArquivosQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getListarArquivosUrl(disciplinaId).url.toString(), ... requestConfig })  
  return res.data
}