/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { RegisterMutationRequest, RegisterMutationResponse, Register400 } from "../models/Register.ts";

function getRegisterUrl() {
  const res = { method: 'POST', url: `http://localhost:8080/auth/register` as const }  
  return res
}

/**
 * @summary Realiza o registro de usuários
 * {@link /auth/register}
 */
export async function register(data: RegisterMutationRequest, config: Partial<RequestConfig<RegisterMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<RegisterMutationResponse, ResponseErrorConfig<Register400>, RegisterMutationRequest>({ method : "POST", url : getRegisterUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}