/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { RemoverMutationResponse, RemoverPathParams, Remover404 } from "../models/Remover.ts";

function getRemoverUrl(id: RemoverPathParams["id"]) {
  const res = { method: 'DELETE', url: `http://localhost:8080/estudantes/${id}` as const }  
  return res
}

/**
 * @summary Remove um Estudante do sistema
 * {@link /estudantes/:id}
 */
export async function remover(id: RemoverPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<RemoverMutationResponse, ResponseErrorConfig<Remover404>, unknown>({ method : "DELETE", url : getRemoverUrl(id).url.toString(), ... requestConfig })  
  return res.data
}