/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { RemoverFormacaoMutationResponse, RemoverFormacaoPathParams } from "../models/RemoverFormacao.ts";

function getRemoverFormacaoUrl(id: RemoverFormacaoPathParams["id"], formacaoId: RemoverFormacaoPathParams["formacaoId"]) {
  const res = { method: 'DELETE', url: `http://localhost:8080/educadores/${id}/formacoes/${formacaoId}` as const }  
  return res
}

/**
 * @summary Remover formação do educador
 * {@link /educadores/:id/formacoes/:formacaoId}
 */
export async function removerFormacao(id: RemoverFormacaoPathParams["id"], formacaoId: RemoverFormacaoPathParams["formacaoId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<RemoverFormacaoMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getRemoverFormacaoUrl(id, formacaoId).url.toString(), ... requestConfig })  
  return res.data
}