/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { RemoveEstudanteToDisciplinaMutationResponse, RemoveEstudanteToDisciplinaPathParams, RemoveEstudanteToDisciplinaQueryParams, RemoveEstudanteToDisciplina404 } from "../models/RemoveEstudanteToDisciplina.ts";

function getRemoveEstudanteToDisciplinaUrl(id: RemoveEstudanteToDisciplinaPathParams["id"]) {
  const res = { method: 'DELETE', url: `http://localhost:8080/disciplinas/${id}/estudantes` as const }  
  return res
}

/**
 * @summary Adiciona um Estudante a uma Disciplina
 * {@link /disciplinas/:id/estudantes}
 */
export async function removeEstudanteToDisciplina(id: RemoveEstudanteToDisciplinaPathParams["id"], params: RemoveEstudanteToDisciplinaQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<RemoveEstudanteToDisciplinaMutationResponse, ResponseErrorConfig<RemoveEstudanteToDisciplina404>, unknown>({ method : "DELETE", url : getRemoveEstudanteToDisciplinaUrl(id).url.toString(), params, ... requestConfig })  
  return res.data
}