/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { RemoveTarefaMutationResponse, RemoveTarefaPathParams } from "../models/RemoveTarefa.ts";

function getRemoveTarefaUrl(id: RemoveTarefaPathParams["id"]) {
  const res = { method: 'DELETE', url: `http://localhost:8080/tarefas/${id}` as const }  
  return res
}

/**
 * @summary Remove uma tarefa existente
 * {@link /tarefas/:id}
 */
export async function removeTarefa(id: RemoveTarefaPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<RemoveTarefaMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getRemoveTarefaUrl(id).url.toString(), ... requestConfig })  
  return res.data
}