/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { RemoverComentarioMutationResponse, RemoverComentarioPathParams, RemoverComentario404 } from "../models/RemoverComentario.ts";

function getRemoverComentarioUrl(id: RemoverComentarioPathParams["id"]) {
  const res = { method: 'DELETE', url: `http://localhost:8080/comentarios/${id}` as const }  
  return res
}

/**
 * @summary Atualiza um comentário
 * {@link /comentarios/:id}
 */
export async function removerComentario(id: RemoverComentarioPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<RemoverComentarioMutationResponse, ResponseErrorConfig<RemoverComentario404>, unknown>({ method : "DELETE", url : getRemoverComentarioUrl(id).url.toString(), ... requestConfig })  
  return res.data
}