/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { RemoveUsuarioFromInstituicaoMutationResponse, RemoveUsuarioFromInstituicaoPathParams, RemoveUsuarioFromInstituicao404, RemoveUsuarioFromInstituicao409 } from "../models/RemoveUsuarioFromInstituicao.ts";

function getRemoveUsuarioFromInstituicaoUrl(instituicaoId: RemoveUsuarioFromInstituicaoPathParams["instituicaoId"], usuarioId: RemoveUsuarioFromInstituicaoPathParams["usuarioId"]) {
  const res = { method: 'DELETE', url: `http://localhost:8080/instituicoes/${instituicaoId}/usuarios/${usuarioId}` as const }  
  return res
}

/**
 * @summary Remove Usuário de uma Instituição de Ensino
 * {@link /instituicoes/:instituicaoId/usuarios/:usuarioId}
 */
export async function removeUsuarioFromInstituicao(instituicaoId: RemoveUsuarioFromInstituicaoPathParams["instituicaoId"], usuarioId: RemoveUsuarioFromInstituicaoPathParams["usuarioId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<RemoveUsuarioFromInstituicaoMutationResponse, ResponseErrorConfig<RemoveUsuarioFromInstituicao404 | RemoveUsuarioFromInstituicao409>, unknown>({ method : "DELETE", url : getRemoveUsuarioFromInstituicaoUrl(instituicaoId, usuarioId).url.toString(), ... requestConfig })  
  return res.data
}