/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { RemovePerfilAcessibilidadeMutationResponse, RemovePerfilAcessibilidadePathParams, RemovePerfilAcessibilidade404 } from "../models/RemovePerfilAcessibilidade.ts";

function getRemovePerfilAcessibilidadeUrl(id: RemovePerfilAcessibilidadePathParams["id"]) {
  const res = { method: 'DELETE', url: `http://localhost:8080/acessibilidade/${id}` as const }  
  return res
}

/**
 * @summary Remove um Perfil de Acessibilidade
 * {@link /acessibilidade/:id}
 */
export async function removePerfilAcessibilidade(id: RemovePerfilAcessibilidadePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<RemovePerfilAcessibilidadeMutationResponse, ResponseErrorConfig<RemovePerfilAcessibilidade404>, unknown>({ method : "DELETE", url : getRemovePerfilAcessibilidadeUrl(id).url.toString(), ... requestConfig })  
  return res.data
}