/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { ResponderComentarioMutationRequest, ResponderComentarioMutationResponse, ResponderComentarioQueryParams, ResponderComentario404, ResponderComentario409 } from "../models/ResponderComentario.ts";

function getResponderComentarioUrl() {
  const res = { method: 'POST', url: `http://localhost:8080/comentarios/responder/comentario` as const }  
  return res
}

/**
 * @summary Responde um comentário em uma Publicação
 * {@link /comentarios/responder/comentario}
 */
export async function responderComentario(data: ResponderComentarioMutationRequest, params: ResponderComentarioQueryParams, config: Partial<RequestConfig<ResponderComentarioMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ResponderComentarioMutationResponse, ResponseErrorConfig<ResponderComentario404 | ResponderComentario409>, ResponderComentarioMutationRequest>({ method : "POST", url : getResponderComentarioUrl().url.toString(), params, data : requestData, ... requestConfig })  
  return res.data
}