/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { ResponderPublicacaoMutationRequest, ResponderPublicacaoMutationResponse, ResponderPublicacaoQueryParams, ResponderPublicacao404, ResponderPublicacao409 } from "../models/ResponderPublicacao.ts";

function getResponderPublicacaoUrl() {
  const res = { method: 'POST', url: `http://localhost:8080/comentarios/responder/publicacao` as const }  
  return res
}

/**
 * @summary Adiciona um comentário a uma Publicação
 * {@link /comentarios/responder/publicacao}
 */
export async function responderPublicacao(data: ResponderPublicacaoMutationRequest, params: ResponderPublicacaoQueryParams, config: Partial<RequestConfig<ResponderPublicacaoMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ResponderPublicacaoMutationResponse, ResponseErrorConfig<ResponderPublicacao404 | ResponderPublicacao409>, ResponderPublicacaoMutationRequest>({ method : "POST", url : getResponderPublicacaoUrl().url.toString(), params, data : requestData, ... requestConfig })  
  return res.data
}