/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UpdateDisciplinaMutationRequest, UpdateDisciplinaMutationResponse, UpdateDisciplinaPathParams, UpdateDisciplina404, UpdateDisciplina409 } from "../models/UpdateDisciplina.ts";

function getUpdateDisciplinaUrl(id: UpdateDisciplinaPathParams["id"]) {
  const res = { method: 'PUT', url: `http://localhost:8080/disciplinas/${id}` as const }  
  return res
}

/**
 * @summary Atualiza as informações de uma Disciplina
 * {@link /disciplinas/:id}
 */
export async function updateDisciplina(id: UpdateDisciplinaPathParams["id"], data?: UpdateDisciplinaMutationRequest, config: Partial<RequestConfig<UpdateDisciplinaMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdateDisciplinaMutationResponse, ResponseErrorConfig<UpdateDisciplina404 | UpdateDisciplina409>, UpdateDisciplinaMutationRequest>({ method : "PUT", url : getUpdateDisciplinaUrl(id).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}