/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UpdatePasswordMutationRequest, UpdatePasswordMutationResponse, UpdatePassword400 } from "../models/UpdatePassword.ts";

function getUpdatePasswordUrl() {
  const res = { method: 'PUT', url: `http://localhost:8080/reset-password` as const }  
  return res
}

/**
 * @summary Recebe o token e senha nova do usuário para redefiní-la
 * {@link /reset-password}
 */
export async function updatePassword(data: UpdatePasswordMutationRequest, config: Partial<RequestConfig<UpdatePasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdatePasswordMutationResponse, ResponseErrorConfig<UpdatePassword400>, UpdatePasswordMutationRequest>({ method : "PUT", url : getUpdatePasswordUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}