/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UpdateTarefaMutationRequest, UpdateTarefaMutationResponse, UpdateTarefaPathParams } from "../models/UpdateTarefa.ts";

function getUpdateTarefaUrl(id: UpdateTarefaPathParams["id"]) {
  const res = { method: 'PUT', url: `http://localhost:8080/tarefas/${id}` as const }  
  return res
}

/**
 * @summary Atualiza uma tarefa existente
 * {@link /tarefas/:id}
 */
export async function updateTarefa(id: UpdateTarefaPathParams["id"], data?: UpdateTarefaMutationRequest, config: Partial<RequestConfig<UpdateTarefaMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdateTarefaMutationResponse, ResponseErrorConfig<Error>, UpdateTarefaMutationRequest>({ method : "PUT", url : getUpdateTarefaUrl(id).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}