/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UpdateGestorMutationRequest, UpdateGestorMutationResponse, UpdateGestorPathParams, UpdateGestor400, UpdateGestor404 } from "../models/UpdateGestor.ts";

function getUpdateGestorUrl(id: UpdateGestorPathParams["id"]) {
  const res = { method: 'PUT', url: `http://localhost:8080/gestor/${id}` as const }  
  return res
}

/**
 * @summary Atualiza as informações de um Gestor
 * {@link /gestor/:id}
 */
export async function updateGestor(id: UpdateGestorPathParams["id"], data?: UpdateGestorMutationRequest, config: Partial<RequestConfig<UpdateGestorMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdateGestorMutationResponse, ResponseErrorConfig<UpdateGestor400 | UpdateGestor404>, UpdateGestorMutationRequest>({ method : "PUT", url : getUpdateGestorUrl(id).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}