/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UpdatePerfilAcessibilidadeMutationRequest, UpdatePerfilAcessibilidadeMutationResponse, UpdatePerfilAcessibilidadePathParams, UpdatePerfilAcessibilidade400, UpdatePerfilAcessibilidade404 } from "../models/UpdatePerfilAcessibilidade.ts";

function getUpdatePerfilAcessibilidadeUrl(id: UpdatePerfilAcessibilidadePathParams["id"]) {
  const res = { method: 'PUT', url: `http://localhost:8080/acessibilidade/${id}` as const }  
  return res
}

/**
 * @summary Atualiza um Perfil de Acessibilidade
 * {@link /acessibilidade/:id}
 */
export async function updatePerfilAcessibilidade(id: UpdatePerfilAcessibilidadePathParams["id"], data?: UpdatePerfilAcessibilidadeMutationRequest, config: Partial<RequestConfig<UpdatePerfilAcessibilidadeMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdatePerfilAcessibilidadeMutationResponse, ResponseErrorConfig<UpdatePerfilAcessibilidade400 | UpdatePerfilAcessibilidade404>, UpdatePerfilAcessibilidadeMutationRequest>({ method : "PUT", url : getUpdatePerfilAcessibilidadeUrl(id).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}