/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UpdatePublicacaoMutationRequest, UpdatePublicacaoMutationResponse, UpdatePublicacaoPathParams, UpdatePublicacao404, UpdatePublicacao409 } from "../models/UpdatePublicacao.ts";

function getUpdatePublicacaoUrl(publicacaoId: UpdatePublicacaoPathParams["publicacaoId"]) {
  const res = { method: 'PUT', url: `http://localhost:8080/publicacoes/${publicacaoId}` as const }  
  return res
}

/**
 * @summary Atualiza as informações de uma Publicação
 * {@link /publicacoes/:publicacaoId}
 */
export async function updatePublicacao(publicacaoId: UpdatePublicacaoPathParams["publicacaoId"], data?: UpdatePublicacaoMutationRequest, config: Partial<RequestConfig<UpdatePublicacaoMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdatePublicacaoMutationResponse, ResponseErrorConfig<UpdatePublicacao404 | UpdatePublicacao409>, UpdatePublicacaoMutationRequest>({ method : "PUT", url : getUpdatePublicacaoUrl(publicacaoId).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}