/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { ValidateTokenMutationResponse, ValidateTokenQueryParams, ValidateToken400 } from "../models/ValidateToken.ts";

function getValidateTokenUrl() {
  const res = { method: 'POST', url: `http://localhost:8080/reset-password/validate` as const }  
  return res
}

/**
 * @summary Valida o token enviado através do email
 * {@link /reset-password/validate}
 */
export async function validateToken(params: ValidateTokenQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ValidateTokenMutationResponse, ResponseErrorConfig<ValidateToken400>, unknown>({ method : "POST", url : getValidateTokenUrl().url.toString(), params, ... requestConfig })  
  return res.data
}