/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { AtualizarMutationRequest, AtualizarMutationResponse, AtualizarPathParams, Atualizar400, Atualizar404 } from "../../models/Atualizar.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { atualizar } from "../../client/atualizar.ts";

export const atualizarMutationKey = () => [{ url: '/estudantes/:id' }] as const

export type AtualizarMutationKey = ReturnType<typeof atualizarMutationKey>

export function atualizarMutationOptions(config: Partial<RequestConfig<AtualizarMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = atualizarMutationKey()
  return mutationOptions<AtualizarMutationResponse, ResponseErrorConfig<Atualizar400 | Atualizar404>, {id: AtualizarPathParams["id"], data?: AtualizarMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return atualizar(id, data, config)
    },
  })
}

/**
 * @summary Atualiza as informações de um Estudante
 * {@link /estudantes/:id}
 */
export function useAtualizar<TContext>(options: 
{
  mutation?: UseMutationOptions<AtualizarMutationResponse, ResponseErrorConfig<Atualizar400 | Atualizar404>, {id: AtualizarPathParams["id"], data?: AtualizarMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AtualizarMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? atualizarMutationKey()

  const baseOptions = atualizarMutationOptions(config) as UseMutationOptions<AtualizarMutationResponse, ResponseErrorConfig<Atualizar400 | Atualizar404>, {id: AtualizarPathParams["id"], data?: AtualizarMutationRequest}, TContext>

  return useMutation<AtualizarMutationResponse, ResponseErrorConfig<Atualizar400 | Atualizar404>, {id: AtualizarPathParams["id"], data?: AtualizarMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<AtualizarMutationResponse, ResponseErrorConfig<Atualizar400 | Atualizar404>, {id: AtualizarPathParams["id"], data?: AtualizarMutationRequest}, TContext>
}