/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { BuscarPorIdQueryResponse, BuscarPorIdPathParams, BuscarPorId404 } from "../../models/BuscarPorId.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { buscarPorId } from "../../client/buscarPorId.ts";

export const buscarPorIdSuspenseQueryKey = (id: BuscarPorIdPathParams["id"]) => [{ url: '/estudantes/:id', params: {id:id} }] as const

export type BuscarPorIdSuspenseQueryKey = ReturnType<typeof buscarPorIdSuspenseQueryKey>

export function buscarPorIdSuspenseQueryOptions(id: BuscarPorIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = buscarPorIdSuspenseQueryKey(id)
  return queryOptions<BuscarPorIdQueryResponse, ResponseErrorConfig<BuscarPorId404>, BuscarPorIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return buscarPorId(id, config)
   },
  })
}

/**
 * @summary Obtém um Estudante de acordo com seu ID
 * {@link /estudantes/:id}
 */
export function useBuscarPorIdSuspense<TData = BuscarPorIdQueryResponse, TQueryKey extends QueryKey = BuscarPorIdSuspenseQueryKey>(id: BuscarPorIdPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<BuscarPorIdQueryResponse, ResponseErrorConfig<BuscarPorId404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? buscarPorIdSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...buscarPorIdSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<BuscarPorId404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}