/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { BuscarPorIdQueryResponse, BuscarPorIdPathParams, BuscarPorId404 } from "../../models/BuscarPorId.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { buscarPorId } from "../../client/buscarPorId.ts";

export const buscarPorIdQueryKey = (id: BuscarPorIdPathParams["id"]) => [{ url: '/estudantes/:id', params: {id:id} }] as const

export type BuscarPorIdQueryKey = ReturnType<typeof buscarPorIdQueryKey>

export function buscarPorIdQueryOptions(id: BuscarPorIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = buscarPorIdQueryKey(id)
  return queryOptions<BuscarPorIdQueryResponse, ResponseErrorConfig<BuscarPorId404>, BuscarPorIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return buscarPorId(id, config)
   },
  })
}

/**
 * @summary Obtém um Estudante de acordo com seu ID
 * {@link /estudantes/:id}
 */
export function useBuscarPorId<TData = BuscarPorIdQueryResponse, TQueryData = BuscarPorIdQueryResponse, TQueryKey extends QueryKey = BuscarPorIdQueryKey>(id: BuscarPorIdPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<BuscarPorIdQueryResponse, ResponseErrorConfig<BuscarPorId404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? buscarPorIdQueryKey(id)

  const query = useQuery({
   ...buscarPorIdQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<BuscarPorId404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}