/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { ListarQueryResponse, ListarQueryParams, Listar404 } from "../../models/Listar.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { listar } from "../../client/listar.ts";

export const listarQueryKey = (params?: ListarQueryParams) => [{ url: '/estudantes' }, ...(params ? [params] : [])] as const

export type ListarQueryKey = ReturnType<typeof listarQueryKey>

export function listarQueryOptions(params?: ListarQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = listarQueryKey(params)
  return queryOptions<ListarQueryResponse, ResponseErrorConfig<Listar404>, ListarQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return listar(params, config)
   },
  })
}

/**
 * @summary Lista Estudantes com filtros opcionais
 * {@link /estudantes}
 */
export function useListar<TData = ListarQueryResponse, TQueryData = ListarQueryResponse, TQueryKey extends QueryKey = ListarQueryKey>(params?: ListarQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ListarQueryResponse, ResponseErrorConfig<Listar404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? listarQueryKey(params)

  const query = useQuery({
   ...listarQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Listar404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}