/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { ListarQueryResponse, ListarQueryParams, Listar404 } from "../../models/Listar.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { listar } from "../../client/listar.ts";

export const listarSuspenseQueryKey = (params?: ListarQueryParams) => [{ url: '/estudantes' }, ...(params ? [params] : [])] as const

export type ListarSuspenseQueryKey = ReturnType<typeof listarSuspenseQueryKey>

export function listarSuspenseQueryOptions(params?: ListarQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = listarSuspenseQueryKey(params)
  return queryOptions<ListarQueryResponse, ResponseErrorConfig<Listar404>, ListarQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return listar(params, config)
   },
  })
}

/**
 * @summary Lista Estudantes com filtros opcionais
 * {@link /estudantes}
 */
export function useListarSuspense<TData = ListarQueryResponse, TQueryKey extends QueryKey = ListarSuspenseQueryKey>(params?: ListarQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ListarQueryResponse, ResponseErrorConfig<Listar404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? listarSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...listarSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Listar404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}