/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { RemoverMutationResponse, RemoverPathParams, Remover404 } from "../../models/Remover.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { remover } from "../../client/remover.ts";

export const removerMutationKey = () => [{ url: '/estudantes/:id' }] as const

export type RemoverMutationKey = ReturnType<typeof removerMutationKey>

export function removerMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = removerMutationKey()
  return mutationOptions<RemoverMutationResponse, ResponseErrorConfig<Remover404>, {id: RemoverPathParams["id"]}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id }) => {
      return remover(id, config)
    },
  })
}

/**
 * @summary Remove um Estudante do sistema
 * {@link /estudantes/:id}
 */
export function useRemover<TContext>(options: 
{
  mutation?: UseMutationOptions<RemoverMutationResponse, ResponseErrorConfig<Remover404>, {id: RemoverPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? removerMutationKey()

  const baseOptions = removerMutationOptions(config) as UseMutationOptions<RemoverMutationResponse, ResponseErrorConfig<Remover404>, {id: RemoverPathParams["id"]}, TContext>

  return useMutation<RemoverMutationResponse, ResponseErrorConfig<Remover404>, {id: RemoverPathParams["id"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<RemoverMutationResponse, ResponseErrorConfig<Remover404>, {id: RemoverPathParams["id"]}, TContext>
}