/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetGestorByEmailQueryRequest, GetGestorByEmailQueryResponse, GetGestorByEmail400, GetGestorByEmail404 } from "../../models/GetGestorByEmail.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getGestorByEmail } from "../../client/getGestorByEmail.ts";

export const getGestorByEmailQueryKey = (data: GetGestorByEmailQueryRequest) => [{ url: '/gestor' }, ...(data ? [data] : [])] as const

export type GetGestorByEmailQueryKey = ReturnType<typeof getGestorByEmailQueryKey>

export function getGestorByEmailQueryOptions(data: GetGestorByEmailQueryRequest, config: Partial<RequestConfig<GetGestorByEmailQueryRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = getGestorByEmailQueryKey(data)
  return queryOptions<GetGestorByEmailQueryResponse, ResponseErrorConfig<GetGestorByEmail400 | GetGestorByEmail404>, GetGestorByEmailQueryResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getGestorByEmail(data, config)
   },
  })
}

/**
 * @summary Obtém um Gestor de acordo com seu e-mail
 * {@link /gestor}
 */
export function useGetGestorByEmail<TData = GetGestorByEmailQueryResponse, TQueryData = GetGestorByEmailQueryResponse, TQueryKey extends QueryKey = GetGestorByEmailQueryKey>(data: GetGestorByEmailQueryRequest, options: 
{
  query?: Partial<QueryObserverOptions<GetGestorByEmailQueryResponse, ResponseErrorConfig<GetGestorByEmail400 | GetGestorByEmail404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<GetGestorByEmailQueryRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getGestorByEmailQueryKey(data)

  const query = useQuery({
   ...getGestorByEmailQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetGestorByEmail400 | GetGestorByEmail404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}