/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetGestorByIdQueryResponse, GetGestorByIdPathParams, GetGestorById400, GetGestorById404 } from "../../models/GetGestorById.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getGestorById } from "../../client/getGestorById.ts";

export const getGestorByIdSuspenseQueryKey = (id: GetGestorByIdPathParams["id"]) => [{ url: '/gestor/:id', params: {id:id} }] as const

export type GetGestorByIdSuspenseQueryKey = ReturnType<typeof getGestorByIdSuspenseQueryKey>

export function getGestorByIdSuspenseQueryOptions(id: GetGestorByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getGestorByIdSuspenseQueryKey(id)
  return queryOptions<GetGestorByIdQueryResponse, ResponseErrorConfig<GetGestorById400 | GetGestorById404>, GetGestorByIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getGestorById(id, config)
   },
  })
}

/**
 * @summary Obtém um Gestor de acordo com seu ID
 * {@link /gestor/:id}
 */
export function useGetGestorByIdSuspense<TData = GetGestorByIdQueryResponse, TQueryKey extends QueryKey = GetGestorByIdSuspenseQueryKey>(id: GetGestorByIdPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetGestorByIdQueryResponse, ResponseErrorConfig<GetGestorById400 | GetGestorById404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getGestorByIdSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...getGestorByIdSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetGestorById400 | GetGestorById404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}