/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetGestorByEmailQueryRequest, GetGestorByEmailQueryResponse, GetGestorByEmail400, GetGestorByEmail404 } from "../../models/GetGestorByEmail.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getGestorByEmail } from "../../client/getGestorByEmail.ts";

export const getGestorByEmailSuspenseQueryKey = (data: GetGestorByEmailQueryRequest) => [{ url: '/gestor' }, ...(data ? [data] : [])] as const

export type GetGestorByEmailSuspenseQueryKey = ReturnType<typeof getGestorByEmailSuspenseQueryKey>

export function getGestorByEmailSuspenseQueryOptions(data: GetGestorByEmailQueryRequest, config: Partial<RequestConfig<GetGestorByEmailQueryRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = getGestorByEmailSuspenseQueryKey(data)
  return queryOptions<GetGestorByEmailQueryResponse, ResponseErrorConfig<GetGestorByEmail400 | GetGestorByEmail404>, GetGestorByEmailQueryResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getGestorByEmail(data, config)
   },
  })
}

/**
 * @summary Obtém um Gestor de acordo com seu e-mail
 * {@link /gestor}
 */
export function useGetGestorByEmailSuspense<TData = GetGestorByEmailQueryResponse, TQueryKey extends QueryKey = GetGestorByEmailSuspenseQueryKey>(data: GetGestorByEmailQueryRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetGestorByEmailQueryResponse, ResponseErrorConfig<GetGestorByEmail400 | GetGestorByEmail404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<GetGestorByEmailQueryRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getGestorByEmailSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...getGestorByEmailSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetGestorByEmail400 | GetGestorByEmail404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}