/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { UpdateGestorMutationRequest, UpdateGestorMutationResponse, UpdateGestorPathParams, UpdateGestor400, UpdateGestor404 } from "../../models/UpdateGestor.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { updateGestor } from "../../client/updateGestor.ts";

export const updateGestorMutationKey = () => [{ url: '/gestor/:id' }] as const

export type UpdateGestorMutationKey = ReturnType<typeof updateGestorMutationKey>

export function updateGestorMutationOptions(config: Partial<RequestConfig<UpdateGestorMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = updateGestorMutationKey()
  return mutationOptions<UpdateGestorMutationResponse, ResponseErrorConfig<UpdateGestor400 | UpdateGestor404>, {id: UpdateGestorPathParams["id"], data?: UpdateGestorMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return updateGestor(id, data, config)
    },
  })
}

/**
 * @summary Atualiza as informações de um Gestor
 * {@link /gestor/:id}
 */
export function useUpdateGestor<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateGestorMutationResponse, ResponseErrorConfig<UpdateGestor400 | UpdateGestor404>, {id: UpdateGestorPathParams["id"], data?: UpdateGestorMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateGestorMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updateGestorMutationKey()

  const baseOptions = updateGestorMutationOptions(config) as UseMutationOptions<UpdateGestorMutationResponse, ResponseErrorConfig<UpdateGestor400 | UpdateGestor404>, {id: UpdateGestorPathParams["id"], data?: UpdateGestorMutationRequest}, TContext>

  return useMutation<UpdateGestorMutationResponse, ResponseErrorConfig<UpdateGestor400 | UpdateGestor404>, {id: UpdateGestorPathParams["id"], data?: UpdateGestorMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<UpdateGestorMutationResponse, ResponseErrorConfig<UpdateGestor400 | UpdateGestor404>, {id: UpdateGestorPathParams["id"], data?: UpdateGestorMutationRequest}, TContext>
}