/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetUsuarioByIdQueryResponse, GetUsuarioByIdPathParams, GetUsuarioById404 } from "../../models/GetUsuarioById.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getUsuarioById } from "../../client/getUsuarioById.ts";

export const getUsuarioByIdQueryKey = (id: GetUsuarioByIdPathParams["id"]) => [{ url: '/usuarios/:id', params: {id:id} }] as const

export type GetUsuarioByIdQueryKey = ReturnType<typeof getUsuarioByIdQueryKey>

export function getUsuarioByIdQueryOptions(id: GetUsuarioByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getUsuarioByIdQueryKey(id)
  return queryOptions<GetUsuarioByIdQueryResponse, ResponseErrorConfig<GetUsuarioById404>, GetUsuarioByIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getUsuarioById(id, config)
   },
  })
}

/**
 * @summary Busca um usuário com base no seu ID
 * {@link /usuarios/:id}
 */
export function useGetUsuarioById<TData = GetUsuarioByIdQueryResponse, TQueryData = GetUsuarioByIdQueryResponse, TQueryKey extends QueryKey = GetUsuarioByIdQueryKey>(id: GetUsuarioByIdPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<GetUsuarioByIdQueryResponse, ResponseErrorConfig<GetUsuarioById404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getUsuarioByIdQueryKey(id)

  const query = useQuery({
   ...getUsuarioByIdQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetUsuarioById404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}