/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetAllUsuariosQueryResponse } from "../../models/GetAllUsuarios.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getAllUsuarios } from "../../client/getAllUsuarios.ts";

export const getAllUsuariosSuspenseQueryKey = () => [{ url: '/usuarios' }] as const

export type GetAllUsuariosSuspenseQueryKey = ReturnType<typeof getAllUsuariosSuspenseQueryKey>

export function getAllUsuariosSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getAllUsuariosSuspenseQueryKey()
  return queryOptions<GetAllUsuariosQueryResponse, ResponseErrorConfig<Error>, GetAllUsuariosQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getAllUsuarios(config)
   },
  })
}

/**
 * @summary Busca todos os usuários
 * {@link /usuarios}
 */
export function useGetAllUsuariosSuspense<TData = GetAllUsuariosQueryResponse, TQueryKey extends QueryKey = GetAllUsuariosSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetAllUsuariosQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getAllUsuariosSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getAllUsuariosSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}