/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetAllUsuariosQueryResponse } from "../../models/GetAllUsuarios.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getAllUsuarios } from "../../client/getAllUsuarios.ts";

export const getAllUsuariosQueryKey = () => [{ url: '/usuarios' }] as const

export type GetAllUsuariosQueryKey = ReturnType<typeof getAllUsuariosQueryKey>

export function getAllUsuariosQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getAllUsuariosQueryKey()
  return queryOptions<GetAllUsuariosQueryResponse, ResponseErrorConfig<Error>, GetAllUsuariosQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getAllUsuarios(config)
   },
  })
}

/**
 * @summary Busca todos os usuários
 * {@link /usuarios}
 */
export function useGetAllUsuarios<TData = GetAllUsuariosQueryResponse, TQueryData = GetAllUsuariosQueryResponse, TQueryKey extends QueryKey = GetAllUsuariosQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetAllUsuariosQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getAllUsuariosQueryKey()

  const query = useQuery({
   ...getAllUsuariosQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}