/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetUsuarioByIdQueryResponse, GetUsuarioByIdPathParams, GetUsuarioById404 } from "../../models/GetUsuarioById.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getUsuarioById } from "../../client/getUsuarioById.ts";

export const getUsuarioByIdSuspenseQueryKey = (id: GetUsuarioByIdPathParams["id"]) => [{ url: '/usuarios/:id', params: {id:id} }] as const

export type GetUsuarioByIdSuspenseQueryKey = ReturnType<typeof getUsuarioByIdSuspenseQueryKey>

export function getUsuarioByIdSuspenseQueryOptions(id: GetUsuarioByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getUsuarioByIdSuspenseQueryKey(id)
  return queryOptions<GetUsuarioByIdQueryResponse, ResponseErrorConfig<GetUsuarioById404>, GetUsuarioByIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getUsuarioById(id, config)
   },
  })
}

/**
 * @summary Busca um usuário com base no seu ID
 * {@link /usuarios/:id}
 */
export function useGetUsuarioByIdSuspense<TData = GetUsuarioByIdQueryResponse, TQueryKey extends QueryKey = GetUsuarioByIdSuspenseQueryKey>(id: GetUsuarioByIdPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetUsuarioByIdQueryResponse, ResponseErrorConfig<GetUsuarioById404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getUsuarioByIdSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...getUsuarioByIdSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetUsuarioById404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}