export type { AddEstudanteToDisciplinaPathParams, AddEstudanteToDisciplinaQueryParams, AddEstudanteToDisciplina200, AddEstudanteToDisciplina404, AddEstudanteToDisciplinaMutationResponse, AddEstudanteToDisciplinaMutation } from "./models/AddEstudanteToDisciplina.ts";
export type { AddUsuarioToInstituicaoPathParams, AddUsuarioToInstituicao200, AddUsuarioToInstituicao404, AddUsuarioToInstituicao409, AddUsuarioToInstituicaoMutationResponse, AddUsuarioToInstituicaoMutation } from "./models/AddUsuarioToInstituicao.ts";
export type { AdicionarFormacaoPathParams, AdicionarFormacao200, AdicionarFormacaoMutationRequest, AdicionarFormacaoMutationResponse, AdicionarFormacaoMutation } from "./models/AdicionarFormacao.ts";
export type { ArquivoDTO } from "./models/ArquivoDTO.ts";
export type { AtualizarPathParams, Atualizar200, Atualizar400, Atualizar404, AtualizarMutationRequest, AtualizarMutationResponse, AtualizarMutation } from "./models/Atualizar.ts";
export type { AtualizarComentarioPathParams, AtualizarComentario200, AtualizarComentario404, AtualizarComentarioMutationRequest, AtualizarComentarioMutationResponse, AtualizarComentarioMutation } from "./models/AtualizarComentario.ts";
export type { AuthenticationDTO } from "./models/AuthenticationDTO.ts";
export type { AvaliarRespostaPathParams, AvaliarResposta200, AvaliarRespostaMutationRequest, AvaliarRespostaMutationResponse, AvaliarRespostaMutation } from "./models/AvaliarResposta.ts";
export type { AvaliarRespostaDTO } from "./models/AvaliarRespostaDTO.ts";
export type { BuscarPorIdPathParams, BuscarPorId200, BuscarPorId404, BuscarPorIdQueryResponse, BuscarPorIdQuery } from "./models/BuscarPorId.ts";
export type { ComentarioSummaryDTO } from "./models/ComentarioSummaryDTO.ts";
export type { CreateComentarioDTO } from "./models/CreateComentarioDTO.ts";
export type { CreateDisciplina201, CreateDisciplina404, CreateDisciplina409, CreateDisciplinaMutationRequest, CreateDisciplinaMutationResponse, CreateDisciplinaMutation } from "./models/CreateDisciplina.ts";
export type { CreateDisciplinaDTO } from "./models/CreateDisciplinaDTO.ts";
export type { CreateInstituicao201, CreateInstituicao409, CreateInstituicao422, CreateInstituicaoMutationRequest, CreateInstituicaoMutationResponse, CreateInstituicaoMutation } from "./models/CreateInstituicao.ts";
export type { CreateInstituicaoDTO } from "./models/CreateInstituicaoDTO.ts";
export type { CreatePerfilAcessibilidadeQueryParams, CreatePerfilAcessibilidade201, CreatePerfilAcessibilidade400, CreatePerfilAcessibilidade404, CreatePerfilAcessibilidadeMutationRequest, CreatePerfilAcessibilidadeMutationResponse, CreatePerfilAcessibilidadeMutation } from "./models/CreatePerfilAcessibilidade.ts";
export type { CreatePerfilAcessibilidadeDTOTipoDeficienciaEnumKey, CreatePerfilAcessibilidadeDTO } from "./models/CreatePerfilAcessibilidadeDTO.ts";
export type { CreatePublicacao201, CreatePublicacao403, CreatePublicacao404, CreatePublicacao409, CreatePublicacaoMutationRequest, CreatePublicacaoMutationResponse, CreatePublicacaoMutation } from "./models/CreatePublicacao.ts";
export type { CreatePublicacaoDTO } from "./models/CreatePublicacaoDTO.ts";
export type { CreateRespostaDTO } from "./models/CreateRespostaDTO.ts";
export type { CreateRespostaMultipartDTO } from "./models/CreateRespostaMultipartDTO.ts";
export type { CreateTarefa200, CreateTarefaMutationRequest, CreateTarefaMutationResponse, CreateTarefaMutation } from "./models/CreateTarefa.ts";
export type { CreateTarefaDTO } from "./models/CreateTarefaDTO.ts";
export type { CriarRespostaComUpload200, CriarRespostaComUploadMutationRequest, CriarRespostaComUploadMutationResponse, CriarRespostaComUploadMutation } from "./models/CriarRespostaComUpload.ts";
export type { DeletarArquivoPathParams, DeletarArquivoQueryParams, DeletarArquivo200, DeletarArquivoMutationResponse, DeletarArquivoMutation } from "./models/DeletarArquivo.ts";
export type { DeletePublicacaoPathParams, DeletePublicacao204, DeletePublicacao404, DeletePublicacaoMutationResponse, DeletePublicacaoMutation } from "./models/DeletePublicacao.ts";
export type { DisciplinaSummaryDTO } from "./models/DisciplinaSummaryDTO.ts";
export type { DownloadArquivoPathParams, DownloadArquivo200, DownloadArquivoQueryResponse, DownloadArquivoQuery } from "./models/DownloadArquivo.ts";
export type { EducadorResponseDTO } from "./models/EducadorResponseDTO.ts";
export type { EducadorSummaryDTO } from "./models/EducadorSummaryDTO.ts";
export type { Endereco } from "./models/Endereco.ts";
export type { EnviarResposta200, EnviarRespostaMutationRequest, EnviarRespostaMutationResponse, EnviarRespostaMutation } from "./models/EnviarResposta.ts";
export type { EstudanteListDTOAnoEscolarEnumKey, EstudanteListDTOPeriodoEnumKey, EstudanteListDTO } from "./models/EstudanteListDTO.ts";
export type { EstudanteResponseDTOPeriodoEnumKey, EstudanteResponseDTOAnoEscolarEnumKey, EstudanteResponseDTOGeneroEnumKey, EstudanteResponseDTO } from "./models/EstudanteResponseDTO.ts";
export type { EstudanteSummaryDTOPeriodoEnumKey, EstudanteSummaryDTOAnoEscolarEnumKey, EstudanteSummaryDTOGeneroEnumKey, EstudanteSummaryDTO } from "./models/EstudanteSummaryDTO.ts";
export type { EstudanteUpdateDTOGeneroEnumKey, EstudanteUpdateDTO } from "./models/EstudanteUpdateDTO.ts";
export type { ForgotPassword200, ForgotPasswordMutationRequest, ForgotPasswordMutationResponse, ForgotPasswordMutation } from "./models/ForgotPassword.ts";
export type { FormacaoListResponseDTO } from "./models/FormacaoListResponseDTO.ts";
export type { FormacaoRequestDTO } from "./models/FormacaoRequestDTO.ts";
export type { FormacaoResponseDTO } from "./models/FormacaoResponseDTO.ts";
export type { GestorDetailsDTOGeneroEnumKey, GestorDetailsDTO } from "./models/GestorDetailsDTO.ts";
export type { GestorGetByEmailDTO } from "./models/GestorGetByEmailDTO.ts";
export type { GetAllUsuarios200, GetAllUsuarios204, GetAllUsuariosQueryResponse, GetAllUsuariosQuery } from "./models/GetAllUsuarios.ts";
export type { GetComentarioByIdPathParams, GetComentarioById200, GetComentarioById404, GetComentarioByIdQueryResponse, GetComentarioByIdQuery } from "./models/GetComentarioById.ts";
export type { GetDisciplinaByIdPathParams, GetDisciplinaById200, GetDisciplinaById404, GetDisciplinaByIdQueryResponse, GetDisciplinaByIdQuery } from "./models/GetDisciplinaById.ts";
export type { GetDisciplinasByEducadorQueryParams, GetDisciplinasByEducador200, GetDisciplinasByEducador204, GetDisciplinasByEducadorQueryResponse, GetDisciplinasByEducadorQuery } from "./models/GetDisciplinasByEducador.ts";
export type { GetDisciplinasByEstudanteQueryParams, GetDisciplinasByEstudante200, GetDisciplinasByEstudante204, GetDisciplinasByEstudante404, GetDisciplinasByEstudanteQueryResponse, GetDisciplinasByEstudanteQuery } from "./models/GetDisciplinasByEstudante.ts";
export type { GetDisciplinasByInstituicaoQueryParams, GetDisciplinasByInstituicao200, GetDisciplinasByInstituicao204, GetDisciplinasByInstituicao404, GetDisciplinasByInstituicaoQueryResponse, GetDisciplinasByInstituicaoQuery } from "./models/GetDisciplinasByInstituicao.ts";
export type { GetEducadorPathParams, GetEducador200, GetEducadorQueryResponse, GetEducadorQuery } from "./models/GetEducador.ts";
export type { GetEstudantesFromDisciplinaPathParams, GetEstudantesFromDisciplina200, GetEstudantesFromDisciplina204, GetEstudantesFromDisciplina404, GetEstudantesFromDisciplinaQueryResponse, GetEstudantesFromDisciplinaQuery } from "./models/GetEstudantesFromDisciplina.ts";
export type { GetGestorByEmail200, GetGestorByEmail400, GetGestorByEmail404, GetGestorByEmailQueryRequest, GetGestorByEmailQueryResponse, GetGestorByEmailQuery } from "./models/GetGestorByEmail.ts";
export type { GetGestorByIdPathParams, GetGestorById200, GetGestorById400, GetGestorById404, GetGestorByIdQueryResponse, GetGestorByIdQuery } from "./models/GetGestorById.ts";
export type { GetInstituicaoByCnpj200, GetInstituicaoByCnpj404, GetInstituicaoByCnpjQueryRequest, GetInstituicaoByCnpjQueryResponse, GetInstituicaoByCnpjQuery } from "./models/GetInstituicaoByCnpj.ts";
export type { GetInstituicaoByEmail200, GetInstituicaoByEmailQueryRequest, GetInstituicaoByEmailQueryResponse, GetInstituicaoByEmailQuery } from "./models/GetInstituicaoByEmail.ts";
export type { GetInstituicaoByIdPathParams, GetInstituicaoById200, GetInstituicaoById404, GetInstituicaoByIdQueryResponse, GetInstituicaoByIdQuery } from "./models/GetInstituicaoById.ts";
export type { GetInstituicoes200, GetInstituicoes204, GetInstituicoesQueryResponse, GetInstituicoesQuery } from "./models/GetInstituicoes.ts";
export type { GetPerfilByEstudanteIdPathParams, GetPerfilByEstudanteId200, GetPerfilByEstudanteId404, GetPerfilByEstudanteIdQueryResponse, GetPerfilByEstudanteIdQuery } from "./models/GetPerfilByEstudanteId.ts";
export type { GetPerfilByIdPathParams, GetPerfilById200, GetPerfilById404, GetPerfilByIdQueryResponse, GetPerfilByIdQuery } from "./models/GetPerfilById.ts";
export type { GetPublicacaoPathParams, GetPublicacao200, GetPublicacao404, GetPublicacaoQueryResponse, GetPublicacaoQuery } from "./models/GetPublicacao.ts";
export type { GetPublicacoesQueryParams, GetPublicacoes200, GetPublicacoes204, GetPublicacoes404, GetPublicacoesQueryResponse, GetPublicacoesQuery } from "./models/GetPublicacoes.ts";
export type { GetTarefaByIdPathParams, GetTarefaById200, GetTarefaByIdQueryResponse, GetTarefaByIdQuery } from "./models/GetTarefaById.ts";
export type { GetTarefasByDisciplinaPathParams, GetTarefasByDisciplina200, GetTarefasByDisciplinaQueryResponse, GetTarefasByDisciplinaQuery } from "./models/GetTarefasByDisciplina.ts";
export type { GetUsuarioByIdPathParams, GetUsuarioById200, GetUsuarioById404, GetUsuarioByIdQueryResponse, GetUsuarioByIdQuery } from "./models/GetUsuarioById.ts";
export type { GetUsuariosFromInstituicaoPathParams, GetUsuariosFromInstituicao200, GetUsuariosFromInstituicao204, GetUsuariosFromInstituicao404, GetUsuariosFromInstituicaoQueryResponse, GetUsuariosFromInstituicaoQuery } from "./models/GetUsuariosFromInstituicao.ts";
export type { InstituicaoCnpjDTO } from "./models/InstituicaoCnpjDTO.ts";
export type { InstituicaoDetailsDTO } from "./models/InstituicaoDetailsDTO.ts";
export type { InstituicaoEmailDTO } from "./models/InstituicaoEmailDTO.ts";
export type { ListarQueryParamsAnoEscolarEnumKey, ListarQueryParamsPeriodoEnumKey, ListarQueryParams, Listar200, Listar404, ListarQueryResponse, ListarQuery } from "./models/Listar.ts";
export type { ListarArquivosPathParams, ListarArquivos200, ListarArquivos204, ListarArquivosQueryResponse, ListarArquivosQuery } from "./models/ListarArquivos.ts";
export type { ListarFormacoesPathParams, ListarFormacoes200, ListarFormacoesQueryResponse, ListarFormacoesQuery } from "./models/ListarFormacoes.ts";
export type { Login200, Login400, LoginMutationRequest, LoginMutationResponse, LoginMutation } from "./models/Login.ts";
export type { ObterComentariosDaPublicacaoQueryParams, ObterComentariosDaPublicacao200, ObterComentariosDaPublicacao204, ObterComentariosDaPublicacao404, ObterComentariosDaPublicacaoQueryResponse, ObterComentariosDaPublicacaoQuery } from "./models/ObterComentariosDaPublicacao.ts";
export type { PasswordResetDTO } from "./models/PasswordResetDTO.ts";
export type { PublicacaoDetailsDTO } from "./models/PublicacaoDetailsDTO.ts";
export type { PublicacaoSummaryDTO } from "./models/PublicacaoSummaryDTO.ts";
export type { Register201, Register400, RegisterMutationRequest, RegisterMutationResponse, RegisterMutation } from "./models/Register.ts";
export type { RegisterDTOGeneroEnumKey, RegisterDTOUserTypeEnumKey, RegisterDTOPeriodoEnumKey, RegisterDTOAnoEscolarEnumKey, RegisterDTO } from "./models/RegisterDTO.ts";
export type { RemoveEstudanteToDisciplinaPathParams, RemoveEstudanteToDisciplinaQueryParams, RemoveEstudanteToDisciplina200, RemoveEstudanteToDisciplina404, RemoveEstudanteToDisciplinaMutationResponse, RemoveEstudanteToDisciplinaMutation } from "./models/RemoveEstudanteToDisciplina.ts";
export type { RemovePerfilAcessibilidadePathParams, RemovePerfilAcessibilidade204, RemovePerfilAcessibilidade404, RemovePerfilAcessibilidadeMutationResponse, RemovePerfilAcessibilidadeMutation } from "./models/RemovePerfilAcessibilidade.ts";
export type { RemoverPathParams, Remover204, Remover404, RemoverMutationResponse, RemoverMutation } from "./models/Remover.ts";
export type { RemoverComentarioPathParams, RemoverComentario204, RemoverComentario404, RemoverComentarioMutationResponse, RemoverComentarioMutation } from "./models/RemoverComentario.ts";
export type { RemoverFormacaoPathParams, RemoverFormacao204, RemoverFormacaoMutationResponse, RemoverFormacaoMutation } from "./models/RemoverFormacao.ts";
export type { RemoveTarefaPathParams, RemoveTarefa200, RemoveTarefaMutationResponse, RemoveTarefaMutation } from "./models/RemoveTarefa.ts";
export type { RemoveUsuarioFromInstituicaoPathParams, RemoveUsuarioFromInstituicao200, RemoveUsuarioFromInstituicao404, RemoveUsuarioFromInstituicao409, RemoveUsuarioFromInstituicaoMutationResponse, RemoveUsuarioFromInstituicaoMutation } from "./models/RemoveUsuarioFromInstituicao.ts";
export type { RequestResetDTO } from "./models/RequestResetDTO.ts";
export type { ResponderComentarioQueryParams, ResponderComentario200, ResponderComentario404, ResponderComentario409, ResponderComentarioMutationRequest, ResponderComentarioMutationResponse, ResponderComentarioMutation } from "./models/ResponderComentario.ts";
export type { ResponderPublicacaoQueryParams, ResponderPublicacao201, ResponderPublicacao404, ResponderPublicacao409, ResponderPublicacaoMutationRequest, ResponderPublicacaoMutationResponse, ResponderPublicacaoMutation } from "./models/ResponderPublicacao.ts";
export type { RespostaAComentarioSummaryDTO } from "./models/RespostaAComentarioSummaryDTO.ts";
export type { RespostaDTO } from "./models/RespostaDTO.ts";
export type { SummaryTarefaDTO } from "./models/SummaryTarefaDTO.ts";
export type { TarefaDetailsDTO } from "./models/TarefaDetailsDTO.ts";
export type { UpdateComentarioDTO } from "./models/UpdateComentarioDTO.ts";
export type { UpdateDisciplinaPathParams, UpdateDisciplina200, UpdateDisciplina404, UpdateDisciplina409, UpdateDisciplinaMutationRequest, UpdateDisciplinaMutationResponse, UpdateDisciplinaMutation } from "./models/UpdateDisciplina.ts";
export type { UpdateDisciplinaDTO } from "./models/UpdateDisciplinaDTO.ts";
export type { UpdateEducadorPathParams, UpdateEducador200, UpdateEducador404, UpdateEducador409, UpdateEducadorMutationRequest, UpdateEducadorMutationResponse, UpdateEducadorMutation } from "./models/UpdateEducador.ts";
export type { UpdateEducadorDTOGeneroEnumKey, UpdateEducadorDTO } from "./models/UpdateEducadorDTO.ts";
export type { UpdateGestorPathParams, UpdateGestor200, UpdateGestor400, UpdateGestor404, UpdateGestorMutationRequest, UpdateGestorMutationResponse, UpdateGestorMutation } from "./models/UpdateGestor.ts";
export type { UpdateGestorDTOGeneroEnumKey, UpdateGestorDTO } from "./models/UpdateGestorDTO.ts";
export type { UpdateInstituicaoPathParams, UpdateInstituicao200, UpdateInstituicao404, UpdateInstituicao422, UpdateInstituicaoMutationRequest, UpdateInstituicaoMutationResponse, UpdateInstituicaoMutation } from "./models/UpdateInstituicao.ts";
export type { UpdateInstituicaoDTO } from "./models/UpdateInstituicaoDTO.ts";
export type { UpdatePassword200, UpdatePassword400, UpdatePasswordMutationRequest, UpdatePasswordMutationResponse, UpdatePasswordMutation } from "./models/UpdatePassword.ts";
export type { UpdatePerfilAcessibilidadePathParams, UpdatePerfilAcessibilidade200, UpdatePerfilAcessibilidade400, UpdatePerfilAcessibilidade404, UpdatePerfilAcessibilidadeMutationRequest, UpdatePerfilAcessibilidadeMutationResponse, UpdatePerfilAcessibilidadeMutation } from "./models/UpdatePerfilAcessibilidade.ts";
export type { UpdatePerfilAcessibilidadeDTOTipoDeficienciaEnumKey, UpdatePerfilAcessibilidadeDTO } from "./models/UpdatePerfilAcessibilidadeDTO.ts";
export type { UpdatePublicacaoPathParams, UpdatePublicacao200, UpdatePublicacao404, UpdatePublicacao409, UpdatePublicacaoMutationRequest, UpdatePublicacaoMutationResponse, UpdatePublicacaoMutation } from "./models/UpdatePublicacao.ts";
export type { UpdatePublicacaoDTO } from "./models/UpdatePublicacaoDTO.ts";
export type { UpdateTarefaPathParams, UpdateTarefa200, UpdateTarefaMutationRequest, UpdateTarefaMutationResponse, UpdateTarefaMutation } from "./models/UpdateTarefa.ts";
export type { UpdateTarefaDTO } from "./models/UpdateTarefaDTO.ts";
export type { UploadArquivoPathParams, UploadArquivoQueryParams, UploadArquivo201, UploadArquivo400, UploadArquivo404, UploadArquivoMutationRequest, UploadArquivoMutationResponse, UploadArquivoMutation } from "./models/UploadArquivo.ts";
export type { UsuarioDetailsDTOGeneroEnumKey, UsuarioDetailsDTORolesEnumKey, UsuarioDetailsDTO } from "./models/UsuarioDetailsDTO.ts";
export type { UsuarioSummaryDTO } from "./models/UsuarioSummaryDTO.ts";
export type { ValidateTokenQueryParams, ValidateToken200, ValidateToken400, ValidateTokenMutationResponse, ValidateTokenMutation } from "./models/ValidateToken.ts";
export type { DeletarArquivoMutationKey } from "./react-query/arquivoControllerController/useDeletarArquivo.ts";
export type { DownloadArquivoQueryKey } from "./react-query/arquivoControllerController/useDownloadArquivo.ts";
export type { DownloadArquivoSuspenseQueryKey } from "./react-query/arquivoControllerController/useDownloadArquivoSuspense.ts";
export type { ListarArquivosQueryKey } from "./react-query/arquivoControllerController/useListarArquivos.ts";
export type { ListarArquivosSuspenseQueryKey } from "./react-query/arquivoControllerController/useListarArquivosSuspense.ts";
export type { UploadArquivoMutationKey } from "./react-query/arquivoControllerController/useUploadArquivo.ts";
export type { LoginMutationKey } from "./react-query/authenticationController/useLogin.ts";
export type { RegisterMutationKey } from "./react-query/authenticationController/useRegister.ts";
export type { GetAllUsuariosQueryKey } from "./react-query/buscaDeUsuriosController/useGetAllUsuarios.ts";
export type { GetAllUsuariosSuspenseQueryKey } from "./react-query/buscaDeUsuriosController/useGetAllUsuariosSuspense.ts";
export type { GetUsuarioByIdQueryKey } from "./react-query/buscaDeUsuriosController/useGetUsuarioById.ts";
export type { GetUsuarioByIdSuspenseQueryKey } from "./react-query/buscaDeUsuriosController/useGetUsuarioByIdSuspense.ts";
export type { AdicionarFormacaoMutationKey } from "./react-query/EducadoresController/useAdicionarFormacao.ts";
export type { GetEducadorQueryKey } from "./react-query/EducadoresController/useGetEducador.ts";
export type { GetEducadorSuspenseQueryKey } from "./react-query/EducadoresController/useGetEducadorSuspense.ts";
export type { ListarFormacoesQueryKey } from "./react-query/EducadoresController/useListarFormacoes.ts";
export type { ListarFormacoesSuspenseQueryKey } from "./react-query/EducadoresController/useListarFormacoesSuspense.ts";
export type { RemoverFormacaoMutationKey } from "./react-query/EducadoresController/useRemoverFormacao.ts";
export type { UpdateEducadorMutationKey } from "./react-query/EducadoresController/useUpdateEducador.ts";
export type { AtualizarComentarioMutationKey } from "./react-query/mduloComentriosController/useAtualizarComentario.ts";
export type { GetComentarioByIdQueryKey } from "./react-query/mduloComentriosController/useGetComentarioById.ts";
export type { GetComentarioByIdSuspenseQueryKey } from "./react-query/mduloComentriosController/useGetComentarioByIdSuspense.ts";
export type { ObterComentariosDaPublicacaoQueryKey } from "./react-query/mduloComentriosController/useObterComentariosDaPublicacao.ts";
export type { ObterComentariosDaPublicacaoSuspenseQueryKey } from "./react-query/mduloComentriosController/useObterComentariosDaPublicacaoSuspense.ts";
export type { RemoverComentarioMutationKey } from "./react-query/mduloComentriosController/useRemoverComentario.ts";
export type { ResponderComentarioMutationKey } from "./react-query/mduloComentriosController/useResponderComentario.ts";
export type { ResponderPublicacaoMutationKey } from "./react-query/mduloComentriosController/useResponderPublicacao.ts";
export type { AtualizarMutationKey } from "./react-query/mduloDeEstudantesController/useAtualizar.ts";
export type { BuscarPorIdQueryKey } from "./react-query/mduloDeEstudantesController/useBuscarPorId.ts";
export type { BuscarPorIdSuspenseQueryKey } from "./react-query/mduloDeEstudantesController/useBuscarPorIdSuspense.ts";
export type { ListarQueryKey } from "./react-query/mduloDeEstudantesController/useListar.ts";
export type { ListarSuspenseQueryKey } from "./react-query/mduloDeEstudantesController/useListarSuspense.ts";
export type { RemoverMutationKey } from "./react-query/mduloDeEstudantesController/useRemover.ts";
export type { GetGestorByEmailQueryKey } from "./react-query/mduloDeGestoresController/useGetGestorByEmail.ts";
export type { GetGestorByEmailSuspenseQueryKey } from "./react-query/mduloDeGestoresController/useGetGestorByEmailSuspense.ts";
export type { GetGestorByIdQueryKey } from "./react-query/mduloDeGestoresController/useGetGestorById.ts";
export type { GetGestorByIdSuspenseQueryKey } from "./react-query/mduloDeGestoresController/useGetGestorByIdSuspense.ts";
export type { UpdateGestorMutationKey } from "./react-query/mduloDeGestoresController/useUpdateGestor.ts";
export type { AddEstudanteToDisciplinaMutationKey } from "./react-query/mduloDisciplinasController/useAddEstudanteToDisciplina.ts";
export type { CreateDisciplinaMutationKey } from "./react-query/mduloDisciplinasController/useCreateDisciplina.ts";
export type { GetDisciplinaByIdQueryKey } from "./react-query/mduloDisciplinasController/useGetDisciplinaById.ts";
export type { GetDisciplinaByIdSuspenseQueryKey } from "./react-query/mduloDisciplinasController/useGetDisciplinaByIdSuspense.ts";
export type { GetDisciplinasByEducadorQueryKey } from "./react-query/mduloDisciplinasController/useGetDisciplinasByEducador.ts";
export type { GetDisciplinasByEducadorSuspenseQueryKey } from "./react-query/mduloDisciplinasController/useGetDisciplinasByEducadorSuspense.ts";
export type { GetDisciplinasByEstudanteQueryKey } from "./react-query/mduloDisciplinasController/useGetDisciplinasByEstudante.ts";
export type { GetDisciplinasByEstudanteSuspenseQueryKey } from "./react-query/mduloDisciplinasController/useGetDisciplinasByEstudanteSuspense.ts";
export type { GetDisciplinasByInstituicaoQueryKey } from "./react-query/mduloDisciplinasController/useGetDisciplinasByInstituicao.ts";
export type { GetDisciplinasByInstituicaoSuspenseQueryKey } from "./react-query/mduloDisciplinasController/useGetDisciplinasByInstituicaoSuspense.ts";
export type { GetEstudantesFromDisciplinaQueryKey } from "./react-query/mduloDisciplinasController/useGetEstudantesFromDisciplina.ts";
export type { GetEstudantesFromDisciplinaSuspenseQueryKey } from "./react-query/mduloDisciplinasController/useGetEstudantesFromDisciplinaSuspense.ts";
export type { RemoveEstudanteToDisciplinaMutationKey } from "./react-query/mduloDisciplinasController/useRemoveEstudanteToDisciplina.ts";
export type { UpdateDisciplinaMutationKey } from "./react-query/mduloDisciplinasController/useUpdateDisciplina.ts";
export type { AddUsuarioToInstituicaoMutationKey } from "./react-query/mduloInstituiesDeEnsinoController/useAddUsuarioToInstituicao.ts";
export type { CreateInstituicaoMutationKey } from "./react-query/mduloInstituiesDeEnsinoController/useCreateInstituicao.ts";
export type { GetInstituicaoByCnpjQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByCnpj.ts";
export type { GetInstituicaoByCnpjSuspenseQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByCnpjSuspense.ts";
export type { GetInstituicaoByEmailQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByEmail.ts";
export type { GetInstituicaoByEmailSuspenseQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByEmailSuspense.ts";
export type { GetInstituicaoByIdQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoById.ts";
export type { GetInstituicaoByIdSuspenseQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByIdSuspense.ts";
export type { GetInstituicoesQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicoes.ts";
export type { GetInstituicoesSuspenseQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicoesSuspense.ts";
export type { GetUsuariosFromInstituicaoQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetUsuariosFromInstituicao.ts";
export type { GetUsuariosFromInstituicaoSuspenseQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetUsuariosFromInstituicaoSuspense.ts";
export type { RemoveUsuarioFromInstituicaoMutationKey } from "./react-query/mduloInstituiesDeEnsinoController/useRemoveUsuarioFromInstituicao.ts";
export type { UpdateInstituicaoMutationKey } from "./react-query/mduloInstituiesDeEnsinoController/useUpdateInstituicao.ts";
export type { CreatePerfilAcessibilidadeMutationKey } from "./react-query/mduloPerfilDeAcessibilidadeController/useCreatePerfilAcessibilidade.ts";
export type { GetPerfilByEstudanteIdQueryKey } from "./react-query/mduloPerfilDeAcessibilidadeController/useGetPerfilByEstudanteId.ts";
export type { GetPerfilByEstudanteIdSuspenseQueryKey } from "./react-query/mduloPerfilDeAcessibilidadeController/useGetPerfilByEstudanteIdSuspense.ts";
export type { GetPerfilByIdQueryKey } from "./react-query/mduloPerfilDeAcessibilidadeController/useGetPerfilById.ts";
export type { GetPerfilByIdSuspenseQueryKey } from "./react-query/mduloPerfilDeAcessibilidadeController/useGetPerfilByIdSuspense.ts";
export type { RemovePerfilAcessibilidadeMutationKey } from "./react-query/mduloPerfilDeAcessibilidadeController/useRemovePerfilAcessibilidade.ts";
export type { UpdatePerfilAcessibilidadeMutationKey } from "./react-query/mduloPerfilDeAcessibilidadeController/useUpdatePerfilAcessibilidade.ts";
export type { CreatePublicacaoMutationKey } from "./react-query/mduloPublicaesController/useCreatePublicacao.ts";
export type { DeletePublicacaoMutationKey } from "./react-query/mduloPublicaesController/useDeletePublicacao.ts";
export type { GetPublicacaoQueryKey } from "./react-query/mduloPublicaesController/useGetPublicacao.ts";
export type { GetPublicacaoSuspenseQueryKey } from "./react-query/mduloPublicaesController/useGetPublicacaoSuspense.ts";
export type { GetPublicacoesQueryKey } from "./react-query/mduloPublicaesController/useGetPublicacoes.ts";
export type { GetPublicacoesSuspenseQueryKey } from "./react-query/mduloPublicaesController/useGetPublicacoesSuspense.ts";
export type { UpdatePublicacaoMutationKey } from "./react-query/mduloPublicaesController/useUpdatePublicacao.ts";
export type { CreateTarefaMutationKey } from "./react-query/mduloTarefasController/useCreateTarefa.ts";
export type { GetTarefaByIdQueryKey } from "./react-query/mduloTarefasController/useGetTarefaById.ts";
export type { GetTarefaByIdSuspenseQueryKey } from "./react-query/mduloTarefasController/useGetTarefaByIdSuspense.ts";
export type { GetTarefasByDisciplinaQueryKey } from "./react-query/mduloTarefasController/useGetTarefasByDisciplina.ts";
export type { GetTarefasByDisciplinaSuspenseQueryKey } from "./react-query/mduloTarefasController/useGetTarefasByDisciplinaSuspense.ts";
export type { RemoveTarefaMutationKey } from "./react-query/mduloTarefasController/useRemoveTarefa.ts";
export type { UpdateTarefaMutationKey } from "./react-query/mduloTarefasController/useUpdateTarefa.ts";
export type { ForgotPasswordMutationKey } from "./react-query/redefinioDeSenhaController/useForgotPassword.ts";
export type { UpdatePasswordMutationKey } from "./react-query/redefinioDeSenhaController/useUpdatePassword.ts";
export type { ValidateTokenMutationKey } from "./react-query/redefinioDeSenhaController/useValidateToken.ts";
export type { AvaliarRespostaMutationKey } from "./react-query/respostasController/useAvaliarResposta.ts";
export type { CriarRespostaComUploadMutationKey } from "./react-query/respostasController/useCriarRespostaComUpload.ts";
export type { EnviarRespostaMutationKey } from "./react-query/respostasController/useEnviarResposta.ts";
export { addEstudanteToDisciplina } from "./client/addEstudanteToDisciplina.ts";
export { addUsuarioToInstituicao } from "./client/addUsuarioToInstituicao.ts";
export { adicionarFormacao } from "./client/adicionarFormacao.ts";
export { atualizar } from "./client/atualizar.ts";
export { atualizarComentario } from "./client/atualizarComentario.ts";
export { avaliarResposta } from "./client/avaliarResposta.ts";
export { buscarPorId } from "./client/buscarPorId.ts";
export { createDisciplina } from "./client/createDisciplina.ts";
export { createInstituicao } from "./client/createInstituicao.ts";
export { createPerfilAcessibilidade } from "./client/createPerfilAcessibilidade.ts";
export { createPublicacao } from "./client/createPublicacao.ts";
export { createTarefa } from "./client/createTarefa.ts";
export { criarRespostaComUpload } from "./client/criarRespostaComUpload.ts";
export { deletarArquivo } from "./client/deletarArquivo.ts";
export { deletePublicacao } from "./client/deletePublicacao.ts";
export { downloadArquivo } from "./client/downloadArquivo.ts";
export { enviarResposta } from "./client/enviarResposta.ts";
export { forgotPassword } from "./client/forgotPassword.ts";
export { getAllUsuarios } from "./client/getAllUsuarios.ts";
export { getComentarioById } from "./client/getComentarioById.ts";
export { getDisciplinaById } from "./client/getDisciplinaById.ts";
export { getDisciplinasByEducador } from "./client/getDisciplinasByEducador.ts";
export { getDisciplinasByEstudante } from "./client/getDisciplinasByEstudante.ts";
export { getDisciplinasByInstituicao } from "./client/getDisciplinasByInstituicao.ts";
export { getEducador } from "./client/getEducador.ts";
export { getEstudantesFromDisciplina } from "./client/getEstudantesFromDisciplina.ts";
export { getGestorByEmail } from "./client/getGestorByEmail.ts";
export { getGestorById } from "./client/getGestorById.ts";
export { getInstituicaoByCnpj } from "./client/getInstituicaoByCnpj.ts";
export { getInstituicaoByEmail } from "./client/getInstituicaoByEmail.ts";
export { getInstituicaoById } from "./client/getInstituicaoById.ts";
export { getInstituicoes } from "./client/getInstituicoes.ts";
export { getPerfilByEstudanteId } from "./client/getPerfilByEstudanteId.ts";
export { getPerfilById } from "./client/getPerfilById.ts";
export { getPublicacao } from "./client/getPublicacao.ts";
export { getPublicacoes } from "./client/getPublicacoes.ts";
export { getTarefaById } from "./client/getTarefaById.ts";
export { getTarefasByDisciplina } from "./client/getTarefasByDisciplina.ts";
export { getUsuarioById } from "./client/getUsuarioById.ts";
export { getUsuariosFromInstituicao } from "./client/getUsuariosFromInstituicao.ts";
export { listar } from "./client/listar.ts";
export { listarArquivos } from "./client/listarArquivos.ts";
export { listarFormacoes } from "./client/listarFormacoes.ts";
export { login } from "./client/login.ts";
export { obterComentariosDaPublicacao } from "./client/obterComentariosDaPublicacao.ts";
export { register } from "./client/register.ts";
export { removeEstudanteToDisciplina } from "./client/removeEstudanteToDisciplina.ts";
export { removePerfilAcessibilidade } from "./client/removePerfilAcessibilidade.ts";
export { remover } from "./client/remover.ts";
export { removerComentario } from "./client/removerComentario.ts";
export { removerFormacao } from "./client/removerFormacao.ts";
export { removeTarefa } from "./client/removeTarefa.ts";
export { removeUsuarioFromInstituicao } from "./client/removeUsuarioFromInstituicao.ts";
export { responderComentario } from "./client/responderComentario.ts";
export { responderPublicacao } from "./client/responderPublicacao.ts";
export { updateDisciplina } from "./client/updateDisciplina.ts";
export { updateEducador } from "./client/updateEducador.ts";
export { updateGestor } from "./client/updateGestor.ts";
export { updateInstituicao } from "./client/updateInstituicao.ts";
export { updatePassword } from "./client/updatePassword.ts";
export { updatePerfilAcessibilidade } from "./client/updatePerfilAcessibilidade.ts";
export { updatePublicacao } from "./client/updatePublicacao.ts";
export { updateTarefa } from "./client/updateTarefa.ts";
export { uploadArquivo } from "./client/uploadArquivo.ts";
export { validateToken } from "./client/validateToken.ts";
export { createPerfilAcessibilidadeDTOTipoDeficienciaEnum } from "./models/CreatePerfilAcessibilidadeDTO.ts";
export { estudanteListDTOAnoEscolarEnum } from "./models/EstudanteListDTO.ts";
export { estudanteListDTOPeriodoEnum } from "./models/EstudanteListDTO.ts";
export { estudanteResponseDTOPeriodoEnum } from "./models/EstudanteResponseDTO.ts";
export { estudanteResponseDTOAnoEscolarEnum } from "./models/EstudanteResponseDTO.ts";
export { estudanteResponseDTOGeneroEnum } from "./models/EstudanteResponseDTO.ts";
export { estudanteSummaryDTOPeriodoEnum } from "./models/EstudanteSummaryDTO.ts";
export { estudanteSummaryDTOAnoEscolarEnum } from "./models/EstudanteSummaryDTO.ts";
export { estudanteSummaryDTOGeneroEnum } from "./models/EstudanteSummaryDTO.ts";
export { estudanteUpdateDTOGeneroEnum } from "./models/EstudanteUpdateDTO.ts";
export { gestorDetailsDTOGeneroEnum } from "./models/GestorDetailsDTO.ts";
export { listarQueryParamsAnoEscolarEnum } from "./models/Listar.ts";
export { listarQueryParamsPeriodoEnum } from "./models/Listar.ts";
export { registerDTOGeneroEnum } from "./models/RegisterDTO.ts";
export { registerDTOUserTypeEnum } from "./models/RegisterDTO.ts";
export { registerDTOPeriodoEnum } from "./models/RegisterDTO.ts";
export { registerDTOAnoEscolarEnum } from "./models/RegisterDTO.ts";
export { updateEducadorDTOGeneroEnum } from "./models/UpdateEducadorDTO.ts";
export { updateGestorDTOGeneroEnum } from "./models/UpdateGestorDTO.ts";
export { updatePerfilAcessibilidadeDTOTipoDeficienciaEnum } from "./models/UpdatePerfilAcessibilidadeDTO.ts";
export { usuarioDetailsDTOGeneroEnum } from "./models/UsuarioDetailsDTO.ts";
export { usuarioDetailsDTORolesEnum } from "./models/UsuarioDetailsDTO.ts";
export { deletarArquivoMutationKey } from "./react-query/arquivoControllerController/useDeletarArquivo.ts";
export { deletarArquivoMutationOptions } from "./react-query/arquivoControllerController/useDeletarArquivo.ts";
export { useDeletarArquivo } from "./react-query/arquivoControllerController/useDeletarArquivo.ts";
export { downloadArquivoQueryKey } from "./react-query/arquivoControllerController/useDownloadArquivo.ts";
export { downloadArquivoQueryOptions } from "./react-query/arquivoControllerController/useDownloadArquivo.ts";
export { useDownloadArquivo } from "./react-query/arquivoControllerController/useDownloadArquivo.ts";
export { downloadArquivoSuspenseQueryKey } from "./react-query/arquivoControllerController/useDownloadArquivoSuspense.ts";
export { downloadArquivoSuspenseQueryOptions } from "./react-query/arquivoControllerController/useDownloadArquivoSuspense.ts";
export { useDownloadArquivoSuspense } from "./react-query/arquivoControllerController/useDownloadArquivoSuspense.ts";
export { listarArquivosQueryKey } from "./react-query/arquivoControllerController/useListarArquivos.ts";
export { listarArquivosQueryOptions } from "./react-query/arquivoControllerController/useListarArquivos.ts";
export { useListarArquivos } from "./react-query/arquivoControllerController/useListarArquivos.ts";
export { listarArquivosSuspenseQueryKey } from "./react-query/arquivoControllerController/useListarArquivosSuspense.ts";
export { listarArquivosSuspenseQueryOptions } from "./react-query/arquivoControllerController/useListarArquivosSuspense.ts";
export { useListarArquivosSuspense } from "./react-query/arquivoControllerController/useListarArquivosSuspense.ts";
export { uploadArquivoMutationKey } from "./react-query/arquivoControllerController/useUploadArquivo.ts";
export { uploadArquivoMutationOptions } from "./react-query/arquivoControllerController/useUploadArquivo.ts";
export { useUploadArquivo } from "./react-query/arquivoControllerController/useUploadArquivo.ts";
export { loginMutationKey } from "./react-query/authenticationController/useLogin.ts";
export { loginMutationOptions } from "./react-query/authenticationController/useLogin.ts";
export { useLogin } from "./react-query/authenticationController/useLogin.ts";
export { registerMutationKey } from "./react-query/authenticationController/useRegister.ts";
export { registerMutationOptions } from "./react-query/authenticationController/useRegister.ts";
export { useRegister } from "./react-query/authenticationController/useRegister.ts";
export { getAllUsuariosQueryKey } from "./react-query/buscaDeUsuriosController/useGetAllUsuarios.ts";
export { getAllUsuariosQueryOptions } from "./react-query/buscaDeUsuriosController/useGetAllUsuarios.ts";
export { useGetAllUsuarios } from "./react-query/buscaDeUsuriosController/useGetAllUsuarios.ts";
export { getAllUsuariosSuspenseQueryKey } from "./react-query/buscaDeUsuriosController/useGetAllUsuariosSuspense.ts";
export { getAllUsuariosSuspenseQueryOptions } from "./react-query/buscaDeUsuriosController/useGetAllUsuariosSuspense.ts";
export { useGetAllUsuariosSuspense } from "./react-query/buscaDeUsuriosController/useGetAllUsuariosSuspense.ts";
export { getUsuarioByIdQueryKey } from "./react-query/buscaDeUsuriosController/useGetUsuarioById.ts";
export { getUsuarioByIdQueryOptions } from "./react-query/buscaDeUsuriosController/useGetUsuarioById.ts";
export { useGetUsuarioById } from "./react-query/buscaDeUsuriosController/useGetUsuarioById.ts";
export { getUsuarioByIdSuspenseQueryKey } from "./react-query/buscaDeUsuriosController/useGetUsuarioByIdSuspense.ts";
export { getUsuarioByIdSuspenseQueryOptions } from "./react-query/buscaDeUsuriosController/useGetUsuarioByIdSuspense.ts";
export { useGetUsuarioByIdSuspense } from "./react-query/buscaDeUsuriosController/useGetUsuarioByIdSuspense.ts";
export { adicionarFormacaoMutationKey } from "./react-query/EducadoresController/useAdicionarFormacao.ts";
export { adicionarFormacaoMutationOptions } from "./react-query/EducadoresController/useAdicionarFormacao.ts";
export { useAdicionarFormacao } from "./react-query/EducadoresController/useAdicionarFormacao.ts";
export { getEducadorQueryKey } from "./react-query/EducadoresController/useGetEducador.ts";
export { getEducadorQueryOptions } from "./react-query/EducadoresController/useGetEducador.ts";
export { useGetEducador } from "./react-query/EducadoresController/useGetEducador.ts";
export { getEducadorSuspenseQueryKey } from "./react-query/EducadoresController/useGetEducadorSuspense.ts";
export { getEducadorSuspenseQueryOptions } from "./react-query/EducadoresController/useGetEducadorSuspense.ts";
export { useGetEducadorSuspense } from "./react-query/EducadoresController/useGetEducadorSuspense.ts";
export { listarFormacoesQueryKey } from "./react-query/EducadoresController/useListarFormacoes.ts";
export { listarFormacoesQueryOptions } from "./react-query/EducadoresController/useListarFormacoes.ts";
export { useListarFormacoes } from "./react-query/EducadoresController/useListarFormacoes.ts";
export { listarFormacoesSuspenseQueryKey } from "./react-query/EducadoresController/useListarFormacoesSuspense.ts";
export { listarFormacoesSuspenseQueryOptions } from "./react-query/EducadoresController/useListarFormacoesSuspense.ts";
export { useListarFormacoesSuspense } from "./react-query/EducadoresController/useListarFormacoesSuspense.ts";
export { removerFormacaoMutationKey } from "./react-query/EducadoresController/useRemoverFormacao.ts";
export { removerFormacaoMutationOptions } from "./react-query/EducadoresController/useRemoverFormacao.ts";
export { useRemoverFormacao } from "./react-query/EducadoresController/useRemoverFormacao.ts";
export { updateEducadorMutationKey } from "./react-query/EducadoresController/useUpdateEducador.ts";
export { updateEducadorMutationOptions } from "./react-query/EducadoresController/useUpdateEducador.ts";
export { useUpdateEducador } from "./react-query/EducadoresController/useUpdateEducador.ts";
export { atualizarComentarioMutationKey } from "./react-query/mduloComentriosController/useAtualizarComentario.ts";
export { atualizarComentarioMutationOptions } from "./react-query/mduloComentriosController/useAtualizarComentario.ts";
export { useAtualizarComentario } from "./react-query/mduloComentriosController/useAtualizarComentario.ts";
export { getComentarioByIdQueryKey } from "./react-query/mduloComentriosController/useGetComentarioById.ts";
export { getComentarioByIdQueryOptions } from "./react-query/mduloComentriosController/useGetComentarioById.ts";
export { useGetComentarioById } from "./react-query/mduloComentriosController/useGetComentarioById.ts";
export { getComentarioByIdSuspenseQueryKey } from "./react-query/mduloComentriosController/useGetComentarioByIdSuspense.ts";
export { getComentarioByIdSuspenseQueryOptions } from "./react-query/mduloComentriosController/useGetComentarioByIdSuspense.ts";
export { useGetComentarioByIdSuspense } from "./react-query/mduloComentriosController/useGetComentarioByIdSuspense.ts";
export { obterComentariosDaPublicacaoQueryKey } from "./react-query/mduloComentriosController/useObterComentariosDaPublicacao.ts";
export { obterComentariosDaPublicacaoQueryOptions } from "./react-query/mduloComentriosController/useObterComentariosDaPublicacao.ts";
export { useObterComentariosDaPublicacao } from "./react-query/mduloComentriosController/useObterComentariosDaPublicacao.ts";
export { obterComentariosDaPublicacaoSuspenseQueryKey } from "./react-query/mduloComentriosController/useObterComentariosDaPublicacaoSuspense.ts";
export { obterComentariosDaPublicacaoSuspenseQueryOptions } from "./react-query/mduloComentriosController/useObterComentariosDaPublicacaoSuspense.ts";
export { useObterComentariosDaPublicacaoSuspense } from "./react-query/mduloComentriosController/useObterComentariosDaPublicacaoSuspense.ts";
export { removerComentarioMutationKey } from "./react-query/mduloComentriosController/useRemoverComentario.ts";
export { removerComentarioMutationOptions } from "./react-query/mduloComentriosController/useRemoverComentario.ts";
export { useRemoverComentario } from "./react-query/mduloComentriosController/useRemoverComentario.ts";
export { responderComentarioMutationKey } from "./react-query/mduloComentriosController/useResponderComentario.ts";
export { responderComentarioMutationOptions } from "./react-query/mduloComentriosController/useResponderComentario.ts";
export { useResponderComentario } from "./react-query/mduloComentriosController/useResponderComentario.ts";
export { responderPublicacaoMutationKey } from "./react-query/mduloComentriosController/useResponderPublicacao.ts";
export { responderPublicacaoMutationOptions } from "./react-query/mduloComentriosController/useResponderPublicacao.ts";
export { useResponderPublicacao } from "./react-query/mduloComentriosController/useResponderPublicacao.ts";
export { atualizarMutationKey } from "./react-query/mduloDeEstudantesController/useAtualizar.ts";
export { atualizarMutationOptions } from "./react-query/mduloDeEstudantesController/useAtualizar.ts";
export { useAtualizar } from "./react-query/mduloDeEstudantesController/useAtualizar.ts";
export { buscarPorIdQueryKey } from "./react-query/mduloDeEstudantesController/useBuscarPorId.ts";
export { buscarPorIdQueryOptions } from "./react-query/mduloDeEstudantesController/useBuscarPorId.ts";
export { useBuscarPorId } from "./react-query/mduloDeEstudantesController/useBuscarPorId.ts";
export { buscarPorIdSuspenseQueryKey } from "./react-query/mduloDeEstudantesController/useBuscarPorIdSuspense.ts";
export { buscarPorIdSuspenseQueryOptions } from "./react-query/mduloDeEstudantesController/useBuscarPorIdSuspense.ts";
export { useBuscarPorIdSuspense } from "./react-query/mduloDeEstudantesController/useBuscarPorIdSuspense.ts";
export { listarQueryKey } from "./react-query/mduloDeEstudantesController/useListar.ts";
export { listarQueryOptions } from "./react-query/mduloDeEstudantesController/useListar.ts";
export { useListar } from "./react-query/mduloDeEstudantesController/useListar.ts";
export { listarSuspenseQueryKey } from "./react-query/mduloDeEstudantesController/useListarSuspense.ts";
export { listarSuspenseQueryOptions } from "./react-query/mduloDeEstudantesController/useListarSuspense.ts";
export { useListarSuspense } from "./react-query/mduloDeEstudantesController/useListarSuspense.ts";
export { removerMutationKey } from "./react-query/mduloDeEstudantesController/useRemover.ts";
export { removerMutationOptions } from "./react-query/mduloDeEstudantesController/useRemover.ts";
export { useRemover } from "./react-query/mduloDeEstudantesController/useRemover.ts";
export { getGestorByEmailQueryKey } from "./react-query/mduloDeGestoresController/useGetGestorByEmail.ts";
export { getGestorByEmailQueryOptions } from "./react-query/mduloDeGestoresController/useGetGestorByEmail.ts";
export { useGetGestorByEmail } from "./react-query/mduloDeGestoresController/useGetGestorByEmail.ts";
export { getGestorByEmailSuspenseQueryKey } from "./react-query/mduloDeGestoresController/useGetGestorByEmailSuspense.ts";
export { getGestorByEmailSuspenseQueryOptions } from "./react-query/mduloDeGestoresController/useGetGestorByEmailSuspense.ts";
export { useGetGestorByEmailSuspense } from "./react-query/mduloDeGestoresController/useGetGestorByEmailSuspense.ts";
export { getGestorByIdQueryKey } from "./react-query/mduloDeGestoresController/useGetGestorById.ts";
export { getGestorByIdQueryOptions } from "./react-query/mduloDeGestoresController/useGetGestorById.ts";
export { useGetGestorById } from "./react-query/mduloDeGestoresController/useGetGestorById.ts";
export { getGestorByIdSuspenseQueryKey } from "./react-query/mduloDeGestoresController/useGetGestorByIdSuspense.ts";
export { getGestorByIdSuspenseQueryOptions } from "./react-query/mduloDeGestoresController/useGetGestorByIdSuspense.ts";
export { useGetGestorByIdSuspense } from "./react-query/mduloDeGestoresController/useGetGestorByIdSuspense.ts";
export { updateGestorMutationKey } from "./react-query/mduloDeGestoresController/useUpdateGestor.ts";
export { updateGestorMutationOptions } from "./react-query/mduloDeGestoresController/useUpdateGestor.ts";
export { useUpdateGestor } from "./react-query/mduloDeGestoresController/useUpdateGestor.ts";
export { addEstudanteToDisciplinaMutationKey } from "./react-query/mduloDisciplinasController/useAddEstudanteToDisciplina.ts";
export { addEstudanteToDisciplinaMutationOptions } from "./react-query/mduloDisciplinasController/useAddEstudanteToDisciplina.ts";
export { useAddEstudanteToDisciplina } from "./react-query/mduloDisciplinasController/useAddEstudanteToDisciplina.ts";
export { createDisciplinaMutationKey } from "./react-query/mduloDisciplinasController/useCreateDisciplina.ts";
export { createDisciplinaMutationOptions } from "./react-query/mduloDisciplinasController/useCreateDisciplina.ts";
export { useCreateDisciplina } from "./react-query/mduloDisciplinasController/useCreateDisciplina.ts";
export { getDisciplinaByIdQueryKey } from "./react-query/mduloDisciplinasController/useGetDisciplinaById.ts";
export { getDisciplinaByIdQueryOptions } from "./react-query/mduloDisciplinasController/useGetDisciplinaById.ts";
export { useGetDisciplinaById } from "./react-query/mduloDisciplinasController/useGetDisciplinaById.ts";
export { getDisciplinaByIdSuspenseQueryKey } from "./react-query/mduloDisciplinasController/useGetDisciplinaByIdSuspense.ts";
export { getDisciplinaByIdSuspenseQueryOptions } from "./react-query/mduloDisciplinasController/useGetDisciplinaByIdSuspense.ts";
export { useGetDisciplinaByIdSuspense } from "./react-query/mduloDisciplinasController/useGetDisciplinaByIdSuspense.ts";
export { getDisciplinasByEducadorQueryKey } from "./react-query/mduloDisciplinasController/useGetDisciplinasByEducador.ts";
export { getDisciplinasByEducadorQueryOptions } from "./react-query/mduloDisciplinasController/useGetDisciplinasByEducador.ts";
export { useGetDisciplinasByEducador } from "./react-query/mduloDisciplinasController/useGetDisciplinasByEducador.ts";
export { getDisciplinasByEducadorSuspenseQueryKey } from "./react-query/mduloDisciplinasController/useGetDisciplinasByEducadorSuspense.ts";
export { getDisciplinasByEducadorSuspenseQueryOptions } from "./react-query/mduloDisciplinasController/useGetDisciplinasByEducadorSuspense.ts";
export { useGetDisciplinasByEducadorSuspense } from "./react-query/mduloDisciplinasController/useGetDisciplinasByEducadorSuspense.ts";
export { getDisciplinasByEstudanteQueryKey } from "./react-query/mduloDisciplinasController/useGetDisciplinasByEstudante.ts";
export { getDisciplinasByEstudanteQueryOptions } from "./react-query/mduloDisciplinasController/useGetDisciplinasByEstudante.ts";
export { useGetDisciplinasByEstudante } from "./react-query/mduloDisciplinasController/useGetDisciplinasByEstudante.ts";
export { getDisciplinasByEstudanteSuspenseQueryKey } from "./react-query/mduloDisciplinasController/useGetDisciplinasByEstudanteSuspense.ts";
export { getDisciplinasByEstudanteSuspenseQueryOptions } from "./react-query/mduloDisciplinasController/useGetDisciplinasByEstudanteSuspense.ts";
export { useGetDisciplinasByEstudanteSuspense } from "./react-query/mduloDisciplinasController/useGetDisciplinasByEstudanteSuspense.ts";
export { getDisciplinasByInstituicaoQueryKey } from "./react-query/mduloDisciplinasController/useGetDisciplinasByInstituicao.ts";
export { getDisciplinasByInstituicaoQueryOptions } from "./react-query/mduloDisciplinasController/useGetDisciplinasByInstituicao.ts";
export { useGetDisciplinasByInstituicao } from "./react-query/mduloDisciplinasController/useGetDisciplinasByInstituicao.ts";
export { getDisciplinasByInstituicaoSuspenseQueryKey } from "./react-query/mduloDisciplinasController/useGetDisciplinasByInstituicaoSuspense.ts";
export { getDisciplinasByInstituicaoSuspenseQueryOptions } from "./react-query/mduloDisciplinasController/useGetDisciplinasByInstituicaoSuspense.ts";
export { useGetDisciplinasByInstituicaoSuspense } from "./react-query/mduloDisciplinasController/useGetDisciplinasByInstituicaoSuspense.ts";
export { getEstudantesFromDisciplinaQueryKey } from "./react-query/mduloDisciplinasController/useGetEstudantesFromDisciplina.ts";
export { getEstudantesFromDisciplinaQueryOptions } from "./react-query/mduloDisciplinasController/useGetEstudantesFromDisciplina.ts";
export { useGetEstudantesFromDisciplina } from "./react-query/mduloDisciplinasController/useGetEstudantesFromDisciplina.ts";
export { getEstudantesFromDisciplinaSuspenseQueryKey } from "./react-query/mduloDisciplinasController/useGetEstudantesFromDisciplinaSuspense.ts";
export { getEstudantesFromDisciplinaSuspenseQueryOptions } from "./react-query/mduloDisciplinasController/useGetEstudantesFromDisciplinaSuspense.ts";
export { useGetEstudantesFromDisciplinaSuspense } from "./react-query/mduloDisciplinasController/useGetEstudantesFromDisciplinaSuspense.ts";
export { removeEstudanteToDisciplinaMutationKey } from "./react-query/mduloDisciplinasController/useRemoveEstudanteToDisciplina.ts";
export { removeEstudanteToDisciplinaMutationOptions } from "./react-query/mduloDisciplinasController/useRemoveEstudanteToDisciplina.ts";
export { useRemoveEstudanteToDisciplina } from "./react-query/mduloDisciplinasController/useRemoveEstudanteToDisciplina.ts";
export { updateDisciplinaMutationKey } from "./react-query/mduloDisciplinasController/useUpdateDisciplina.ts";
export { updateDisciplinaMutationOptions } from "./react-query/mduloDisciplinasController/useUpdateDisciplina.ts";
export { useUpdateDisciplina } from "./react-query/mduloDisciplinasController/useUpdateDisciplina.ts";
export { addUsuarioToInstituicaoMutationKey } from "./react-query/mduloInstituiesDeEnsinoController/useAddUsuarioToInstituicao.ts";
export { addUsuarioToInstituicaoMutationOptions } from "./react-query/mduloInstituiesDeEnsinoController/useAddUsuarioToInstituicao.ts";
export { useAddUsuarioToInstituicao } from "./react-query/mduloInstituiesDeEnsinoController/useAddUsuarioToInstituicao.ts";
export { createInstituicaoMutationKey } from "./react-query/mduloInstituiesDeEnsinoController/useCreateInstituicao.ts";
export { createInstituicaoMutationOptions } from "./react-query/mduloInstituiesDeEnsinoController/useCreateInstituicao.ts";
export { useCreateInstituicao } from "./react-query/mduloInstituiesDeEnsinoController/useCreateInstituicao.ts";
export { getInstituicaoByCnpjQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByCnpj.ts";
export { getInstituicaoByCnpjQueryOptions } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByCnpj.ts";
export { useGetInstituicaoByCnpj } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByCnpj.ts";
export { getInstituicaoByCnpjSuspenseQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByCnpjSuspense.ts";
export { getInstituicaoByCnpjSuspenseQueryOptions } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByCnpjSuspense.ts";
export { useGetInstituicaoByCnpjSuspense } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByCnpjSuspense.ts";
export { getInstituicaoByEmailQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByEmail.ts";
export { getInstituicaoByEmailQueryOptions } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByEmail.ts";
export { useGetInstituicaoByEmail } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByEmail.ts";
export { getInstituicaoByEmailSuspenseQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByEmailSuspense.ts";
export { getInstituicaoByEmailSuspenseQueryOptions } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByEmailSuspense.ts";
export { useGetInstituicaoByEmailSuspense } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByEmailSuspense.ts";
export { getInstituicaoByIdQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoById.ts";
export { getInstituicaoByIdQueryOptions } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoById.ts";
export { useGetInstituicaoById } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoById.ts";
export { getInstituicaoByIdSuspenseQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByIdSuspense.ts";
export { getInstituicaoByIdSuspenseQueryOptions } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByIdSuspense.ts";
export { useGetInstituicaoByIdSuspense } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicaoByIdSuspense.ts";
export { getInstituicoesQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicoes.ts";
export { getInstituicoesQueryOptions } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicoes.ts";
export { useGetInstituicoes } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicoes.ts";
export { getInstituicoesSuspenseQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicoesSuspense.ts";
export { getInstituicoesSuspenseQueryOptions } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicoesSuspense.ts";
export { useGetInstituicoesSuspense } from "./react-query/mduloInstituiesDeEnsinoController/useGetInstituicoesSuspense.ts";
export { getUsuariosFromInstituicaoQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetUsuariosFromInstituicao.ts";
export { getUsuariosFromInstituicaoQueryOptions } from "./react-query/mduloInstituiesDeEnsinoController/useGetUsuariosFromInstituicao.ts";
export { useGetUsuariosFromInstituicao } from "./react-query/mduloInstituiesDeEnsinoController/useGetUsuariosFromInstituicao.ts";
export { getUsuariosFromInstituicaoSuspenseQueryKey } from "./react-query/mduloInstituiesDeEnsinoController/useGetUsuariosFromInstituicaoSuspense.ts";
export { getUsuariosFromInstituicaoSuspenseQueryOptions } from "./react-query/mduloInstituiesDeEnsinoController/useGetUsuariosFromInstituicaoSuspense.ts";
export { useGetUsuariosFromInstituicaoSuspense } from "./react-query/mduloInstituiesDeEnsinoController/useGetUsuariosFromInstituicaoSuspense.ts";
export { removeUsuarioFromInstituicaoMutationKey } from "./react-query/mduloInstituiesDeEnsinoController/useRemoveUsuarioFromInstituicao.ts";
export { removeUsuarioFromInstituicaoMutationOptions } from "./react-query/mduloInstituiesDeEnsinoController/useRemoveUsuarioFromInstituicao.ts";
export { useRemoveUsuarioFromInstituicao } from "./react-query/mduloInstituiesDeEnsinoController/useRemoveUsuarioFromInstituicao.ts";
export { updateInstituicaoMutationKey } from "./react-query/mduloInstituiesDeEnsinoController/useUpdateInstituicao.ts";
export { updateInstituicaoMutationOptions } from "./react-query/mduloInstituiesDeEnsinoController/useUpdateInstituicao.ts";
export { useUpdateInstituicao } from "./react-query/mduloInstituiesDeEnsinoController/useUpdateInstituicao.ts";
export { createPerfilAcessibilidadeMutationKey } from "./react-query/mduloPerfilDeAcessibilidadeController/useCreatePerfilAcessibilidade.ts";
export { createPerfilAcessibilidadeMutationOptions } from "./react-query/mduloPerfilDeAcessibilidadeController/useCreatePerfilAcessibilidade.ts";
export { useCreatePerfilAcessibilidade } from "./react-query/mduloPerfilDeAcessibilidadeController/useCreatePerfilAcessibilidade.ts";
export { getPerfilByEstudanteIdQueryKey } from "./react-query/mduloPerfilDeAcessibilidadeController/useGetPerfilByEstudanteId.ts";
export { getPerfilByEstudanteIdQueryOptions } from "./react-query/mduloPerfilDeAcessibilidadeController/useGetPerfilByEstudanteId.ts";
export { useGetPerfilByEstudanteId } from "./react-query/mduloPerfilDeAcessibilidadeController/useGetPerfilByEstudanteId.ts";
export { getPerfilByEstudanteIdSuspenseQueryKey } from "./react-query/mduloPerfilDeAcessibilidadeController/useGetPerfilByEstudanteIdSuspense.ts";
export { getPerfilByEstudanteIdSuspenseQueryOptions } from "./react-query/mduloPerfilDeAcessibilidadeController/useGetPerfilByEstudanteIdSuspense.ts";
export { useGetPerfilByEstudanteIdSuspense } from "./react-query/mduloPerfilDeAcessibilidadeController/useGetPerfilByEstudanteIdSuspense.ts";
export { getPerfilByIdQueryKey } from "./react-query/mduloPerfilDeAcessibilidadeController/useGetPerfilById.ts";
export { getPerfilByIdQueryOptions } from "./react-query/mduloPerfilDeAcessibilidadeController/useGetPerfilById.ts";
export { useGetPerfilById } from "./react-query/mduloPerfilDeAcessibilidadeController/useGetPerfilById.ts";
export { getPerfilByIdSuspenseQueryKey } from "./react-query/mduloPerfilDeAcessibilidadeController/useGetPerfilByIdSuspense.ts";
export { getPerfilByIdSuspenseQueryOptions } from "./react-query/mduloPerfilDeAcessibilidadeController/useGetPerfilByIdSuspense.ts";
export { useGetPerfilByIdSuspense } from "./react-query/mduloPerfilDeAcessibilidadeController/useGetPerfilByIdSuspense.ts";
export { removePerfilAcessibilidadeMutationKey } from "./react-query/mduloPerfilDeAcessibilidadeController/useRemovePerfilAcessibilidade.ts";
export { removePerfilAcessibilidadeMutationOptions } from "./react-query/mduloPerfilDeAcessibilidadeController/useRemovePerfilAcessibilidade.ts";
export { useRemovePerfilAcessibilidade } from "./react-query/mduloPerfilDeAcessibilidadeController/useRemovePerfilAcessibilidade.ts";
export { updatePerfilAcessibilidadeMutationKey } from "./react-query/mduloPerfilDeAcessibilidadeController/useUpdatePerfilAcessibilidade.ts";
export { updatePerfilAcessibilidadeMutationOptions } from "./react-query/mduloPerfilDeAcessibilidadeController/useUpdatePerfilAcessibilidade.ts";
export { useUpdatePerfilAcessibilidade } from "./react-query/mduloPerfilDeAcessibilidadeController/useUpdatePerfilAcessibilidade.ts";
export { createPublicacaoMutationKey } from "./react-query/mduloPublicaesController/useCreatePublicacao.ts";
export { createPublicacaoMutationOptions } from "./react-query/mduloPublicaesController/useCreatePublicacao.ts";
export { useCreatePublicacao } from "./react-query/mduloPublicaesController/useCreatePublicacao.ts";
export { deletePublicacaoMutationKey } from "./react-query/mduloPublicaesController/useDeletePublicacao.ts";
export { deletePublicacaoMutationOptions } from "./react-query/mduloPublicaesController/useDeletePublicacao.ts";
export { useDeletePublicacao } from "./react-query/mduloPublicaesController/useDeletePublicacao.ts";
export { getPublicacaoQueryKey } from "./react-query/mduloPublicaesController/useGetPublicacao.ts";
export { getPublicacaoQueryOptions } from "./react-query/mduloPublicaesController/useGetPublicacao.ts";
export { useGetPublicacao } from "./react-query/mduloPublicaesController/useGetPublicacao.ts";
export { getPublicacaoSuspenseQueryKey } from "./react-query/mduloPublicaesController/useGetPublicacaoSuspense.ts";
export { getPublicacaoSuspenseQueryOptions } from "./react-query/mduloPublicaesController/useGetPublicacaoSuspense.ts";
export { useGetPublicacaoSuspense } from "./react-query/mduloPublicaesController/useGetPublicacaoSuspense.ts";
export { getPublicacoesQueryKey } from "./react-query/mduloPublicaesController/useGetPublicacoes.ts";
export { getPublicacoesQueryOptions } from "./react-query/mduloPublicaesController/useGetPublicacoes.ts";
export { useGetPublicacoes } from "./react-query/mduloPublicaesController/useGetPublicacoes.ts";
export { getPublicacoesSuspenseQueryKey } from "./react-query/mduloPublicaesController/useGetPublicacoesSuspense.ts";
export { getPublicacoesSuspenseQueryOptions } from "./react-query/mduloPublicaesController/useGetPublicacoesSuspense.ts";
export { useGetPublicacoesSuspense } from "./react-query/mduloPublicaesController/useGetPublicacoesSuspense.ts";
export { updatePublicacaoMutationKey } from "./react-query/mduloPublicaesController/useUpdatePublicacao.ts";
export { updatePublicacaoMutationOptions } from "./react-query/mduloPublicaesController/useUpdatePublicacao.ts";
export { useUpdatePublicacao } from "./react-query/mduloPublicaesController/useUpdatePublicacao.ts";
export { createTarefaMutationKey } from "./react-query/mduloTarefasController/useCreateTarefa.ts";
export { createTarefaMutationOptions } from "./react-query/mduloTarefasController/useCreateTarefa.ts";
export { useCreateTarefa } from "./react-query/mduloTarefasController/useCreateTarefa.ts";
export { getTarefaByIdQueryKey } from "./react-query/mduloTarefasController/useGetTarefaById.ts";
export { getTarefaByIdQueryOptions } from "./react-query/mduloTarefasController/useGetTarefaById.ts";
export { useGetTarefaById } from "./react-query/mduloTarefasController/useGetTarefaById.ts";
export { getTarefaByIdSuspenseQueryKey } from "./react-query/mduloTarefasController/useGetTarefaByIdSuspense.ts";
export { getTarefaByIdSuspenseQueryOptions } from "./react-query/mduloTarefasController/useGetTarefaByIdSuspense.ts";
export { useGetTarefaByIdSuspense } from "./react-query/mduloTarefasController/useGetTarefaByIdSuspense.ts";
export { getTarefasByDisciplinaQueryKey } from "./react-query/mduloTarefasController/useGetTarefasByDisciplina.ts";
export { getTarefasByDisciplinaQueryOptions } from "./react-query/mduloTarefasController/useGetTarefasByDisciplina.ts";
export { useGetTarefasByDisciplina } from "./react-query/mduloTarefasController/useGetTarefasByDisciplina.ts";
export { getTarefasByDisciplinaSuspenseQueryKey } from "./react-query/mduloTarefasController/useGetTarefasByDisciplinaSuspense.ts";
export { getTarefasByDisciplinaSuspenseQueryOptions } from "./react-query/mduloTarefasController/useGetTarefasByDisciplinaSuspense.ts";
export { useGetTarefasByDisciplinaSuspense } from "./react-query/mduloTarefasController/useGetTarefasByDisciplinaSuspense.ts";
export { removeTarefaMutationKey } from "./react-query/mduloTarefasController/useRemoveTarefa.ts";
export { removeTarefaMutationOptions } from "./react-query/mduloTarefasController/useRemoveTarefa.ts";
export { useRemoveTarefa } from "./react-query/mduloTarefasController/useRemoveTarefa.ts";
export { updateTarefaMutationKey } from "./react-query/mduloTarefasController/useUpdateTarefa.ts";
export { updateTarefaMutationOptions } from "./react-query/mduloTarefasController/useUpdateTarefa.ts";
export { useUpdateTarefa } from "./react-query/mduloTarefasController/useUpdateTarefa.ts";
export { forgotPasswordMutationKey } from "./react-query/redefinioDeSenhaController/useForgotPassword.ts";
export { forgotPasswordMutationOptions } from "./react-query/redefinioDeSenhaController/useForgotPassword.ts";
export { useForgotPassword } from "./react-query/redefinioDeSenhaController/useForgotPassword.ts";
export { updatePasswordMutationKey } from "./react-query/redefinioDeSenhaController/useUpdatePassword.ts";
export { updatePasswordMutationOptions } from "./react-query/redefinioDeSenhaController/useUpdatePassword.ts";
export { useUpdatePassword } from "./react-query/redefinioDeSenhaController/useUpdatePassword.ts";
export { validateTokenMutationKey } from "./react-query/redefinioDeSenhaController/useValidateToken.ts";
export { validateTokenMutationOptions } from "./react-query/redefinioDeSenhaController/useValidateToken.ts";
export { useValidateToken } from "./react-query/redefinioDeSenhaController/useValidateToken.ts";
export { avaliarRespostaMutationKey } from "./react-query/respostasController/useAvaliarResposta.ts";
export { avaliarRespostaMutationOptions } from "./react-query/respostasController/useAvaliarResposta.ts";
export { useAvaliarResposta } from "./react-query/respostasController/useAvaliarResposta.ts";
export { criarRespostaComUploadMutationKey } from "./react-query/respostasController/useCriarRespostaComUpload.ts";
export { criarRespostaComUploadMutationOptions } from "./react-query/respostasController/useCriarRespostaComUpload.ts";
export { useCriarRespostaComUpload } from "./react-query/respostasController/useCriarRespostaComUpload.ts";
export { enviarRespostaMutationKey } from "./react-query/respostasController/useEnviarResposta.ts";
export { enviarRespostaMutationOptions } from "./react-query/respostasController/useEnviarResposta.ts";
export { useEnviarResposta } from "./react-query/respostasController/useEnviarResposta.ts";
export { addEstudanteToDisciplinaPathParamsSchema, addEstudanteToDisciplinaQueryParamsSchema, addEstudanteToDisciplina200Schema, addEstudanteToDisciplina404Schema, addEstudanteToDisciplinaMutationResponseSchema } from "./zod/addEstudanteToDisciplinaSchema.ts";
export { addUsuarioToInstituicaoPathParamsSchema, addUsuarioToInstituicao200Schema, addUsuarioToInstituicao404Schema, addUsuarioToInstituicao409Schema, addUsuarioToInstituicaoMutationResponseSchema } from "./zod/addUsuarioToInstituicaoSchema.ts";
export { adicionarFormacaoPathParamsSchema, adicionarFormacao200Schema, adicionarFormacaoMutationRequestSchema, adicionarFormacaoMutationResponseSchema } from "./zod/adicionarFormacaoSchema.ts";
export { arquivoDTOSchema } from "./zod/arquivoDTOSchema.ts";
export { atualizarComentarioPathParamsSchema, atualizarComentario200Schema, atualizarComentario404Schema, atualizarComentarioMutationRequestSchema, atualizarComentarioMutationResponseSchema } from "./zod/atualizarComentarioSchema.ts";
export { atualizarPathParamsSchema, atualizar200Schema, atualizar400Schema, atualizar404Schema, atualizarMutationRequestSchema, atualizarMutationResponseSchema } from "./zod/atualizarSchema.ts";
export { authenticationDTOSchema } from "./zod/authenticationDTOSchema.ts";
export { avaliarRespostaDTOSchema } from "./zod/avaliarRespostaDTOSchema.ts";
export { avaliarRespostaPathParamsSchema, avaliarResposta200Schema, avaliarRespostaMutationRequestSchema, avaliarRespostaMutationResponseSchema } from "./zod/avaliarRespostaSchema.ts";
export { buscarPorIdPathParamsSchema, buscarPorId200Schema, buscarPorId404Schema, buscarPorIdQueryResponseSchema } from "./zod/buscarPorIdSchema.ts";
export { comentarioSummaryDTOSchema } from "./zod/comentarioSummaryDTOSchema.ts";
export { createComentarioDTOSchema } from "./zod/createComentarioDTOSchema.ts";
export { createDisciplinaDTOSchema } from "./zod/createDisciplinaDTOSchema.ts";
export { createDisciplina201Schema, createDisciplina404Schema, createDisciplina409Schema, createDisciplinaMutationRequestSchema, createDisciplinaMutationResponseSchema } from "./zod/createDisciplinaSchema.ts";
export { createInstituicaoDTOSchema } from "./zod/createInstituicaoDTOSchema.ts";
export { createInstituicao201Schema, createInstituicao409Schema, createInstituicao422Schema, createInstituicaoMutationRequestSchema, createInstituicaoMutationResponseSchema } from "./zod/createInstituicaoSchema.ts";
export { createPerfilAcessibilidadeDTOSchema } from "./zod/createPerfilAcessibilidadeDTOSchema.ts";
export { createPerfilAcessibilidadeQueryParamsSchema, createPerfilAcessibilidade201Schema, createPerfilAcessibilidade400Schema, createPerfilAcessibilidade404Schema, createPerfilAcessibilidadeMutationRequestSchema, createPerfilAcessibilidadeMutationResponseSchema } from "./zod/createPerfilAcessibilidadeSchema.ts";
export { createPublicacaoDTOSchema } from "./zod/createPublicacaoDTOSchema.ts";
export { createPublicacao201Schema, createPublicacao403Schema, createPublicacao404Schema, createPublicacao409Schema, createPublicacaoMutationRequestSchema, createPublicacaoMutationResponseSchema } from "./zod/createPublicacaoSchema.ts";
export { createRespostaDTOSchema } from "./zod/createRespostaDTOSchema.ts";
export { createRespostaMultipartDTOSchema } from "./zod/createRespostaMultipartDTOSchema.ts";
export { createTarefaDTOSchema } from "./zod/createTarefaDTOSchema.ts";
export { createTarefa200Schema, createTarefaMutationRequestSchema, createTarefaMutationResponseSchema } from "./zod/createTarefaSchema.ts";
export { criarRespostaComUpload200Schema, criarRespostaComUploadMutationRequestSchema, criarRespostaComUploadMutationResponseSchema } from "./zod/criarRespostaComUploadSchema.ts";
export { deletarArquivoPathParamsSchema, deletarArquivoQueryParamsSchema, deletarArquivo200Schema, deletarArquivoMutationResponseSchema } from "./zod/deletarArquivoSchema.ts";
export { deletePublicacaoPathParamsSchema, deletePublicacao204Schema, deletePublicacao404Schema, deletePublicacaoMutationResponseSchema } from "./zod/deletePublicacaoSchema.ts";
export { disciplinaSummaryDTOSchema } from "./zod/disciplinaSummaryDTOSchema.ts";
export { downloadArquivoPathParamsSchema, downloadArquivo200Schema, downloadArquivoQueryResponseSchema } from "./zod/downloadArquivoSchema.ts";
export { educadorResponseDTOSchema } from "./zod/educadorResponseDTOSchema.ts";
export { educadorSummaryDTOSchema } from "./zod/educadorSummaryDTOSchema.ts";
export { enderecoSchema } from "./zod/enderecoSchema.ts";
export { enviarResposta200Schema, enviarRespostaMutationRequestSchema, enviarRespostaMutationResponseSchema } from "./zod/enviarRespostaSchema.ts";
export { estudanteListDTOSchema } from "./zod/estudanteListDTOSchema.ts";
export { estudanteResponseDTOSchema } from "./zod/estudanteResponseDTOSchema.ts";
export { estudanteSummaryDTOSchema } from "./zod/estudanteSummaryDTOSchema.ts";
export { estudanteUpdateDTOSchema } from "./zod/estudanteUpdateDTOSchema.ts";
export { forgotPassword200Schema, forgotPasswordMutationRequestSchema, forgotPasswordMutationResponseSchema } from "./zod/forgotPasswordSchema.ts";
export { formacaoListResponseDTOSchema } from "./zod/formacaoListResponseDTOSchema.ts";
export { formacaoRequestDTOSchema } from "./zod/formacaoRequestDTOSchema.ts";
export { formacaoResponseDTOSchema } from "./zod/formacaoResponseDTOSchema.ts";
export { gestorDetailsDTOSchema } from "./zod/gestorDetailsDTOSchema.ts";
export { gestorGetByEmailDTOSchema } from "./zod/gestorGetByEmailDTOSchema.ts";
export { getAllUsuarios200Schema, getAllUsuarios204Schema, getAllUsuariosQueryResponseSchema } from "./zod/getAllUsuariosSchema.ts";
export { getComentarioByIdPathParamsSchema, getComentarioById200Schema, getComentarioById404Schema, getComentarioByIdQueryResponseSchema } from "./zod/getComentarioByIdSchema.ts";
export { getDisciplinaByIdPathParamsSchema, getDisciplinaById200Schema, getDisciplinaById404Schema, getDisciplinaByIdQueryResponseSchema } from "./zod/getDisciplinaByIdSchema.ts";
export { getDisciplinasByEducadorQueryParamsSchema, getDisciplinasByEducador200Schema, getDisciplinasByEducador204Schema, getDisciplinasByEducadorQueryResponseSchema } from "./zod/getDisciplinasByEducadorSchema.ts";
export { getDisciplinasByEstudanteQueryParamsSchema, getDisciplinasByEstudante200Schema, getDisciplinasByEstudante204Schema, getDisciplinasByEstudante404Schema, getDisciplinasByEstudanteQueryResponseSchema } from "./zod/getDisciplinasByEstudanteSchema.ts";
export { getDisciplinasByInstituicaoQueryParamsSchema, getDisciplinasByInstituicao200Schema, getDisciplinasByInstituicao204Schema, getDisciplinasByInstituicao404Schema, getDisciplinasByInstituicaoQueryResponseSchema } from "./zod/getDisciplinasByInstituicaoSchema.ts";
export { getEducadorPathParamsSchema, getEducador200Schema, getEducadorQueryResponseSchema } from "./zod/getEducadorSchema.ts";
export { getEstudantesFromDisciplinaPathParamsSchema, getEstudantesFromDisciplina200Schema, getEstudantesFromDisciplina204Schema, getEstudantesFromDisciplina404Schema, getEstudantesFromDisciplinaQueryResponseSchema } from "./zod/getEstudantesFromDisciplinaSchema.ts";
export { getGestorByEmail200Schema, getGestorByEmail400Schema, getGestorByEmail404Schema, getGestorByEmailQueryRequestSchema, getGestorByEmailQueryResponseSchema } from "./zod/getGestorByEmailSchema.ts";
export { getGestorByIdPathParamsSchema, getGestorById200Schema, getGestorById400Schema, getGestorById404Schema, getGestorByIdQueryResponseSchema } from "./zod/getGestorByIdSchema.ts";
export { getInstituicaoByCnpj200Schema, getInstituicaoByCnpj404Schema, getInstituicaoByCnpjQueryRequestSchema, getInstituicaoByCnpjQueryResponseSchema } from "./zod/getInstituicaoByCnpjSchema.ts";
export { getInstituicaoByEmail200Schema, getInstituicaoByEmailQueryRequestSchema, getInstituicaoByEmailQueryResponseSchema } from "./zod/getInstituicaoByEmailSchema.ts";
export { getInstituicaoByIdPathParamsSchema, getInstituicaoById200Schema, getInstituicaoById404Schema, getInstituicaoByIdQueryResponseSchema } from "./zod/getInstituicaoByIdSchema.ts";
export { getInstituicoes200Schema, getInstituicoes204Schema, getInstituicoesQueryResponseSchema } from "./zod/getInstituicoesSchema.ts";
export { getPerfilByEstudanteIdPathParamsSchema, getPerfilByEstudanteId200Schema, getPerfilByEstudanteId404Schema, getPerfilByEstudanteIdQueryResponseSchema } from "./zod/getPerfilByEstudanteIdSchema.ts";
export { getPerfilByIdPathParamsSchema, getPerfilById200Schema, getPerfilById404Schema, getPerfilByIdQueryResponseSchema } from "./zod/getPerfilByIdSchema.ts";
export { getPublicacaoPathParamsSchema, getPublicacao200Schema, getPublicacao404Schema, getPublicacaoQueryResponseSchema } from "./zod/getPublicacaoSchema.ts";
export { getPublicacoesQueryParamsSchema, getPublicacoes200Schema, getPublicacoes204Schema, getPublicacoes404Schema, getPublicacoesQueryResponseSchema } from "./zod/getPublicacoesSchema.ts";
export { getTarefaByIdPathParamsSchema, getTarefaById200Schema, getTarefaByIdQueryResponseSchema } from "./zod/getTarefaByIdSchema.ts";
export { getTarefasByDisciplinaPathParamsSchema, getTarefasByDisciplina200Schema, getTarefasByDisciplinaQueryResponseSchema } from "./zod/getTarefasByDisciplinaSchema.ts";
export { getUsuarioByIdPathParamsSchema, getUsuarioById200Schema, getUsuarioById404Schema, getUsuarioByIdQueryResponseSchema } from "./zod/getUsuarioByIdSchema.ts";
export { getUsuariosFromInstituicaoPathParamsSchema, getUsuariosFromInstituicao200Schema, getUsuariosFromInstituicao204Schema, getUsuariosFromInstituicao404Schema, getUsuariosFromInstituicaoQueryResponseSchema } from "./zod/getUsuariosFromInstituicaoSchema.ts";
export { instituicaoCnpjDTOSchema } from "./zod/instituicaoCnpjDTOSchema.ts";
export { instituicaoDetailsDTOSchema } from "./zod/instituicaoDetailsDTOSchema.ts";
export { instituicaoEmailDTOSchema } from "./zod/instituicaoEmailDTOSchema.ts";
export { listarArquivosPathParamsSchema, listarArquivos200Schema, listarArquivos204Schema, listarArquivosQueryResponseSchema } from "./zod/listarArquivosSchema.ts";
export { listarFormacoesPathParamsSchema, listarFormacoes200Schema, listarFormacoesQueryResponseSchema } from "./zod/listarFormacoesSchema.ts";
export { listarQueryParamsSchema, listar200Schema, listar404Schema, listarQueryResponseSchema } from "./zod/listarSchema.ts";
export { login200Schema, login400Schema, loginMutationRequestSchema, loginMutationResponseSchema } from "./zod/loginSchema.ts";
export { obterComentariosDaPublicacaoQueryParamsSchema, obterComentariosDaPublicacao200Schema, obterComentariosDaPublicacao204Schema, obterComentariosDaPublicacao404Schema, obterComentariosDaPublicacaoQueryResponseSchema } from "./zod/obterComentariosDaPublicacaoSchema.ts";
export { passwordResetDTOSchema } from "./zod/passwordResetDTOSchema.ts";
export { publicacaoDetailsDTOSchema } from "./zod/publicacaoDetailsDTOSchema.ts";
export { publicacaoSummaryDTOSchema } from "./zod/publicacaoSummaryDTOSchema.ts";
export { registerDTOSchema } from "./zod/registerDTOSchema.ts";
export { register201Schema, register400Schema, registerMutationRequestSchema, registerMutationResponseSchema } from "./zod/registerSchema.ts";
export { removeEstudanteToDisciplinaPathParamsSchema, removeEstudanteToDisciplinaQueryParamsSchema, removeEstudanteToDisciplina200Schema, removeEstudanteToDisciplina404Schema, removeEstudanteToDisciplinaMutationResponseSchema } from "./zod/removeEstudanteToDisciplinaSchema.ts";
export { removePerfilAcessibilidadePathParamsSchema, removePerfilAcessibilidade204Schema, removePerfilAcessibilidade404Schema, removePerfilAcessibilidadeMutationResponseSchema } from "./zod/removePerfilAcessibilidadeSchema.ts";
export { removerComentarioPathParamsSchema, removerComentario204Schema, removerComentario404Schema, removerComentarioMutationResponseSchema } from "./zod/removerComentarioSchema.ts";
export { removerFormacaoPathParamsSchema, removerFormacao204Schema, removerFormacaoMutationResponseSchema } from "./zod/removerFormacaoSchema.ts";
export { removerPathParamsSchema, remover204Schema, remover404Schema, removerMutationResponseSchema } from "./zod/removerSchema.ts";
export { removeTarefaPathParamsSchema, removeTarefa200Schema, removeTarefaMutationResponseSchema } from "./zod/removeTarefaSchema.ts";
export { removeUsuarioFromInstituicaoPathParamsSchema, removeUsuarioFromInstituicao200Schema, removeUsuarioFromInstituicao404Schema, removeUsuarioFromInstituicao409Schema, removeUsuarioFromInstituicaoMutationResponseSchema } from "./zod/removeUsuarioFromInstituicaoSchema.ts";
export { requestResetDTOSchema } from "./zod/requestResetDTOSchema.ts";
export { responderComentarioQueryParamsSchema, responderComentario200Schema, responderComentario404Schema, responderComentario409Schema, responderComentarioMutationRequestSchema, responderComentarioMutationResponseSchema } from "./zod/responderComentarioSchema.ts";
export { responderPublicacaoQueryParamsSchema, responderPublicacao201Schema, responderPublicacao404Schema, responderPublicacao409Schema, responderPublicacaoMutationRequestSchema, responderPublicacaoMutationResponseSchema } from "./zod/responderPublicacaoSchema.ts";
export { respostaAComentarioSummaryDTOSchema } from "./zod/respostaAComentarioSummaryDTOSchema.ts";
export { respostaDTOSchema } from "./zod/respostaDTOSchema.ts";
export { summaryTarefaDTOSchema } from "./zod/summaryTarefaDTOSchema.ts";
export { tarefaDetailsDTOSchema } from "./zod/tarefaDetailsDTOSchema.ts";
export { updateComentarioDTOSchema } from "./zod/updateComentarioDTOSchema.ts";
export { updateDisciplinaDTOSchema } from "./zod/updateDisciplinaDTOSchema.ts";
export { updateDisciplinaPathParamsSchema, updateDisciplina200Schema, updateDisciplina404Schema, updateDisciplina409Schema, updateDisciplinaMutationRequestSchema, updateDisciplinaMutationResponseSchema } from "./zod/updateDisciplinaSchema.ts";
export { updateEducadorDTOSchema } from "./zod/updateEducadorDTOSchema.ts";
export { updateEducadorPathParamsSchema, updateEducador200Schema, updateEducador404Schema, updateEducador409Schema, updateEducadorMutationRequestSchema, updateEducadorMutationResponseSchema } from "./zod/updateEducadorSchema.ts";
export { updateGestorDTOSchema } from "./zod/updateGestorDTOSchema.ts";
export { updateGestorPathParamsSchema, updateGestor200Schema, updateGestor400Schema, updateGestor404Schema, updateGestorMutationRequestSchema, updateGestorMutationResponseSchema } from "./zod/updateGestorSchema.ts";
export { updateInstituicaoDTOSchema } from "./zod/updateInstituicaoDTOSchema.ts";
export { updateInstituicaoPathParamsSchema, updateInstituicao200Schema, updateInstituicao404Schema, updateInstituicao422Schema, updateInstituicaoMutationRequestSchema, updateInstituicaoMutationResponseSchema } from "./zod/updateInstituicaoSchema.ts";
export { updatePassword200Schema, updatePassword400Schema, updatePasswordMutationRequestSchema, updatePasswordMutationResponseSchema } from "./zod/updatePasswordSchema.ts";
export { updatePerfilAcessibilidadeDTOSchema } from "./zod/updatePerfilAcessibilidadeDTOSchema.ts";
export { updatePerfilAcessibilidadePathParamsSchema, updatePerfilAcessibilidade200Schema, updatePerfilAcessibilidade400Schema, updatePerfilAcessibilidade404Schema, updatePerfilAcessibilidadeMutationRequestSchema, updatePerfilAcessibilidadeMutationResponseSchema } from "./zod/updatePerfilAcessibilidadeSchema.ts";
export { updatePublicacaoDTOSchema } from "./zod/updatePublicacaoDTOSchema.ts";
export { updatePublicacaoPathParamsSchema, updatePublicacao200Schema, updatePublicacao404Schema, updatePublicacao409Schema, updatePublicacaoMutationRequestSchema, updatePublicacaoMutationResponseSchema } from "./zod/updatePublicacaoSchema.ts";
export { updateTarefaDTOSchema } from "./zod/updateTarefaDTOSchema.ts";
export { updateTarefaPathParamsSchema, updateTarefa200Schema, updateTarefaMutationRequestSchema, updateTarefaMutationResponseSchema } from "./zod/updateTarefaSchema.ts";
export { uploadArquivoPathParamsSchema, uploadArquivoQueryParamsSchema, uploadArquivo201Schema, uploadArquivo400Schema, uploadArquivo404Schema, uploadArquivoMutationRequestSchema, uploadArquivoMutationResponseSchema } from "./zod/uploadArquivoSchema.ts";
export { usuarioDetailsDTOSchema } from "./zod/usuarioDetailsDTOSchema.ts";
export { usuarioSummaryDTOSchema } from "./zod/usuarioSummaryDTOSchema.ts";
export { validateTokenQueryParamsSchema, validateToken200Schema, validateToken400Schema, validateTokenMutationResponseSchema } from "./zod/validateTokenSchema.ts";