/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { AvaliarRespostaMutationRequest, AvaliarRespostaMutationResponse, AvaliarRespostaPathParams } from "../../models/AvaliarResposta.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { avaliarResposta } from "../../client/avaliarResposta.ts";

export const avaliarRespostaMutationKey = () => [{ url: '/respostas/:id/avaliar' }] as const

export type AvaliarRespostaMutationKey = ReturnType<typeof avaliarRespostaMutationKey>

export function avaliarRespostaMutationOptions(config: Partial<RequestConfig<AvaliarRespostaMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = avaliarRespostaMutationKey()
  return mutationOptions<AvaliarRespostaMutationResponse, ResponseErrorConfig<Error>, {id: AvaliarRespostaPathParams["id"], data: AvaliarRespostaMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return avaliarResposta(id, data, config)
    },
  })
}

/**
 * @summary Avalia uma resposta enviada por um estudante
 * {@link /respostas/:id/avaliar}
 */
export function useAvaliarResposta<TContext>(options: 
{
  mutation?: UseMutationOptions<AvaliarRespostaMutationResponse, ResponseErrorConfig<Error>, {id: AvaliarRespostaPathParams["id"], data: AvaliarRespostaMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AvaliarRespostaMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? avaliarRespostaMutationKey()

  const baseOptions = avaliarRespostaMutationOptions(config) as UseMutationOptions<AvaliarRespostaMutationResponse, ResponseErrorConfig<Error>, {id: AvaliarRespostaPathParams["id"], data: AvaliarRespostaMutationRequest}, TContext>

  return useMutation<AvaliarRespostaMutationResponse, ResponseErrorConfig<Error>, {id: AvaliarRespostaPathParams["id"], data: AvaliarRespostaMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<AvaliarRespostaMutationResponse, ResponseErrorConfig<Error>, {id: AvaliarRespostaPathParams["id"], data: AvaliarRespostaMutationRequest}, TContext>
}