/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { CriarRespostaComUploadMutationRequest, CriarRespostaComUploadMutationResponse } from "../../models/CriarRespostaComUpload.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { criarRespostaComUpload } from "../../client/criarRespostaComUpload.ts";

export const criarRespostaComUploadMutationKey = () => [{ url: '/respostas/upload' }] as const

export type CriarRespostaComUploadMutationKey = ReturnType<typeof criarRespostaComUploadMutationKey>

export function criarRespostaComUploadMutationOptions(config: Partial<RequestConfig<CriarRespostaComUploadMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = criarRespostaComUploadMutationKey()
  return mutationOptions<CriarRespostaComUploadMutationResponse, ResponseErrorConfig<Error>, {data?: CriarRespostaComUploadMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return criarRespostaComUpload(data, config)
    },
  })
}

/**
 * @summary Cria uma nova resposta com upload de arquivo
 * {@link /respostas/upload}
 */
export function useCriarRespostaComUpload<TContext>(options: 
{
  mutation?: UseMutationOptions<CriarRespostaComUploadMutationResponse, ResponseErrorConfig<Error>, {data?: CriarRespostaComUploadMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CriarRespostaComUploadMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? criarRespostaComUploadMutationKey()

  const baseOptions = criarRespostaComUploadMutationOptions(config) as UseMutationOptions<CriarRespostaComUploadMutationResponse, ResponseErrorConfig<Error>, {data?: CriarRespostaComUploadMutationRequest}, TContext>

  return useMutation<CriarRespostaComUploadMutationResponse, ResponseErrorConfig<Error>, {data?: CriarRespostaComUploadMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CriarRespostaComUploadMutationResponse, ResponseErrorConfig<Error>, {data?: CriarRespostaComUploadMutationRequest}, TContext>
}