/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { EnviarRespostaMutationRequest, EnviarRespostaMutationResponse } from "../../models/EnviarResposta.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { enviarResposta } from "../../client/enviarResposta.ts";

export const enviarRespostaMutationKey = () => [{ url: '/respostas' }] as const

export type EnviarRespostaMutationKey = ReturnType<typeof enviarRespostaMutationKey>

export function enviarRespostaMutationOptions(config: Partial<RequestConfig<EnviarRespostaMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = enviarRespostaMutationKey()
  return mutationOptions<EnviarRespostaMutationResponse, ResponseErrorConfig<Error>, {data: EnviarRespostaMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return enviarResposta(data, config)
    },
  })
}

/**
 * @summary Cria uma nova resposta de texto para uma tarefa
 * {@link /respostas}
 */
export function useEnviarResposta<TContext>(options: 
{
  mutation?: UseMutationOptions<EnviarRespostaMutationResponse, ResponseErrorConfig<Error>, {data: EnviarRespostaMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<EnviarRespostaMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? enviarRespostaMutationKey()

  const baseOptions = enviarRespostaMutationOptions(config) as UseMutationOptions<EnviarRespostaMutationResponse, ResponseErrorConfig<Error>, {data: EnviarRespostaMutationRequest}, TContext>

  return useMutation<EnviarRespostaMutationResponse, ResponseErrorConfig<Error>, {data: EnviarRespostaMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<EnviarRespostaMutationResponse, ResponseErrorConfig<Error>, {data: EnviarRespostaMutationRequest}, TContext>
}