/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UsuarioSummaryDTO } from "./UsuarioSummaryDTO.ts";

export type AddUsuarioToInstituicaoPathParams = {
    /**
     * @type integer, int64
    */
    instituicaoId: number;
    /**
     * @type integer, int64
    */
    usuarioId: number;
};

/**
 * @description Usuário adicionado com sucesso
*/
export type AddUsuarioToInstituicao200 = UsuarioSummaryDTO[];

/**
 * @description Instituição ou Usuário não encontrados
*/
export type AddUsuarioToInstituicao404 = UsuarioSummaryDTO[];

/**
 * @description Usuário já vinculado a uma Instituição de Ensino
*/
export type AddUsuarioToInstituicao409 = UsuarioSummaryDTO[];

export type AddUsuarioToInstituicaoMutationResponse = AddUsuarioToInstituicao200;

export type AddUsuarioToInstituicaoMutation = {
    Response: AddUsuarioToInstituicao200;
    PathParams: AddUsuarioToInstituicaoPathParams;
    Errors: AddUsuarioToInstituicao404 | AddUsuarioToInstituicao409;
};