/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { EducadorResponseDTO } from "./EducadorResponseDTO.ts";
import type { FormacaoRequestDTO } from "./FormacaoRequestDTO.ts";

export type AdicionarFormacaoPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description Formação adicionada com sucesso
*/
export type AdicionarFormacao200 = EducadorResponseDTO;

export type AdicionarFormacaoMutationRequest = FormacaoRequestDTO;

export type AdicionarFormacaoMutationResponse = AdicionarFormacao200;

export type AdicionarFormacaoMutation = {
    Response: AdicionarFormacao200;
    Request: AdicionarFormacaoMutationRequest;
    PathParams: AdicionarFormacaoPathParams;
    Errors: any;
};