/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ArquivoDTO = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type string | undefined
    */
    nomeOriginal?: string;
    /**
     * @type string | undefined
    */
    caminho?: string;
    /**
     * @type string | undefined, date-time
    */
    dataEnvio?: string;
    /**
     * @type string | undefined
    */
    tipoMime?: string;
    /**
     * @type string | undefined
    */
    enviadoPor?: string;
};