/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { EstudanteResponseDTO } from "./EstudanteResponseDTO.ts";
import type { EstudanteUpdateDTO } from "./EstudanteUpdateDTO.ts";

export type AtualizarPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description Estudante atualizado com sucesso
*/
export type Atualizar200 = EstudanteResponseDTO;

/**
 * @description Erro na validação dos dados enviados
*/
export type Atualizar400 = EstudanteResponseDTO;

/**
 * @description Estudante não encontrado
*/
export type Atualizar404 = EstudanteResponseDTO;

export type AtualizarMutationRequest = EstudanteUpdateDTO;

export type AtualizarMutationResponse = Atualizar200;

export type AtualizarMutation = {
    Response: Atualizar200;
    Request: AtualizarMutationRequest;
    PathParams: AtualizarPathParams;
    Errors: Atualizar400 | Atualizar404;
};