/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ComentarioSummaryDTO } from "./ComentarioSummaryDTO.ts";
import type { UpdateComentarioDTO } from "./UpdateComentarioDTO.ts";

export type AtualizarComentarioPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description Comentário atualizado com sucesso
*/
export type AtualizarComentario200 = ComentarioSummaryDTO;

/**
 * @description Comentário não encontrado
*/
export type AtualizarComentario404 = ComentarioSummaryDTO;

export type AtualizarComentarioMutationRequest = UpdateComentarioDTO;

export type AtualizarComentarioMutationResponse = AtualizarComentario200;

export type AtualizarComentarioMutation = {
    Response: AtualizarComentario200;
    Request: AtualizarComentarioMutationRequest;
    PathParams: AtualizarComentarioPathParams;
    Errors: AtualizarComentario404;
};