/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AuthenticationDTO = {
    /**
     * @type string | undefined
    */
    email?: string;
    /**
     * @type string | undefined
    */
    senha?: string;
};