/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AvaliarRespostaDTO = {
    /**
     * @type integer, int64
    */
    respostaId: number;
    /**
     * @type number, double
    */
    nota: number;
    /**
     * @type string | undefined
    */
    comentario?: string;
};