/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AvaliarRespostaDTO } from "./AvaliarRespostaDTO.ts";
import type { RespostaDTO } from "./RespostaDTO.ts";

export type AvaliarRespostaPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description OK
*/
export type AvaliarResposta200 = RespostaDTO;

export type AvaliarRespostaMutationRequest = AvaliarRespostaDTO;

export type AvaliarRespostaMutationResponse = AvaliarResposta200;

export type AvaliarRespostaMutation = {
    Response: AvaliarResposta200;
    Request: AvaliarRespostaMutationRequest;
    PathParams: AvaliarRespostaPathParams;
    Errors: any;
};