/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RespostaAComentarioSummaryDTO } from "./RespostaAComentarioSummaryDTO.ts";
import type { UsuarioSummaryDTO } from "./UsuarioSummaryDTO.ts";

export type ComentarioSummaryDTO = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type string | undefined
    */
    conteudo?: string;
    /**
     * @description Sumário de usuários
     * @type object | undefined
    */
    autor?: UsuarioSummaryDTO;
    /**
     * @type string | undefined, date-time
    */
    dataCriacao?: string;
    /**
     * @type array | undefined
    */
    respostas?: RespostaAComentarioSummaryDTO[];
};