/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateTarefaDTO = {
    /**
     * @minLength 1
     * @type string
    */
    titulo: string;
    /**
     * @minLength 1
     * @type string
    */
    conteudo: string;
    /**
     * @type integer, int64
    */
    disciplinaId: number;
    /**
     * @type integer, int64
    */
    autorId: number;
    /**
     * @type string, date-time
    */
    dataExpiracao: string;
    /**
     * @type number, double
    */
    valorTotal: number;
    /**
     * @type boolean | undefined
    */
    permitirArquivoResposta?: boolean;
};