/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const createPerfilAcessibilidadeDTOTipoDeficienciaEnum = {
    "NENHUMA": "NENHUMA",
    "VISUAL": "VISUAL",
    "AUDITIVA": "AUDITIVA",
    "MOTORA": "MOTORA",
    "COGNITIVA": "COGNITIVA",
    "OUTRA": "OUTRA"
} as const;

export type CreatePerfilAcessibilidadeDTOTipoDeficienciaEnumKey = (typeof createPerfilAcessibilidadeDTOTipoDeficienciaEnum)[keyof typeof createPerfilAcessibilidadeDTOTipoDeficienciaEnum];

export type CreatePerfilAcessibilidadeDTO = {
    /**
     * @type string
    */
    tipoDeficiencia: CreatePerfilAcessibilidadeDTOTipoDeficienciaEnumKey;
    /**
     * @type boolean
    */
    usaLeitorDeTela: boolean;
    /**
     * @type boolean
    */
    modoAltoContraste: boolean;
    /**
     * @type integer, int32
    */
    tamanhoFonte: number;
    /**
     * @type boolean
    */
    talkBack: boolean;
};