/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateRespostaDTO = {
    /**
     * @type integer, int64
    */
    tarefaId: number;
    /**
     * @type integer, int64
    */
    estudanteId: number;
    /**
     * @type string | undefined
    */
    caminhoAnexo?: string;
    /**
     * @type string | undefined
    */
    conteudoTexto?: string;
};