/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateDisciplinaDTO } from "./CreateDisciplinaDTO.ts";
import type { DisciplinaSummaryDTO } from "./DisciplinaSummaryDTO.ts";

/**
 * @description Disciplina criada com sucesso
*/
export type CreateDisciplina201 = DisciplinaSummaryDTO;

/**
 * @description Instituição de Ensino ou Educador não encontrados
*/
export type CreateDisciplina404 = DisciplinaSummaryDTO;

/**
 * @description Dados inválidos ou conflitantes
*/
export type CreateDisciplina409 = DisciplinaSummaryDTO;

export type CreateDisciplinaMutationRequest = CreateDisciplinaDTO;

export type CreateDisciplinaMutationResponse = CreateDisciplina201;

export type CreateDisciplinaMutation = {
    Response: CreateDisciplina201;
    Request: CreateDisciplinaMutationRequest;
    Errors: CreateDisciplina404 | CreateDisciplina409;
};