/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateComentarioDTO = {
    /**
     * @minLength 0
     * @maxLength 280
     * @type string
    */
    conteudo: string;
};