/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateInstituicaoDTO } from "./CreateInstituicaoDTO.ts";
import type { InstituicaoDetailsDTO } from "./InstituicaoDetailsDTO.ts";

/**
 * @description Instituição de Ensino criada com sucesso
*/
export type CreateInstituicao201 = InstituicaoDetailsDTO;

/**
 * @description Email ou CNPJ já cadastrados
*/
export type CreateInstituicao409 = InstituicaoDetailsDTO;

/**
 * @description Dados inválidos ou ausentes
*/
export type CreateInstituicao422 = InstituicaoDetailsDTO;

export type CreateInstituicaoMutationRequest = CreateInstituicaoDTO;

export type CreateInstituicaoMutationResponse = CreateInstituicao201;

export type CreateInstituicaoMutation = {
    Response: CreateInstituicao201;
    Request: CreateInstituicaoMutationRequest;
    Errors: CreateInstituicao409 | CreateInstituicao422;
};