/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateTarefaDTO } from "./CreateTarefaDTO.ts";
import type { SummaryTarefaDTO } from "./SummaryTarefaDTO.ts";

/**
 * @description OK
*/
export type CreateTarefa200 = SummaryTarefaDTO;

export type CreateTarefaMutationRequest = CreateTarefaDTO;

export type CreateTarefaMutationResponse = CreateTarefa200;

export type CreateTarefaMutation = {
    Response: CreateTarefa200;
    Request: CreateTarefaMutationRequest;
    Errors: any;
};