/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreatePublicacaoDTO } from "./CreatePublicacaoDTO.ts";
import type { PublicacaoSummaryDTO } from "./PublicacaoSummaryDTO.ts";

/**
 * @description Publicação criada com sucesso
*/
export type CreatePublicacao201 = PublicacaoSummaryDTO;

/**
 * @description O Educador que está realizando a Publicação não é o responsável pela Disciplina
*/
export type CreatePublicacao403 = PublicacaoSummaryDTO;

/**
 * @description Disciplina não encontrada
*/
export type CreatePublicacao404 = PublicacaoSummaryDTO;

/**
 * @description Dados inválidos ou conflitantes
*/
export type CreatePublicacao409 = PublicacaoSummaryDTO;

export type CreatePublicacaoMutationRequest = CreatePublicacaoDTO;

export type CreatePublicacaoMutationResponse = CreatePublicacao201;

export type CreatePublicacaoMutation = {
    Response: CreatePublicacao201;
    Request: CreatePublicacaoMutationRequest;
    Errors: CreatePublicacao403 | CreatePublicacao404 | CreatePublicacao409;
};