/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateRespostaMultipartDTO = {
    /**
     * @type integer | undefined, int64
    */
    tarefaId?: number;
    /**
     * @type string | undefined
    */
    conteudoTexto?: string;
    /**
     * @type string | undefined, binary
    */
    arquivo?: Blob;
};