/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreatePublicacaoDTO = {
    /**
     * @minLength 0
     * @maxLength 120
     * @type string
    */
    titulo: string;
    /**
     * @minLength 0
     * @maxLength 5000
     * @type string
    */
    conteudo: string;
    /**
     * @type string | undefined
    */
    caminhoAnexo?: string;
    /**
     * @type integer, int64
    */
    disciplinaId: number;
    /**
     * @type integer, int64
    */
    educadorId: number;
};