/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateDisciplinaDTO = {
    /**
     * @minLength 1
     * @type string
    */
    nome: string;
    /**
     * @minLength 1
     * @type string
    */
    descricao: string;
    /**
     * @type integer, int64
    */
    idEducadorResponsavel: number;
    /**
     * @type integer, int64
    */
    idInstituicao: number;
};