/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateRespostaMultipartDTO } from "./CreateRespostaMultipartDTO.ts";
import type { RespostaDTO } from "./RespostaDTO.ts";

/**
 * @description OK
*/
export type CriarRespostaComUpload200 = RespostaDTO;

export type CriarRespostaComUploadMutationRequest = CreateRespostaMultipartDTO;

export type CriarRespostaComUploadMutationResponse = CriarRespostaComUpload200;

export type CriarRespostaComUploadMutation = {
    Response: CriarRespostaComUpload200;
    Request: CriarRespostaComUploadMutationRequest;
    Errors: any;
};