/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeletarArquivoPathParams = {
    /**
     * @type integer, int64
    */
    arquivoId: number;
};

export type DeletarArquivoQueryParams = {
    /**
     * @type integer, int64
    */
    usuarioId: number;
    /**
     * @default false
     * @type boolean | undefined
    */
    isEducador?: boolean;
};

/**
 * @description OK
*/
export type DeletarArquivo200 = any;

export type DeletarArquivoMutationResponse = DeletarArquivo200;

export type DeletarArquivoMutation = {
    Response: DeletarArquivo200;
    PathParams: DeletarArquivoPathParams;
    QueryParams: DeletarArquivoQueryParams;
    Errors: any;
};