/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeletePublicacaoPathParams = {
    /**
     * @type integer, int64
    */
    publicacaoId: number;
};

/**
 * @description Publicação deletada com sucesso
*/
export type DeletePublicacao204 = object;

/**
 * @description Disciplina não encontrada
*/
export type DeletePublicacao404 = object;

export type DeletePublicacaoMutationResponse = DeletePublicacao204;

export type DeletePublicacaoMutation = {
    Response: DeletePublicacao204;
    PathParams: DeletePublicacaoPathParams;
    Errors: DeletePublicacao404;
};