/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DisciplinaSummaryDTO = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type string | undefined
    */
    nome?: string;
    /**
     * @type string | undefined
    */
    descricao?: string;
    /**
     * @type string | undefined
    */
    educadorResponsavel?: string;
    /**
     * @type string | undefined
    */
    instituicao?: string;
    /**
     * @type integer | undefined, int32
    */
    alunos?: number;
};