/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DownloadArquivoPathParams = {
    /**
     * @type integer, int64
    */
    arquivoId: number;
};

/**
 * @description OK
*/
export type DownloadArquivo200 = Blob;

export type DownloadArquivoQueryResponse = DownloadArquivo200;

export type DownloadArquivoQuery = {
    Response: DownloadArquivo200;
    PathParams: DownloadArquivoPathParams;
    Errors: any;
};