/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FormacaoResponseDTO } from "./FormacaoResponseDTO.ts";

export type EducadorResponseDTO = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type string | undefined
    */
    nome?: string;
    /**
     * @type string | undefined
    */
    email?: string;
    /**
     * @type string | undefined
    */
    matricula?: string;
    /**
     * @type string | undefined
    */
    titulo?: string;
    /**
     * @type array | undefined
    */
    formacaoAcademica?: FormacaoResponseDTO[];
};