/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type Endereco = {
    /**
     * @minLength 1
     * @type string
    */
    logradouro: string;
    /**
     * @minLength 1
     * @type string
    */
    numero: string;
    /**
     * @minLength 1
     * @type string
    */
    bairro: string;
    /**
     * @minLength 1
     * @type string
    */
    cidade: string;
    /**
     * @minLength 1
     * @type string
    */
    estado: string;
    /**
     * @minLength 1
     * @type string
    */
    cep: string;
};