/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateRespostaDTO } from "./CreateRespostaDTO.ts";
import type { RespostaDTO } from "./RespostaDTO.ts";

/**
 * @description OK
*/
export type EnviarResposta200 = RespostaDTO;

export type EnviarRespostaMutationRequest = CreateRespostaDTO;

export type EnviarRespostaMutationResponse = EnviarResposta200;

export type EnviarRespostaMutation = {
    Response: EnviarResposta200;
    Request: EnviarRespostaMutationRequest;
    Errors: any;
};