/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const estudanteUpdateDTOGeneroEnum = {
    "MASCULINO": "MASCULINO",
    "FEMININO": "FEMININO",
    "OUTRO": "OUTRO",
    "NAO_INFORMAR": "NAO_INFORMAR"
} as const;

export type EstudanteUpdateDTOGeneroEnumKey = (typeof estudanteUpdateDTOGeneroEnum)[keyof typeof estudanteUpdateDTOGeneroEnum];

export type EstudanteUpdateDTO = {
    /**
     * @type string | undefined
    */
    nome?: string;
    /**
     * @type string | undefined
    */
    telefone?: string;
    /**
     * @type string | undefined
    */
    genero?: EstudanteUpdateDTOGeneroEnumKey;
    /**
     * @type string | undefined, date
    */
    dataNascimento?: string;
};