/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { InstituicaoDetailsDTO } from "./InstituicaoDetailsDTO.ts";

export const estudanteResponseDTOPeriodoEnum = {
    "MATUTINO": "MATUTINO",
    "VESPERTINO": "VESPERTINO",
    "NOTURNO": "NOTURNO"
} as const;

export type EstudanteResponseDTOPeriodoEnumKey = (typeof estudanteResponseDTOPeriodoEnum)[keyof typeof estudanteResponseDTOPeriodoEnum];

export const estudanteResponseDTOAnoEscolarEnum = {
    "PRIMEIRO_ANO": "PRIMEIRO_ANO",
    "SEGUNDO_ANO": "SEGUNDO_ANO",
    "TERCEIRO_ANO": "TERCEIRO_ANO",
    "QUARTO_ANO": "QUARTO_ANO",
    "QUINTO_ANO": "QUINTO_ANO",
    "SEXTO_ANO": "SEXTO_ANO",
    "SETIMO_ANO": "SETIMO_ANO",
    "OITAVO_ANO": "OITAVO_ANO",
    "NONO_ANO": "NONO_ANO",
    "PRIMEIO_ANO_EM": "PRIMEIO_ANO_EM",
    "SEGUNDO_ANO_EM": "SEGUNDO_ANO_EM",
    "TERCEIRO_ANO_EM": "TERCEIRO_ANO_EM"
} as const;

export type EstudanteResponseDTOAnoEscolarEnumKey = (typeof estudanteResponseDTOAnoEscolarEnum)[keyof typeof estudanteResponseDTOAnoEscolarEnum];

export const estudanteResponseDTOGeneroEnum = {
    "MASCULINO": "MASCULINO",
    "FEMININO": "FEMININO",
    "OUTRO": "OUTRO",
    "NAO_INFORMAR": "NAO_INFORMAR"
} as const;

export type EstudanteResponseDTOGeneroEnumKey = (typeof estudanteResponseDTOGeneroEnum)[keyof typeof estudanteResponseDTOGeneroEnum];

export type EstudanteResponseDTO = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type string | undefined
    */
    nome?: string;
    /**
     * @type string | undefined
    */
    cpf?: string;
    /**
     * @type string | undefined
    */
    email?: string;
    /**
     * @type string | undefined
    */
    matricula?: string;
    /**
     * @type string | undefined
    */
    periodo?: EstudanteResponseDTOPeriodoEnumKey;
    /**
     * @type string | undefined
    */
    anoEscolar?: EstudanteResponseDTOAnoEscolarEnumKey;
    /**
     * @type string | undefined
    */
    telefone?: string;
    /**
     * @type string | undefined
    */
    genero?: EstudanteResponseDTOGeneroEnumKey;
    /**
     * @type string | undefined, date
    */
    dataNascimento?: string;
    /**
     * @type object | undefined
    */
    instituicao?: InstituicaoDetailsDTO;
};