/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const estudanteListDTOAnoEscolarEnum = {
    "PRIMEIRO_ANO": "PRIMEIRO_ANO",
    "SEGUNDO_ANO": "SEGUNDO_ANO",
    "TERCEIRO_ANO": "TERCEIRO_ANO",
    "QUARTO_ANO": "QUARTO_ANO",
    "QUINTO_ANO": "QUINTO_ANO",
    "SEXTO_ANO": "SEXTO_ANO",
    "SETIMO_ANO": "SETIMO_ANO",
    "OITAVO_ANO": "OITAVO_ANO",
    "NONO_ANO": "NONO_ANO",
    "PRIMEIO_ANO_EM": "PRIMEIO_ANO_EM",
    "SEGUNDO_ANO_EM": "SEGUNDO_ANO_EM",
    "TERCEIRO_ANO_EM": "TERCEIRO_ANO_EM"
} as const;

export type EstudanteListDTOAnoEscolarEnumKey = (typeof estudanteListDTOAnoEscolarEnum)[keyof typeof estudanteListDTOAnoEscolarEnum];

export const estudanteListDTOPeriodoEnum = {
    "MATUTINO": "MATUTINO",
    "VESPERTINO": "VESPERTINO",
    "NOTURNO": "NOTURNO"
} as const;

export type EstudanteListDTOPeriodoEnumKey = (typeof estudanteListDTOPeriodoEnum)[keyof typeof estudanteListDTOPeriodoEnum];

export type EstudanteListDTO = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type string | undefined
    */
    nome?: string;
    /**
     * @type string | undefined
    */
    email?: string;
    /**
     * @type string | undefined
    */
    matricula?: string;
    /**
     * @type string | undefined
    */
    anoEscolar?: EstudanteListDTOAnoEscolarEnumKey;
    /**
     * @type string | undefined
    */
    periodo?: EstudanteListDTOPeriodoEnumKey;
};