/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const estudanteSummaryDTOPeriodoEnum = {
    "MATUTINO": "MATUTINO",
    "VESPERTINO": "VESPERTINO",
    "NOTURNO": "NOTURNO"
} as const;

export type EstudanteSummaryDTOPeriodoEnumKey = (typeof estudanteSummaryDTOPeriodoEnum)[keyof typeof estudanteSummaryDTOPeriodoEnum];

export const estudanteSummaryDTOAnoEscolarEnum = {
    "PRIMEIRO_ANO": "PRIMEIRO_ANO",
    "SEGUNDO_ANO": "SEGUNDO_ANO",
    "TERCEIRO_ANO": "TERCEIRO_ANO",
    "QUARTO_ANO": "QUARTO_ANO",
    "QUINTO_ANO": "QUINTO_ANO",
    "SEXTO_ANO": "SEXTO_ANO",
    "SETIMO_ANO": "SETIMO_ANO",
    "OITAVO_ANO": "OITAVO_ANO",
    "NONO_ANO": "NONO_ANO",
    "PRIMEIO_ANO_EM": "PRIMEIO_ANO_EM",
    "SEGUNDO_ANO_EM": "SEGUNDO_ANO_EM",
    "TERCEIRO_ANO_EM": "TERCEIRO_ANO_EM"
} as const;

export type EstudanteSummaryDTOAnoEscolarEnumKey = (typeof estudanteSummaryDTOAnoEscolarEnum)[keyof typeof estudanteSummaryDTOAnoEscolarEnum];

export const estudanteSummaryDTOGeneroEnum = {
    "MASCULINO": "MASCULINO",
    "FEMININO": "FEMININO",
    "OUTRO": "OUTRO",
    "NAO_INFORMAR": "NAO_INFORMAR"
} as const;

export type EstudanteSummaryDTOGeneroEnumKey = (typeof estudanteSummaryDTOGeneroEnum)[keyof typeof estudanteSummaryDTOGeneroEnum];

export type EstudanteSummaryDTO = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type string | undefined
    */
    nome?: string;
    /**
     * @type string | undefined
    */
    cpf?: string;
    /**
     * @type string | undefined
    */
    email?: string;
    /**
     * @type string | undefined
    */
    matricula?: string;
    /**
     * @type string | undefined
    */
    periodo?: EstudanteSummaryDTOPeriodoEnumKey;
    /**
     * @type string | undefined
    */
    anoEscolar?: EstudanteSummaryDTOAnoEscolarEnumKey;
    /**
     * @type string | undefined
    */
    telefone?: string;
    /**
     * @type string | undefined
    */
    genero?: EstudanteSummaryDTOGeneroEnumKey;
    /**
     * @type string | undefined, date
    */
    dataNascimento?: string;
};