/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestResetDTO } from "./RequestResetDTO.ts";

/**
 * @description Caso o e-mail existir, será enviado um link com token de redefinição
*/
export type ForgotPassword200 = object;

export type ForgotPasswordMutationRequest = RequestResetDTO;

export type ForgotPasswordMutationResponse = ForgotPassword200;

export type ForgotPasswordMutation = {
    Response: ForgotPassword200;
    Request: ForgotPasswordMutationRequest;
    Errors: any;
};