/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FormacaoResponseDTO } from "./FormacaoResponseDTO.ts";

export type FormacaoListResponseDTO = {
    /**
     * @type array | undefined
    */
    formacoes?: FormacaoResponseDTO[];
    /**
     * @type integer | undefined, int32
    */
    totalRegistros?: number;
};