/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type FormacaoRequestDTO = {
    /**
     * @type string | undefined
    */
    titulo?: string;
    /**
     * @type string | undefined
    */
    instituicao?: string;
    /**
     * @type string | undefined, date
    */
    dataInicio?: string;
    /**
     * @type string | undefined, date
    */
    dataConclusao?: string;
    /**
     * @type string | undefined
    */
    descricao?: string;
};