/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { InstituicaoDetailsDTO } from "./InstituicaoDetailsDTO.ts";

export const gestorDetailsDTOGeneroEnum = {
    "MASCULINO": "MASCULINO",
    "FEMININO": "FEMININO",
    "OUTRO": "OUTRO",
    "NAO_INFORMAR": "NAO_INFORMAR"
} as const;

export type GestorDetailsDTOGeneroEnumKey = (typeof gestorDetailsDTOGeneroEnum)[keyof typeof gestorDetailsDTOGeneroEnum];

export type GestorDetailsDTO = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type string | undefined
    */
    nome?: string;
    /**
     * @type string | undefined
    */
    cpf?: string;
    /**
     * @type string | undefined
    */
    email?: string;
    /**
     * @type string | undefined
    */
    telefone?: string;
    /**
     * @type string | undefined
    */
    genero?: GestorDetailsDTOGeneroEnumKey;
    /**
     * @type string | undefined, date
    */
    dataNascimento?: string;
    /**
     * @type string | undefined
    */
    cargo?: string;
    /**
     * @type object | undefined
    */
    instituicao?: InstituicaoDetailsDTO;
};