/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UsuarioDetailsDTO } from "./UsuarioDetailsDTO.ts";

/**
 * @description Lista de usuários retornada com sucesso
*/
export type GetAllUsuarios200 = UsuarioDetailsDTO[];

/**
 * @description Nenhum usuário encontrado
*/
export type GetAllUsuarios204 = UsuarioDetailsDTO[];

export type GetAllUsuariosQueryResponse = (GetAllUsuarios200 | GetAllUsuarios204);

export type GetAllUsuariosQuery = {
    Response: GetAllUsuarios200 | GetAllUsuarios204;
    Errors: any;
};