/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ComentarioSummaryDTO } from "./ComentarioSummaryDTO.ts";

export type GetComentarioByIdPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description Comentário obtido com sucesso
*/
export type GetComentarioById200 = ComentarioSummaryDTO;

/**
 * @description Comentário não encontrado
*/
export type GetComentarioById404 = ComentarioSummaryDTO;

export type GetComentarioByIdQueryResponse = GetComentarioById200;

export type GetComentarioByIdQuery = {
    Response: GetComentarioById200;
    PathParams: GetComentarioByIdPathParams;
    Errors: GetComentarioById404;
};