/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DisciplinaSummaryDTO } from "./DisciplinaSummaryDTO.ts";

export type GetDisciplinaByIdPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description Disciplina obtida com sucesso
*/
export type GetDisciplinaById200 = DisciplinaSummaryDTO;

/**
 * @description Disciplina não encontrada
*/
export type GetDisciplinaById404 = DisciplinaSummaryDTO;

export type GetDisciplinaByIdQueryResponse = GetDisciplinaById200;

export type GetDisciplinaByIdQuery = {
    Response: GetDisciplinaById200;
    PathParams: GetDisciplinaByIdPathParams;
    Errors: GetDisciplinaById404;
};