/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DisciplinaSummaryDTO } from "./DisciplinaSummaryDTO.ts";

export type GetDisciplinasByEstudanteQueryParams = {
    /**
     * @type integer, int64
    */
    estudanteId: number;
};

/**
 * @description Disciplinas obtidas com sucesso
*/
export type GetDisciplinasByEstudante200 = DisciplinaSummaryDTO[];

/**
 * @description O estudante não está matriculado em nenhuma disciplina
*/
export type GetDisciplinasByEstudante204 = DisciplinaSummaryDTO[];

/**
 * @description Estudante não encontrado
*/
export type GetDisciplinasByEstudante404 = DisciplinaSummaryDTO[];

export type GetDisciplinasByEstudanteQueryResponse = (GetDisciplinasByEstudante200 | GetDisciplinasByEstudante204);

export type GetDisciplinasByEstudanteQuery = {
    Response: GetDisciplinasByEstudante200 | GetDisciplinasByEstudante204;
    QueryParams: GetDisciplinasByEstudanteQueryParams;
    Errors: GetDisciplinasByEstudante404;
};