/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { EducadorResponseDTO } from "./EducadorResponseDTO.ts";

export type GetEducadorPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description OK
*/
export type GetEducador200 = EducadorResponseDTO;

export type GetEducadorQueryResponse = GetEducador200;

export type GetEducadorQuery = {
    Response: GetEducador200;
    PathParams: GetEducadorPathParams;
    Errors: any;
};