/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { EstudanteSummaryDTO } from "./EstudanteSummaryDTO.ts";

export type GetEstudantesFromDisciplinaPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description Estudantes obtidos com sucesso
*/
export type GetEstudantesFromDisciplina200 = EstudanteSummaryDTO[];

/**
 * @description Nenhum Estudante está matriculado nesta Disciplina
*/
export type GetEstudantesFromDisciplina204 = EstudanteSummaryDTO[];

/**
 * @description Disciplina não encontrada
*/
export type GetEstudantesFromDisciplina404 = EstudanteSummaryDTO[];

export type GetEstudantesFromDisciplinaQueryResponse = (GetEstudantesFromDisciplina200 | GetEstudantesFromDisciplina204);

export type GetEstudantesFromDisciplinaQuery = {
    Response: GetEstudantesFromDisciplina200 | GetEstudantesFromDisciplina204;
    PathParams: GetEstudantesFromDisciplinaPathParams;
    Errors: GetEstudantesFromDisciplina404;
};