/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GestorDetailsDTO } from "./GestorDetailsDTO.ts";

export type GetGestorByIdPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description Gestor obtido com sucesso
*/
export type GetGestorById200 = GestorDetailsDTO;

/**
 * @description Ocorreu erro durante o processamento da requsição
*/
export type GetGestorById400 = GestorDetailsDTO;

/**
 * @description Não foi possível obter o Gestor com o ID especificado
*/
export type GetGestorById404 = GestorDetailsDTO;

export type GetGestorByIdQueryResponse = GetGestorById200;

export type GetGestorByIdQuery = {
    Response: GetGestorById200;
    PathParams: GetGestorByIdPathParams;
    Errors: GetGestorById400 | GetGestorById404;
};