/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { InstituicaoCnpjDTO } from "./InstituicaoCnpjDTO.ts";
import type { InstituicaoDetailsDTO } from "./InstituicaoDetailsDTO.ts";

/**
 * @description Instituição de Ensino encontrada com sucesso
*/
export type GetInstituicaoByCnpj200 = InstituicaoDetailsDTO;

/**
 * @description Instituição de Ensino não encontrada
*/
export type GetInstituicaoByCnpj404 = InstituicaoDetailsDTO;

export type GetInstituicaoByCnpjQueryRequest = InstituicaoCnpjDTO;

export type GetInstituicaoByCnpjQueryResponse = GetInstituicaoByCnpj200;

export type GetInstituicaoByCnpjQuery = {
    Response: GetInstituicaoByCnpj200;
    Request: GetInstituicaoByCnpjQueryRequest;
    Errors: GetInstituicaoByCnpj404;
};