/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { InstituicaoDetailsDTO } from "./InstituicaoDetailsDTO.ts";
import type { InstituicaoEmailDTO } from "./InstituicaoEmailDTO.ts";

/**
 * @description OK
*/
export type GetInstituicaoByEmail200 = InstituicaoDetailsDTO;

export type GetInstituicaoByEmailQueryRequest = InstituicaoEmailDTO;

export type GetInstituicaoByEmailQueryResponse = GetInstituicaoByEmail200;

export type GetInstituicaoByEmailQuery = {
    Response: GetInstituicaoByEmail200;
    Request: GetInstituicaoByEmailQueryRequest;
    Errors: any;
};