/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { InstituicaoDetailsDTO } from "./InstituicaoDetailsDTO.ts";

export type GetInstituicaoByIdPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description Instituição de Ensino encontrada com sucesso
*/
export type GetInstituicaoById200 = InstituicaoDetailsDTO;

/**
 * @description Instituição de Ensino não encontrada
*/
export type GetInstituicaoById404 = InstituicaoDetailsDTO;

export type GetInstituicaoByIdQueryResponse = GetInstituicaoById200;

export type GetInstituicaoByIdQuery = {
    Response: GetInstituicaoById200;
    PathParams: GetInstituicaoByIdPathParams;
    Errors: GetInstituicaoById404;
};