/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PublicacaoDetailsDTO } from "./PublicacaoDetailsDTO.ts";

export type GetPublicacaoPathParams = {
    /**
     * @type integer, int64
    */
    publicacaoId: number;
};

/**
 * @description Publicação obtida com sucesso
*/
export type GetPublicacao200 = PublicacaoDetailsDTO;

/**
 * @description Publicação não encontrada
*/
export type GetPublicacao404 = PublicacaoDetailsDTO;

export type GetPublicacaoQueryResponse = GetPublicacao200;

export type GetPublicacaoQuery = {
    Response: GetPublicacao200;
    PathParams: GetPublicacaoPathParams;
    Errors: GetPublicacao404;
};