/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetPerfilByEstudanteIdPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description Perfil de Acessibilidade obtido com sucesso
*/
export type GetPerfilByEstudanteId200 = object;

/**
 * @description Perfil de Acessibilidade ou Estudante não encontrado
*/
export type GetPerfilByEstudanteId404 = object;

export type GetPerfilByEstudanteIdQueryResponse = GetPerfilByEstudanteId200;

export type GetPerfilByEstudanteIdQuery = {
    Response: GetPerfilByEstudanteId200;
    PathParams: GetPerfilByEstudanteIdPathParams;
    Errors: GetPerfilByEstudanteId404;
};