/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetPerfilByIdPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description Perfil de Acessibilidade obtido com sucesso
*/
export type GetPerfilById200 = object;

/**
 * @description Perfil de Acessibilidade não encontrado
*/
export type GetPerfilById404 = object;

export type GetPerfilByIdQueryResponse = GetPerfilById200;

export type GetPerfilByIdQuery = {
    Response: GetPerfilById200;
    PathParams: GetPerfilByIdPathParams;
    Errors: GetPerfilById404;
};