/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PublicacaoDetailsDTO } from "./PublicacaoDetailsDTO.ts";

export type GetPublicacoesQueryParams = {
    /**
     * @type integer, int64
    */
    discplinaId: number;
};

/**
 * @description Publicações listadas com sucesso
*/
export type GetPublicacoes200 = PublicacaoDetailsDTO[];

/**
 * @description Não há Publicações cadastradas nesta Disciplina
*/
export type GetPublicacoes204 = PublicacaoDetailsDTO[];

/**
 * @description Disciplina não encontrada
*/
export type GetPublicacoes404 = PublicacaoDetailsDTO[];

export type GetPublicacoesQueryResponse = (GetPublicacoes200 | GetPublicacoes204);

export type GetPublicacoesQuery = {
    Response: GetPublicacoes200 | GetPublicacoes204;
    QueryParams: GetPublicacoesQueryParams;
    Errors: GetPublicacoes404;
};