/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SummaryTarefaDTO } from "./SummaryTarefaDTO.ts";

export type GetTarefasByDisciplinaPathParams = {
    /**
     * @type integer, int64
    */
    disciplinaId: number;
};

/**
 * @description OK
*/
export type GetTarefasByDisciplina200 = SummaryTarefaDTO[];

export type GetTarefasByDisciplinaQueryResponse = GetTarefasByDisciplina200;

export type GetTarefasByDisciplinaQuery = {
    Response: GetTarefasByDisciplina200;
    PathParams: GetTarefasByDisciplinaPathParams;
    Errors: any;
};