/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TarefaDetailsDTO } from "./TarefaDetailsDTO.ts";

export type GetTarefaByIdPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description OK
*/
export type GetTarefaById200 = TarefaDetailsDTO;

export type GetTarefaByIdQueryResponse = GetTarefaById200;

export type GetTarefaByIdQuery = {
    Response: GetTarefaById200;
    PathParams: GetTarefaByIdPathParams;
    Errors: any;
};