/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UsuarioSummaryDTO } from "./UsuarioSummaryDTO.ts";

export type GetUsuariosFromInstituicaoPathParams = {
    /**
     * @type integer, int64
    */
    instituicaoId: number;
};

/**
 * @description Dados listados com sucesso
*/
export type GetUsuariosFromInstituicao200 = UsuarioSummaryDTO[];

/**
 * @description Nenhum usuário para listar
*/
export type GetUsuariosFromInstituicao204 = UsuarioSummaryDTO[];

/**
 * @description Instituição não encontrada
*/
export type GetUsuariosFromInstituicao404 = UsuarioSummaryDTO[];

export type GetUsuariosFromInstituicaoQueryResponse = (GetUsuariosFromInstituicao200 | GetUsuariosFromInstituicao204);

export type GetUsuariosFromInstituicaoQuery = {
    Response: GetUsuariosFromInstituicao200 | GetUsuariosFromInstituicao204;
    PathParams: GetUsuariosFromInstituicaoPathParams;
    Errors: GetUsuariosFromInstituicao404;
};