export type { AddEstudanteToDisciplinaPathParams, AddEstudanteToDisciplinaQueryParams, AddEstudanteToDisciplina200, AddEstudanteToDisciplina404, AddEstudanteToDisciplinaMutationResponse, AddEstudanteToDisciplinaMutation } from "./AddEstudanteToDisciplina.ts";
export type { AddUsuarioToInstituicaoPathParams, AddUsuarioToInstituicao200, AddUsuarioToInstituicao404, AddUsuarioToInstituicao409, AddUsuarioToInstituicaoMutationResponse, AddUsuarioToInstituicaoMutation } from "./AddUsuarioToInstituicao.ts";
export type { AdicionarFormacaoPathParams, AdicionarFormacao200, AdicionarFormacaoMutationRequest, AdicionarFormacaoMutationResponse, AdicionarFormacaoMutation } from "./AdicionarFormacao.ts";
export type { ArquivoDTO } from "./ArquivoDTO.ts";
export type { AtualizarPathParams, Atualizar200, Atualizar400, Atualizar404, AtualizarMutationRequest, AtualizarMutationResponse, AtualizarMutation } from "./Atualizar.ts";
export type { AtualizarComentarioPathParams, AtualizarComentario200, AtualizarComentario404, AtualizarComentarioMutationRequest, AtualizarComentarioMutationResponse, AtualizarComentarioMutation } from "./AtualizarComentario.ts";
export type { AuthenticationDTO } from "./AuthenticationDTO.ts";
export type { AvaliarRespostaPathParams, AvaliarResposta200, AvaliarRespostaMutationRequest, AvaliarRespostaMutationResponse, AvaliarRespostaMutation } from "./AvaliarResposta.ts";
export type { AvaliarRespostaDTO } from "./AvaliarRespostaDTO.ts";
export type { BuscarPorIdPathParams, BuscarPorId200, BuscarPorId404, BuscarPorIdQueryResponse, BuscarPorIdQuery } from "./BuscarPorId.ts";
export type { ComentarioSummaryDTO } from "./ComentarioSummaryDTO.ts";
export type { CreateComentarioDTO } from "./CreateComentarioDTO.ts";
export type { CreateDisciplina201, CreateDisciplina404, CreateDisciplina409, CreateDisciplinaMutationRequest, CreateDisciplinaMutationResponse, CreateDisciplinaMutation } from "./CreateDisciplina.ts";
export type { CreateDisciplinaDTO } from "./CreateDisciplinaDTO.ts";
export type { CreateInstituicao201, CreateInstituicao409, CreateInstituicao422, CreateInstituicaoMutationRequest, CreateInstituicaoMutationResponse, CreateInstituicaoMutation } from "./CreateInstituicao.ts";
export type { CreateInstituicaoDTO } from "./CreateInstituicaoDTO.ts";
export type { CreatePerfilAcessibilidadeQueryParams, CreatePerfilAcessibilidade201, CreatePerfilAcessibilidade400, CreatePerfilAcessibilidade404, CreatePerfilAcessibilidadeMutationRequest, CreatePerfilAcessibilidadeMutationResponse, CreatePerfilAcessibilidadeMutation } from "./CreatePerfilAcessibilidade.ts";
export type { CreatePerfilAcessibilidadeDTOTipoDeficienciaEnumKey, CreatePerfilAcessibilidadeDTO } from "./CreatePerfilAcessibilidadeDTO.ts";
export type { CreatePublicacao201, CreatePublicacao403, CreatePublicacao404, CreatePublicacao409, CreatePublicacaoMutationRequest, CreatePublicacaoMutationResponse, CreatePublicacaoMutation } from "./CreatePublicacao.ts";
export type { CreatePublicacaoDTO } from "./CreatePublicacaoDTO.ts";
export type { CreateRespostaDTO } from "./CreateRespostaDTO.ts";
export type { CreateRespostaMultipartDTO } from "./CreateRespostaMultipartDTO.ts";
export type { CreateTarefa200, CreateTarefaMutationRequest, CreateTarefaMutationResponse, CreateTarefaMutation } from "./CreateTarefa.ts";
export type { CreateTarefaDTO } from "./CreateTarefaDTO.ts";
export type { CriarRespostaComUpload200, CriarRespostaComUploadMutationRequest, CriarRespostaComUploadMutationResponse, CriarRespostaComUploadMutation } from "./CriarRespostaComUpload.ts";
export type { DeletarArquivoPathParams, DeletarArquivoQueryParams, DeletarArquivo200, DeletarArquivoMutationResponse, DeletarArquivoMutation } from "./DeletarArquivo.ts";
export type { DeletePublicacaoPathParams, DeletePublicacao204, DeletePublicacao404, DeletePublicacaoMutationResponse, DeletePublicacaoMutation } from "./DeletePublicacao.ts";
export type { DisciplinaSummaryDTO } from "./DisciplinaSummaryDTO.ts";
export type { DownloadArquivoPathParams, DownloadArquivo200, DownloadArquivoQueryResponse, DownloadArquivoQuery } from "./DownloadArquivo.ts";
export type { EducadorResponseDTO } from "./EducadorResponseDTO.ts";
export type { EducadorSummaryDTO } from "./EducadorSummaryDTO.ts";
export type { Endereco } from "./Endereco.ts";
export type { EnviarResposta200, EnviarRespostaMutationRequest, EnviarRespostaMutationResponse, EnviarRespostaMutation } from "./EnviarResposta.ts";
export type { EstudanteListDTOAnoEscolarEnumKey, EstudanteListDTOPeriodoEnumKey, EstudanteListDTO } from "./EstudanteListDTO.ts";
export type { EstudanteResponseDTOPeriodoEnumKey, EstudanteResponseDTOAnoEscolarEnumKey, EstudanteResponseDTOGeneroEnumKey, EstudanteResponseDTO } from "./EstudanteResponseDTO.ts";
export type { EstudanteSummaryDTOPeriodoEnumKey, EstudanteSummaryDTOAnoEscolarEnumKey, EstudanteSummaryDTOGeneroEnumKey, EstudanteSummaryDTO } from "./EstudanteSummaryDTO.ts";
export type { EstudanteUpdateDTOGeneroEnumKey, EstudanteUpdateDTO } from "./EstudanteUpdateDTO.ts";
export type { ForgotPassword200, ForgotPasswordMutationRequest, ForgotPasswordMutationResponse, ForgotPasswordMutation } from "./ForgotPassword.ts";
export type { FormacaoListResponseDTO } from "./FormacaoListResponseDTO.ts";
export type { FormacaoRequestDTO } from "./FormacaoRequestDTO.ts";
export type { FormacaoResponseDTO } from "./FormacaoResponseDTO.ts";
export type { GestorDetailsDTOGeneroEnumKey, GestorDetailsDTO } from "./GestorDetailsDTO.ts";
export type { GestorGetByEmailDTO } from "./GestorGetByEmailDTO.ts";
export type { GetAllUsuarios200, GetAllUsuarios204, GetAllUsuariosQueryResponse, GetAllUsuariosQuery } from "./GetAllUsuarios.ts";
export type { GetComentarioByIdPathParams, GetComentarioById200, GetComentarioById404, GetComentarioByIdQueryResponse, GetComentarioByIdQuery } from "./GetComentarioById.ts";
export type { GetDisciplinaByIdPathParams, GetDisciplinaById200, GetDisciplinaById404, GetDisciplinaByIdQueryResponse, GetDisciplinaByIdQuery } from "./GetDisciplinaById.ts";
export type { GetDisciplinasByEducadorQueryParams, GetDisciplinasByEducador200, GetDisciplinasByEducador204, GetDisciplinasByEducadorQueryResponse, GetDisciplinasByEducadorQuery } from "./GetDisciplinasByEducador.ts";
export type { GetDisciplinasByEstudanteQueryParams, GetDisciplinasByEstudante200, GetDisciplinasByEstudante204, GetDisciplinasByEstudante404, GetDisciplinasByEstudanteQueryResponse, GetDisciplinasByEstudanteQuery } from "./GetDisciplinasByEstudante.ts";
export type { GetDisciplinasByInstituicaoQueryParams, GetDisciplinasByInstituicao200, GetDisciplinasByInstituicao204, GetDisciplinasByInstituicao404, GetDisciplinasByInstituicaoQueryResponse, GetDisciplinasByInstituicaoQuery } from "./GetDisciplinasByInstituicao.ts";
export type { GetEducadorPathParams, GetEducador200, GetEducadorQueryResponse, GetEducadorQuery } from "./GetEducador.ts";
export type { GetEstudantesFromDisciplinaPathParams, GetEstudantesFromDisciplina200, GetEstudantesFromDisciplina204, GetEstudantesFromDisciplina404, GetEstudantesFromDisciplinaQueryResponse, GetEstudantesFromDisciplinaQuery } from "./GetEstudantesFromDisciplina.ts";
export type { GetGestorByEmail200, GetGestorByEmail400, GetGestorByEmail404, GetGestorByEmailQueryRequest, GetGestorByEmailQueryResponse, GetGestorByEmailQuery } from "./GetGestorByEmail.ts";
export type { GetGestorByIdPathParams, GetGestorById200, GetGestorById400, GetGestorById404, GetGestorByIdQueryResponse, GetGestorByIdQuery } from "./GetGestorById.ts";
export type { GetInstituicaoByCnpj200, GetInstituicaoByCnpj404, GetInstituicaoByCnpjQueryRequest, GetInstituicaoByCnpjQueryResponse, GetInstituicaoByCnpjQuery } from "./GetInstituicaoByCnpj.ts";
export type { GetInstituicaoByEmail200, GetInstituicaoByEmailQueryRequest, GetInstituicaoByEmailQueryResponse, GetInstituicaoByEmailQuery } from "./GetInstituicaoByEmail.ts";
export type { GetInstituicaoByIdPathParams, GetInstituicaoById200, GetInstituicaoById404, GetInstituicaoByIdQueryResponse, GetInstituicaoByIdQuery } from "./GetInstituicaoById.ts";
export type { GetInstituicoes200, GetInstituicoes204, GetInstituicoesQueryResponse, GetInstituicoesQuery } from "./GetInstituicoes.ts";
export type { GetPerfilByEstudanteIdPathParams, GetPerfilByEstudanteId200, GetPerfilByEstudanteId404, GetPerfilByEstudanteIdQueryResponse, GetPerfilByEstudanteIdQuery } from "./GetPerfilByEstudanteId.ts";
export type { GetPerfilByIdPathParams, GetPerfilById200, GetPerfilById404, GetPerfilByIdQueryResponse, GetPerfilByIdQuery } from "./GetPerfilById.ts";
export type { GetPublicacaoPathParams, GetPublicacao200, GetPublicacao404, GetPublicacaoQueryResponse, GetPublicacaoQuery } from "./GetPublicacao.ts";
export type { GetPublicacoesQueryParams, GetPublicacoes200, GetPublicacoes204, GetPublicacoes404, GetPublicacoesQueryResponse, GetPublicacoesQuery } from "./GetPublicacoes.ts";
export type { GetTarefaByIdPathParams, GetTarefaById200, GetTarefaByIdQueryResponse, GetTarefaByIdQuery } from "./GetTarefaById.ts";
export type { GetTarefasByDisciplinaPathParams, GetTarefasByDisciplina200, GetTarefasByDisciplinaQueryResponse, GetTarefasByDisciplinaQuery } from "./GetTarefasByDisciplina.ts";
export type { GetUsuarioByIdPathParams, GetUsuarioById200, GetUsuarioById404, GetUsuarioByIdQueryResponse, GetUsuarioByIdQuery } from "./GetUsuarioById.ts";
export type { GetUsuariosFromInstituicaoPathParams, GetUsuariosFromInstituicao200, GetUsuariosFromInstituicao204, GetUsuariosFromInstituicao404, GetUsuariosFromInstituicaoQueryResponse, GetUsuariosFromInstituicaoQuery } from "./GetUsuariosFromInstituicao.ts";
export type { InstituicaoCnpjDTO } from "./InstituicaoCnpjDTO.ts";
export type { InstituicaoDetailsDTO } from "./InstituicaoDetailsDTO.ts";
export type { InstituicaoEmailDTO } from "./InstituicaoEmailDTO.ts";
export type { ListarQueryParamsAnoEscolarEnumKey, ListarQueryParamsPeriodoEnumKey, ListarQueryParams, Listar200, Listar404, ListarQueryResponse, ListarQuery } from "./Listar.ts";
export type { ListarArquivosPathParams, ListarArquivos200, ListarArquivos204, ListarArquivosQueryResponse, ListarArquivosQuery } from "./ListarArquivos.ts";
export type { ListarFormacoesPathParams, ListarFormacoes200, ListarFormacoesQueryResponse, ListarFormacoesQuery } from "./ListarFormacoes.ts";
export type { Login200, Login400, LoginMutationRequest, LoginMutationResponse, LoginMutation } from "./Login.ts";
export type { ObterComentariosDaPublicacaoQueryParams, ObterComentariosDaPublicacao200, ObterComentariosDaPublicacao204, ObterComentariosDaPublicacao404, ObterComentariosDaPublicacaoQueryResponse, ObterComentariosDaPublicacaoQuery } from "./ObterComentariosDaPublicacao.ts";
export type { PasswordResetDTO } from "./PasswordResetDTO.ts";
export type { PublicacaoDetailsDTO } from "./PublicacaoDetailsDTO.ts";
export type { PublicacaoSummaryDTO } from "./PublicacaoSummaryDTO.ts";
export type { Register201, Register400, RegisterMutationRequest, RegisterMutationResponse, RegisterMutation } from "./Register.ts";
export type { RegisterDTOGeneroEnumKey, RegisterDTOUserTypeEnumKey, RegisterDTOPeriodoEnumKey, RegisterDTOAnoEscolarEnumKey, RegisterDTO } from "./RegisterDTO.ts";
export type { RemoveEstudanteToDisciplinaPathParams, RemoveEstudanteToDisciplinaQueryParams, RemoveEstudanteToDisciplina200, RemoveEstudanteToDisciplina404, RemoveEstudanteToDisciplinaMutationResponse, RemoveEstudanteToDisciplinaMutation } from "./RemoveEstudanteToDisciplina.ts";
export type { RemovePerfilAcessibilidadePathParams, RemovePerfilAcessibilidade204, RemovePerfilAcessibilidade404, RemovePerfilAcessibilidadeMutationResponse, RemovePerfilAcessibilidadeMutation } from "./RemovePerfilAcessibilidade.ts";
export type { RemoverPathParams, Remover204, Remover404, RemoverMutationResponse, RemoverMutation } from "./Remover.ts";
export type { RemoverComentarioPathParams, RemoverComentario204, RemoverComentario404, RemoverComentarioMutationResponse, RemoverComentarioMutation } from "./RemoverComentario.ts";
export type { RemoverFormacaoPathParams, RemoverFormacao204, RemoverFormacaoMutationResponse, RemoverFormacaoMutation } from "./RemoverFormacao.ts";
export type { RemoveTarefaPathParams, RemoveTarefa200, RemoveTarefaMutationResponse, RemoveTarefaMutation } from "./RemoveTarefa.ts";
export type { RemoveUsuarioFromInstituicaoPathParams, RemoveUsuarioFromInstituicao200, RemoveUsuarioFromInstituicao404, RemoveUsuarioFromInstituicao409, RemoveUsuarioFromInstituicaoMutationResponse, RemoveUsuarioFromInstituicaoMutation } from "./RemoveUsuarioFromInstituicao.ts";
export type { RequestResetDTO } from "./RequestResetDTO.ts";
export type { ResponderComentarioQueryParams, ResponderComentario200, ResponderComentario404, ResponderComentario409, ResponderComentarioMutationRequest, ResponderComentarioMutationResponse, ResponderComentarioMutation } from "./ResponderComentario.ts";
export type { ResponderPublicacaoQueryParams, ResponderPublicacao201, ResponderPublicacao404, ResponderPublicacao409, ResponderPublicacaoMutationRequest, ResponderPublicacaoMutationResponse, ResponderPublicacaoMutation } from "./ResponderPublicacao.ts";
export type { RespostaAComentarioSummaryDTO } from "./RespostaAComentarioSummaryDTO.ts";
export type { RespostaDTO } from "./RespostaDTO.ts";
export type { SummaryTarefaDTO } from "./SummaryTarefaDTO.ts";
export type { TarefaDetailsDTO } from "./TarefaDetailsDTO.ts";
export type { UpdateComentarioDTO } from "./UpdateComentarioDTO.ts";
export type { UpdateDisciplinaPathParams, UpdateDisciplina200, UpdateDisciplina404, UpdateDisciplina409, UpdateDisciplinaMutationRequest, UpdateDisciplinaMutationResponse, UpdateDisciplinaMutation } from "./UpdateDisciplina.ts";
export type { UpdateDisciplinaDTO } from "./UpdateDisciplinaDTO.ts";
export type { UpdateEducadorPathParams, UpdateEducador200, UpdateEducador404, UpdateEducador409, UpdateEducadorMutationRequest, UpdateEducadorMutationResponse, UpdateEducadorMutation } from "./UpdateEducador.ts";
export type { UpdateEducadorDTOGeneroEnumKey, UpdateEducadorDTO } from "./UpdateEducadorDTO.ts";
export type { UpdateGestorPathParams, UpdateGestor200, UpdateGestor400, UpdateGestor404, UpdateGestorMutationRequest, UpdateGestorMutationResponse, UpdateGestorMutation } from "./UpdateGestor.ts";
export type { UpdateGestorDTOGeneroEnumKey, UpdateGestorDTO } from "./UpdateGestorDTO.ts";
export type { UpdateInstituicaoPathParams, UpdateInstituicao200, UpdateInstituicao404, UpdateInstituicao422, UpdateInstituicaoMutationRequest, UpdateInstituicaoMutationResponse, UpdateInstituicaoMutation } from "./UpdateInstituicao.ts";
export type { UpdateInstituicaoDTO } from "./UpdateInstituicaoDTO.ts";
export type { UpdatePassword200, UpdatePassword400, UpdatePasswordMutationRequest, UpdatePasswordMutationResponse, UpdatePasswordMutation } from "./UpdatePassword.ts";
export type { UpdatePerfilAcessibilidadePathParams, UpdatePerfilAcessibilidade200, UpdatePerfilAcessibilidade400, UpdatePerfilAcessibilidade404, UpdatePerfilAcessibilidadeMutationRequest, UpdatePerfilAcessibilidadeMutationResponse, UpdatePerfilAcessibilidadeMutation } from "./UpdatePerfilAcessibilidade.ts";
export type { UpdatePerfilAcessibilidadeDTOTipoDeficienciaEnumKey, UpdatePerfilAcessibilidadeDTO } from "./UpdatePerfilAcessibilidadeDTO.ts";
export type { UpdatePublicacaoPathParams, UpdatePublicacao200, UpdatePublicacao404, UpdatePublicacao409, UpdatePublicacaoMutationRequest, UpdatePublicacaoMutationResponse, UpdatePublicacaoMutation } from "./UpdatePublicacao.ts";
export type { UpdatePublicacaoDTO } from "./UpdatePublicacaoDTO.ts";
export type { UpdateTarefaPathParams, UpdateTarefa200, UpdateTarefaMutationRequest, UpdateTarefaMutationResponse, UpdateTarefaMutation } from "./UpdateTarefa.ts";
export type { UpdateTarefaDTO } from "./UpdateTarefaDTO.ts";
export type { UploadArquivoPathParams, UploadArquivoQueryParams, UploadArquivo201, UploadArquivo400, UploadArquivo404, UploadArquivoMutationRequest, UploadArquivoMutationResponse, UploadArquivoMutation } from "./UploadArquivo.ts";
export type { UsuarioDetailsDTOGeneroEnumKey, UsuarioDetailsDTORolesEnumKey, UsuarioDetailsDTO } from "./UsuarioDetailsDTO.ts";
export type { UsuarioSummaryDTO } from "./UsuarioSummaryDTO.ts";
export type { ValidateTokenQueryParams, ValidateToken200, ValidateToken400, ValidateTokenMutationResponse, ValidateTokenMutation } from "./ValidateToken.ts";
export { createPerfilAcessibilidadeDTOTipoDeficienciaEnum } from "./CreatePerfilAcessibilidadeDTO.ts";
export { estudanteListDTOAnoEscolarEnum } from "./EstudanteListDTO.ts";
export { estudanteListDTOPeriodoEnum } from "./EstudanteListDTO.ts";
export { estudanteResponseDTOPeriodoEnum } from "./EstudanteResponseDTO.ts";
export { estudanteResponseDTOAnoEscolarEnum } from "./EstudanteResponseDTO.ts";
export { estudanteResponseDTOGeneroEnum } from "./EstudanteResponseDTO.ts";
export { estudanteSummaryDTOPeriodoEnum } from "./EstudanteSummaryDTO.ts";
export { estudanteSummaryDTOAnoEscolarEnum } from "./EstudanteSummaryDTO.ts";
export { estudanteSummaryDTOGeneroEnum } from "./EstudanteSummaryDTO.ts";
export { estudanteUpdateDTOGeneroEnum } from "./EstudanteUpdateDTO.ts";
export { gestorDetailsDTOGeneroEnum } from "./GestorDetailsDTO.ts";
export { listarQueryParamsAnoEscolarEnum } from "./Listar.ts";
export { listarQueryParamsPeriodoEnum } from "./Listar.ts";
export { registerDTOGeneroEnum } from "./RegisterDTO.ts";
export { registerDTOUserTypeEnum } from "./RegisterDTO.ts";
export { registerDTOPeriodoEnum } from "./RegisterDTO.ts";
export { registerDTOAnoEscolarEnum } from "./RegisterDTO.ts";
export { updateEducadorDTOGeneroEnum } from "./UpdateEducadorDTO.ts";
export { updateGestorDTOGeneroEnum } from "./UpdateGestorDTO.ts";
export { updatePerfilAcessibilidadeDTOTipoDeficienciaEnum } from "./UpdatePerfilAcessibilidadeDTO.ts";
export { usuarioDetailsDTOGeneroEnum } from "./UsuarioDetailsDTO.ts";
export { usuarioDetailsDTORolesEnum } from "./UsuarioDetailsDTO.ts";