/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Endereco } from "./Endereco.ts";

export type InstituicaoDetailsDTO = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type string | undefined
    */
    nome?: string;
    /**
     * @type string | undefined
    */
    telefone?: string;
    /**
     * @type string | undefined
    */
    email?: string;
    /**
     * @type string | undefined
    */
    cnpj?: string;
    /**
     * @type object | undefined
    */
    endereco?: Endereco;
};