/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { EstudanteListDTO } from "./EstudanteListDTO.ts";

export const listarQueryParamsAnoEscolarEnum = {
    "PRIMEIRO_ANO": "PRIMEIRO_ANO",
    "SEGUNDO_ANO": "SEGUNDO_ANO",
    "TERCEIRO_ANO": "TERCEIRO_ANO",
    "QUARTO_ANO": "QUARTO_ANO",
    "QUINTO_ANO": "QUINTO_ANO",
    "SEXTO_ANO": "SEXTO_ANO",
    "SETIMO_ANO": "SETIMO_ANO",
    "OITAVO_ANO": "OITAVO_ANO",
    "NONO_ANO": "NONO_ANO",
    "PRIMEIO_ANO_EM": "PRIMEIO_ANO_EM",
    "SEGUNDO_ANO_EM": "SEGUNDO_ANO_EM",
    "TERCEIRO_ANO_EM": "TERCEIRO_ANO_EM"
} as const;

export type ListarQueryParamsAnoEscolarEnumKey = (typeof listarQueryParamsAnoEscolarEnum)[keyof typeof listarQueryParamsAnoEscolarEnum];

export const listarQueryParamsPeriodoEnum = {
    "MATUTINO": "MATUTINO",
    "VESPERTINO": "VESPERTINO",
    "NOTURNO": "NOTURNO"
} as const;

export type ListarQueryParamsPeriodoEnumKey = (typeof listarQueryParamsPeriodoEnum)[keyof typeof listarQueryParamsPeriodoEnum];

export type ListarQueryParams = {
    /**
     * @type string | undefined
    */
    anoEscolar?: ListarQueryParamsAnoEscolarEnumKey;
    /**
     * @type string | undefined
    */
    periodo?: ListarQueryParamsPeriodoEnumKey;
    /**
     * @type string | undefined
    */
    nome?: string;
};

/**
 * @description Lista de estudantes obtida com sucesso
*/
export type Listar200 = EstudanteListDTO[];

/**
 * @description Nenhum estudante encontrado
*/
export type Listar404 = EstudanteListDTO[];

export type ListarQueryResponse = Listar200;

export type ListarQuery = {
    Response: Listar200;
    QueryParams: ListarQueryParams;
    Errors: Listar404;
};