/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ArquivoDTO } from "./ArquivoDTO.ts";

export type ListarArquivosPathParams = {
    /**
     * @type integer, int64
    */
    disciplinaId: number;
};

/**
 * @description Arquivos listados com sucesso
*/
export type ListarArquivos200 = ArquivoDTO[];

/**
 * @description Nenhum arquivo encontrado
*/
export type ListarArquivos204 = ArquivoDTO[];

export type ListarArquivosQueryResponse = (ListarArquivos200 | ListarArquivos204);

export type ListarArquivosQuery = {
    Response: ListarArquivos200 | ListarArquivos204;
    PathParams: ListarArquivosPathParams;
    Errors: any;
};