/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuthenticationDTO } from "./AuthenticationDTO.ts";

/**
 * @description Usuário autenticado com sucesso
*/
export type Login200 = object;

/**
 * @description Requisição tem parâmetros inválidos
*/
export type Login400 = object;

export type LoginMutationRequest = AuthenticationDTO;

export type LoginMutationResponse = Login200;

export type LoginMutation = {
    Response: Login200;
    Request: LoginMutationRequest;
    Errors: Login400;
};