/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ComentarioSummaryDTO } from "./ComentarioSummaryDTO.ts";

export type ObterComentariosDaPublicacaoQueryParams = {
    /**
     * @type integer, int64
    */
    publicacaoId: number;
};

/**
 * @description Comentário obtidos com sucesso
*/
export type ObterComentariosDaPublicacao200 = ComentarioSummaryDTO[];

/**
 * @description Publicação não possui comentários
*/
export type ObterComentariosDaPublicacao204 = ComentarioSummaryDTO[];

/**
 * @description Publicação não encontrada
*/
export type ObterComentariosDaPublicacao404 = ComentarioSummaryDTO[];

export type ObterComentariosDaPublicacaoQueryResponse = (ObterComentariosDaPublicacao200 | ObterComentariosDaPublicacao204);

export type ObterComentariosDaPublicacaoQuery = {
    Response: ObterComentariosDaPublicacao200 | ObterComentariosDaPublicacao204;
    QueryParams: ObterComentariosDaPublicacaoQueryParams;
    Errors: ObterComentariosDaPublicacao404;
};