/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PasswordResetDTO = {
    /**
     * @minLength 1
     * @type string
    */
    token: string;
    /**
     * @minLength 1
     * @type string
    */
    password: string;
};