/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { EducadorSummaryDTO } from "./EducadorSummaryDTO.ts";

export type PublicacaoDetailsDTO = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type string | undefined
    */
    titulo?: string;
    /**
     * @type string | undefined
    */
    conteudo?: string;
    /**
     * @type string | undefined
    */
    caminhoAnexo?: string;
    /**
     * @type string | undefined, date-time
    */
    dataEnvio?: string;
    /**
     * @type object | undefined
    */
    autor?: EducadorSummaryDTO;
};