/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PublicacaoSummaryDTO = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type string | undefined
    */
    titulo?: string;
    /**
     * @type string | undefined, date-time
    */
    dataEnvio?: string;
};