/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const registerDTOGeneroEnum = {
    "MASCULINO": "MASCULINO",
    "FEMININO": "FEMININO",
    "OUTRO": "OUTRO",
    "NAO_INFORMAR": "NAO_INFORMAR"
} as const;

export type RegisterDTOGeneroEnumKey = (typeof registerDTOGeneroEnum)[keyof typeof registerDTOGeneroEnum];

export const registerDTOUserTypeEnum = {
    "ESTUDANTE": "ESTUDANTE",
    "EDUCADOR": "EDUCADOR",
    "GESTOR": "GESTOR"
} as const;

export type RegisterDTOUserTypeEnumKey = (typeof registerDTOUserTypeEnum)[keyof typeof registerDTOUserTypeEnum];

export const registerDTOPeriodoEnum = {
    "MATUTINO": "MATUTINO",
    "VESPERTINO": "VESPERTINO",
    "NOTURNO": "NOTURNO"
} as const;

export type RegisterDTOPeriodoEnumKey = (typeof registerDTOPeriodoEnum)[keyof typeof registerDTOPeriodoEnum];

export const registerDTOAnoEscolarEnum = {
    "PRIMEIRO_ANO": "PRIMEIRO_ANO",
    "SEGUNDO_ANO": "SEGUNDO_ANO",
    "TERCEIRO_ANO": "TERCEIRO_ANO",
    "QUARTO_ANO": "QUARTO_ANO",
    "QUINTO_ANO": "QUINTO_ANO",
    "SEXTO_ANO": "SEXTO_ANO",
    "SETIMO_ANO": "SETIMO_ANO",
    "OITAVO_ANO": "OITAVO_ANO",
    "NONO_ANO": "NONO_ANO",
    "PRIMEIO_ANO_EM": "PRIMEIO_ANO_EM",
    "SEGUNDO_ANO_EM": "SEGUNDO_ANO_EM",
    "TERCEIRO_ANO_EM": "TERCEIRO_ANO_EM"
} as const;

export type RegisterDTOAnoEscolarEnumKey = (typeof registerDTOAnoEscolarEnum)[keyof typeof registerDTOAnoEscolarEnum];

export type RegisterDTO = {
    /**
     * @minLength 1
     * @type string
    */
    nome: string;
    /**
     * @minLength 1
     * @type string
    */
    cpf: string;
    /**
     * @minLength 1
     * @type string
    */
    email: string;
    /**
     * @minLength 1
     * @type string
    */
    telefone: string;
    /**
     * @type string | undefined
    */
    genero?: RegisterDTOGeneroEnumKey;
    /**
     * @type string | undefined, date
    */
    dataNascimento?: string;
    /**
     * @minLength 1
     * @type string
    */
    senha: string;
    /**
     * @type string | undefined
    */
    userType?: RegisterDTOUserTypeEnumKey;
    /**
     * @type string | undefined
    */
    matricula?: string;
    /**
     * @type string | undefined
    */
    titulo?: string;
    /**
     * @type string | undefined
    */
    periodo?: RegisterDTOPeriodoEnumKey;
    /**
     * @type string | undefined
    */
    anoEscolar?: RegisterDTOAnoEscolarEnumKey;
    /**
     * @type string | undefined
    */
    cargo?: string;
    /**
     * @type boolean | undefined
    */
    educadorValido?: boolean;
    /**
     * @type boolean | undefined
    */
    estudanteValido?: boolean;
};