/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RegisterDTO } from "./RegisterDTO.ts";

/**
 * @description Usuário registrado com sucesso
*/
export type Register201 = object;

/**
 * @description Requisição tem parâmetros inválidos
*/
export type Register400 = object;

export type RegisterMutationRequest = RegisterDTO;

export type RegisterMutationResponse = Register201;

export type RegisterMutation = {
    Response: Register201;
    Request: RegisterMutationRequest;
    Errors: Register400;
};