/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UsuarioSummaryDTO } from "./UsuarioSummaryDTO.ts";

export type RemoveUsuarioFromInstituicaoPathParams = {
    /**
     * @type integer, int64
    */
    instituicaoId: number;
    /**
     * @type integer, int64
    */
    usuarioId: number;
};

/**
 * @description Usuário removidos com sucesso
*/
export type RemoveUsuarioFromInstituicao200 = UsuarioSummaryDTO[];

/**
 * @description Instituição ou Usuário não encontrados
*/
export type RemoveUsuarioFromInstituicao404 = UsuarioSummaryDTO[];

/**
 * @description Usuário não está associado a Instituição de Ensino
*/
export type RemoveUsuarioFromInstituicao409 = UsuarioSummaryDTO[];

export type RemoveUsuarioFromInstituicaoMutationResponse = RemoveUsuarioFromInstituicao200;

export type RemoveUsuarioFromInstituicaoMutation = {
    Response: RemoveUsuarioFromInstituicao200;
    PathParams: RemoveUsuarioFromInstituicaoPathParams;
    Errors: RemoveUsuarioFromInstituicao404 | RemoveUsuarioFromInstituicao409;
};