/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { EstudanteSummaryDTO } from "./EstudanteSummaryDTO.ts";

export type RemoveEstudanteToDisciplinaPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

export type RemoveEstudanteToDisciplinaQueryParams = {
    /**
     * @type integer, int64
    */
    estudanteId: number;
};

/**
 * @description Estudante removido com sucesso
*/
export type RemoveEstudanteToDisciplina200 = EstudanteSummaryDTO[];

/**
 * @description Estudante ou Disciplina não encontrados
*/
export type RemoveEstudanteToDisciplina404 = EstudanteSummaryDTO[];

export type RemoveEstudanteToDisciplinaMutationResponse = RemoveEstudanteToDisciplina200;

export type RemoveEstudanteToDisciplinaMutation = {
    Response: RemoveEstudanteToDisciplina200;
    PathParams: RemoveEstudanteToDisciplinaPathParams;
    QueryParams: RemoveEstudanteToDisciplinaQueryParams;
    Errors: RemoveEstudanteToDisciplina404;
};