/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type RemoverPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description Estudante removido com sucesso
*/
export type Remover204 = any;

/**
 * @description Estudante não encontrado
*/
export type Remover404 = any;

export type RemoverMutationResponse = Remover204;

export type RemoverMutation = {
    Response: Remover204;
    PathParams: RemoverPathParams;
    Errors: Remover404;
};