/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type RemovePerfilAcessibilidadePathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description Perfil de Acessibilidade removido com sucesso
*/
export type RemovePerfilAcessibilidade204 = object;

/**
 * @description Perfil de Acessibilidade não encontrado
*/
export type RemovePerfilAcessibilidade404 = object;

export type RemovePerfilAcessibilidadeMutationResponse = RemovePerfilAcessibilidade204;

export type RemovePerfilAcessibilidadeMutation = {
    Response: RemovePerfilAcessibilidade204;
    PathParams: RemovePerfilAcessibilidadePathParams;
    Errors: RemovePerfilAcessibilidade404;
};