/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type RemoverComentarioPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description Comentário removido com sucesso
*/
export type RemoverComentario204 = object;

/**
 * @description Comentário não encontrado
*/
export type RemoverComentario404 = object;

export type RemoverComentarioMutationResponse = RemoverComentario204;

export type RemoverComentarioMutation = {
    Response: RemoverComentario204;
    PathParams: RemoverComentarioPathParams;
    Errors: RemoverComentario404;
};