/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type RemoverFormacaoPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
    /**
     * @type integer, int64
    */
    formacaoId: number;
};

/**
 * @description Formação removida com sucesso
*/
export type RemoverFormacao204 = any;

export type RemoverFormacaoMutationResponse = RemoverFormacao204;

export type RemoverFormacaoMutation = {
    Response: RemoverFormacao204;
    PathParams: RemoverFormacaoPathParams;
    Errors: any;
};