/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ComentarioSummaryDTO } from "./ComentarioSummaryDTO.ts";
import type { CreateComentarioDTO } from "./CreateComentarioDTO.ts";

export type ResponderPublicacaoQueryParams = {
    /**
     * @type integer, int64
    */
    publicacaoId: number;
};

/**
 * @description Comentário criado com sucesso
*/
export type ResponderPublicacao201 = ComentarioSummaryDTO;

/**
 * @description Publicação ou Usuário Autenticado não encontrados
*/
export type ResponderPublicacao404 = ComentarioSummaryDTO;

/**
 * @description Dados inválidos ou conflitantes
*/
export type ResponderPublicacao409 = ComentarioSummaryDTO;

export type ResponderPublicacaoMutationRequest = CreateComentarioDTO;

export type ResponderPublicacaoMutationResponse = ResponderPublicacao201;

export type ResponderPublicacaoMutation = {
    Response: ResponderPublicacao201;
    Request: ResponderPublicacaoMutationRequest;
    QueryParams: ResponderPublicacaoQueryParams;
    Errors: ResponderPublicacao404 | ResponderPublicacao409;
};