/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UsuarioSummaryDTO } from "./UsuarioSummaryDTO.ts";

export type RespostaAComentarioSummaryDTO = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type string | undefined
    */
    conteudo?: string;
    /**
     * @description Sumário de usuários
     * @type object | undefined
    */
    autor?: UsuarioSummaryDTO;
    /**
     * @type string | undefined, date-time
    */
    dataCriacao?: string;
};