/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ArquivoDTO } from "./ArquivoDTO.ts";

export type RespostaDTO = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type string | undefined
    */
    estudanteNome?: string;
    /**
     * @type number | undefined, double
    */
    nota?: number;
    /**
     * @type string | undefined
    */
    comentarioEducador?: string;
    /**
     * @type object | undefined
    */
    arquivo?: ArquivoDTO;
    /**
     * @type string | undefined
    */
    conteudoTexto?: string;
    /**
     * @type string | undefined, date-time
    */
    dataUpload?: string;
};