/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type SummaryTarefaDTO = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type string | undefined
    */
    titulo?: string;
    /**
     * @type string | undefined
    */
    resumoConteudo?: string;
    /**
     * @type string | undefined, date-time
    */
    dataCriacao?: string;
    /**
     * @type string | undefined, date-time
    */
    dataExpiracao?: string;
    /**
     * @type number | undefined, double
    */
    valorTotal?: number;
    /**
     * @type string | undefined
    */
    educadorResponsavel?: string;
    /**
     * @type integer | undefined, int64
    */
    disciplinaId?: number;
};