/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RespostaDTO } from "./RespostaDTO.ts";

export type TarefaDetailsDTO = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type string | undefined
    */
    titulo?: string;
    /**
     * @type string | undefined
    */
    conteudo?: string;
    /**
     * @type string | undefined, date-time
    */
    dataEnvio?: string;
    /**
     * @type string | undefined, date-time
    */
    dataExpiracao?: string;
    /**
     * @type number | undefined, double
    */
    valorTotal?: number;
    /**
     * @type boolean | undefined
    */
    permitirArquivoResposta?: boolean;
    /**
     * @type string | undefined
    */
    disciplinaNome?: string;
    /**
     * @type string | undefined
    */
    autorNome?: string;
    /**
     * @type array | undefined
    */
    respostas?: RespostaDTO[];
};