/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const updateEducadorDTOGeneroEnum = {
    "MASCULINO": "MASCULINO",
    "FEMININO": "FEMININO",
    "OUTRO": "OUTRO",
    "NAO_INFORMAR": "NAO_INFORMAR"
} as const;

export type UpdateEducadorDTOGeneroEnumKey = (typeof updateEducadorDTOGeneroEnum)[keyof typeof updateEducadorDTOGeneroEnum];

export type UpdateEducadorDTO = {
    /**
     * @type string | undefined
    */
    nome?: string;
    /**
     * @type string | undefined
    */
    telefone?: string;
    /**
     * @type string | undefined
    */
    genero?: UpdateEducadorDTOGeneroEnumKey;
    /**
     * @type string | undefined, date
    */
    dataNascimento?: string;
    /**
     * @type string | undefined
    */
    matricula?: string;
    /**
     * @type string | undefined
    */
    titulo?: string;
};