/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PublicacaoDetailsDTO } from "./PublicacaoDetailsDTO.ts";
import type { UpdatePublicacaoDTO } from "./UpdatePublicacaoDTO.ts";

export type UpdatePublicacaoPathParams = {
    /**
     * @type integer, int64
    */
    publicacaoId: number;
};

/**
 * @description Publicação atualizada com sucesso
*/
export type UpdatePublicacao200 = PublicacaoDetailsDTO;

/**
 * @description Disciplina não encontrada
*/
export type UpdatePublicacao404 = PublicacaoDetailsDTO;

/**
 * @description Dados inválidos ou conflitantes
*/
export type UpdatePublicacao409 = PublicacaoDetailsDTO;

export type UpdatePublicacaoMutationRequest = UpdatePublicacaoDTO;

export type UpdatePublicacaoMutationResponse = UpdatePublicacao200;

export type UpdatePublicacaoMutation = {
    Response: UpdatePublicacao200;
    Request: UpdatePublicacaoMutationRequest;
    PathParams: UpdatePublicacaoPathParams;
    Errors: UpdatePublicacao404 | UpdatePublicacao409;
};