/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DisciplinaSummaryDTO } from "./DisciplinaSummaryDTO.ts";
import type { UpdateDisciplinaDTO } from "./UpdateDisciplinaDTO.ts";

export type UpdateDisciplinaPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description Disciplina atualizada com sucesso
*/
export type UpdateDisciplina200 = DisciplinaSummaryDTO;

/**
 * @description Disciplina ou Educador responsável não encontrados
*/
export type UpdateDisciplina404 = DisciplinaSummaryDTO;

/**
 * @description Dados inválidos ou conflitantes
*/
export type UpdateDisciplina409 = DisciplinaSummaryDTO;

export type UpdateDisciplinaMutationRequest = UpdateDisciplinaDTO;

export type UpdateDisciplinaMutationResponse = UpdateDisciplina200;

export type UpdateDisciplinaMutation = {
    Response: UpdateDisciplina200;
    Request: UpdateDisciplinaMutationRequest;
    PathParams: UpdateDisciplinaPathParams;
    Errors: UpdateDisciplina404 | UpdateDisciplina409;
};