/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { EducadorSummaryDTO } from "./EducadorSummaryDTO.ts";
import type { UpdateEducadorDTO } from "./UpdateEducadorDTO.ts";

export type UpdateEducadorPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description Atualização realizada com sucesso
*/
export type UpdateEducador200 = EducadorSummaryDTO;

/**
 * @description Educador não encontrado
*/
export type UpdateEducador404 = EducadorSummaryDTO;

/**
 * @description Dados conflitantes ou inválidos
*/
export type UpdateEducador409 = EducadorSummaryDTO;

export type UpdateEducadorMutationRequest = UpdateEducadorDTO;

export type UpdateEducadorMutationResponse = UpdateEducador200;

export type UpdateEducadorMutation = {
    Response: UpdateEducador200;
    Request: UpdateEducadorMutationRequest;
    PathParams: UpdateEducadorPathParams;
    Errors: UpdateEducador404 | UpdateEducador409;
};