/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdatePublicacaoDTO = {
    /**
     * @type string | undefined
    */
    titulo?: string;
    /**
     * @type string | undefined
    */
    conteudo?: string;
    /**
     * @type string | undefined
    */
    caminhoAnexo?: string;
};