/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateComentarioDTO = {
    /**
     * @minLength 0
     * @maxLength 280
     * @type string | undefined
    */
    conteudo?: string;
};