/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const updatePerfilAcessibilidadeDTOTipoDeficienciaEnum = {
    "NENHUMA": "NENHUMA",
    "VISUAL": "VISUAL",
    "AUDITIVA": "AUDITIVA",
    "MOTORA": "MOTORA",
    "COGNITIVA": "COGNITIVA",
    "OUTRA": "OUTRA"
} as const;

export type UpdatePerfilAcessibilidadeDTOTipoDeficienciaEnumKey = (typeof updatePerfilAcessibilidadeDTOTipoDeficienciaEnum)[keyof typeof updatePerfilAcessibilidadeDTOTipoDeficienciaEnum];

export type UpdatePerfilAcessibilidadeDTO = {
    /**
     * @type string | undefined
    */
    tipoDeficiencia?: UpdatePerfilAcessibilidadeDTOTipoDeficienciaEnumKey;
    /**
     * @type boolean | undefined
    */
    usaLeitorDeTela?: boolean;
    /**
     * @type boolean | undefined
    */
    modoAltoContraste?: boolean;
    /**
     * @type integer | undefined, int32
    */
    tamanhoFonte?: number;
    /**
     * @type boolean | undefined
    */
    talkBack?: boolean;
};