/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdatePerfilAcessibilidadeDTO } from "./UpdatePerfilAcessibilidadeDTO.ts";

export type UpdatePerfilAcessibilidadePathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description Perfil de Acessibilidade atualizado com sucesso
*/
export type UpdatePerfilAcessibilidade200 = object;

/**
 * @description Requisição tem parâmetros inválidos
*/
export type UpdatePerfilAcessibilidade400 = object;

/**
 * @description Perfil de Acessibilidade não encontrado
*/
export type UpdatePerfilAcessibilidade404 = object;

export type UpdatePerfilAcessibilidadeMutationRequest = UpdatePerfilAcessibilidadeDTO;

export type UpdatePerfilAcessibilidadeMutationResponse = UpdatePerfilAcessibilidade200;

export type UpdatePerfilAcessibilidadeMutation = {
    Response: UpdatePerfilAcessibilidade200;
    Request: UpdatePerfilAcessibilidadeMutationRequest;
    PathParams: UpdatePerfilAcessibilidadePathParams;
    Errors: UpdatePerfilAcessibilidade400 | UpdatePerfilAcessibilidade404;
};