/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { InstituicaoDetailsDTO } from "./InstituicaoDetailsDTO.ts";
import type { UpdateInstituicaoDTO } from "./UpdateInstituicaoDTO.ts";

export type UpdateInstituicaoPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description Atualização concluída
*/
export type UpdateInstituicao200 = InstituicaoDetailsDTO;

/**
 * @description Instituição não encontrada
*/
export type UpdateInstituicao404 = InstituicaoDetailsDTO;

/**
 * @description Dados inválidos
*/
export type UpdateInstituicao422 = InstituicaoDetailsDTO;

export type UpdateInstituicaoMutationRequest = UpdateInstituicaoDTO;

export type UpdateInstituicaoMutationResponse = UpdateInstituicao200;

export type UpdateInstituicaoMutation = {
    Response: UpdateInstituicao200;
    Request: UpdateInstituicaoMutationRequest;
    PathParams: UpdateInstituicaoPathParams;
    Errors: UpdateInstituicao404 | UpdateInstituicao422;
};