/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateDisciplinaDTO = {
    /**
     * @type string | undefined
    */
    nome?: string;
    /**
     * @type string | undefined
    */
    descricao?: string;
    /**
     * @type integer | undefined, int64
    */
    idEducadorResponsavel?: number;
};