/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GestorDetailsDTO } from "./GestorDetailsDTO.ts";
import type { UpdateGestorDTO } from "./UpdateGestorDTO.ts";

export type UpdateGestorPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description Gestor obtido com sucesso
*/
export type UpdateGestor200 = GestorDetailsDTO;

/**
 * @description Ocorreu erro durante o processamento da requsição
*/
export type UpdateGestor400 = GestorDetailsDTO;

/**
 * @description Não foi possível obter o Gestor com o ID especificado
*/
export type UpdateGestor404 = GestorDetailsDTO;

export type UpdateGestorMutationRequest = UpdateGestorDTO;

export type UpdateGestorMutationResponse = UpdateGestor200;

export type UpdateGestorMutation = {
    Response: UpdateGestor200;
    Request: UpdateGestorMutationRequest;
    PathParams: UpdateGestorPathParams;
    Errors: UpdateGestor400 | UpdateGestor404;
};