/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PasswordResetDTO } from "./PasswordResetDTO.ts";

/**
 * @description A senha é alterada com sucesso
*/
export type UpdatePassword200 = object;

/**
 * @description Não foi possível atualizar a senha
*/
export type UpdatePassword400 = object;

export type UpdatePasswordMutationRequest = PasswordResetDTO;

export type UpdatePasswordMutationResponse = UpdatePassword200;

export type UpdatePasswordMutation = {
    Response: UpdatePassword200;
    Request: UpdatePasswordMutationRequest;
    Errors: UpdatePassword400;
};