/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Endereco } from "./Endereco.ts";

export type UpdateInstituicaoDTO = {
    /**
     * @minLength 1
     * @type string
    */
    nome: string;
    /**
     * @minLength 1
     * @type string
    */
    telefone: string;
    /**
     * @minLength 1
     * @type string
    */
    cnpj: string;
    /**
     * @minLength 1
     * @type string, email
    */
    email: string;
    /**
     * @type object
    */
    endereco: Endereco;
};