/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ArquivoDTO } from "./ArquivoDTO.ts";

export type UploadArquivoPathParams = {
    /**
     * @type integer, int64
    */
    disciplinaId: number;
};

export type UploadArquivoQueryParams = {
    /**
     * @type string | undefined
    */
    descricao?: string;
    /**
     * @type integer, int64
    */
    usuarioId: number;
};

/**
 * @description Arquivo enviado com sucesso
*/
export type UploadArquivo201 = ArquivoDTO;

/**
 * @description Falha ao enviar o arquivo
*/
export type UploadArquivo400 = ArquivoDTO;

/**
 * @description Disciplina ou Educador não encontrados
*/
export type UploadArquivo404 = ArquivoDTO;

export type UploadArquivoMutationRequest = {
    /**
     * @type string, binary
    */
    arquivo: Blob;
};

export type UploadArquivoMutationResponse = UploadArquivo201;

export type UploadArquivoMutation = {
    Response: UploadArquivo201;
    Request: UploadArquivoMutationRequest;
    PathParams: UploadArquivoPathParams;
    QueryParams: UploadArquivoQueryParams;
    Errors: UploadArquivo400 | UploadArquivo404;
};