/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ValidateTokenQueryParams = {
    /**
     * @type string
    */
    token: string;
};

/**
 * @description O token é válido
*/
export type ValidateToken200 = object;

/**
 * @description O token não é válido
*/
export type ValidateToken400 = object;

export type ValidateTokenMutationResponse = ValidateToken200;

export type ValidateTokenMutation = {
    Response: ValidateToken200;
    QueryParams: ValidateTokenQueryParams;
    Errors: ValidateToken400;
};