/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { CreatePublicacaoMutationRequest, CreatePublicacaoMutationResponse, CreatePublicacao403, CreatePublicacao404, CreatePublicacao409 } from "../../models/CreatePublicacao.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { createPublicacao } from "../../client/createPublicacao.ts";

export const createPublicacaoMutationKey = () => [{ url: '/publicacoes' }] as const

export type CreatePublicacaoMutationKey = ReturnType<typeof createPublicacaoMutationKey>

export function createPublicacaoMutationOptions(config: Partial<RequestConfig<CreatePublicacaoMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = createPublicacaoMutationKey()
  return mutationOptions<CreatePublicacaoMutationResponse, ResponseErrorConfig<CreatePublicacao403 | CreatePublicacao404 | CreatePublicacao409>, {data: CreatePublicacaoMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return createPublicacao(data, config)
    },
  })
}

/**
 * @summary Cria uma Publicação
 * {@link /publicacoes}
 */
export function useCreatePublicacao<TContext>(options: 
{
  mutation?: UseMutationOptions<CreatePublicacaoMutationResponse, ResponseErrorConfig<CreatePublicacao403 | CreatePublicacao404 | CreatePublicacao409>, {data: CreatePublicacaoMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreatePublicacaoMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createPublicacaoMutationKey()

  const baseOptions = createPublicacaoMutationOptions(config) as UseMutationOptions<CreatePublicacaoMutationResponse, ResponseErrorConfig<CreatePublicacao403 | CreatePublicacao404 | CreatePublicacao409>, {data: CreatePublicacaoMutationRequest}, TContext>

  return useMutation<CreatePublicacaoMutationResponse, ResponseErrorConfig<CreatePublicacao403 | CreatePublicacao404 | CreatePublicacao409>, {data: CreatePublicacaoMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreatePublicacaoMutationResponse, ResponseErrorConfig<CreatePublicacao403 | CreatePublicacao404 | CreatePublicacao409>, {data: CreatePublicacaoMutationRequest}, TContext>
}