/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { DeletePublicacaoMutationResponse, DeletePublicacaoPathParams, DeletePublicacao404 } from "../../models/DeletePublicacao.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { deletePublicacao } from "../../client/deletePublicacao.ts";

export const deletePublicacaoMutationKey = () => [{ url: '/publicacoes/:publicacaoId' }] as const

export type DeletePublicacaoMutationKey = ReturnType<typeof deletePublicacaoMutationKey>

export function deletePublicacaoMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = deletePublicacaoMutationKey()
  return mutationOptions<DeletePublicacaoMutationResponse, ResponseErrorConfig<DeletePublicacao404>, {publicacaoId: DeletePublicacaoPathParams["publicacaoId"]}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ publicacaoId }) => {
      return deletePublicacao(publicacaoId, config)
    },
  })
}

/**
 * @summary Deleta uma Publicação a partir do seu ID
 * {@link /publicacoes/:publicacaoId}
 */
export function useDeletePublicacao<TContext>(options: 
{
  mutation?: UseMutationOptions<DeletePublicacaoMutationResponse, ResponseErrorConfig<DeletePublicacao404>, {publicacaoId: DeletePublicacaoPathParams["publicacaoId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deletePublicacaoMutationKey()

  const baseOptions = deletePublicacaoMutationOptions(config) as UseMutationOptions<DeletePublicacaoMutationResponse, ResponseErrorConfig<DeletePublicacao404>, {publicacaoId: DeletePublicacaoPathParams["publicacaoId"]}, TContext>

  return useMutation<DeletePublicacaoMutationResponse, ResponseErrorConfig<DeletePublicacao404>, {publicacaoId: DeletePublicacaoPathParams["publicacaoId"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<DeletePublicacaoMutationResponse, ResponseErrorConfig<DeletePublicacao404>, {publicacaoId: DeletePublicacaoPathParams["publicacaoId"]}, TContext>
}