/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetPublicacaoQueryResponse, GetPublicacaoPathParams, GetPublicacao404 } from "../../models/GetPublicacao.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getPublicacao } from "../../client/getPublicacao.ts";

export const getPublicacaoQueryKey = (publicacaoId: GetPublicacaoPathParams["publicacaoId"]) => [{ url: '/publicacoes/:publicacaoId', params: {publicacaoId:publicacaoId} }] as const

export type GetPublicacaoQueryKey = ReturnType<typeof getPublicacaoQueryKey>

export function getPublicacaoQueryOptions(publicacaoId: GetPublicacaoPathParams["publicacaoId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getPublicacaoQueryKey(publicacaoId)
  return queryOptions<GetPublicacaoQueryResponse, ResponseErrorConfig<GetPublicacao404>, GetPublicacaoQueryResponse, typeof queryKey>({
   enabled: !!(publicacaoId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getPublicacao(publicacaoId, config)
   },
  })
}

/**
 * @description Obtém uma Publicação através de seu ID
 * {@link /publicacoes/:publicacaoId}
 */
export function useGetPublicacao<TData = GetPublicacaoQueryResponse, TQueryData = GetPublicacaoQueryResponse, TQueryKey extends QueryKey = GetPublicacaoQueryKey>(publicacaoId: GetPublicacaoPathParams["publicacaoId"], options: 
{
  query?: Partial<QueryObserverOptions<GetPublicacaoQueryResponse, ResponseErrorConfig<GetPublicacao404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getPublicacaoQueryKey(publicacaoId)

  const query = useQuery({
   ...getPublicacaoQueryOptions(publicacaoId, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetPublicacao404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}