/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetPublicacaoQueryResponse, GetPublicacaoPathParams, GetPublicacao404 } from "../../models/GetPublicacao.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getPublicacao } from "../../client/getPublicacao.ts";

export const getPublicacaoSuspenseQueryKey = (publicacaoId: GetPublicacaoPathParams["publicacaoId"]) => [{ url: '/publicacoes/:publicacaoId', params: {publicacaoId:publicacaoId} }] as const

export type GetPublicacaoSuspenseQueryKey = ReturnType<typeof getPublicacaoSuspenseQueryKey>

export function getPublicacaoSuspenseQueryOptions(publicacaoId: GetPublicacaoPathParams["publicacaoId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getPublicacaoSuspenseQueryKey(publicacaoId)
  return queryOptions<GetPublicacaoQueryResponse, ResponseErrorConfig<GetPublicacao404>, GetPublicacaoQueryResponse, typeof queryKey>({
   enabled: !!(publicacaoId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getPublicacao(publicacaoId, config)
   },
  })
}

/**
 * @description Obtém uma Publicação através de seu ID
 * {@link /publicacoes/:publicacaoId}
 */
export function useGetPublicacaoSuspense<TData = GetPublicacaoQueryResponse, TQueryKey extends QueryKey = GetPublicacaoSuspenseQueryKey>(publicacaoId: GetPublicacaoPathParams["publicacaoId"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetPublicacaoQueryResponse, ResponseErrorConfig<GetPublicacao404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getPublicacaoSuspenseQueryKey(publicacaoId)

  const query = useSuspenseQuery({
   ...getPublicacaoSuspenseQueryOptions(publicacaoId, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetPublicacao404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}