/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetPublicacoesQueryResponse, GetPublicacoesQueryParams, GetPublicacoes404 } from "../../models/GetPublicacoes.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getPublicacoes } from "../../client/getPublicacoes.ts";

export const getPublicacoesSuspenseQueryKey = (params: GetPublicacoesQueryParams) => [{ url: '/publicacoes/disciplina' }, ...(params ? [params] : [])] as const

export type GetPublicacoesSuspenseQueryKey = ReturnType<typeof getPublicacoesSuspenseQueryKey>

export function getPublicacoesSuspenseQueryOptions(params: GetPublicacoesQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getPublicacoesSuspenseQueryKey(params)
  return queryOptions<GetPublicacoesQueryResponse, ResponseErrorConfig<GetPublicacoes404>, GetPublicacoesQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getPublicacoes(params, config)
   },
  })
}

/**
 * @summary Busca as Publicações em uma Disciplina
 * {@link /publicacoes/disciplina}
 */
export function useGetPublicacoesSuspense<TData = GetPublicacoesQueryResponse, TQueryKey extends QueryKey = GetPublicacoesSuspenseQueryKey>(params: GetPublicacoesQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetPublicacoesQueryResponse, ResponseErrorConfig<GetPublicacoes404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getPublicacoesSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...getPublicacoesSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetPublicacoes404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}