/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetPublicacoesQueryResponse, GetPublicacoesQueryParams, GetPublicacoes404 } from "../../models/GetPublicacoes.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getPublicacoes } from "../../client/getPublicacoes.ts";

export const getPublicacoesQueryKey = (params: GetPublicacoesQueryParams) => [{ url: '/publicacoes/disciplina' }, ...(params ? [params] : [])] as const

export type GetPublicacoesQueryKey = ReturnType<typeof getPublicacoesQueryKey>

export function getPublicacoesQueryOptions(params: GetPublicacoesQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getPublicacoesQueryKey(params)
  return queryOptions<GetPublicacoesQueryResponse, ResponseErrorConfig<GetPublicacoes404>, GetPublicacoesQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getPublicacoes(params, config)
   },
  })
}

/**
 * @summary Busca as Publicações em uma Disciplina
 * {@link /publicacoes/disciplina}
 */
export function useGetPublicacoes<TData = GetPublicacoesQueryResponse, TQueryData = GetPublicacoesQueryResponse, TQueryKey extends QueryKey = GetPublicacoesQueryKey>(params: GetPublicacoesQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetPublicacoesQueryResponse, ResponseErrorConfig<GetPublicacoes404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getPublicacoesQueryKey(params)

  const query = useQuery({
   ...getPublicacoesQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetPublicacoes404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}