/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { UpdatePublicacaoMutationRequest, UpdatePublicacaoMutationResponse, UpdatePublicacaoPathParams, UpdatePublicacao404, UpdatePublicacao409 } from "../../models/UpdatePublicacao.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { updatePublicacao } from "../../client/updatePublicacao.ts";

export const updatePublicacaoMutationKey = () => [{ url: '/publicacoes/:publicacaoId' }] as const

export type UpdatePublicacaoMutationKey = ReturnType<typeof updatePublicacaoMutationKey>

export function updatePublicacaoMutationOptions(config: Partial<RequestConfig<UpdatePublicacaoMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = updatePublicacaoMutationKey()
  return mutationOptions<UpdatePublicacaoMutationResponse, ResponseErrorConfig<UpdatePublicacao404 | UpdatePublicacao409>, {publicacaoId: UpdatePublicacaoPathParams["publicacaoId"], data?: UpdatePublicacaoMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ publicacaoId, data }) => {
      return updatePublicacao(publicacaoId, data, config)
    },
  })
}

/**
 * @summary Atualiza as informações de uma Publicação
 * {@link /publicacoes/:publicacaoId}
 */
export function useUpdatePublicacao<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdatePublicacaoMutationResponse, ResponseErrorConfig<UpdatePublicacao404 | UpdatePublicacao409>, {publicacaoId: UpdatePublicacaoPathParams["publicacaoId"], data?: UpdatePublicacaoMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdatePublicacaoMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updatePublicacaoMutationKey()

  const baseOptions = updatePublicacaoMutationOptions(config) as UseMutationOptions<UpdatePublicacaoMutationResponse, ResponseErrorConfig<UpdatePublicacao404 | UpdatePublicacao409>, {publicacaoId: UpdatePublicacaoPathParams["publicacaoId"], data?: UpdatePublicacaoMutationRequest}, TContext>

  return useMutation<UpdatePublicacaoMutationResponse, ResponseErrorConfig<UpdatePublicacao404 | UpdatePublicacao409>, {publicacaoId: UpdatePublicacaoPathParams["publicacaoId"], data?: UpdatePublicacaoMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<UpdatePublicacaoMutationResponse, ResponseErrorConfig<UpdatePublicacao404 | UpdatePublicacao409>, {publicacaoId: UpdatePublicacaoPathParams["publicacaoId"], data?: UpdatePublicacaoMutationRequest}, TContext>
}