/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { LoginMutationRequest, LoginMutationResponse, Login400 } from "../../models/Login.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { login } from "../../client/login.ts";

export const loginMutationKey = () => [{ url: '/auth/login' }] as const

export type LoginMutationKey = ReturnType<typeof loginMutationKey>

export function loginMutationOptions(config: Partial<RequestConfig<LoginMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = loginMutationKey()
  return mutationOptions<LoginMutationResponse, ResponseErrorConfig<Login400>, {data?: LoginMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return login(data, config)
    },
  })
}

/**
 * @summary Realiza a autenticação de usuários
 * {@link /auth/login}
 */
export function useLogin<TContext>(options: 
{
  mutation?: UseMutationOptions<LoginMutationResponse, ResponseErrorConfig<Login400>, {data?: LoginMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<LoginMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? loginMutationKey()

  const baseOptions = loginMutationOptions(config) as UseMutationOptions<LoginMutationResponse, ResponseErrorConfig<Login400>, {data?: LoginMutationRequest}, TContext>

  return useMutation<LoginMutationResponse, ResponseErrorConfig<Login400>, {data?: LoginMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<LoginMutationResponse, ResponseErrorConfig<Login400>, {data?: LoginMutationRequest}, TContext>
}