/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { RegisterMutationRequest, RegisterMutationResponse, Register400 } from "../../models/Register.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { register } from "../../client/register.ts";

export const registerMutationKey = () => [{ url: '/auth/register' }] as const

export type RegisterMutationKey = ReturnType<typeof registerMutationKey>

export function registerMutationOptions(config: Partial<RequestConfig<RegisterMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = registerMutationKey()
  return mutationOptions<RegisterMutationResponse, ResponseErrorConfig<Register400>, {data: RegisterMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return register(data, config)
    },
  })
}

/**
 * @summary Realiza o registro de usuários
 * {@link /auth/register}
 */
export function useRegister<TContext>(options: 
{
  mutation?: UseMutationOptions<RegisterMutationResponse, ResponseErrorConfig<Register400>, {data: RegisterMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<RegisterMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? registerMutationKey()

  const baseOptions = registerMutationOptions(config) as UseMutationOptions<RegisterMutationResponse, ResponseErrorConfig<Register400>, {data: RegisterMutationRequest}, TContext>

  return useMutation<RegisterMutationResponse, ResponseErrorConfig<Register400>, {data: RegisterMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<RegisterMutationResponse, ResponseErrorConfig<Register400>, {data: RegisterMutationRequest}, TContext>
}